INSERT INTO CONFIG_KEY_VALUE_INTEGER(CONFIGURATION_KEY, CONFIGURATION_VALUE) VALUES ('sessionTimeout',60);

/* remove the row from SYSTEM_CONFIGURATION that previously held the session timeout value */
DELETE FROM SYSTEM_CONFIGURATION WHERE OFFICE_ID IS NULL;

/* remove the column that was used for the single session timeout entry */
ALTER TABLE SYSTEM_CONFIGURATION DROP COLUMN SESSION_TIME_OUT;

UPDATE DATABASE_VERSION SET DATABASE_VERSION = 109 WHERE DATABASE_VERSION = 108;
