UPDATE LOOKUP_ENTITY SET ENTITY_NAME='CustomerAttendanceType', DESCRIPTION='CustomerAttendanceType' WHERE ENTITY_ID = 75;
UPDATE LOOKUP_ENTITY SET DESCRIPTION='BulkEntry' WHERE ENTITY_ID = 77;

UPDATE DATABASE_VERSION SET DATABASE_VERSION = 210 WHERE DATABASE_VERSION = 209;