// ============================================================================
//
// Copyright (c) 2005-2007, Talend Inc.
//
// This source code has been automatically generated by Talend Open Studio
// / JobDesigner (CodeGenerator version 2.3.0.RC1_r8112).
// You can find more information about Talend products at www.talend.com.
// You may distribute this code under the terms of the GNU LGPL license
// (http://www.gnu.org/licenses/lgpl.html).
//
// ============================================================================ 
package org_mifos_etl.clientloanfactloader;

import routines.DataOperation;
import routines.Mathematical;
import routines.Numeric;
import routines.Relational;
import routines.StringHandling;
import routines.TalendDataGenerator;
import routines.TalendDate;
import routines.TalendString;
import routines.system.*;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.math.BigDecimal;

/**
 * Job: ClientLoanFactLoader Purpose: Load client loan facts<br>
 * Description: Loads the client loan facts from MifOS transaction schema. <br>
 * 
 * @author ravikasar@gmail.com
 * @version 0.1
 * @status DEV
 */
public class ClientLoanFactLoader {
	// create and load default properties
	private static java.util.Properties defaultProps = new java.util.Properties();
	// create application properties with default
	private static java.util.Properties context = new java.util.Properties();
	private static String OLTP_DB_HOST;
	private static String OLTP_DB_PORT;
	private static String OLTP_DB_SCHEMA;
	private static String OLTP_DB_USER;
	private static String OLTP_DB_PASSWORD;
	private static String OLAP_DB_HOST;
	private static String OLAP_DB_PORT;
	private static String OLAP_DB_SCHEMA;
	private static String OLAP_DB_USER;
	private static String OLAP_DB_PASSWORD;
	private static final String jobName = "ClientLoanFactLoader";
	private static final String projectName = "ORG_MIFOS_ETL";
	public static Integer errorCode = null;
	private static String currentComponent = "";
	private static final java.util.Map<String, Long> start_Hash = new java.util.HashMap<String, Long>();
	private static final java.util.Map<String, Long> end_Hash = new java.util.HashMap<String, Long>();
	private static final java.util.Map<String, Boolean> ok_Hash = new java.util.HashMap<String, Boolean>();
	private static final java.util.Map<String, Object> globalMap = new java.util.HashMap<String, Object>();

	LogCatcherUtils tLogCatcher_1 = new LogCatcherUtils();
	StatCatcherUtils tStatCatcher_1 = new StatCatcherUtils(
			"_Tr0-kP8aEdyXf5mSz4-Utw", "0.1");

	private class TalendException extends Exception {
		private Exception e = null;
		private ClientLoanFactLoader c = null;

		private TalendException(ClientLoanFactLoader c, Exception e) {
			this.e = e;
			this.c = c;
		}

		@Override
		public void printStackTrace() {
			if (!(e instanceof TalendException || e instanceof TDieException)) {
				globalMap.put(currentComponent + "_ERROR_MESSAGE", e
						.getMessage());
				System.err
						.println("Exception in component " + currentComponent);
			}
			if (!(e instanceof TDieException)) {
				e.printStackTrace();
			}
			if (!(e instanceof TalendException)) {
				try {
					for (java.lang.reflect.Method m : this.getClass()
							.getEnclosingClass().getMethods()) {
						if (m.getName().compareTo(currentComponent + "_error") == 0) {
							m.invoke(c, new Object[] { e });
							break;
						}
					}
					if (!(e instanceof TDieException)) {
						tLogCatcher_1.addMessage("Java Exception",
								currentComponent, 6, e.getMessage(), 1);
						tLogCatcher_1Process();
					}

				} catch (java.lang.SecurityException e) {
					this.e.printStackTrace();
				} catch (java.lang.IllegalArgumentException e) {
					this.e.printStackTrace();
				} catch (java.lang.IllegalAccessException e) {
					this.e.printStackTrace();
				} catch (java.lang.reflect.InvocationTargetException e) {
					this.e.printStackTrace();
				} catch (TalendException e) {
					// do nothing
				}

			}
		}
	}

	public void tJava_1_error(Exception exception) throws TalendException {
		end_Hash.put("tJava_1", System.currentTimeMillis());
		tJava_1_onSubJobError(exception);
	}

	public void tMysqlConnection_1_error(Exception exception)
			throws TalendException {
		end_Hash.put("tMysqlConnection_1", System.currentTimeMillis());
		tMysqlConnection_1_onSubJobError(exception);
	}

	public void tMysqlConnection_2_error(Exception exception)
			throws TalendException {
		end_Hash.put("tMysqlConnection_2", System.currentTimeMillis());
		tMysqlConnection_2_onSubJobError(exception);
	}

	public void tMysqlInput_1_error(Exception exception) throws TalendException {
		end_Hash.put("tMysqlInput_1", System.currentTimeMillis());
		tMysqlInput_1_onSubJobError(exception);
	}

	public void tMap_1_error(Exception exception) throws TalendException {
		end_Hash.put("tMap_1", System.currentTimeMillis());
		tMysqlInput_1_onSubJobError(exception);
	}

	public void tMysqlOutput_1_error(Exception exception)
			throws TalendException {
		end_Hash.put("tMysqlOutput_1", System.currentTimeMillis());
		tMysqlInput_1_onSubJobError(exception);
	}

	public void tMysqlCommit_1_error(Exception exception)
			throws TalendException {
		end_Hash.put("tMysqlCommit_1", System.currentTimeMillis());
		tMysqlCommit_1_onSubJobError(exception);
	}

	public void tLogCatcher_1_error(Exception exception) throws TalendException {
		end_Hash.put("tLogCatcher_1", System.currentTimeMillis());
		tLogCatcher_1_onSubJobError(exception);
	}

	public void tFileOutputDelimited_2_error(Exception exception)
			throws TalendException {
		end_Hash.put("tFileOutputDelimited_2", System.currentTimeMillis());
		tLogCatcher_1_onSubJobError(exception);
	}

	public void tMysqlInput_2_error(Exception exception) throws TalendException {
		end_Hash.put("tMysqlInput_2", System.currentTimeMillis());
		tMysqlInput_2_onSubJobError(exception);
	}

	public void tMysqlInput_3_error(Exception exception) throws TalendException {
		end_Hash.put("tMysqlInput_3", System.currentTimeMillis());
		tMysqlInput_3_onSubJobError(exception);
	}

	public void tStatCatcher_1_error(Exception exception)
			throws TalendException {
		end_Hash.put("tStatCatcher_1", System.currentTimeMillis());
		tStatCatcher_1_onSubJobError(exception);
	}

	public void tFileOutputDelimited_1_error(Exception exception)
			throws TalendException {
		end_Hash.put("tFileOutputDelimited_1", System.currentTimeMillis());
		tStatCatcher_1_onSubJobError(exception);
	}

	public void tAdvancedHash_row2_error(Exception exception)
			throws TalendException {
		end_Hash.put("tAdvancedHash_row2", System.currentTimeMillis());
		tMysqlInput_2_onSubJobError(exception);
	}

	public void tAdvancedHash_row3_error(Exception exception)
			throws TalendException {
		end_Hash.put("tAdvancedHash_row3", System.currentTimeMillis());
		tMysqlInput_3_onSubJobError(exception);
	}

	public void tJava_1_onSubJobError(Exception exception)
			throws TalendException {
	}

	public void tMysqlConnection_1_onSubJobError(Exception exception)
			throws TalendException {
	}

	public void tMysqlConnection_2_onSubJobError(Exception exception)
			throws TalendException {
	}

	public void tMysqlInput_1_onSubJobError(Exception exception)
			throws TalendException {
	}

	public void tMysqlCommit_1_onSubJobError(Exception exception)
			throws TalendException {
	}

	public void tLogCatcher_1_onSubJobError(Exception exception)
			throws TalendException {
	}

	public void tMysqlInput_2_onSubJobError(Exception exception)
			throws TalendException {
	}

	public void tMysqlInput_3_onSubJobError(Exception exception)
			throws TalendException {
	}

	public void tStatCatcher_1_onSubJobError(Exception exception)
			throws TalendException {
	}

	public void tJava_1Process() throws TalendException {
		try {

			/**
			 * [tJava_1 begin ] start
			 */

			ok_Hash.put("tJava_1", false);
			start_Hash.put("tJava_1", System.currentTimeMillis());
			currentComponent = "tJava_1";

			java.util.Properties p = new java.util.Properties();

			java.io.InputStream inStream = this.getClass().getClassLoader()
					.getResourceAsStream("hibernate.properties");

			p.load(inStream);
			OLTP_DB_PASSWORD = (String) p.get("OLTP_DB_PASSWORD");
			OLTP_DB_USER = (String) p.get("OLTP_DB_USER");
			OLTP_DB_SCHEMA = (String) p.get("OLTP_DB_NAME");
			OLTP_DB_PORT = (String) p.get("OLTP_DB_PORT");
			OLTP_DB_HOST = (String) p.get("OLTP_HOST_NAME");
			OLAP_DB_HOST = (String) p.get("OLAP_DB_HOST");
			OLAP_DB_PORT = (String) p.get("OLAP_DB_PORT");
			OLAP_DB_SCHEMA = (String) p.get("OLAP_DB_NAME");
			OLAP_DB_USER = (String) p.get("OLAP_DB_USER");
			OLAP_DB_PASSWORD = (String) p.get("OLAP_DB_PASSWORD");

			/**
			 * [tJava_1 begin ] stop
			 */
			/**
			 * [tJava_1 main ] start
			 */

			currentComponent = "tJava_1";

			/**
			 * [tJava_1 main ] stop
			 */

			/**
			 * [tJava_1 end ] start
			 */

			currentComponent = "tJava_1";

			ok_Hash.put("tJava_1", true);
			end_Hash.put("tJava_1", System.currentTimeMillis());

			/**
			 * [tJava_1 end ] stop
			 */

			tMysqlConnection_1Process();

		} catch (Exception e) {
			throw new TalendException(this, e);
		}
	}

	public void tMysqlConnection_1Process() throws TalendException {
		try {

			/**
			 * [tMysqlConnection_1 begin ] start
			 */

			ok_Hash.put("tMysqlConnection_1", false);
			start_Hash.put("tMysqlConnection_1", System.currentTimeMillis());
			currentComponent = "tMysqlConnection_1";

			java.lang.Class.forName("org.gjt.mm.mysql.Driver");

			String url_tMysqlConnection_1 = "jdbc:mysql://" + OLAP_DB_HOST
					+ ":" + OLAP_DB_PORT + "/" + OLAP_DB_SCHEMA + "?"
					+ "noDatetimeStringSync=true";

			String userName_tMysqlConnection_1 = OLAP_DB_USER;

			String password_tMysqlConnection_1 = OLAP_DB_PASSWORD;

			java.sql.Connection conn_tMysqlConnection_1 = java.sql.DriverManager
					.getConnection(url_tMysqlConnection_1,
							userName_tMysqlConnection_1,
							password_tMysqlConnection_1);

			conn_tMysqlConnection_1.setAutoCommit(false);

			globalMap.put("conn_" + "tMysqlConnection_1",
					conn_tMysqlConnection_1);

			/**
			 * [tMysqlConnection_1 begin ] stop
			 */
			/**
			 * [tMysqlConnection_1 main ] start
			 */

			currentComponent = "tMysqlConnection_1";

			/**
			 * [tMysqlConnection_1 main ] stop
			 */

			/**
			 * [tMysqlConnection_1 end ] start
			 */

			currentComponent = "tMysqlConnection_1";

			ok_Hash.put("tMysqlConnection_1", true);
			end_Hash.put("tMysqlConnection_1", System.currentTimeMillis());

			/**
			 * [tMysqlConnection_1 end ] stop
			 */

			tMysqlConnection_2Process();

		} catch (Exception e) {
			throw new TalendException(this, e);
		}
	}

	public void tMysqlConnection_2Process() throws TalendException {
		try {

			/**
			 * [tMysqlConnection_2 begin ] start
			 */

			ok_Hash.put("tMysqlConnection_2", false);
			start_Hash.put("tMysqlConnection_2", System.currentTimeMillis());
			currentComponent = "tMysqlConnection_2";

			java.lang.Class.forName("org.gjt.mm.mysql.Driver");

			String url_tMysqlConnection_2 = "jdbc:mysql://" + OLTP_DB_HOST
					+ ":" + OLTP_DB_PORT + "/" + OLTP_DB_SCHEMA + "?"
					+ "noDatetimeStringSync=true";

			String userName_tMysqlConnection_2 = OLTP_DB_USER;

			String password_tMysqlConnection_2 = OLTP_DB_PASSWORD;

			java.sql.Connection conn_tMysqlConnection_2 = java.sql.DriverManager
					.getConnection(url_tMysqlConnection_2,
							userName_tMysqlConnection_2,
							password_tMysqlConnection_2);

			conn_tMysqlConnection_2.setAutoCommit(false);

			globalMap.put("conn_" + "tMysqlConnection_2",
					conn_tMysqlConnection_2);

			/**
			 * [tMysqlConnection_2 begin ] stop
			 */
			/**
			 * [tMysqlConnection_2 main ] start
			 */

			currentComponent = "tMysqlConnection_2";

			/**
			 * [tMysqlConnection_2 main ] stop
			 */

			/**
			 * [tMysqlConnection_2 end ] start
			 */

			currentComponent = "tMysqlConnection_2";

			ok_Hash.put("tMysqlConnection_2", true);
			end_Hash.put("tMysqlConnection_2", System.currentTimeMillis());

			/**
			 * [tMysqlConnection_2 end ] stop
			 */

			tMysqlInput_1Process();
			tMysqlCommit_1Process();

		} catch (Exception e) {
			throw new TalendException(this, e);
		}
	}

	private class client_loan_factStruct {
		private static final int DEFAULT_HASHCODE = 1;
		private static final int PRIME = 31;
		private int hashCode = DEFAULT_HASHCODE;
		public boolean hashCodeDirty = true;

		BigDecimal overdue_balance;

		Short days_in_arrears;

		BigDecimal loan_balance;

		int client_loan_account_id;

		short time_id;

		@Override
		public int hashCode() {
			if (this.hashCodeDirty) {
				final int prime = PRIME;
				int result = DEFAULT_HASHCODE;

				result = prime * result + (int) this.client_loan_account_id;

				result = prime * result + (int) this.time_id;

				this.hashCode = result;
				this.hashCodeDirty = false;
			}
			return this.hashCode;
		}

		@Override
		public boolean equals(Object obj) {
			if (this == obj)
				return true;
			if (obj == null)
				return false;
			if (getClass() != obj.getClass())
				return false;
			final client_loan_factStruct other = (client_loan_factStruct) obj;

			if (this.client_loan_account_id != other.client_loan_account_id)
				return false;

			if (this.time_id != other.time_id)
				return false;

			return true;
		}

	}

	private class row1Struct {

		String global_cust_num;

		String global_account_num;

		BigDecimal overdue_balance;

		Short days_in_arrears;

		BigDecimal loan_balance;

	}

	private class after_tMysqlInput_1Struct {
		private static final int DEFAULT_HASHCODE = 1;
		private static final int PRIME = 31;
		private int hashCode = DEFAULT_HASHCODE;
		public boolean hashCodeDirty = true;

		String global_cust_num;

		String global_account_num;

		BigDecimal overdue_balance;

		Short days_in_arrears;

		BigDecimal loan_balance;

		@Override
		public int hashCode() {
			if (this.hashCodeDirty) {
				final int prime = PRIME;
				int result = DEFAULT_HASHCODE;

				result = prime
						* result
						+ ((this.global_cust_num == null) ? 0
								: this.global_cust_num.hashCode());

				result = prime
						* result
						+ ((this.global_account_num == null) ? 0
								: this.global_account_num.hashCode());

				this.hashCode = result;
				this.hashCodeDirty = false;
			}
			return this.hashCode;
		}

		@Override
		public boolean equals(Object obj) {
			if (this == obj)
				return true;
			if (obj == null)
				return false;
			if (getClass() != obj.getClass())
				return false;
			final after_tMysqlInput_1Struct other = (after_tMysqlInput_1Struct) obj;

			if (this.global_cust_num == null) {
				if (other.global_cust_num != null)
					return false;
			} else if (!this.global_cust_num.equals(other.global_cust_num))
				return false;

			if (this.global_account_num == null) {
				if (other.global_account_num != null)
					return false;
			} else if (!this.global_account_num
					.equals(other.global_account_num))
				return false;

			return true;
		}

	}

	public void tMysqlInput_1Process() throws TalendException {
		try {
			tMysqlInput_2Process();
			tMysqlInput_3Process();

			row1Struct row1 = new row1Struct();
			client_loan_factStruct client_loan_fact = new client_loan_factStruct();

			/**
			 * [tMysqlOutput_1 begin ] start
			 */

			ok_Hash.put("tMysqlOutput_1", false);
			start_Hash.put("tMysqlOutput_1", System.currentTimeMillis());
			currentComponent = "tMysqlOutput_1";

			int keyCount_tMysqlOutput_1 = 2;
			if (keyCount_tMysqlOutput_1 < 1) {
				throw new Exception(
						"For update or delete, Schema must have a key");
			}

			int nb_line_tMysqlOutput_1 = 0;
			int nb_line_update_tMysqlOutput_1 = 0;
			int nb_line_inserted_tMysqlOutput_1 = 0;
			int nb_line_deleted_tMysqlOutput_1 = 0;

			int deletedCount_tMysqlOutput_1 = 0;
			int updatedCount_tMysqlOutput_1 = 0;
			int insertedCount_tMysqlOutput_1 = 0;

			String tableName_tMysqlOutput_1 = "client_loan_fact";
			boolean whetherReject_tMysqlOutput_1 = false;

			java.util.Calendar calendar_tMysqlOutput_1 = java.util.Calendar
					.getInstance();
			calendar_tMysqlOutput_1.set(1, 0, 1, 0, 0, 0);
			long year1_tMysqlOutput_1 = calendar_tMysqlOutput_1.getTime()
					.getTime();
			calendar_tMysqlOutput_1.set(10000, 0, 1, 0, 0, 0);
			long year10000_tMysqlOutput_1 = calendar_tMysqlOutput_1.getTime()
					.getTime();
			long date_tMysqlOutput_1;

			java.sql.Connection conn_tMysqlOutput_1 = null;
			conn_tMysqlOutput_1 = (java.sql.Connection) globalMap
					.get("conn_tMysqlConnection_1");

			java.sql.DatabaseMetaData dbMetaData_tMysqlOutput_1 = conn_tMysqlOutput_1
					.getMetaData();
			java.sql.ResultSet rsTable_tMysqlOutput_1 = dbMetaData_tMysqlOutput_1
					.getTables(null, null, null, new String[] { "TABLE" });
			boolean whetherExist_tMysqlOutput_1 = false;
			while (rsTable_tMysqlOutput_1.next()) {
				String table_tMysqlOutput_1 = rsTable_tMysqlOutput_1
						.getString("TABLE_NAME");
				if (table_tMysqlOutput_1.equalsIgnoreCase("client_loan_fact")) {
					whetherExist_tMysqlOutput_1 = true;
					break;
				}
			}
			if (!whetherExist_tMysqlOutput_1) {
				java.sql.Statement stmtCreate_tMysqlOutput_1 = conn_tMysqlOutput_1
						.createStatement();
				stmtCreate_tMysqlOutput_1
						.execute("CREATE TABLE `"
								+ tableName_tMysqlOutput_1
								+ "`(`overdue_balance` DECIMAL(10,3)  ,`days_in_arrears` SMALLINT(6)  ,`loan_balance` DECIMAL(10,3)  ,`client_loan_account_id` INT(10)  not null,`time_id` SMALLINT(5)  not null,primary key(`client_loan_account_id`,`time_id`))");
			}
			java.sql.PreparedStatement pstmtUpdate_tMysqlOutput_1 = conn_tMysqlOutput_1
					.prepareStatement("UPDATE `"
							+ "client_loan_fact"
							+ "` SET `overdue_balance` = ?,`days_in_arrears` = ?,`loan_balance` = ? WHERE `client_loan_account_id` = ? AND `time_id` = ?");

			java.sql.PreparedStatement pstmtInsert_tMysqlOutput_1 = conn_tMysqlOutput_1
					.prepareStatement("INSERT INTO `"
							+ "client_loan_fact"
							+ "` (`overdue_balance`,`days_in_arrears`,`loan_balance`,`client_loan_account_id`,`time_id`) VALUES (?,?,?,?,?)");

			/**
			 * [tMysqlOutput_1 begin ] stop
			 */

			/**
			 * [tMap_1 begin ] start
			 */

			ok_Hash.put("tMap_1", false);
			start_Hash.put("tMap_1", System.currentTimeMillis());
			currentComponent = "tMap_1";

			// ###############################
			// # Lookup's keys initialization

			org.talend.designer.components.commons.AdvancedLookup<row2Struct> tHash_Lookup_row2 = (org.talend.designer.components.commons.AdvancedLookup<row2Struct>) globalMap
					.get("tHash_Lookup_row2");
			row2Struct row2HashKey = new row2Struct();
			row2Struct row2Default = new row2Struct();

			org.talend.designer.components.commons.AdvancedLookup<row3Struct> tHash_Lookup_row3 = (org.talend.designer.components.commons.AdvancedLookup<row3Struct>) globalMap
					.get("tHash_Lookup_row3");
			row3Struct row3HashKey = new row3Struct();
			row3Struct row3Default = new row3Struct();
			// ###############################

			// ###############################
			// # Vars initialization
			// ###############################

			// ###############################
			// # Outputs initialization
			client_loan_factStruct client_loan_fact_tmp = new client_loan_factStruct();
			// ###############################

			/**
			 * [tMap_1 begin ] stop
			 */

			/**
			 * [tMysqlInput_1 begin ] start
			 */

			ok_Hash.put("tMysqlInput_1", false);
			start_Hash.put("tMysqlInput_1", System.currentTimeMillis());
			currentComponent = "tMysqlInput_1";

			int nb_line_tMysqlInput_1 = 0;
			java.sql.Connection conn_tMysqlInput_1 = null;
			conn_tMysqlInput_1 = (java.sql.Connection) globalMap
					.get("conn_tMysqlConnection_2");

			java.sql.Statement stmt_tMysqlInput_1 = conn_tMysqlInput_1
					.createStatement();
			java.sql.ResultSet rs_tMysqlInput_1 = stmt_tMysqlInput_1
					.executeQuery("select c.global_cust_num, a.global_account_num, laa.overdue_balance, laa.days_in_arrears, la.loan_balance from loan_account la, loan_arrears_aging laa, customer c, account a where laa.account_id = la.account_id and laa.customer_id = c.customer_id and a.customer_id = c.customer_id and c.customer_level_id = 1 order by laa.days_in_arrears asc");
			java.sql.ResultSetMetaData rsmd_tMysqlInput_1 = rs_tMysqlInput_1
					.getMetaData();
			int colQtyInRs_tMysqlInput_1 = rsmd_tMysqlInput_1.getColumnCount();

			java.util.Calendar calendar_tMysqlInput_1 = java.util.Calendar
					.getInstance();
			calendar_tMysqlInput_1.set(0, 0, 0, 0, 0, 0);
			java.util.Date year0_tMysqlInput_1 = calendar_tMysqlInput_1
					.getTime();

			globalMap
					.put(
							"tMysqlInput_1_QUERY",
							"select c.global_cust_num, a.global_account_num, laa.overdue_balance, laa.days_in_arrears, la.loan_balance from loan_account la, loan_arrears_aging laa, customer c, account a where laa.account_id = la.account_id and laa.customer_id = c.customer_id and a.customer_id = c.customer_id and c.customer_level_id = 1 order by laa.days_in_arrears asc");

			while (rs_tMysqlInput_1.next()) {
				nb_line_tMysqlInput_1++;

				if (colQtyInRs_tMysqlInput_1 < 1) {

					row1.global_cust_num = null;

				} else {

					if (rs_tMysqlInput_1.getObject(1) != null) {
						row1.global_cust_num = rs_tMysqlInput_1.getString(1);
					} else {

						throw new RuntimeException(
								"Null value in non-Nullable column");
					}

				}

				if (colQtyInRs_tMysqlInput_1 < 2) {

					row1.global_account_num = null;

				} else {

					if (rs_tMysqlInput_1.getObject(2) != null) {
						row1.global_account_num = rs_tMysqlInput_1.getString(2);
					} else {

						throw new RuntimeException(
								"Null value in non-Nullable column");
					}

				}

				if (colQtyInRs_tMysqlInput_1 < 3) {

					row1.overdue_balance = null;

				} else {

					if (rs_tMysqlInput_1.getObject(3) != null) {
						row1.overdue_balance = rs_tMysqlInput_1
								.getBigDecimal(3);
					} else {

						row1.overdue_balance = null;

					}

				}

				if (colQtyInRs_tMysqlInput_1 < 4) {

					row1.days_in_arrears = null;

				} else {

					if (rs_tMysqlInput_1.getObject(4) != null) {
						row1.days_in_arrears = rs_tMysqlInput_1.getShort(4);
					} else {

						row1.days_in_arrears = null;

					}

				}

				if (colQtyInRs_tMysqlInput_1 < 5) {

					row1.loan_balance = null;

				} else {

					if (rs_tMysqlInput_1.getObject(5) != null) {
						row1.loan_balance = rs_tMysqlInput_1.getBigDecimal(5);
					} else {

						row1.loan_balance = null;

					}

				}

				/**
				 * [tMysqlInput_1 begin ] stop
				 */
				/**
				 * [tMysqlInput_1 main ] start
				 */

				currentComponent = "tMysqlInput_1";

				/**
				 * [tMysqlInput_1 main ] stop
				 */
				/**
				 * [tMap_1 main ] start
				 */

				currentComponent = "tMap_1";

				boolean rejectedInnerJoin_tMap_1 = false;

				// ###############################
				// # Input tables (lookups)

				row2HashKey.global_account_num = row1.global_account_num;

				row2Struct row2ObjectFromLookup = null;

				if (!rejectedInnerJoin_tMap_1) { // G 20
					row2HashKey.hashCodeDirty = true;
					tHash_Lookup_row2.get(row2HashKey);

					if (tHash_Lookup_row2.hasResult()) { // G 90

						row2ObjectFromLookup = (row2Struct) tHash_Lookup_row2
								.getResultObject();

					} // G 90
					else { // G 91

						rejectedInnerJoin_tMap_1 = true;

					} // G 91

				} // G 20

				if (tHash_Lookup_row2.getCount(row2HashKey) > 1) {

					System.out
							.println("WARNING: UNIQUE MATCH is configured for the lookup 'row2' and it contains more one result from keys :  row2.global_account_num = '"
									+ row2HashKey.global_account_num + "'");
				}

				row2Struct fromLookup_row2 = null;
				row2Struct row2 = row2Default;

				if (row2ObjectFromLookup != null) {

					fromLookup_row2 = row2ObjectFromLookup;
					row2 = fromLookup_row2;
				}

				boolean forceLooprow3 = false;
				int sizeResultsFromLookup_row3 = -1;

				boolean hasAtLeastOneValidLookup_row3 = false;
				Object[] row3Array = null;

				if (!rejectedInnerJoin_tMap_1) { // G 35
					row3Array = tHash_Lookup_row3.getResultArray();

					if (row3Array.length == 0) {

						forceLooprow3 = true;
					}
				} // G 35
				else { // G 36
					forceLooprow3 = true;
				} // G 36
				sizeResultsFromLookup_row3 = row3Array != null ? row3Array.length
						: -1;

				for (int irow3 = 0; sizeResultsFromLookup_row3 != -1
						&& irow3 < sizeResultsFromLookup_row3 || forceLooprow3; irow3++) {

					row3Struct fromLookup_row3 = null;
					row3Struct row3 = row3Default;

					if (!forceLooprow3) { // G 46

						if (irow3 < row3Array.length) {
							fromLookup_row3 = (row3Struct) row3Array[irow3];
							row3 = fromLookup_row3;
						}

					} // G 46

					forceLooprow3 = false;

					// ###############################

					{ // start of Var scope

						// ###############################
						// # Vars tables
						// ###############################

						// ###############################
						// # Output tables
						client_loan_fact = null;

						if (!rejectedInnerJoin_tMap_1) {

							// # Output table : 'client_loan_fact'
							client_loan_fact_tmp.overdue_balance = row1.overdue_balance;
							client_loan_fact_tmp.days_in_arrears = row1.days_in_arrears;
							client_loan_fact_tmp.loan_balance = row1.loan_balance;
							client_loan_fact_tmp.client_loan_account_id = row2.client_loan_account_id;
							client_loan_fact_tmp.time_id = row3.time_id;
							client_loan_fact = client_loan_fact_tmp;
						} // closing inner join bracket (2)
						// ###############################

					} // end of Var scope

					rejectedInnerJoin_tMap_1 = false;

					/**
					 * [tMap_1 main ] stop
					 */
					// Start of branch "client_loan_fact"
					if (client_loan_fact != null) {

						/**
						 * [tMysqlOutput_1 main ] start
						 */

						currentComponent = "tMysqlOutput_1";

						whetherReject_tMysqlOutput_1 = false;
						int updateFlag_tMysqlOutput_1 = 0;

						pstmtUpdate_tMysqlOutput_1.setBigDecimal(1,
								client_loan_fact.overdue_balance);

						if (client_loan_fact.days_in_arrears == null) {
							pstmtUpdate_tMysqlOutput_1.setNull(2,
									java.sql.Types.INTEGER);

						} else {

							pstmtUpdate_tMysqlOutput_1.setShort(2,
									client_loan_fact.days_in_arrears);

						}

						pstmtUpdate_tMysqlOutput_1.setBigDecimal(3,
								client_loan_fact.loan_balance);

						pstmtUpdate_tMysqlOutput_1.setInt(4,
								client_loan_fact.client_loan_account_id);

						pstmtUpdate_tMysqlOutput_1.setShort(5,
								client_loan_fact.time_id);

						try {
							updateFlag_tMysqlOutput_1 = pstmtUpdate_tMysqlOutput_1
									.executeUpdate();
							updatedCount_tMysqlOutput_1 = updatedCount_tMysqlOutput_1
									+ updateFlag_tMysqlOutput_1;

						} catch (Exception e) {
							whetherReject_tMysqlOutput_1 = true;
							System.err.print(e.getMessage());
						}
						if (updateFlag_tMysqlOutput_1 == 0) {

							pstmtInsert_tMysqlOutput_1.setBigDecimal(1,
									client_loan_fact.overdue_balance);

							if (client_loan_fact.days_in_arrears == null) {
								pstmtInsert_tMysqlOutput_1.setNull(2,
										java.sql.Types.INTEGER);

							} else {

								pstmtInsert_tMysqlOutput_1.setShort(2,
										client_loan_fact.days_in_arrears);

							}

							pstmtInsert_tMysqlOutput_1.setBigDecimal(3,
									client_loan_fact.loan_balance);

							pstmtInsert_tMysqlOutput_1.setInt(4,
									client_loan_fact.client_loan_account_id);

							pstmtInsert_tMysqlOutput_1.setShort(5,
									client_loan_fact.time_id);

							try {
								insertedCount_tMysqlOutput_1 = insertedCount_tMysqlOutput_1
										+ pstmtInsert_tMysqlOutput_1
												.executeUpdate();
							} catch (Exception e) {
								whetherReject_tMysqlOutput_1 = true;
								System.err.print(e.getMessage());
							}
						}
						nb_line_tMysqlOutput_1++;
						/**
						 * [tMysqlOutput_1 main ] stop
						 */

					} // End of branch "client_loan_fact"

				} // close loop of lookup 'row3'

				/**
				 * [tMysqlInput_1 end ] start
				 */

				currentComponent = "tMysqlInput_1";

			}
			stmt_tMysqlInput_1.close();

			globalMap.put("tMysqlInput_1_NB_LINE", nb_line_tMysqlInput_1);

			ok_Hash.put("tMysqlInput_1", true);
			end_Hash.put("tMysqlInput_1", System.currentTimeMillis());

			/**
			 * [tMysqlInput_1 end ] stop
			 */
			/**
			 * [tMap_1 end ] start
			 */

			currentComponent = "tMap_1";

			// ###############################
			// # Lookup hashes releasing
			globalMap.remove("tHash_row2");
			// ###############################

			globalMap.remove("tHash_row3");
			// ###############################

			ok_Hash.put("tMap_1", true);
			end_Hash.put("tMap_1", System.currentTimeMillis());

			/**
			 * [tMap_1 end ] stop
			 */
			/**
			 * [tMysqlOutput_1 end ] start
			 */

			currentComponent = "tMysqlOutput_1";

			if (pstmtUpdate_tMysqlOutput_1 != null) {

				pstmtUpdate_tMysqlOutput_1.close();

			}
			if (pstmtInsert_tMysqlOutput_1 != null) {

				pstmtInsert_tMysqlOutput_1.close();

			}

			nb_line_deleted_tMysqlOutput_1 = nb_line_deleted_tMysqlOutput_1
					+ deletedCount_tMysqlOutput_1;
			nb_line_update_tMysqlOutput_1 = nb_line_update_tMysqlOutput_1
					+ updatedCount_tMysqlOutput_1;
			nb_line_inserted_tMysqlOutput_1 = nb_line_inserted_tMysqlOutput_1
					+ insertedCount_tMysqlOutput_1;

			globalMap.put("tMysqlOutput_1_NB_LINE", nb_line_tMysqlOutput_1);
			globalMap.put("tMysqlOutput_1_NB_LINE_UPDATED",
					nb_line_update_tMysqlOutput_1);
			globalMap.put("tMysqlOutput_1_NB_LINE_INSERTED",
					nb_line_inserted_tMysqlOutput_1);
			globalMap.put("tMysqlOutput_1_NB_LINE_DELETED",
					nb_line_deleted_tMysqlOutput_1);

			ok_Hash.put("tMysqlOutput_1", true);
			end_Hash.put("tMysqlOutput_1", System.currentTimeMillis());

			/**
			 * [tMysqlOutput_1 end ] stop
			 */

		} catch (Exception e) {
			throw new TalendException(this, e);
		}
	}

	public void tMysqlCommit_1Process() throws TalendException {
		try {
			/**
			 * [tMysqlCommit_1 begin ] start
			 */

			ok_Hash.put("tMysqlCommit_1", false);
			start_Hash.put("tMysqlCommit_1", System.currentTimeMillis());
			currentComponent = "tMysqlCommit_1";

			/**
			 * [tMysqlCommit_1 begin ] stop
			 */
			/**
			 * [tMysqlCommit_1 main ] start
			 */

			currentComponent = "tMysqlCommit_1";

			java.sql.Connection conn_tMysqlCommit_1 = (java.sql.Connection) globalMap
					.get("conn_tMysqlConnection_1");
			if (conn_tMysqlCommit_1 != null && !conn_tMysqlCommit_1.isClosed()) {
				conn_tMysqlCommit_1.commit();
			}

			/**
			 * [tMysqlCommit_1 main ] stop
			 */
			/**
			 * [tMysqlCommit_1 end ] start
			 */

			currentComponent = "tMysqlCommit_1";

			ok_Hash.put("tMysqlCommit_1", true);
			end_Hash.put("tMysqlCommit_1", System.currentTimeMillis());

			/**
			 * [tMysqlCommit_1 end ] stop
			 */

		} catch (Exception e) {
			throw new TalendException(this, e);
		}
	}

	private class row5Struct {

		java.util.Date moment;

		String pid;

		String root_pid;

		String father_pid;

		String project;

		String job;

		String context;

		Integer priority;

		String type;

		String origin;

		String message;

		Integer code;

	}

	public void tLogCatcher_1Process() throws TalendException {
		try {

			row5Struct row5 = new row5Struct();

			/**
			 * [tFileOutputDelimited_2 begin ] start
			 */

			ok_Hash.put("tFileOutputDelimited_2", false);
			start_Hash
					.put("tFileOutputDelimited_2", System.currentTimeMillis());
			currentComponent = "tFileOutputDelimited_2";

			String fileName_tFileOutputDelimited_2 = (new java.io.File(
					"client_loan_fact.csv")).getAbsolutePath().replace("\\",
					"/");
			String fullName_tFileOutputDelimited_2 = null;
			String extension_tFileOutputDelimited_2 = null;
			String directory_tFileOutputDelimited_2 = null;
			if ((fileName_tFileOutputDelimited_2.indexOf("/") != -1)) {
				if (fileName_tFileOutputDelimited_2.lastIndexOf(".") < fileName_tFileOutputDelimited_2
						.lastIndexOf("/")) {
					fullName_tFileOutputDelimited_2 = fileName_tFileOutputDelimited_2;
					extension_tFileOutputDelimited_2 = "";
				} else {
					fullName_tFileOutputDelimited_2 = fileName_tFileOutputDelimited_2
							.substring(0, fileName_tFileOutputDelimited_2
									.lastIndexOf("."));
					extension_tFileOutputDelimited_2 = fileName_tFileOutputDelimited_2
							.substring(fileName_tFileOutputDelimited_2
									.lastIndexOf("."));
				}
				directory_tFileOutputDelimited_2 = fileName_tFileOutputDelimited_2
						.substring(0, fileName_tFileOutputDelimited_2
								.lastIndexOf("/"));
			} else {
				if (fileName_tFileOutputDelimited_2.lastIndexOf(".") != -1) {
					fullName_tFileOutputDelimited_2 = fileName_tFileOutputDelimited_2
							.substring(0, fileName_tFileOutputDelimited_2
									.lastIndexOf("."));
					extension_tFileOutputDelimited_2 = fileName_tFileOutputDelimited_2
							.substring(fileName_tFileOutputDelimited_2
									.lastIndexOf("."));
				} else {
					fullName_tFileOutputDelimited_2 = fileName_tFileOutputDelimited_2;
					extension_tFileOutputDelimited_2 = "";
				}
				directory_tFileOutputDelimited_2 = "";
			}

			int nb_line_tFileOutputDelimited_2 = 0;
			int splitEvery_tFileOutputDelimited_2 = 1000;
			int splitedFileNo_tFileOutputDelimited_2 = 0;
			int currentRow_tFileOutputDelimited_2 = 0;

			final String OUT_DELIM_tFileOutputDelimited_2 = /**
															 * Start field
															 * tFileOutputDelimited_2:FIELDSEPARATOR
															 */
			";"/** End field tFileOutputDelimited_2:FIELDSEPARATOR */
			;

			final String OUT_DELIM_ROWSEP_tFileOutputDelimited_2 = /**
																	 * Start
																	 * field
																	 * tFileOutputDelimited_2:ROWSEPARATOR
																	 */
			"\n"/** End field tFileOutputDelimited_2:ROWSEPARATOR */
			;

			// create directory only if not exists
			if (directory_tFileOutputDelimited_2 != null
					&& directory_tFileOutputDelimited_2.trim().length() != 0) {
				java.io.File dir_tFileOutputDelimited_2 = new java.io.File(
						directory_tFileOutputDelimited_2);
				if (!dir_tFileOutputDelimited_2.exists()) {
					dir_tFileOutputDelimited_2.mkdirs();
				}
			}

			java.io.BufferedWriter outtFileOutputDelimited_2 = new java.io.BufferedWriter(
					new java.io.OutputStreamWriter(
							new java.io.FileOutputStream(
									fileName_tFileOutputDelimited_2, true),
							"ISO-8859-15"));
			java.io.File filetFileOutputDelimited_2 = new java.io.File(
					fileName_tFileOutputDelimited_2);

			if (filetFileOutputDelimited_2.length() == 0) {

				outtFileOutputDelimited_2.write("moment");

				outtFileOutputDelimited_2
						.write(OUT_DELIM_tFileOutputDelimited_2);

				outtFileOutputDelimited_2.write("pid");

				outtFileOutputDelimited_2
						.write(OUT_DELIM_tFileOutputDelimited_2);

				outtFileOutputDelimited_2.write("root_pid");

				outtFileOutputDelimited_2
						.write(OUT_DELIM_tFileOutputDelimited_2);

				outtFileOutputDelimited_2.write("father_pid");

				outtFileOutputDelimited_2
						.write(OUT_DELIM_tFileOutputDelimited_2);

				outtFileOutputDelimited_2.write("project");

				outtFileOutputDelimited_2
						.write(OUT_DELIM_tFileOutputDelimited_2);

				outtFileOutputDelimited_2.write("job");

				outtFileOutputDelimited_2
						.write(OUT_DELIM_tFileOutputDelimited_2);

				outtFileOutputDelimited_2.write("context");

				outtFileOutputDelimited_2
						.write(OUT_DELIM_tFileOutputDelimited_2);

				outtFileOutputDelimited_2.write("priority");

				outtFileOutputDelimited_2
						.write(OUT_DELIM_tFileOutputDelimited_2);

				outtFileOutputDelimited_2.write("type");

				outtFileOutputDelimited_2
						.write(OUT_DELIM_tFileOutputDelimited_2);

				outtFileOutputDelimited_2.write("origin");

				outtFileOutputDelimited_2
						.write(OUT_DELIM_tFileOutputDelimited_2);

				outtFileOutputDelimited_2.write("message");

				outtFileOutputDelimited_2
						.write(OUT_DELIM_tFileOutputDelimited_2);

				outtFileOutputDelimited_2.write("code");

				outtFileOutputDelimited_2
						.write(OUT_DELIM_ROWSEP_tFileOutputDelimited_2);
			}

			/**
			 * [tFileOutputDelimited_2 begin ] stop
			 */

			/**
			 * [tLogCatcher_1 begin ] start
			 */

			ok_Hash.put("tLogCatcher_1", false);
			start_Hash.put("tLogCatcher_1", System.currentTimeMillis());
			currentComponent = "tLogCatcher_1";

			for (LogCatcherUtils.LogCatcherMessage lcm : tLogCatcher_1
					.getMessages()) {
				row5.type = lcm.getType();
				row5.origin = (lcm.getOrigin() == null
						|| lcm.getOrigin().length() < 1 ? null : lcm
						.getOrigin());
				row5.priority = lcm.getPriority();
				row5.message = lcm.getMessage();
				row5.code = lcm.getCode();

				row5.moment = java.util.Calendar.getInstance().getTime();

				row5.pid = pid;
				row5.root_pid = rootPid;
				row5.father_pid = fatherPid;

				row5.project = projectName;
				row5.job = jobName;
				row5.context = contextStr;

				/**
				 * [tLogCatcher_1 begin ] stop
				 */
				/**
				 * [tLogCatcher_1 main ] start
				 */

				currentComponent = "tLogCatcher_1";

				/**
				 * [tLogCatcher_1 main ] stop
				 */
				/**
				 * [tFileOutputDelimited_2 main ] start
				 */

				currentComponent = "tFileOutputDelimited_2";

				StringBuilder sb_tFileOutputDelimited_2 = new StringBuilder();

				if (row5.moment != null) {

					sb_tFileOutputDelimited_2.append(

					FormatterUtils.format_Date(row5.moment,
							"yyyy-MM-dd HH:mm:ss")

					);

				}

				sb_tFileOutputDelimited_2
						.append(OUT_DELIM_tFileOutputDelimited_2);

				if (row5.pid != null) {

					sb_tFileOutputDelimited_2.append(

					row5.pid

					);

				}

				sb_tFileOutputDelimited_2
						.append(OUT_DELIM_tFileOutputDelimited_2);

				if (row5.root_pid != null) {

					sb_tFileOutputDelimited_2.append(

					row5.root_pid

					);

				}

				sb_tFileOutputDelimited_2
						.append(OUT_DELIM_tFileOutputDelimited_2);

				if (row5.father_pid != null) {

					sb_tFileOutputDelimited_2.append(

					row5.father_pid

					);

				}

				sb_tFileOutputDelimited_2
						.append(OUT_DELIM_tFileOutputDelimited_2);

				if (row5.project != null) {

					sb_tFileOutputDelimited_2.append(

					row5.project

					);

				}

				sb_tFileOutputDelimited_2
						.append(OUT_DELIM_tFileOutputDelimited_2);

				if (row5.job != null) {

					sb_tFileOutputDelimited_2.append(

					row5.job

					);

				}

				sb_tFileOutputDelimited_2
						.append(OUT_DELIM_tFileOutputDelimited_2);

				if (row5.context != null) {

					sb_tFileOutputDelimited_2.append(

					row5.context

					);

				}

				sb_tFileOutputDelimited_2
						.append(OUT_DELIM_tFileOutputDelimited_2);

				if (row5.priority != null) {

					sb_tFileOutputDelimited_2.append(

					row5.priority

					);

				}

				sb_tFileOutputDelimited_2
						.append(OUT_DELIM_tFileOutputDelimited_2);

				if (row5.type != null) {

					sb_tFileOutputDelimited_2.append(

					row5.type

					);

				}

				sb_tFileOutputDelimited_2
						.append(OUT_DELIM_tFileOutputDelimited_2);

				if (row5.origin != null) {

					sb_tFileOutputDelimited_2.append(

					row5.origin

					);

				}

				sb_tFileOutputDelimited_2
						.append(OUT_DELIM_tFileOutputDelimited_2);

				if (row5.message != null) {

					sb_tFileOutputDelimited_2.append(

					row5.message

					);

				}

				sb_tFileOutputDelimited_2
						.append(OUT_DELIM_tFileOutputDelimited_2);

				if (row5.code != null) {

					sb_tFileOutputDelimited_2.append(

					row5.code

					);

				}

				sb_tFileOutputDelimited_2
						.append(OUT_DELIM_ROWSEP_tFileOutputDelimited_2);

				outtFileOutputDelimited_2.write(sb_tFileOutputDelimited_2
						.toString());

				nb_line_tFileOutputDelimited_2++;

				/**
				 * [tFileOutputDelimited_2 main ] stop
				 */

				/**
				 * [tLogCatcher_1 end ] start
				 */

				currentComponent = "tLogCatcher_1";

			}

			ok_Hash.put("tLogCatcher_1", true);
			end_Hash.put("tLogCatcher_1", System.currentTimeMillis());

			/**
			 * [tLogCatcher_1 end ] stop
			 */
			/**
			 * [tFileOutputDelimited_2 end ] start
			 */

			currentComponent = "tFileOutputDelimited_2";

			outtFileOutputDelimited_2.close();
			globalMap.put("tFileOutputDelimited_2_NB_LINE",
					nb_line_tFileOutputDelimited_2);

			ok_Hash.put("tFileOutputDelimited_2", true);
			end_Hash.put("tFileOutputDelimited_2", System.currentTimeMillis());

			/**
			 * [tFileOutputDelimited_2 end ] stop
			 */

		} catch (Exception e) {
			throw new TalendException(this, e);
		}
	}

	private class row2Struct {
		private static final int DEFAULT_HASHCODE = 1;
		private static final int PRIME = 31;
		private int hashCode = DEFAULT_HASHCODE;
		public boolean hashCodeDirty = true;

		int client_loan_account_id;

		String global_account_num;

		@Override
		public int hashCode() {
			if (this.hashCodeDirty) {
				final int prime = PRIME;
				int result = DEFAULT_HASHCODE;

				result = prime
						* result
						+ ((this.global_account_num == null) ? 0
								: this.global_account_num.hashCode());

				this.hashCode = result;
				this.hashCodeDirty = false;
			}
			return this.hashCode;
		}

		@Override
		public boolean equals(Object obj) {
			if (this == obj)
				return true;
			if (obj == null)
				return false;
			if (getClass() != obj.getClass())
				return false;
			final row2Struct other = (row2Struct) obj;

			if (this.global_account_num == null) {
				if (other.global_account_num != null)
					return false;
			} else if (!this.global_account_num
					.equals(other.global_account_num))
				return false;

			return true;
		}

	}

	public void tMysqlInput_2Process() throws TalendException {
		try {

			row2Struct row2 = new row2Struct();

			/**
			 * [tAdvancedHash_row2 begin ] start
			 */

			ok_Hash.put("tAdvancedHash_row2", false);
			start_Hash.put("tAdvancedHash_row2", System.currentTimeMillis());
			currentComponent = "tAdvancedHash_row2";

			org.talend.designer.components.commons.AdvancedLookup.MATCHING_MODE matchingModeEnum_row2 = org.talend.designer.components.commons.AdvancedLookup.MATCHING_MODE.UNIQUE_MATCH;
			org.talend.designer.components.commons.AdvancedLookup<row2Struct> tHash_Lookup_row2 = org.talend.designer.components.commons.AdvancedLookup
					.<row2Struct> getLookup(matchingModeEnum_row2);
			globalMap.put("tHash_Lookup_row2", tHash_Lookup_row2);

			/**
			 * [tAdvancedHash_row2 begin ] stop
			 */

			/**
			 * [tMysqlInput_2 begin ] start
			 */

			ok_Hash.put("tMysqlInput_2", false);
			start_Hash.put("tMysqlInput_2", System.currentTimeMillis());
			currentComponent = "tMysqlInput_2";

			int nb_line_tMysqlInput_2 = 0;
			java.sql.Connection conn_tMysqlInput_2 = null;
			conn_tMysqlInput_2 = (java.sql.Connection) globalMap
					.get("conn_tMysqlConnection_1");

			java.sql.Statement stmt_tMysqlInput_2 = conn_tMysqlInput_2
					.createStatement();
			java.sql.ResultSet rs_tMysqlInput_2 = stmt_tMysqlInput_2
					.executeQuery("SELECT client_loan_account_dim.client_loan_account_id, client_loan_account_dim.global_account_num FROM client_loan_account_dim");
			java.sql.ResultSetMetaData rsmd_tMysqlInput_2 = rs_tMysqlInput_2
					.getMetaData();
			int colQtyInRs_tMysqlInput_2 = rsmd_tMysqlInput_2.getColumnCount();

			java.util.Calendar calendar_tMysqlInput_2 = java.util.Calendar
					.getInstance();
			calendar_tMysqlInput_2.set(0, 0, 0, 0, 0, 0);
			java.util.Date year0_tMysqlInput_2 = calendar_tMysqlInput_2
					.getTime();

			globalMap
					.put(
							"tMysqlInput_2_QUERY",
							"SELECT client_loan_account_dim.client_loan_account_id, client_loan_account_dim.global_account_num FROM client_loan_account_dim");

			while (rs_tMysqlInput_2.next()) {
				nb_line_tMysqlInput_2++;

				if (colQtyInRs_tMysqlInput_2 < 1) {

					row2.client_loan_account_id = 0;

				} else {

					if (rs_tMysqlInput_2.getObject(1) != null) {
						row2.client_loan_account_id = rs_tMysqlInput_2
								.getInt(1);
					} else {

						throw new RuntimeException(
								"Null value in non-Nullable column");
					}

				}

				if (colQtyInRs_tMysqlInput_2 < 2) {

					row2.global_account_num = null;

				} else {

					if (rs_tMysqlInput_2.getObject(2) != null) {
						row2.global_account_num = rs_tMysqlInput_2.getString(2);
					} else {

						throw new RuntimeException(
								"Null value in non-Nullable column");
					}

				}

				/**
				 * [tMysqlInput_2 begin ] stop
				 */
				/**
				 * [tMysqlInput_2 main ] start
				 */

				currentComponent = "tMysqlInput_2";

				/**
				 * [tMysqlInput_2 main ] stop
				 */

				/**
				 * [tAdvancedHash_row2 main ] start
				 */

				currentComponent = "tAdvancedHash_row2";

				row2Struct row2_HashRow = new row2Struct();

				row2_HashRow.client_loan_account_id = row2.client_loan_account_id;
				row2_HashRow.global_account_num = row2.global_account_num;
				tHash_Lookup_row2.put(row2_HashRow);

				/**
				 * [tAdvancedHash_row2 main ] stop
				 */

				/**
				 * [tMysqlInput_2 end ] start
				 */

				currentComponent = "tMysqlInput_2";

			}
			stmt_tMysqlInput_2.close();

			globalMap.put("tMysqlInput_2_NB_LINE", nb_line_tMysqlInput_2);

			ok_Hash.put("tMysqlInput_2", true);
			end_Hash.put("tMysqlInput_2", System.currentTimeMillis());

			/**
			 * [tMysqlInput_2 end ] stop
			 */

			/**
			 * [tAdvancedHash_row2 end ] start
			 */

			currentComponent = "tAdvancedHash_row2";

			ok_Hash.put("tAdvancedHash_row2", true);
			end_Hash.put("tAdvancedHash_row2", System.currentTimeMillis());

			/**
			 * [tAdvancedHash_row2 end ] stop
			 */

		} catch (Exception e) {
			throw new TalendException(this, e);
		}
	}

	private class row3Struct {

		short time_id;

	}

	public void tMysqlInput_3Process() throws TalendException {
		try {

			row3Struct row3 = new row3Struct();

			/**
			 * [tAdvancedHash_row3 begin ] start
			 */

			ok_Hash.put("tAdvancedHash_row3", false);
			start_Hash.put("tAdvancedHash_row3", System.currentTimeMillis());
			currentComponent = "tAdvancedHash_row3";

			org.talend.designer.components.commons.AdvancedLookup.MATCHING_MODE matchingModeEnum_row3 = org.talend.designer.components.commons.AdvancedLookup.MATCHING_MODE.ALL_ROWS;
			org.talend.designer.components.commons.AdvancedLookup<row3Struct> tHash_Lookup_row3 = org.talend.designer.components.commons.AdvancedLookup
					.<row3Struct> getLookup(matchingModeEnum_row3);
			globalMap.put("tHash_Lookup_row3", tHash_Lookup_row3);

			/**
			 * [tAdvancedHash_row3 begin ] stop
			 */

			/**
			 * [tMysqlInput_3 begin ] start
			 */

			ok_Hash.put("tMysqlInput_3", false);
			start_Hash.put("tMysqlInput_3", System.currentTimeMillis());
			currentComponent = "tMysqlInput_3";

			int nb_line_tMysqlInput_3 = 0;
			java.sql.Connection conn_tMysqlInput_3 = null;
			conn_tMysqlInput_3 = (java.sql.Connection) globalMap
					.get("conn_tMysqlConnection_1");

			java.sql.Statement stmt_tMysqlInput_3 = conn_tMysqlInput_3
					.createStatement();
			java.sql.ResultSet rs_tMysqlInput_3 = stmt_tMysqlInput_3
					.executeQuery("SELECT max(time_id) FROM time_dim");
			java.sql.ResultSetMetaData rsmd_tMysqlInput_3 = rs_tMysqlInput_3
					.getMetaData();
			int colQtyInRs_tMysqlInput_3 = rsmd_tMysqlInput_3.getColumnCount();

			java.util.Calendar calendar_tMysqlInput_3 = java.util.Calendar
					.getInstance();
			calendar_tMysqlInput_3.set(0, 0, 0, 0, 0, 0);
			java.util.Date year0_tMysqlInput_3 = calendar_tMysqlInput_3
					.getTime();

			globalMap.put("tMysqlInput_3_QUERY",
					"SELECT max(time_id) FROM time_dim");

			while (rs_tMysqlInput_3.next()) {
				nb_line_tMysqlInput_3++;

				if (colQtyInRs_tMysqlInput_3 < 1) {

					row3.time_id = 0;

				} else {

					if (rs_tMysqlInput_3.getObject(1) != null) {
						row3.time_id = rs_tMysqlInput_3.getShort(1);
					} else {

						throw new RuntimeException(
								"Null value in non-Nullable column");
					}

				}

				/**
				 * [tMysqlInput_3 begin ] stop
				 */
				/**
				 * [tMysqlInput_3 main ] start
				 */

				currentComponent = "tMysqlInput_3";

				/**
				 * [tMysqlInput_3 main ] stop
				 */

				/**
				 * [tAdvancedHash_row3 main ] start
				 */

				currentComponent = "tAdvancedHash_row3";

				row3Struct row3_HashRow = new row3Struct();

				row3_HashRow.time_id = row3.time_id;
				tHash_Lookup_row3.put(row3_HashRow);

				/**
				 * [tAdvancedHash_row3 main ] stop
				 */

				/**
				 * [tMysqlInput_3 end ] start
				 */

				currentComponent = "tMysqlInput_3";

			}
			stmt_tMysqlInput_3.close();

			globalMap.put("tMysqlInput_3_NB_LINE", nb_line_tMysqlInput_3);

			ok_Hash.put("tMysqlInput_3", true);
			end_Hash.put("tMysqlInput_3", System.currentTimeMillis());

			/**
			 * [tMysqlInput_3 end ] stop
			 */

			/**
			 * [tAdvancedHash_row3 end ] start
			 */

			currentComponent = "tAdvancedHash_row3";

			ok_Hash.put("tAdvancedHash_row3", true);
			end_Hash.put("tAdvancedHash_row3", System.currentTimeMillis());

			/**
			 * [tAdvancedHash_row3 end ] stop
			 */

		} catch (Exception e) {
			throw new TalendException(this, e);
		}
	}

	private class row6Struct {

		java.util.Date moment;

		String pid;

		String father_pid;

		String root_pid;

		Long system_pid;

		String project;

		String job;

		String job_repository_id;

		String job_version;

		String context;

		String origin;

		String message_type;

		String message;

		Long duration;

	}

	public void tStatCatcher_1Process() throws TalendException {
		try {

			row6Struct row6 = new row6Struct();

			/**
			 * [tFileOutputDelimited_1 begin ] start
			 */

			ok_Hash.put("tFileOutputDelimited_1", false);
			start_Hash
					.put("tFileOutputDelimited_1", System.currentTimeMillis());
			currentComponent = "tFileOutputDelimited_1";

			String fileName_tFileOutputDelimited_1 = (new java.io.File(
					"client_loan_fact_stats.csv")).getAbsolutePath().replace(
					"\\", "/");
			String fullName_tFileOutputDelimited_1 = null;
			String extension_tFileOutputDelimited_1 = null;
			String directory_tFileOutputDelimited_1 = null;
			if ((fileName_tFileOutputDelimited_1.indexOf("/") != -1)) {
				if (fileName_tFileOutputDelimited_1.lastIndexOf(".") < fileName_tFileOutputDelimited_1
						.lastIndexOf("/")) {
					fullName_tFileOutputDelimited_1 = fileName_tFileOutputDelimited_1;
					extension_tFileOutputDelimited_1 = "";
				} else {
					fullName_tFileOutputDelimited_1 = fileName_tFileOutputDelimited_1
							.substring(0, fileName_tFileOutputDelimited_1
									.lastIndexOf("."));
					extension_tFileOutputDelimited_1 = fileName_tFileOutputDelimited_1
							.substring(fileName_tFileOutputDelimited_1
									.lastIndexOf("."));
				}
				directory_tFileOutputDelimited_1 = fileName_tFileOutputDelimited_1
						.substring(0, fileName_tFileOutputDelimited_1
								.lastIndexOf("/"));
			} else {
				if (fileName_tFileOutputDelimited_1.lastIndexOf(".") != -1) {
					fullName_tFileOutputDelimited_1 = fileName_tFileOutputDelimited_1
							.substring(0, fileName_tFileOutputDelimited_1
									.lastIndexOf("."));
					extension_tFileOutputDelimited_1 = fileName_tFileOutputDelimited_1
							.substring(fileName_tFileOutputDelimited_1
									.lastIndexOf("."));
				} else {
					fullName_tFileOutputDelimited_1 = fileName_tFileOutputDelimited_1;
					extension_tFileOutputDelimited_1 = "";
				}
				directory_tFileOutputDelimited_1 = "";
			}

			int nb_line_tFileOutputDelimited_1 = 0;
			int splitEvery_tFileOutputDelimited_1 = 1000;
			int splitedFileNo_tFileOutputDelimited_1 = 0;
			int currentRow_tFileOutputDelimited_1 = 0;

			final String OUT_DELIM_tFileOutputDelimited_1 = /**
															 * Start field
															 * tFileOutputDelimited_1:FIELDSEPARATOR
															 */
			";"/** End field tFileOutputDelimited_1:FIELDSEPARATOR */
			;

			final String OUT_DELIM_ROWSEP_tFileOutputDelimited_1 = /**
																	 * Start
																	 * field
																	 * tFileOutputDelimited_1:ROWSEPARATOR
																	 */
			"\n"/** End field tFileOutputDelimited_1:ROWSEPARATOR */
			;

			// create directory only if not exists
			if (directory_tFileOutputDelimited_1 != null
					&& directory_tFileOutputDelimited_1.trim().length() != 0) {
				java.io.File dir_tFileOutputDelimited_1 = new java.io.File(
						directory_tFileOutputDelimited_1);
				if (!dir_tFileOutputDelimited_1.exists()) {
					dir_tFileOutputDelimited_1.mkdirs();
				}
			}

			java.io.BufferedWriter outtFileOutputDelimited_1 = new java.io.BufferedWriter(
					new java.io.OutputStreamWriter(
							new java.io.FileOutputStream(
									fileName_tFileOutputDelimited_1, true),
							"ISO-8859-15"));
			java.io.File filetFileOutputDelimited_1 = new java.io.File(
					fileName_tFileOutputDelimited_1);

			if (filetFileOutputDelimited_1.length() == 0) {

				outtFileOutputDelimited_1.write("moment");

				outtFileOutputDelimited_1
						.write(OUT_DELIM_tFileOutputDelimited_1);

				outtFileOutputDelimited_1.write("pid");

				outtFileOutputDelimited_1
						.write(OUT_DELIM_tFileOutputDelimited_1);

				outtFileOutputDelimited_1.write("father_pid");

				outtFileOutputDelimited_1
						.write(OUT_DELIM_tFileOutputDelimited_1);

				outtFileOutputDelimited_1.write("root_pid");

				outtFileOutputDelimited_1
						.write(OUT_DELIM_tFileOutputDelimited_1);

				outtFileOutputDelimited_1.write("system_pid");

				outtFileOutputDelimited_1
						.write(OUT_DELIM_tFileOutputDelimited_1);

				outtFileOutputDelimited_1.write("project");

				outtFileOutputDelimited_1
						.write(OUT_DELIM_tFileOutputDelimited_1);

				outtFileOutputDelimited_1.write("job");

				outtFileOutputDelimited_1
						.write(OUT_DELIM_tFileOutputDelimited_1);

				outtFileOutputDelimited_1.write("job_repository_id");

				outtFileOutputDelimited_1
						.write(OUT_DELIM_tFileOutputDelimited_1);

				outtFileOutputDelimited_1.write("job_version");

				outtFileOutputDelimited_1
						.write(OUT_DELIM_tFileOutputDelimited_1);

				outtFileOutputDelimited_1.write("context");

				outtFileOutputDelimited_1
						.write(OUT_DELIM_tFileOutputDelimited_1);

				outtFileOutputDelimited_1.write("origin");

				outtFileOutputDelimited_1
						.write(OUT_DELIM_tFileOutputDelimited_1);

				outtFileOutputDelimited_1.write("message_type");

				outtFileOutputDelimited_1
						.write(OUT_DELIM_tFileOutputDelimited_1);

				outtFileOutputDelimited_1.write("message");

				outtFileOutputDelimited_1
						.write(OUT_DELIM_tFileOutputDelimited_1);

				outtFileOutputDelimited_1.write("duration");

				outtFileOutputDelimited_1
						.write(OUT_DELIM_ROWSEP_tFileOutputDelimited_1);
			}

			/**
			 * [tFileOutputDelimited_1 begin ] stop
			 */

			/**
			 * [tStatCatcher_1 begin ] start
			 */

			ok_Hash.put("tStatCatcher_1", false);
			start_Hash.put("tStatCatcher_1", System.currentTimeMillis());
			currentComponent = "tStatCatcher_1";

			for (StatCatcherUtils.StatCatcherMessage scm : tStatCatcher_1
					.getMessages()) {
				row6.pid = pid;
				row6.root_pid = rootPid;
				row6.father_pid = fatherPid;
				row6.project = projectName;
				row6.job = jobName;
				row6.context = contextStr;
				row6.origin = (scm.getOrigin() == null
						|| scm.getOrigin().length() < 1 ? null : scm
						.getOrigin());
				row6.message = scm.getMessage();
				row6.duration = scm.getDuration();
				row6.moment = scm.getMoment();
				row6.message_type = scm.getMessageType();
				row6.job_version = scm.getJobVersion();
				row6.job_repository_id = scm.getJobId();
				row6.system_pid = scm.getSystemPid();

				/**
				 * [tStatCatcher_1 begin ] stop
				 */
				/**
				 * [tStatCatcher_1 main ] start
				 */

				currentComponent = "tStatCatcher_1";

				/**
				 * [tStatCatcher_1 main ] stop
				 */
				/**
				 * [tFileOutputDelimited_1 main ] start
				 */

				currentComponent = "tFileOutputDelimited_1";

				StringBuilder sb_tFileOutputDelimited_1 = new StringBuilder();

				if (row6.moment != null) {

					sb_tFileOutputDelimited_1.append(

					FormatterUtils.format_Date(row6.moment,
							"yyyy-MM-dd HH:mm:ss")

					);

				}

				sb_tFileOutputDelimited_1
						.append(OUT_DELIM_tFileOutputDelimited_1);

				if (row6.pid != null) {

					sb_tFileOutputDelimited_1.append(

					row6.pid

					);

				}

				sb_tFileOutputDelimited_1
						.append(OUT_DELIM_tFileOutputDelimited_1);

				if (row6.father_pid != null) {

					sb_tFileOutputDelimited_1.append(

					row6.father_pid

					);

				}

				sb_tFileOutputDelimited_1
						.append(OUT_DELIM_tFileOutputDelimited_1);

				if (row6.root_pid != null) {

					sb_tFileOutputDelimited_1.append(

					row6.root_pid

					);

				}

				sb_tFileOutputDelimited_1
						.append(OUT_DELIM_tFileOutputDelimited_1);

				if (row6.system_pid != null) {

					sb_tFileOutputDelimited_1.append(

					row6.system_pid

					);

				}

				sb_tFileOutputDelimited_1
						.append(OUT_DELIM_tFileOutputDelimited_1);

				if (row6.project != null) {

					sb_tFileOutputDelimited_1.append(

					row6.project

					);

				}

				sb_tFileOutputDelimited_1
						.append(OUT_DELIM_tFileOutputDelimited_1);

				if (row6.job != null) {

					sb_tFileOutputDelimited_1.append(

					row6.job

					);

				}

				sb_tFileOutputDelimited_1
						.append(OUT_DELIM_tFileOutputDelimited_1);

				if (row6.job_repository_id != null) {

					sb_tFileOutputDelimited_1.append(

					row6.job_repository_id

					);

				}

				sb_tFileOutputDelimited_1
						.append(OUT_DELIM_tFileOutputDelimited_1);

				if (row6.job_version != null) {

					sb_tFileOutputDelimited_1.append(

					row6.job_version

					);

				}

				sb_tFileOutputDelimited_1
						.append(OUT_DELIM_tFileOutputDelimited_1);

				if (row6.context != null) {

					sb_tFileOutputDelimited_1.append(

					row6.context

					);

				}

				sb_tFileOutputDelimited_1
						.append(OUT_DELIM_tFileOutputDelimited_1);

				if (row6.origin != null) {

					sb_tFileOutputDelimited_1.append(

					row6.origin

					);

				}

				sb_tFileOutputDelimited_1
						.append(OUT_DELIM_tFileOutputDelimited_1);

				if (row6.message_type != null) {

					sb_tFileOutputDelimited_1.append(

					row6.message_type

					);

				}

				sb_tFileOutputDelimited_1
						.append(OUT_DELIM_tFileOutputDelimited_1);

				if (row6.message != null) {

					sb_tFileOutputDelimited_1.append(

					row6.message

					);

				}

				sb_tFileOutputDelimited_1
						.append(OUT_DELIM_tFileOutputDelimited_1);

				if (row6.duration != null) {

					sb_tFileOutputDelimited_1.append(

					row6.duration

					);

				}

				sb_tFileOutputDelimited_1
						.append(OUT_DELIM_ROWSEP_tFileOutputDelimited_1);

				outtFileOutputDelimited_1.write(sb_tFileOutputDelimited_1
						.toString());

				nb_line_tFileOutputDelimited_1++;

				/**
				 * [tFileOutputDelimited_1 main ] stop
				 */

				/**
				 * [tStatCatcher_1 end ] start
				 */

				currentComponent = "tStatCatcher_1";

			}

			ok_Hash.put("tStatCatcher_1", true);
			end_Hash.put("tStatCatcher_1", System.currentTimeMillis());

			/**
			 * [tStatCatcher_1 end ] stop
			 */
			/**
			 * [tFileOutputDelimited_1 end ] start
			 */

			currentComponent = "tFileOutputDelimited_1";

			outtFileOutputDelimited_1.close();
			globalMap.put("tFileOutputDelimited_1_NB_LINE",
					nb_line_tFileOutputDelimited_1);

			ok_Hash.put("tFileOutputDelimited_1", true);
			end_Hash.put("tFileOutputDelimited_1", System.currentTimeMillis());

			/**
			 * [tFileOutputDelimited_1 end ] stop
			 */

		} catch (Exception e) {
			throw new TalendException(this, e);
		}
	}

	public static boolean watch = false;
	public static int portStats = 3334;
	public static int portTraces = 4334;
	public static String clientHost;
	public static String defaultClientHost = "localhost";
	public static String contextStr = "Default";
	public static String pid = "0";
	public static String rootPid = null;
	public static String fatherPid = null;

	private static java.util.Properties context_param = new java.util.Properties();

	public static String status = "";

	public static void main(String[] args) {
		int exitCode = runJob(args);
		System.exit(exitCode);
	}

	public static synchronized int runJob(String[] args) {

		init();

		String lastStr = "";
		for (String arg : args) {
			if (arg.equalsIgnoreCase("--context_param")) {
				lastStr = arg;
			} else if (lastStr.equals("")) {
				evalParam(arg);
			} else {
				evalParam(lastStr + " " + arg);
				lastStr = "";
			}
		}

		if (clientHost == null) {
			clientHost = defaultClientHost;
		}

		pid = TalendString.getAsciiRandomString(6);
		if (rootPid == null) {
			rootPid = pid;
		}
		if (fatherPid == null) {
			fatherPid = pid;
		}

		try {
			java.io.InputStream inContext = ClientLoanFactLoader.class
					.getClassLoader()
					.getResourceAsStream(
							"org_mifos_etl/clientloanfactloader/contexts/Default.properties");
			if (inContext != null) {
				defaultProps.load(inContext);
				inContext.close();
				context = new java.util.Properties(defaultProps);
			}

			if (contextStr.compareTo("Default") != 0) {
				inContext = ClientLoanFactLoader.class.getClassLoader()
						.getResourceAsStream(
								"org_mifos_etl/clientloanfactloader/contexts/"
										+ contextStr + ".properties");
				if (inContext != null) {
					context.load(inContext);
					inContext.close();
				}
			}

			if (!context_param.isEmpty()) {
				context.putAll(context_param);
			}

			OLTP_DB_HOST = (String) context.getProperty("OLTP_DB_HOST");

			OLTP_DB_PORT = (String) context.getProperty("OLTP_DB_PORT");

			OLTP_DB_SCHEMA = (String) context.getProperty("OLTP_DB_SCHEMA");

			OLTP_DB_USER = (String) context.getProperty("OLTP_DB_USER");

			OLTP_DB_PASSWORD = (String) context.getProperty("OLTP_DB_PASSWORD");

			OLAP_DB_HOST = (String) context.getProperty("OLAP_DB_HOST");

			OLAP_DB_PORT = (String) context.getProperty("OLAP_DB_PORT");

			OLAP_DB_SCHEMA = (String) context.getProperty("OLAP_DB_SCHEMA");

			OLAP_DB_USER = (String) context.getProperty("OLAP_DB_USER");

			OLAP_DB_PASSWORD = (String) context.getProperty("OLAP_DB_PASSWORD");

		} catch (java.io.IOException ie) {
			System.err.println("Could not load context " + contextStr);
			ie.printStackTrace();
		}

		long end = 0;
		long start = System.currentTimeMillis();
		final ClientLoanFactLoader ClientLoanFactLoaderClass = new ClientLoanFactLoader();
		ClientLoanFactLoaderClass.tStatCatcher_1.addMessage("begin");
		try {
			ClientLoanFactLoaderClass.tStatCatcher_1Process();
		} catch (Exception e) {
			e.printStackTrace();
		}
		try {
			errorCode = null;
			ClientLoanFactLoaderClass.tJava_1Process();
			status = "end";
		} catch (TalendException e_tJava_1) {
			status = "failure";
			e_tJava_1.printStackTrace();

		} finally {
		}
		end = System.currentTimeMillis();
		if (watch) {
			System.out.println((end - start) + " milliseconds");
		}
		ClientLoanFactLoaderClass.tStatCatcher_1.addMessage(
				status == "" ? "end" : status, (end - start));
		try {
			ClientLoanFactLoaderClass.tStatCatcher_1Process();
		} catch (Exception e) {
			e.printStackTrace();
		}
		if (errorCode == null) {
			return status != null && status.equals("failure") ? 1 : 0;
		} else {
			return errorCode.intValue();
		}
	}

	public static void evalParam(String arg) {
		if (arg.startsWith("--watch")) {
			watch = true;
		} else if (arg.startsWith("--stat_port=")) {
			portStats = Integer.parseInt(arg.substring(12));
		} else if (arg.startsWith("--trace_port=")) {
			portTraces = Integer.parseInt(arg.substring(13));
		} else if (arg.startsWith("--client_host=")) {
			clientHost = arg.substring(14);
		} else if (arg.startsWith("--context=")) {
			contextStr = arg.substring(10);
		} else if (arg.startsWith("--father_pid=")) {
			fatherPid = arg.substring(13);
		} else if (arg.startsWith("--root_pid=")) {
			rootPid = arg.substring(11);
		} else if (arg.startsWith("--context_param")) {
			String keyValue = arg.substring(16);
			int index = -1;
			if (keyValue != null && (index = keyValue.indexOf('=')) > -1) {
				context_param.put(keyValue.substring(0, index), keyValue
						.substring(index + 1));
			}
		}

	}

	private static void init() {

		defaultProps.clear();
		context.clear();
		errorCode = null;
		currentComponent = "";
		start_Hash.clear();
		end_Hash.clear();
		ok_Hash.clear();
		globalMap.clear();
		watch = false;
		portStats = 3334;
		portTraces = 4334;
		clientHost = null;
		defaultClientHost = "localhost";
		contextStr = "Default";
		pid = "0";
		rootPid = null;
		fatherPid = null;
		context_param.clear();
		status = "";
	}
}
/*******************************************************************************
 * 74681 characters generated by Talend OpenStudio on the April 2, 2008 4:20:56
 * PM BST
 ******************************************************************************/
