//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.09.15 at 06:28:52 PM GMT+05:30 
//


package org.mifos.framework.util.jaxb.dependency;


/**
 * Java content class for DependenciesType complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/E:/MiFos/WorkSpace/src/org/mifos/framework/util/resources/Dependency.xsd line 10)
 * <p>
 * <pre>
 * &lt;complexType name="DependenciesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dependency" type="{}DependencyType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface DependenciesType {


    /**
     * Gets the value of the Dependency property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the Dependency property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDependency().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link org.mifos.framework.util.jaxb.dependency.DependencyType}
     * 
     */
    java.util.List getDependency();

}
