//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.09.15 at 06:28:52 PM GMT+05:30 
//


package org.mifos.framework.util.jaxb.dependency;


/**
 * Java content class for DependencyType complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/E:/MiFos/WorkSpace/src/org/mifos/framework/util/resources/Dependency.xsd line 15)
 * <p>
 * <pre>
 * &lt;complexType name="DependencyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="valueobject" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="businessprocessor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dao" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface DependencyType {


    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getType();

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setType(java.lang.String value);

    /**
     * Gets the value of the dao property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getDao();

    /**
     * Sets the value of the dao property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setDao(java.lang.String value);

    /**
     * Gets the value of the businessprocessor property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getBusinessprocessor();

    /**
     * Sets the value of the businessprocessor property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setBusinessprocessor(java.lang.String value);

    /**
     * Gets the value of the valueobject property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getValueobject();

    /**
     * Sets the value of the valueobject property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setValueobject(java.lang.String value);

}
