INSERT INTO LOAN_PERF_HISTORY (ACCOUNT_ID,NO_OF_PAYMENTS,NO_OF_MISSED_PAYMENTS,DAYS_IN_ARREARS,LOAN_MATURITY_DATE)
SELECT ACCOUNT_ID,0,0,0,NULL FROM LOAN_ACCOUNT WHERE ACCOUNT_ID NOT IN (SELECT ACCOUNT_ID FROM LOAN_PERF_HISTORY) ;

UPDATE SAVINGS_ACCOUNT SA,ACCOUNT A SET SA.ACTIVATION_DATE=A.UPDATED_DATE
WHERE A.ACCOUNT_ID=SA.ACCOUNT_ID AND  SA.ACTIVATION_DATE IS NULL AND A.ACCOUNT_STATE_ID NOT IN (13,14,15);

UPDATE ACCOUNT_TRXN SET INSTALLMENT_ID=1 WHERE INSTALLMENT_ID IS NULL AND ACCOUNT_ID IN (SELECT ACCOUNT_ID FROM CUSTOMER_ACCOUNT);

INSERT INTO CUSTOMER_TRXN_DETAIL
SELECT ATRXN.ACCOUNT_TRXN_ID, ATRXN.AMOUNT,2,0,2,0,2 FROM ACCOUNT_TRXN ATRXN , CUSTOMER_ACCOUNT CA 
WHERE ATRXN.ACCOUNT_ID=CA.ACCOUNT_ID AND ATRXN.ACCOUNT_TRXN_ID NOT IN 
(SELECT ACCOUNT_TRXN_ID FROM CUSTOMER_TRXN_DETAIL) ;


