ALTER TABLE PERSONNEL_MOVEMENT MODIFY PERSONNEL_ID SMALLINT,MODIFY START_DATE DATE,MODIFY END_DATE DATE;
ALTER TABLE PERSONNEL_MOVEMENT DROP  VERSION_NO,ADD STATUS SMALLINT;
ALTER TABLE PERSONNEL_MOVEMENT DROP FOREIGN KEY personnel_movement_ibfk_2;
ALTER TABLE PERSONNEL_MOVEMENT DROP KEY CREATED_BY;
ALTER TABLE PERSONNEL_MOVEMENT CHANGE CREATED_BY UPDATED_BY SMALLINT,CHANGE CREATED_DATE UPDATED_DATE DATE;
ALTER TABLE PERSONNEL_MOVEMENT ADD FOREIGN KEY (UPDATED_BY) REFERENCES PERSONNEL(PERSONNEL_ID) ON DELETE NO ACTION ON UPDATE NO ACTION; 


ALTER TABLE PERSONNEL_CUSTOM_FIELD ADD PERSONNEL_CUSTOM_FIELD_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY;