UPDATE CUSTOMER_ATTENDANCE_TYPES SET DESCRIPTION = "Leave" WHERE ATTENDANCE_ID = 3;
UPDATE CUSTOMER_ATTENDANCE_TYPES SET DESCRIPTION = "Late Present" WHERE ATTENDANCE_ID = 4;

UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = "A" WHERE LOOKUP_ID = 195;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = "L" WHERE LOOKUP_ID = 196;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = "LP" WHERE LOOKUP_ID = 197;

