ALTER TABLE LOAN_OFFERING DROP FOREIGN KEY LOAN_OFFERING_PENALTY_GLCODE;
ALTER TABLE LOAN_OFFERING DROP FOREIGN KEY LOAN_OFFERING_PENALTY;
ALTER TABLE LOAN_OFFERING DROP FOREIGN KEY LOAN_OFFERING_INTEREST_CALC_RULE;

ALTER TABLE LOAN_OFFERING DROP INTEREST_CALC_RULE_ID;
ALTER TABLE LOAN_OFFERING DROP PENALTY_ID;
ALTER TABLE LOAN_OFFERING DROP PENALTY_GRACE;
ALTER TABLE LOAN_OFFERING DROP PENALTY_RATE;
ALTER TABLE LOAN_OFFERING DROP PENALTIES_GLCODE_ID;

ALTER TABLE ROLE MODIFY COLUMN DESCRIPTION VARCHAR(50) NULL;