UPDATE CONFIG_KEY_VALUE_INTEGER
   SET CONFIGURATION_KEY = 'sessionTimeout',
       CONFIGURATION_VALUE = 60
 WHERE CONFIGURATION_ID = 2;

UPDATE DATABASE_VERSION SET DATABASE_VERSION = 165 WHERE DATABASE_VERSION = 166;
