ALTER TABLE LOAN_SUMMARY DROP CONSTRAINT FK_LOAN_SUMMARY_RAW_AMOUNT_TOTAL;
ALTER TABLE LOAN_SUMMARY DROP COLUMN RAW_AMOUNT_TOTAL;
ALTER TABLE LOAN_SUMMARY DROP COLUMN RAW_AMOUNT_TOTAL_CURRENCY_ID;


UPDATE DATABASE_VERSION SET DATABASE_VERSION=191 WHERE DATABASE_VERSION=192;