DELETE FROM LOOKUP_VALUE_LOCALE WHERE LOOKUP_VALUE_ID = 919;
DELETE FROM LOOKUP_VALUE_LOCALE WHERE LOOKUP_VALUE_ID = 920;
DELETE FROM LOOKUP_VALUE_LOCALE WHERE LOOKUP_VALUE_ID = 921;
DELETE FROM LOOKUP_VALUE WHERE LOOKUP_ID = 574;
DELETE FROM LOOKUP_VALUE WHERE LOOKUP_ID = 575;
DELETE FROM LOOKUP_VALUE WHERE LOOKUP_ID = 576;
DELETE FROM LOOKUP_ENTITY WHERE ENTITY_ID = 91;

ALTER TABLE HOLIDAY 
	CHANGE HOLIDAY_FROM_DATE HOLIDAY_DATE DATE NOT NULL,
	CHANGE HOLIDAY_NAME HOLIDATY_NAME VARCHAR( 100 ) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
	CHANGE OFFICE_ID OFFICE_ID SMALLINT( 6 ) NOT NULL,
	DROP HOLIDAY_THRU_DATE,
	DROP REPAYMENT_RULE_ID;

DROP TABLE REPAYMENT_RULE;

UPDATE DATABASE_VERSION SET DATABASE_VERSION = 102 WHERE DATABASE_VERSION = 103;
