CREATE TABLE COLLATERAL_TYPE (
  COLLATERAL_TYPE_ID SMALLINT NOT NULL,
  LOOKUP_ID INTEGER NOT NULL,
  PRIMARY KEY(COLLATERAL_TYPE_ID),
  FOREIGN KEY(LOOKUP_ID)
    REFERENCES LOOKUP_VALUE(LOOKUP_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)
ENGINE=InnoDB CHARACTER SET utf8;

INSERT INTO COLLATERAL_TYPE(COLLATERAL_TYPE_ID, LOOKUP_ID) VALUES(1, 109);
INSERT INTO COLLATERAL_TYPE(COLLATERAL_TYPE_ID, LOOKUP_ID) VALUES(2, 110);

ALTER TABLE LOAN_ACCOUNT DROP FOREIGN KEY fk_loan_col_type_id;
ALTER TABLE LOAN_ACCOUNT DROP FOREIGN KEY fk_loan_bus_act_id;
ALTER TABLE LOAN_ACCOUNT DROP FOREIGN KEY fk_loan_prd_off_id;
ALTER TABLE LOAN_ACCOUNT DROP FOREIGN KEY fk_loan_acc_id;
ALTER TABLE LOAN_ACCOUNT DROP FOREIGN KEY fk_loan_account;
ALTER TABLE LOAN_ACCOUNT DROP FOREIGN KEY fk_loan_rankday;
ALTER TABLE LOAN_ACCOUNT DROP FOREIGN KEY fk_loan_monthweek;

ALTER TABLE LOAN_ACCOUNT MODIFY COLUMN COLLATERAL_TYPE_ID SMALLINT;

UPDATE LOAN_ACCOUNT SET COLLATERAL_TYPE_ID=1 WHERE COLLATERAL_TYPE_ID=109;
UPDATE LOAN_ACCOUNT SET COLLATERAL_TYPE_ID=2 WHERE COLLATERAL_TYPE_ID=110;

ALTER TABLE LOAN_ACCOUNT ADD FOREIGN KEY(COLLATERAL_TYPE_ID) REFERENCES COLLATERAL_TYPE(COLLATERAL_TYPE_ID);
ALTER TABLE LOAN_ACCOUNT ADD FOREIGN KEY(BUSINESS_ACTIVITIES_ID) REFERENCES LOOKUP_VALUE(LOOKUP_ID);
ALTER TABLE LOAN_ACCOUNT ADD FOREIGN KEY(PRD_OFFERING_ID) REFERENCES PRD_OFFERING(PRD_OFFERING_ID);
ALTER TABLE LOAN_ACCOUNT ADD FOREIGN KEY(PARENT_ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID);
ALTER TABLE LOAN_ACCOUNT ADD CONSTRAINT fk_loan_account FOREIGN KEY(PARENT_ACCOUNT_ID) REFERENCES LOAN_ACCOUNT(ACCOUNT_ID);
ALTER TABLE LOAN_ACCOUNT ADD CONSTRAINT fk_loan_rankday FOREIGN KEY(MONTH_RANK) REFERENCES RANK_DAYS_MASTER(RANK_DAYS_MASTER_ID);
ALTER TABLE LOAN_ACCOUNT ADD CONSTRAINT fk_loan_monthweek FOREIGN KEY(MONTH_WEEK) REFERENCES WEEK_DAYS_MASTER(WEEK_DAYS_MASTER_ID);

UPDATE DATABASE_VERSION SET DATABASE_VERSION = 181 WHERE DATABASE_VERSION = 182;
