
-- Entity: ClientStatus
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Partial Application' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'ClientStatus-PartialApplication');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Application Pending Approval' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'ClientStatus-ApplicationPendingApproval');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Active' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'ClientStatus-Active');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'On Hold' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'ClientStatus-OnHold');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Cancelled' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'ClientStatus-Cancelled');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Closed' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'ClientStatus-Closed');
-- Entity: GroupStatus
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Partial Application' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'GroupStatus-PartialApplication');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Application Pending Approval' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'GroupStatus-ApplicationPendingApproval');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Active' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'GroupStatus-Active');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'On Hold' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'GroupStatus-OnHold');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Cancelled' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'GroupStatus-Cancelled');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Closed' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'GroupStatus-Closed');
-- Entity: CenterStatus
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Active' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'CenterStatus-Active');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Inactive' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'CenterStatus-Inactive');
-- Entity: OfficeStatus
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Active' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'OfficeStatus-Active');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Inactive' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'OfficeStatus-Inactive');
-- Entity: AccountState
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Partial Application' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'AccountState-PartialApplication');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Application Pending Approval' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'AccountState-ApplicationPendingApproval');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Application Approved' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'AccountState-ApplicationApproved');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Disbursed to LO' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'AccountState-DisbursedToLo');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Active in Good Standing' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'AccountState-ActiveInGoodStanding');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Closed- Obligation met' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'AccountState-ClosedObligationMet');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Closed- Written Off' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'AccountState-ClosedWrittenOff');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Closed- Rescheduled' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'AccountState-ClosedRescheduled');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Active in Bad Standing' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'AccountState-ActiveInBadStanding');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Cancel' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'AccountState-Cancel');
-- Entity: PersonnelStatus
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Active' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'PersonnelStatus-Active');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Inactive' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'PersonnelStatus-Inactive');
-- Entity: GroupFlag
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Withdraw' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'GroupFlag-Withdraw');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Rejected' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'GroupFlag-Rejected');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Blacklisted' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'GroupFlag-Blacklisted');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Duplicate' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'GroupFlag-Duplicate');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Transferred' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'GroupFlag-Transferred');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Left Program' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'GroupFlag-LeftProgram');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Other' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'GroupFlag-Other');
-- Entity: FeeType
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Maintenance Fee' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'FeeType-MaintenanceFee');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Consultancy Fee' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'FeeType-ConsultancyFee');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Training Fee' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'FeeType-TrainingFee');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Meeting Charges' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'FeeType-MeetingCharges');
-- Entity: Titles
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'President' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Titles-President');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Vice President' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Titles-VicePresident');
-- Entity: PovertyStatus
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Very poor' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'PovertyStatus-VeryPoor');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Poor' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'PovertyStatus-Poor');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Non-poor' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'PovertyStatus-NonPoor');
-- Entity: Center
-- Entity: Group
-- Entity: Client
-- Entity: Office
-- Entity: Salutation
-- Entity: Gender
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Male' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Gender-Male');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Female' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Gender-Female');
-- Entity: MaritalStatus
-- Entity: Citizenship
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Hindu' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Citizenship-Hindu');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Muslim' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Citizenship-Muslim');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Christian' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Citizenship-Christian');
-- Entity: Ethinicity
-- Entity: EducationLevel
-- Entity: BusinessActivities
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Daily Labour' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'BusinessActivities-DailyLabour');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Agriculture' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'BusinessActivities-Agriculture');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Animal Husbandry' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'BusinessActivities-AnimalHusbandry');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Micro Enterprise' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'BusinessActivities-MicroEnterprise');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Production' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'BusinessActivities-Production');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Trading' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'BusinessActivities-Trading');
-- Entity: Handicapped
-- Entity: ClientFormedBy
-- Entity: PostalCode
-- Entity: ProductState
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Active' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'ProductState-Active');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Inactive' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'ProductState-Inactive');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Close' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'ProductState-Close');
-- Entity: Loan
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Loan' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Loan-Loan');
-- Entity: Savings
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Savings' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Savings-Savings');
-- Entity: PersonnelTitles
-- Entity: PersonnelLevels
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Loan Officer' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'PersonnelLevels-LoanOfficer');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Non Loan Officer' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'PersonnelLevels-NonLoanOfficer');
-- Entity: OfficeLevels
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Head Office' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'OfficeLevels-HeadOffice');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Regional Office' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'OfficeLevels-RegionalOffice');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Divisional Office' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'OfficeLevels-DivisionalOffice');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Area Office' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'OfficeLevels-AreaOffice');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Branch Office' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'OfficeLevels-BranchOffice');
-- Entity: PrdApplicableMaster
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Clients' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'PrdApplicableMaster-Clients');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Groups' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'PrdApplicableMaster-Groups');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Centers' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'PrdApplicableMaster-Centers');
-- Entity: WeekDays
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Sunday' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'WeekDays-Sunday');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Monday' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'WeekDays-Monday');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Tuesday' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'WeekDays-Tuesday');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Wednesday' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'WeekDays-Wednesday');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Thursday' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'WeekDays-Thursday');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Friday' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'WeekDays-Friday');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Saturday' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'WeekDays-Saturday');
-- Entity: InterestTypes
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Flat' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'InterestTypes-Flat');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Declining Balance' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'InterestTypes-DecliningBalance');
-- Entity: CategoryType
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'All Customers' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'CategoryType-AllCustomers');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Client' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'CategoryType-Client');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Group' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'CategoryType-Group');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Center' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'CategoryType-Center');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'All Product Types' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'CategoryType-AllProductTypes');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Loans' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'CategoryType-Loans');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Savings' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'CategoryType-Savings');
-- Entity: InterestCalcRule
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Always Recalculate' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'InterestCalcRule-AlwaysRecalculate');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Never Recalculate' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'InterestCalcRule-NeverRecalculate');
-- Entity: GracePeriodTypes
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'None' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'GracePeriodTypes-None');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Grace on all repayments' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'GracePeriodTypes-GraceOnAllRepayments');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Principal only grace' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'GracePeriodTypes-PrincipalOnlyGrace');
-- Entity: DayRank
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'First' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'DayRank-First');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Second' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'DayRank-Second');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Third' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'DayRank-Third');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Fourth' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'DayRank-Fourth');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Last' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'DayRank-Last');
-- Entity: CollateralTypes
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Type 1' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'CollateralTypes-Type1');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Type 2' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'CollateralTypes-Type2');
-- Entity: OfficeCode
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Code 1' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'OfficeCode-Code1');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Code 2' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'OfficeCode-Code2');
-- Entity: ProductCategoryStatus
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Inactive' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'ProductCategoryStatus-Inactive');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Active' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'ProductCategoryStatus-Active');
-- Entity: ProductStatus
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Active' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'ProductStatus-Active');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Inactive' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'ProductStatus-Inactive');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Closed' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'ProductStatus-Closed');
-- Entity: SavingsType
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Mandatory' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'SavingsType-Mandatory');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Voluntary' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'SavingsType-Voluntary');
-- Entity: RecommendedAmtUnit
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Per Individual' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'RecommendedAmtUnit-PerIndividual');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Complete Group' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'RecommendedAmtUnit-CompleteGroup');
-- Entity: IntCalTypes
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Minimum Balance' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'IntCalTypes-MinimumBalance');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Average Balance' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'IntCalTypes-AverageBalance');
-- Entity: YESNO
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Yes' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'YESNO-Yes');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'No' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'YESNO-No');
-- Entity: AccountType
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Loan' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'AccountType-Loan');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Saving' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'AccountType-Saving');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Customer' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'AccountType-Customer');
-- Entity: SpouseFather
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Spouse' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'SpouseFather-Spouse');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Father' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'SpouseFather-Father');
-- Entity: CustomerStatus
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Customer Account Active' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'CustomerStatus-CustomerAccountActive');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Customer Account InActive' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'CustomerStatus-CustomerAccountInactive');
-- Entity: FeePayment
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Upfront' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'FeePayment-Upfront');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Time Of Disburstment' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'FeePayment-TimeOfDisburstment');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Time of First Loan Repayment ' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'FeePayment-TimeOfFirstLoanRepayment');
-- Entity: FeeFormulaMaster
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Loan Amount' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'FeeFormulaMaster-LoanAmount');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Loan Amount+Interest' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'FeeFormulaMaster-LoanAmountInterest');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Interest' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'FeeFormulaMaster-Interest');
-- Entity: PersonnelStatus_Unused
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Active' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'PersonnelStatusUnused-Active');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Inactive' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'PersonnelStatusUnused-Inactive');
-- Entity: Personnel
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Personnel' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Personnel-Personnel');
-- Entity: ExternalId
-- Entity: FeeStatus
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Active' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'FeeStatus-Active');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'InActive' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'FeeStatus-Inactive');
-- Entity: AccountAction
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Loan Repayment' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'AccountAction-LoanRepayment');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Penalty' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'AccountAction-Penalty');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Miscellenous Penalty' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'AccountAction-MiscellenousPenalty');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Fee' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'AccountAction-Fee');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Miscellenous Fee' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'AccountAction-MiscellenousFee');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Deposit' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'AccountAction-Deposit');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Withdrawal' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'AccountAction-Withdrawal');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Payment' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'AccountAction-Payment');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Adjustment' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'AccountAction-Adjustment');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Disbursal' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'AccountAction-Disbursal');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Interest_Posting' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'AccountAction-Interest_posting');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Customer Account Repayment' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'AccountAction-CustomerAccountRepayment');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Customer Adjustment' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'AccountAction-CustomerAdjustment');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Savings Adjustment' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'AccountAction-SavingsAdjustment');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Loan Written Off' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'AccountAction-LoanWrittenOff');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Waive Off Due' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'AccountAction-WaiveOffDue');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Waive Off Over Due' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'AccountAction-WaiveOffOverDue');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Loan Reversal' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'AccountAction-LoanReversal');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Disrbursal amount Reversal' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'AccountAction-DisrbursalAmountReversal');
-- Entity: AccountFlags
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Withdraw' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'AccountFlags-Withdraw');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Rejected' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'AccountFlags-Rejected');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Other' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'AccountFlags-Other');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Loan reversal' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'AccountFlags-LoanReversal');
-- Entity: PaymentType
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Cash' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'PaymentType-Cash');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Voucher' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'PaymentType-Voucher');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Cheque' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'PaymentType-Cheque');
-- Entity: SavingsStatus
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Partial Application' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'SavingsStatus-PartialApplication');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Application Pending Approval' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'SavingsStatus-ApplicationPendingApproval');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Cancelled' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'SavingsStatus-Cancelled');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Active' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'SavingsStatus-Active');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Closed' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'SavingsStatus-Closed');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Inactive' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'SavingsStatus-Inactive');
-- Entity: Position
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Center Leader' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Position-CenterLeader');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Center Secretary' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Position-CenterSecretary');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Group Leader' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Position-GroupLeader');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Group Secretary' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Position-GroupSecretary');
-- Entity: Language
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'English' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Language-English');
-- Entity: CustomerAttendance
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'P' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'CustomerAttendance-P');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Ab' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'CustomerAttendance-Ab');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'AL' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'CustomerAttendance-Al');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'L' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'CustomerAttendance-L');
-- Entity: FinancialAction
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Principal' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'FinancialAction-Principal');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Interest' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'FinancialAction-Interest');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Fees' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'FinancialAction-Fees');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Penalty' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'FinancialAction-Penalty');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Rounding Adjustments' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'FinancialAction-RoundingAdjustments');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Mandatory Deposit' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'FinancialAction-MandatoryDeposit');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Voluntory Deposit' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'FinancialAction-VoluntoryDeposit');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Mandatory Withdrawal' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'FinancialAction-MandatoryWithdrawal');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Voluntory Withdrawal' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'FinancialAction-VoluntoryWithdrawal');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Reversal Adjustment' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'FinancialAction-ReversalAdjustment');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Savings Interest Posting' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'FinancialAction-SavingsInterestPosting');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Interest_Posting' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'FinancialAction-Interest_posting');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Loan Disbursement' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'FinancialAction-LoanDisbursement');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Misc Fee' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'FinancialAction-MiscFee');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Misc Penalty' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'FinancialAction-MiscPenalty');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Customer Account Fees Posting' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'FinancialAction-CustomerAccountFeesPosting');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Customer Adjustment' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'FinancialAction-CustomerAdjustment');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Mandatory Deposit Adjustment' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'FinancialAction-MandatoryDepositAdjustment');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Voluntory Deposit Adjustment' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'FinancialAction-VoluntoryDepositAdjustment');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Mandatory Withdrawal Adjustment' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'FinancialAction-MandatoryWithdrawalAdjustment');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Voluntory Withdrawal Adjustment' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'FinancialAction-VoluntoryWithdrawalAdjustment');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Loan Written Off' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'FinancialAction-LoanWrittenOff');
-- Entity: BulkEntry
-- Entity: SavingsAccountFlag
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Withdraw' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'SavingsAccountFlag-Withdraw');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Rejected' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'SavingsAccountFlag-Rejected');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Blacklisted' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'SavingsAccountFlag-Blacklisted');
-- Entity: Address3
-- Entity: City
-- Entity: Interest
-- Entity: LoanPurposes
-- Entity: State
-- Entity: Address1
-- Entity: Address2
-- Entity: GovernmentId
-- Entity: Permissions
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Organization Management' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-OrganizationManagement');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Funds' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Funds');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can create funds' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanCreateFunds');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can modify funds' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanModifyFunds');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Fees' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Fees');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can define new fee type' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanDefineNewFeeType');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can modify fee information' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanModifyFeeInformation');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Checklists' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Checklists');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can define new checklist type' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanDefineNewChecklistType');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can modify checklist information' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanModifyChecklistInformation');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Office management' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-OfficeManagement');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Offices' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Offices');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can create new office' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanCreateNewOffice');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can modify office information' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanModifyOfficeInformation');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'User management' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-UserManagement');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Personnel' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Personnel');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can create new system users' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanCreateNewSystemUsers');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can modify user information' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanModifyUserInformation');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can unlock a user' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanUnlockAUser');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Roles' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Roles');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can create new role' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanCreateNewRole');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can modify a role' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanModifyARole');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can delete a role' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanDeleteARole');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Client management' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-ClientManagement');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Clients' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Clients');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can create new Client in save for later state' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Clients-CanCreateNewClientInSaveForLaterState');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can create new Client in submit for approval state' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Clients-CanCreateNewClientInSubmitForApprovalState');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can change state to partial application' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Clients-CanChangeStateToPartialApplication');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can change state to active' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Clients-CanChangeStateToActive');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can change state to Cancelled' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Clients-CanChangeStateToCancelled');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can change state to On Hold' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Clients-CanChangeStateToOnHold');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can change state to Closed' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Clients-CanChangeStateToClosed');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can change state to application pending approval' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Clients-CanChangeStateToApplicationPendingApproval');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can make payments to Client accounts' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Clients-CanMakePaymentsToClientAccounts');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can make adjustment entries to Client account' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Clients-CanMakeAdjustmentEntriesToClientAccount');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can waive a due amount' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Clients-CanWaiveADueAmount');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can remove fee types from Client account' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Clients-CanRemoveFeeTypesFromClientAccount');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can add notes to Client' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Clients-CanAddNotesToClient');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can edit MFI information' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Clients-CanEditMfiInformation');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can edit group membership' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Clients-CanEditGroupMembership');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can edit office membership' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Clients-CanEditOfficeMembership');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can edit meeting schedule' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Clients-CanEditMeetingSchedule');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can add/edit historical data' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Clients-CanAddEditHistoricalData');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can edit fee amount attached to the account' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Clients-CanEditFeeAmountAttachedToTheAccount');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can Blacklist a Client' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Clients-CanBlacklistAClient');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Groups' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Groups');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can create new group in save for later state' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Groups-CanCreateNewGroupInSaveForLaterState');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can create new group in submit for approval state' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Groups-CanCreateNewGroupInSubmitForApprovalState');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can change state to partial application' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Groups-CanChangeStateToPartialApplication');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can change state to active' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Groups-CanChangeStateToActive');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can change state to Cancelled' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Groups-CanChangeStateToCancelled');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can change state to On Hold' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Groups-CanChangeStateToOnHold');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can change state to Closed' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Groups-CanChangeStateToClosed');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can change state to application pending approval' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Groups-CanChangeStateToApplicationPendingApproval');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can make payments to group accounts' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Groups-CanMakePaymentsToGroupAccounts');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can make adjustment entries to group account' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Groups-CanMakeAdjustmentEntriesToGroupAccount');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can waive a due amount' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Groups-CanWaiveADueAmount');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can remove fee types from group account' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Groups-CanRemoveFeeTypesFromGroupAccount');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can add notes to group' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Groups-CanAddNotesToGroup');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can edit Group information' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Groups-CanEditGroupInformation');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can edit Center Clientship' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Groups-CanEditCenterClientship');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can edit office membership' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Groups-CanEditOfficeMembership');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can edit meeting schedule' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Groups-CanEditMeetingSchedule');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can add/edit historical data' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Groups-CanAddEditHistoricalData');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can edit fee amount attached to the account' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Groups-CanEditFeeAmountAttachedToTheAccount');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can Blacklist a group' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Groups-CanBlacklistAGroup');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Centers' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Centers');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can create new Center ' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Centers-CanCreateNewCenter');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can modify Center information ' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Centers-CanModifyCenterInformation');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can edit Center status' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Centers-CanEditCenterStatus');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can make payments to Center accounts' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Centers-CanMakePaymentsToCenterAccounts');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can make adjustment entries to Center account' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Centers-CanMakeAdjustmentEntriesToCenterAccount');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can waive a due amount' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Centers-CanWaiveADueAmount');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can remove fee types from Center account' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Centers-CanRemoveFeeTypesFromCenterAccount');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can add notes to Center records' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Centers-CanAddNotesToCenterRecords');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can edit fee amount attached to the account' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Centers-CanEditFeeAmountAttachedToTheAccount');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Product definition' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-ProductDefinition');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Product Categories' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-ProductCategories');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can define new product categories' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanDefineNewProductCategories');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can edit product category information' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanEditProductCategoryInformation');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Loan Products' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-LoanProducts');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can define new loan product instance' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanDefineNewLoanProductInstance');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can edit loan product instances' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanEditLoanProductInstances');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Savings Products' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-SavingsProducts');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can define new Savings product instance' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanDefineNewSavingsProductInstance');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can edit Savings product instances' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanEditSavingsProductInstances');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Loan management' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-LoanManagement');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Loan Processing' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-LoanProcessing');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can create new loan account in Save for later state' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanCreateNewLoanAccountInSaveForLaterState');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can create new loan account in Submit for approval state' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanCreateNewLoanAccountInSubmitForApprovalState');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can change state to partial application' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-LoanProcessing-CanChangeStateToPartialApplication');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can change state to Approved' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-LoanProcessing-CanChangeStateToApproved');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can change state to Cancelled' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-LoanProcessing-CanChangeStateToCancelled');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can change state to Disbursed to LO' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-LoanProcessing-CanChangeStateToDisbursedToLo');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can change state to pending approval' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-LoanProcessing-CanChangeStateToPendingApproval');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can change state to Closed- Written off' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-LoanProcessing-CanChangeStateToClosedWrittenOff');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can change state to Closed-rescheduled' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-LoanProcessing-CanChangeStateToClosedRescheduled');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Loan Transactions' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-LoanTransactions');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can make payment to the account' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanMakePaymentToTheAccount');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can make adjustment entry to the account' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanMakeAdjustmentEntryToTheAccount');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can waive penalty' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanWaivePenalty');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can waive a fee installment' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanWaiveAFeeInstallment');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can remove fee types attached to the account' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanRemoveFeeTypesAttachedToTheAccount');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can specify meeting schedule' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Clients-CanSpecifyMeetingSchedule');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can specify meeting schedule' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Groups-CanSpecifyMeetingSchedule');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can edit personal information' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Clients-CanEditPersonalInformation');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can edit meeting schedule ' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Centers-CanEditMeetingSchedule');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can specify meeting schedule' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Centers-CanSpecifyMeetingSchedule');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can edit Loan account information' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanEditLoanAccountInformation');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can apply charges to loans ' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanApplyChargesToLoans');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can edit self information' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanEditSelfInformation');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Savings Management' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-SavingsManagement');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can create new Savings account in Save for later state' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanCreateNewSavingsAccountInSaveForLaterState');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can update Savings account' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanUpdateSavingsAccount');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can close Savings account' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanCloseSavingsAccount');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can change state to partial application' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-SavingsManagement-CanChangeStateToPartialApplication');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Reports Management' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-ReportsManagement');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can Administer Reports' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanAdministerReports');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can Preview Reports' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanPreviewReports');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can upload new reports' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanUploadNewReports');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Client Detail' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-ClientDetail');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Center' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Center');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Status' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Status');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Performance' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Performance');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Loan Product Detail' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-LoanProductDetail');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Analysis' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Analysis');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Miscellaneous' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Miscellaneous');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can view Client Summary.& History Report' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanViewClientSummaryHistoryReport');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can view Client Product Wise History Report' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanViewClientProductWiseHistoryReport');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can view Client Settlement info Report' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanViewClientSettlementInfoReport');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can view Client Loan repayment schedule' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanViewClientLoanRepaymentSchedule');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can view Client Fees, Charges and Penalties report' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanViewClientFeesChargesAndPenaltiesReport');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can view Client pending approval report' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanViewClientPendingApprovalReport');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can view Clients without Savings Account' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanViewClientsWithoutSavingsAccount');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can view Collection sheet' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanViewCollectionSheet');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can view Daily Cash Confirmation Report - Staff Wise' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanViewDailyCashConfirmationReportStaffWise');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can view Daily Cash Flow Report - Branch' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanViewDailyCashFlowReportBranch');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can view Fund Requirement Report' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanViewFundRequirementReport');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can view Daily Transaction Summary report' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanViewDailyTransactionSummaryReport');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can view Branch Performance Status Report' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanViewBranchPerformanceStatusReport');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can view Area Performance Status Report' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanViewAreaPerformanceStatusReport');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can view Division Performance Status Report' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanViewDivisionPerformanceStatusReport');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can view Region Performance Status Report' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanViewRegionPerformanceStatusReport');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can view Grameen Koota Performance Status Report' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanViewGrameenKootaPerformanceStatusReport');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can view Staff Performance Report' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanViewStaffPerformanceReport');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can view Outreach Report' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanViewOutreachReport');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can view Center Summary Report' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanViewCenterSummaryReport');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can view Loan Product Distribution - Activity Wise, Size Wize, Product Wise, Sequency Wise' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanViewLoanProductDistributionActivityWiseSizeWizeProductWiseSequencyWise');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can view Branch Due disbursement Report' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanViewBranchDueDisbursementReport');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can view Loans pending approval report' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanViewLoansPendingApprovalReport');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can view Loan Accounts reports' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanViewLoanAccountsReports');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can view Daily Portfolio quality data report - Aging analysis' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanViewDailyPortfolioQualityDataReportAgingAnalysis');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can view Center Meeting Schedule' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanViewCenterMeetingSchedule');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can repay loan' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanRepayLoan');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can add notes to loan account' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanAddNotesToLoanAccount');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can change state to pending approval' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-SavingsManagement-CanChangeStateToPendingApproval');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can change state to cancel' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-SavingsManagement-CanChangeStateToCancel');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can change state to active' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-SavingsManagement-CanChangeStateToActive');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can change state to inactive' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-SavingsManagement-CanChangeStateToInactive');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can blacklist Savings account' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanBlacklistSavingsAccount');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can create new Savings account in submit for approval state' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanCreateNewSavingsAccountInSubmitForApprovalState');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Not implemented' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-NotImplemented');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can do adjustments for savings account' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanDoAdjustmentsForSavingsAccount');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can waive due deposits for Savings account' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanWaiveDueDepositsForSavingsAccount');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can waive over due deposits for Savings account' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanWaiveOverDueDepositsForSavingsAccount');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can disburse loan' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanDisburseLoan');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can make deposit/withdrawal to savings account' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanMakeDepositWithdrawalToSavingsAccount');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can add notes to Savings account' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanAddNotesToSavingsAccount');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can approve loans in bulk ' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanApproveLoansInBulk');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can modify lateness/dormancy definition' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanModifyLatenessDormancyDefinition');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can modify office hierarchy' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanModifyOfficeHierarchy');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can Add Notes to Personnel' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanAddNotesToPersonnel');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Bulk' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Bulk');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can Enter Collection Sheet Data' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanEnterCollectionSheetData');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can apply charges to Client accounts' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Clients-CanApplyChargesToClientAccounts');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can apply charges to group accounts' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Groups-CanApplyChargesToGroupAccounts');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can apply charges to Center accounts' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Centers-CanApplyChargesToCenterAccounts');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can create multiple Loan accounts' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanCreateMultipleLoanAccounts');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can reverse Loan disbursals' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanReverseLoanDisbursals');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Configuration Management' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-ConfigurationManagement');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can define labels' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanDefineLabels');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can define hidden/mandatory fields' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanDefineHiddenMandatoryFields');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can remove clients from groups' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Clients-CanRemoveClientsFromGroups');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can view Detailed Aging of Portfolio at Risk' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanViewDetailedAgingOfPortfolioAtRisk');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can add an existing client to a group' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-Clients-CanAddAnExistingClientToAGroup');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Product Mix' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-ProductMix');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can define product mix' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanDefineProductMix');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can edit product mix' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanEditProductMix');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can view Active Loans By Loan Officer' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanViewActiveLoansByLoanOfficer');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can Define Lookup Values' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanDefineLookupValues');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can upload report template' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanUploadReportTemplate');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can view reports' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanViewReports');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can edit report information' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanEditReportInformation');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can adjust payment when account status is "closed-obligation met"' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanAdjustPaymentWhenAccountStatusIsClosedObligationMet');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can redo Loan disbursals' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanRedoLoanDisbursals');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can define Accepted Payment Type' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanDefineAcceptedPaymentType');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can define new report category' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanDefineNewReportCategory');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can view report category' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanViewReportCategory');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can delete report category' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanDeleteReportCategory');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can download report template' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanDownloadReportTemplate');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can define custom fields' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanDefineCustomFields');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can upload admin documents' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanUploadAdminDocuments');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Can view admin documents' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'Permissions-CanViewAdminDocuments');
-- Entity: ServiceCharge
-- Entity: feeUpdationType
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Applies to existing & future accounts' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'feeUpdationType-AppliesToExistingFutureAccounts');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Applies to future accounts' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'feeUpdationType-AppliesToFutureAccounts');
-- Entity: FeeFrequency
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Periodic' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'FeeFrequency-Periodic');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'One Time' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'FeeFrequency-OneTime');
-- Entity: RepaymentRule
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Same Day' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'RepaymentRule-SameDay');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Next Meeting/Repayment' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'RepaymentRule-NextMeetingRepayment');
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = 'Next Working Day' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LOOKUP_VALUE WHERE LOOKUP_NAME = 'RepaymentRule-NextWorkingDay');


UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanCreateNewClientInSaveForLaterState' WHERE LOOKUP_ID = 
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 35);
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanCreateNewClientInSubmitForApprovalState' WHERE LOOKUP_ID =
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 36);
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanChangeStateToPartialApplication' WHERE LOOKUP_ID =
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 37);
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanChangeStateToActive' WHERE LOOKUP_ID =
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 38);
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanChangeStateToCancelled' WHERE LOOKUP_ID =
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 39);
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanChangeStateToOnHold' WHERE LOOKUP_ID =
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 40);
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanChangeStateToClosed' WHERE LOOKUP_ID =
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 41);
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanChangeStateToApplicationPendingApproval' WHERE LOOKUP_ID =
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 42);
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanMakePaymentsToClientAccounts' WHERE LOOKUP_ID =
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 43);
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanMakeAdjustmentEntriesToClientAccount' WHERE LOOKUP_ID =
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 44);
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanWaiveADueAmount' WHERE LOOKUP_ID =
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 46);
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanRemoveFeeTypesFromClientAccount' WHERE LOOKUP_ID =
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 47);
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanAddNotesToClient' WHERE LOOKUP_ID =
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 48);
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanEditMfiInformation' WHERE LOOKUP_ID =
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 49);
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanEditGroupMembership' WHERE LOOKUP_ID =
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 50);
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanEditOfficeMembership' WHERE LOOKUP_ID =
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 51);
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanEditMeetingSchedule' WHERE LOOKUP_ID =
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 52);
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanAddEditHistoricalData' WHERE LOOKUP_ID =
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 53);
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanEditFeeAmountAttachedToTheAccount' WHERE LOOKUP_ID =
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 54);
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanBlacklistAClient' WHERE LOOKUP_ID =
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 55);
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanSpecifyMeetingSchedule' WHERE LOOKUP_ID =
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 121);
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanEditPersonalInformation' WHERE LOOKUP_ID =
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 126);
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanApplyChargesToClientAccounts' WHERE LOOKUP_ID =
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 198);
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanRemoveClientsFromGroups' WHERE LOOKUP_ID =
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 206);
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanAddAnExistingClientToAGroup' WHERE LOOKUP_ID =
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 208);

UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanCreateNewGroupInSaveForLaterState' WHERE LOOKUP_ID =
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 57);
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanCreateNewGroupInSubmitForApprovalState' WHERE LOOKUP_ID =
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 58);
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanChangeStateToPartialApplication' WHERE LOOKUP_ID =
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 59);
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanChangeStateToActive' WHERE LOOKUP_ID =
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 60);
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanChangeStateToCancelled' WHERE LOOKUP_ID =
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 61);
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanChangeStateToOnHold' WHERE LOOKUP_ID =
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 62);
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanChangeStateToClosed' WHERE LOOKUP_ID =
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 63);
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanChangeStateToApplicationPendingApproval' WHERE LOOKUP_ID =
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 64);
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanMakePaymentsToGroupAccounts' WHERE LOOKUP_ID =
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 65);
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanMakeAdjustmentEntriesToGroupAccount' WHERE LOOKUP_ID =
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 66);
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanWaiveADueAmount' WHERE LOOKUP_ID =
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 68);
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanRemoveFeeTypesFromGroupAccount' WHERE LOOKUP_ID =
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 69);
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanAddNotesToGroup' WHERE LOOKUP_ID =
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 70);
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanEditGroupInformation' WHERE LOOKUP_ID =
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 71);
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanEditCenterClientship' WHERE LOOKUP_ID =
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 72);
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanEditOfficeMembership' WHERE LOOKUP_ID =
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 73);
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanEditMeetingSchedule' WHERE LOOKUP_ID =
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 74);
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanAddEditHistoricalData' WHERE LOOKUP_ID =
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 75);
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanEditFeeAmountAttachedToTheAccount' WHERE LOOKUP_ID =
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 76);
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanBlacklistAGroup' WHERE LOOKUP_ID =
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 77);
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanSpecifyMeetingSchedule' WHERE LOOKUP_ID =
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 122);
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanApplyChargesToGroupAccounts' WHERE LOOKUP_ID =
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 199);

UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanChangeStateToPartialApplication' WHERE LOOKUP_ID =
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 103);
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanChangeStateToApproved' WHERE LOOKUP_ID =
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 104);
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanChangeStateToCancelled' WHERE LOOKUP_ID =
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 105);
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanChangeStateToDisbursedToLo' WHERE LOOKUP_ID =
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 106);
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanChangeStateToPendingApproval' WHERE LOOKUP_ID =
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 108);
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanChangeStateToClosedWrittenOff' WHERE LOOKUP_ID =
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 109);
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanChangeStateToClosedRescheduled' WHERE LOOKUP_ID =
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 110);


UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanChangeStateToPartialApplication' WHERE LOOKUP_ID =
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 140);
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanChangeStateToPendingApproval' WHERE LOOKUP_ID =
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 180);
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanChangeStateToCancel' WHERE LOOKUP_ID =
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 181);
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanChangeStateToActive' WHERE LOOKUP_ID =
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 182);
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanChangeStateToInactive' WHERE LOOKUP_ID =
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 183);

UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanCreateNewCenter' WHERE LOOKUP_ID = 
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 79);
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanModifyCenterInformation' WHERE LOOKUP_ID = 
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 80);
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanEditCenterStatus' WHERE LOOKUP_ID = 
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 81);
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanMakePaymentsToCenterAccounts' WHERE LOOKUP_ID = 
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 82);
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanMakeAdjustmentEntriesToCenterAccount' WHERE LOOKUP_ID = 
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 83);
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanWaiveADueAmount' WHERE LOOKUP_ID = 
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 85);
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanRemoveFeeTypesFromCenterAccount' WHERE LOOKUP_ID = 
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 86);
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanAddNotesToCenterRecords' WHERE LOOKUP_ID = 
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 87);
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanEditFeeAmountAttachedToTheAccount' WHERE LOOKUP_ID = 
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 88);
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanEditMeetingSchedule' WHERE LOOKUP_ID = 
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 127);
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanSpecifyMeetingSchedule' WHERE LOOKUP_ID = 
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 128);
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'Permissions-CanApplyChargesToCenterAccounts' WHERE LOOKUP_ID = 
(SELECT ACTIVITY_NAME_LOOKUP_ID FROM ACTIVITY WHERE ACTIVITY_ID = 200);

UPDATE LOOKUP_ENTITY SET ENTITY_NAME = 'PersonnelStatus',DESCRIPTION = 'Personnel Status' WHERE ENTITY_ID = 6;


UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'PersonnelStatus-Active' WHERE LOOKUP_ID = 26;
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'PersonnelStatus-Inactive' WHERE LOOKUP_ID = 27;


UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'LOAN_PARTIAL_APPLICATION' WHERE LOOKUP_ID = 17;
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'LOAN_PENDING_APPROVAL' WHERE LOOKUP_ID = 18;
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'LOAN_APPROVED' WHERE LOOKUP_ID = 19;
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'LOAN_DISBURSED_TO_LOAN_OFFICER' WHERE LOOKUP_ID = 20;
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'LOAN_ACTIVE_IN_GOOD_STANDING' WHERE LOOKUP_ID = 21;
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'LOAN_CLOSED_OBLIGATIONS_MET' WHERE LOOKUP_ID = 22;
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'LOAN_CLOSED_WRITTEN_OFF' WHERE LOOKUP_ID = 23;
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'LOAN_CLOSED_RESCHEDULED' WHERE LOOKUP_ID = 24;
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'LOAN_ACTIVE_IN_BAD_STANDING' WHERE LOOKUP_ID = 25;
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'LOAN_CANCELLED' WHERE LOOKUP_ID = 141;

UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'SAVINGS_PARTIAL_APPLICATION' WHERE LOOKUP_ID = 181;
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'SAVINGS_PENDING_APPROVAL' WHERE LOOKUP_ID = 182;
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'SAVINGS_CANCELLED' WHERE LOOKUP_ID = 183;
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'SAVINGS_ACTIVE' WHERE LOOKUP_ID = 184;
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'SAVINGS_CLOSED' WHERE LOOKUP_ID = 185;
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'SAVINGS_INACTIVE' WHERE LOOKUP_ID = 210;

UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'CUSTOMER_ACCOUNT_ACTIVE' WHERE LOOKUP_ID = 142;
UPDATE LOOKUP_VALUE SET LOOKUP_NAME = 'CUSTOMER_ACCOUNT_INACTIVE' WHERE LOOKUP_ID = 143;

-- Potentially unused or orphaned lookup_values (commented out because of upgrade issues)
--INSERT INTO LOOKUP_VALUE(LOOKUP_ID,ENTITY_ID,LOOKUP_NAME) VALUES(65, 34, ' ');
--INSERT INTO LOOKUP_VALUE(LOOKUP_ID,ENTITY_ID,LOOKUP_NAME) VALUES(71, 35, ' ');
--INSERT INTO LOOKUP_VALUE(LOOKUP_ID,ENTITY_ID,LOOKUP_NAME) VALUES(90, 39, ' ');
--INSERT INTO LOOKUP_VALUE(LOOKUP_ID,ENTITY_ID,LOOKUP_NAME) VALUES(223, 79, '');
--INSERT INTO LOOKUP_VALUE(LOOKUP_ID,ENTITY_ID,LOOKUP_NAME) VALUES(224, 80, '');
--INSERT INTO LOOKUP_VALUE(LOOKUP_ID,ENTITY_ID,LOOKUP_NAME) VALUES(259, 82, '');
--INSERT INTO LOOKUP_VALUE(LOOKUP_ID,ENTITY_ID,LOOKUP_NAME) VALUES(263, 82, '');

--UPDATE LOOKUP_VALUE SET LOOKUP_NAME = ' ' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LANGUAGE WHERE LANG_SHORT_NAME = 'IS');
--UPDATE LOOKUP_VALUE SET LOOKUP_NAME = ' ' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LANGUAGE WHERE LANG_SHORT_NAME = 'es');
--UPDATE LOOKUP_VALUE SET LOOKUP_NAME = ' ' WHERE LOOKUP_ID = (SELECT LOOKUP_ID FROM LANGUAGE WHERE LANG_SHORT_NAME = 'fr');

UPDATE DATABASE_VERSION SET DATABASE_VERSION = 173 WHERE DATABASE_VERSION = 174;
