ALTER TABLE SYSTEM_CONFIGURATION ADD COLUMN NO_OF_INTEREST_DAYS SMALLINT;

UPDATE SYSTEM_CONFIGURATION SET NO_OF_INTEREST_DAYS=365 WHERE OFFICE_ID=1;

UPDATE DATABASE_VERSION SET DATABASE_VERSION = 151 WHERE DATABASE_VERSION = 152;