
DELETE FROM CONFIG_KEY_VALUE_INTEGER WHERE CONFIGURATION_KEY = 'maxDaysBetweenDisbursalAndFirstRepaymentDay';
DELETE FROM CONFIG_KEY_VALUE_INTEGER WHERE CONFIGURATION_KEY = 'minDaysBetweenDisbursalAndFirstRepaymentDay';

UPDATE DATABASE_VERSION set DATABASE_VERSION = 158 where DATABASE_VERSION = 159;