ALTER TABLE SYSTEM_CONFIGURATION
ADD COLUMN SCHEDULE_MEETING_ON_HOLIDAY VARCHAR(20)
AFTER OFFICE_ID;
UPDATE SYSTEM_CONFIGURATION
SET SCHEDULE_MEETING_ON_HOLIDAY='same_day'
WHERE OFFICE_ID=1;

ALTER TABLE SYSTEM_CONFIGURATION
ADD COLUMN DAYS_FOR_CAL_DEFINITION SMALLINT
AFTER SCHEDULE_MEETING_ON_HOLIDAY;
UPDATE SYSTEM_CONFIGURATION
SET DAYS_FOR_CAL_DEFINITION=30
WHERE OFFICE_ID=1;

ALTER TABLE SYSTEM_CONFIGURATION
ADD COLUMN NAME_SEQUENCE VARCHAR(100)
AFTER DAYS_FOR_CAL_DEFINITION;
UPDATE SYSTEM_CONFIGURATION
SET NAME_SEQUENCE='first_name,middle_name,last_name,second_last_name'
WHERE OFFICE_ID=1;

UPDATE DATABASE_VERSION SET DATABASE_VERSION = 162 WHERE DATABASE_VERSION = 163;
