UPDATE LOOKUP_ENTITY SET ENTITY_NAME='Member Formed By',DESCRIPTION='CustomField MemberFormedBy for client'
WHERE ENTITY_ID=23;
UPDATE LOOKUP_ENTITY SET ENTITY_NAME='No of Members per Group',DESCRIPTION='Custom Field  No. of Members per Group'
WHERE ENTITY_ID=63;
UPDATE LOOKUP_ENTITY SET ENTITY_NAME='No of Members per Center',DESCRIPTION='Custom Field No. of Members per Center'
WHERE ENTITY_ID=64;
UPDATE LOOKUP_LABEL SET ENTITY_NAME='Member' WHERE LABEL_ID=25;
UPDATE LOOKUP_LABEL SET ENTITY_NAME='Number of Members per Group' WHERE LABEL_ID=118;
UPDATE LOOKUP_LABEL SET ENTITY_NAME='Number of Members per Kendra' WHERE LABEL_ID=120;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Members' WHERE LOOKUP_VALUE_ID=135;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Member' WHERE LOOKUP_VALUE_ID=162;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Only Member' WHERE LOOKUP_VALUE_ID=247;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Member management' WHERE LOOKUP_VALUE_ID=732;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Members' WHERE LOOKUP_VALUE_ID=733;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can create new member in save for later state' WHERE LOOKUP_VALUE_ID=734;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can create new member in submit for approval state' WHERE LOOKUP_VALUE_ID=735;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can make payments to member accounts' WHERE LOOKUP_VALUE_ID=742;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can make adjustment entries to member account' WHERE LOOKUP_VALUE_ID=743;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can remove fee types from member account' WHERE LOOKUP_VALUE_ID=746;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can add notes to member' WHERE LOOKUP_VALUE_ID=747;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can Blacklist a member' WHERE LOOKUP_VALUE_ID=754;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Member Detail' WHERE LOOKUP_VALUE_ID=836;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can view Member Summary.& History Report' WHERE LOOKUP_VALUE_ID=843;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can view Member Product Wise History Report' WHERE LOOKUP_VALUE_ID=844;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can view Member Settlement info Report' WHERE LOOKUP_VALUE_ID=845;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can view Member Loan repayment schedule' WHERE LOOKUP_VALUE_ID=846;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can view Member Fees, Charges and Penalties report' WHERE LOOKUP_VALUE_ID=847;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can view Member pending approval report' WHERE LOOKUP_VALUE_ID=848;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can view Members without Margin Money Account' WHERE LOOKUP_VALUE_ID=849;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can apply charges to member accounts' WHERE LOOKUP_VALUE_ID=904;
UPDATE REPORT SET REPORT_NAME='Members without Saving Accouts' WHERE REPORT_ID=7;
UPDATE REPORT_JASPER_MAP SET REPORT_NAME='Members without Saving Accouts' WHERE REPORT_ID=7;

UPDATE LOOKUP_LABEL SET ENTITY_NAME='Margin Money' WHERE LABEL_ID=53;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Margin Money' WHERE LOOKUP_VALUE_ID=109;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Margin Money' WHERE LOOKUP_VALUE_ID=167;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Margin money Products' WHERE LOOKUP_VALUE_ID=795;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can define new margin money product instance' WHERE LOOKUP_VALUE_ID=796;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can edit margin money product instances' WHERE LOOKUP_VALUE_ID=797;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Margin money Management' WHERE LOOKUP_VALUE_ID=827;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can create new margin money account in Save for later state' WHERE LOOKUP_VALUE_ID=828;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can update margin money account' WHERE LOOKUP_VALUE_ID=829;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can close margin money account' WHERE LOOKUP_VALUE_ID=830;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can blacklist margin money account' WHERE LOOKUP_VALUE_ID=875;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can create new margin money account in submit for approval state' WHERE LOOKUP_VALUE_ID=876;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can waive due deposits for margin money account' WHERE LOOKUP_VALUE_ID=889;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can waive over due deposits for margin money account' WHERE LOOKUP_VALUE_ID=890;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can add notes to margin money account' WHERE LOOKUP_VALUE_ID=893;

UPDATE LOOKUP_ENTITY SET DESCRIPTION='Caste' WHERE ENTITY_ID=19;
UPDATE LOOKUP_LABEL SET ENTITY_NAME='Caste' WHERE LABEL_ID=37;

UPDATE LOOKUP_ENTITY SET DESCRIPTION='Religion' WHERE ENTITY_ID=18;
UPDATE LOOKUP_LABEL SET ENTITY_NAME='Religion' WHERE LABEL_ID=35;

UPDATE LOOKUP_LABEL SET ENTITY_NAME='Village' WHERE LABEL_ID=160;

UPDATE LOOKUP_ENTITY SET DESCRIPTION='Service Charge' WHERE ENTITY_ID=81;
UPDATE LOOKUP_ENTITY SET DESCRIPTION='Service Charge' WHERE ENTITY_ID=88;
UPDATE LOOKUP_LABEL SET ENTITY_NAME='Service Charge' WHERE LABEL_ID=164;
UPDATE LOOKUP_LABEL SET ENTITY_NAME='Service Charge' WHERE LABEL_ID=172;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Loan Amount+Service Charge' WHERE LOOKUP_VALUE_ID=275;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Service Charge' WHERE LOOKUP_VALUE_ID=277;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Service Charge' WHERE LOOKUP_VALUE_ID=395;
UPDATE COA SET COA_NAME='Service Charge' WHERE COA_ID=45;


UPDATE LOOKUP_LABEL SET ENTITY_NAME='Kendra' WHERE LABEL_ID=21;
UPDATE LOOKUP_LABEL SET ENTITY_NAME='Meeting Time for Kendra' WHERE LABEL_ID=112;
UPDATE LOOKUP_LABEL SET ENTITY_NAME='Distance from BO to Kendra' WHERE LABEL_ID=114;
UPDATE LOOKUP_LABEL SET ENTITY_NAME='Number of Members per Kendra' WHERE LABEL_ID=120;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Kendra Manager' WHERE LOOKUP_VALUE_ID=114;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Kendras' WHERE LOOKUP_VALUE_ID=137;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Kendra' WHERE LOOKUP_VALUE_ID=164;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Kendra Leader' WHERE LOOKUP_VALUE_ID=347;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Kendra Secretary' WHERE LOOKUP_VALUE_ID=349;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can edit kendra membership' WHERE LOOKUP_VALUE_ID=771;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Kendras' WHERE LOOKUP_VALUE_ID=777;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can create new kendra ' WHERE LOOKUP_VALUE_ID=778;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can modify kendra information ' WHERE LOOKUP_VALUE_ID=779;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can edit kendra status' WHERE LOOKUP_VALUE_ID=780;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can make payments to kendra accounts' WHERE LOOKUP_VALUE_ID=781;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can make adjustment entries to kendra account' WHERE LOOKUP_VALUE_ID=782;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can remove fee types from kendra account' WHERE LOOKUP_VALUE_ID=785;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can add notes to kendra records' WHERE LOOKUP_VALUE_ID=786;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Kendra' WHERE LOOKUP_VALUE_ID=837;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can view Kendra Summary Report' WHERE LOOKUP_VALUE_ID=862;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can view Kendra Meeting Schedule' WHERE LOOKUP_VALUE_ID=868;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can apply charges to kendra accounts' WHERE LOOKUP_VALUE_ID=906;
UPDATE REPORT_CATEGORY SET REPORT_CATEGORY_VALUE='Kendra' WHERE REPORT_CATEGORY_ID=3;
UPDATE REPORT SET REPORT_NAME='Kendra Summary Report' WHERE REPORT_ID=15;
UPDATE REPORT SET REPORT_NAME='Kendra Meeting Schedule' WHERE REPORT_ID=26;
UPDATE REPORT_JASPER_MAP SET REPORT_NAME='Kendra Summary Report' WHERE REPORT_ID=15;
UPDATE REPORT_JASPER_MAP SET REPORT_NAME='Kendra Meeting Schedule' WHERE REPORT_ID=26;

UPDATE DATABASE_VERSION SET DATABASE_VERSION = 104 WHERE DATABASE_VERSION = 105;