ALTER TABLE SURVEY_INSTANCE MODIFY COLUMN OFFICER_ID SMALLINT NOT NULL;
ALTER TABLE SURVEY_INSTANCE CHANGE COLUMN CUSTOMER_ID CLIENT_ID INTEGER NOT NULL;
ALTER TABLE SURVEY_INSTANCE DROP COLUMN ACCOUNT_ID;

update DATABASE_VERSION set DATABASE_VERSION = 124 where DATABASE_VERSION = 125;
