ALTER TABLE loan_offering MODIFY COLUMN MIN_LOAN_AMOUNT decimal(10,3) NOT NULL;
ALTER TABLE loan_offering MODIFY COLUMN MAX_LOAN_AMNT decimal(10,3) NOT NULL;
ALTER TABLE loan_offering MODIFY COLUMN DEFAULT_LOAN_AMOUNT decimal(10,3);

ALTER TABLE loan_offering MODIFY COLUMN MAX_NO_INSTALLMENTS SMALLINT NOT NULL;
ALTER TABLE loan_offering MODIFY COLUMN MIN_NO_INSTALLMENTS SMALLINT NOT NULL;
ALTER TABLE loan_offering MODIFY COLUMN DEF_NO_INSTALLMENTS SMALLINT NOT NULL;
  
  
UPDATE DATABASE_VERSION SET DATABASE_VERSION = 155 WHERE DATABASE_VERSION = 156;
  
