DROP TABLE IF EXISTS BATCH_CLIENT_SUMMARY;
DROP TABLE IF EXISTS BATCH_STAFF_SUMMARY;
DROP TABLE IF EXISTS BATCH_LOAN_ARREARS_AGING;
DROP TABLE IF EXISTS BATCH_STAFFING_LEVEL_SUMMARY;
DROP TABLE IF EXISTS BATCH_LOAN_DETAILS;
DROP TABLE IF EXISTS BATCH_LOAN_ARREARS_PROFILE;
DROP TABLE IF EXISTS BATCH_BRANCH_REPORT;

DROP TABLE IF EXISTS BATCH_BRANCH_CONFIRMATION_RECOVERY;
DROP TABLE IF EXISTS BATCH_BRANCH_CONFIRMATION_ISSUE;
DROP TABLE IF EXISTS BATCH_BRANCH_CONFIRMATION_DISBURSEMENT;
DROP TABLE IF EXISTS BATCH_BRANCH_CASH_CONFIRMATION_REPORT;

UPDATE DATABASE_VERSION SET DATABASE_VERSION = 179 WHERE DATABASE_VERSION = 180;
