delete from ROLES_ACTIVITY where ACTIVITY_ID = 208;
delete from ACTIVITY where ACTIVITY_ID = 208;
delete from LOOKUP_VALUE_LOCALE where LOOKUP_VALUE_ID = 927;
delete from LOOKUP_VALUE where lookup_id = 582;

update DATABASE_VERSION set DATABASE_VERSION = 117 where DATABASE_VERSION = 118;
