ALTER TABLE BATCH_STAFF_SUMMARY ADD COLUMN NEW_GROUP_COUNT INTEGER NOT NULL;

ALTER TABLE BATCH_STAFF_SUMMARY DROP COLUMN TOTAL_CLIENTS_ENROLLED;
ALTER TABLE BATCH_STAFF_SUMMARY DROP COLUMN CLIENTS_ENROLLED_THIS_MONTH;
ALTER TABLE BATCH_STAFF_SUMMARY DROP COLUMN LOAN_ARREARS_AMOUNT;
ALTER TABLE BATCH_STAFF_SUMMARY DROP COLUMN LOAN_ARREARS_AMOUNT_CURRENCY_ID;

UPDATE DATABASE_VERsION SET DATABASE_VERSION = 193 WHERE DATABASE_VERSION=194;
