update LOOKUP_ENTITY set ENTITY_NAME= 'AccountStates' where ENTITY_ID= 5;
update LOOKUP_ENTITY set ENTITY_NAME= 'Saving Status' where ENTITY_ID= 72;

update LOOKUP_VALUE set LOOKUP_NAME= ' ' where LOOKUP_ID= 17;
update LOOKUP_VALUE set LOOKUP_NAME= ' ' where LOOKUP_ID= 18;
update LOOKUP_VALUE set LOOKUP_NAME= ' ' where LOOKUP_ID= 19;
update LOOKUP_VALUE set LOOKUP_NAME= ' ' where LOOKUP_ID= 20;
update LOOKUP_VALUE set LOOKUP_NAME= ' ' where LOOKUP_ID= 21;
update LOOKUP_VALUE set LOOKUP_NAME= ' ' where LOOKUP_ID= 22;
update LOOKUP_VALUE set LOOKUP_NAME= ' ' where LOOKUP_ID= 23;
update LOOKUP_VALUE set LOOKUP_NAME= ' ' where LOOKUP_ID= 24;
update LOOKUP_VALUE set LOOKUP_NAME= ' ' where LOOKUP_ID= 25;

update LOOKUP_VALUE set LOOKUP_NAME= ' ' where LOOKUP_ID= 141;
update LOOKUP_VALUE set LOOKUP_NAME= ' ' where LOOKUP_ID= 142;
update LOOKUP_VALUE set LOOKUP_NAME= ' ' where LOOKUP_ID= 143;

update LOOKUP_VALUE set LOOKUP_NAME= ' ' where LOOKUP_ID= 181;
update LOOKUP_VALUE set LOOKUP_NAME= ' ' where LOOKUP_ID= 182;
update LOOKUP_VALUE set LOOKUP_NAME= ' ' where LOOKUP_ID= 183;
update LOOKUP_VALUE set LOOKUP_NAME= ' ' where LOOKUP_ID= 184;
update LOOKUP_VALUE set LOOKUP_NAME= ' ' where LOOKUP_ID= 185;
update LOOKUP_VALUE set LOOKUP_NAME= ' ' where LOOKUP_ID= 210;

UPDATE DATABASE_VERSION SET DATABASE_VERSION = 160 WHERE DATABASE_VERSION = 161;
