UPDATE LOOKUP_ENTITY SET ENTITY_NAME='Client Status' WHERE ENTITY_ID=1;
UPDATE LOOKUP_ENTITY SET ENTITY_NAME='Group Status' WHERE ENTITY_ID=2;
UPDATE LOOKUP_ENTITY SET ENTITY_NAME='Center Status' WHERE ENTITY_ID=3;
UPDATE LOOKUP_ENTITY SET ENTITY_NAME='Office Status' WHERE ENTITY_ID=4;
UPDATE LOOKUP_ENTITY SET ENTITY_NAME='Personnel Status' WHERE ENTITY_ID=6;
UPDATE LOOKUP_ENTITY SET ENTITY_NAME='Group Flag' WHERE ENTITY_ID=7;
UPDATE LOOKUP_ENTITY SET ENTITY_NAME='Fee Type' WHERE ENTITY_ID=8;
UPDATE LOOKUP_ENTITY SET ENTITY_NAME='Client Formed By' WHERE ENTITY_ID=23;
UPDATE LOOKUP_ENTITY SET ENTITY_NAME='Product State' WHERE ENTITY_ID=25;
UPDATE LOOKUP_ENTITY SET ENTITY_NAME='Replacement Status' WHERE ENTITY_ID=58;
UPDATE LOOKUP_ENTITY SET ENTITY_NAME='GRT StaffId' WHERE ENTITY_ID=59;
UPDATE LOOKUP_ENTITY SET ENTITY_NAME='Meeting Time' WHERE ENTITY_ID=60;
UPDATE LOOKUP_ENTITY SET ENTITY_NAME='Distance from BO To Center' WHERE ENTITY_ID=61;
UPDATE LOOKUP_ENTITY SET ENTITY_NAME='No of Clients per Group' WHERE ENTITY_ID=63;
UPDATE LOOKUP_ENTITY SET ENTITY_NAME='No of Clients per Center' WHERE ENTITY_ID=64;
UPDATE LOOKUP_ENTITY SET ENTITY_NAME='Distance From HO To BO' WHERE ENTITY_ID=65;
UPDATE LOOKUP_ENTITY SET ENTITY_NAME='External Loan Id' WHERE ENTITY_ID=66;
UPDATE LOOKUP_ENTITY SET ENTITY_NAME='External Savings Id' WHERE ENTITY_ID=67;
UPDATE LOOKUP_ENTITY SET ENTITY_NAME='Financial Action' WHERE ENTITY_ID=76;
UPDATE LOOKUP_ENTITY SET ENTITY_NAME='SavingsAccountFlag ' WHERE ENTITY_ID=78;
UPDATE LOOKUP_ENTITY SET ENTITY_NAME='Loan Purposes' WHERE ENTITY_ID=82;
UPDATE LOOKUP_ENTITY SET ENTITY_NAME='Service Charge' WHERE ENTITY_ID=88;
UPDATE LOOKUP_ENTITY SET ENTITY_NAME='Fee Frequency' WHERE ENTITY_ID=90;
UPDATE LOOKUP_ENTITY SET ENTITY_NAME='Repayment Rule' WHERE ENTITY_ID=91;

UPDATE LOOKUP_LABEL SET ENTITY_NAME='Partial Application' WHERE LABEL_ID=136;
INSERT INTO LOOKUP_LABEL(LABEL_ID,ENTITY_ID,LOCALE_ID,ENTITY_NAME)
VALUES(138,72,1,'Application Pending Approval');
INSERT INTO LOOKUP_LABEL(LABEL_ID,ENTITY_ID,LOCALE_ID,ENTITY_NAME)
VALUES(140,72,1,'Cancelled');
INSERT INTO LOOKUP_LABEL(LABEL_ID,ENTITY_ID,LOCALE_ID,ENTITY_NAME)
VALUES(142,72,1,'Active');
INSERT INTO LOOKUP_LABEL(LABEL_ID,ENTITY_ID,LOCALE_ID,ENTITY_NAME)
VALUES(144,72,1,'Closed');

UPDATE DATABASE_VERSION SET DATABASE_VERSION = 164 WHERE DATABASE_VERSION = 165;
