DROP TABLE IF EXISTS MAX_MIN_NO_OF_INSTALL;
DROP TABLE IF EXISTS MAX_MIN_LOAN_AMOUNT;
DROP TABLE IF EXISTS NO_OF_INSTALL_SAME_FOR_ALL_LOAN;
DROP TABLE IF EXISTS LOAN_AMOUNT_SAME_FOR_ALL_LOAN;
DROP TABLE IF EXISTS NO_OF_INSTALL_FROM_LOAN_CYCLE;
DROP TABLE IF EXISTS LOAN_AMOUNT_FROM_LOAN_CYCLE;
DROP TABLE IF EXISTS NO_OF_INSTALL_FROM_LAST_LOAN;
DROP TABLE IF EXISTS LOAN_AMOUNT_FROM_LAST_LOAN;

UPDATE DATABASE_VERSION SET DATABASE_VERSION = 159 WHERE DATABASE_VERSION = 160;
