delete from ROLES_ACTIVITY where ACTIVITY_ID = 214;
delete from ACTIVITY where ACTIVITY_ID = 214;
delete from LOOKUP_VALUE_LOCALE where LOOKUP_VALUE_ID = 933;
delete from LOOKUP_VALUE where lookup_id = 588;

UPDATE DATABASE_VERSION SET DATABASE_VERSION = 123 WHERE DATABASE_VERSION = 124;