delete from ROLES_ACTIVITY where ACTIVITY_ID = 213;
delete from ACTIVITY where ACTIVITY_ID = 213;
delete from LOOKUP_VALUE_LOCALE where LOOKUP_VALUE_ID = 932;
delete from LOOKUP_VALUE where lookup_id = 587;

UPDATE DATABASE_VERSION SET DATABASE_VERSION = 122 WHERE DATABASE_VERSION = 123;
