delete from ROLES_ACTIVITY where ACTIVITY_ID = 205;
delete from ACTIVITY where ACTIVITY_ID = 205;
delete from LOOKUP_VALUE_LOCALE where LOOKUP_VALUE_ID = 924;
delete from LOOKUP_VALUE where lookup_id = 579;
DELETE FROM FIELD_CONFIGURATION WHERE FIELD_CONFIG_ID=74;

update DATABASE_VERSION set DATABASE_VERSION = 105 where DATABASE_VERSION = 106;