
ALTER TABLE LOAN_ACCOUNT DROP FOREIGN KEY fk_loan_rankday;
ALTER TABLE LOAN_ACCOUNT DROP FOREIGN KEY fk_loan_monthweek;

ALTER TABLE LOAN_ACCOUNT DROP COLUMN MONTH_RANK;
ALTER TABLE LOAN_ACCOUNT DROP COLUMN MONTH_WEEK;
ALTER TABLE LOAN_ACCOUNT DROP COLUMN RECUR_MONTH;
  
UPDATE DATABASE_VERSION SET DATABASE_VERSION = 157 WHERE DATABASE_VERSION = 158;
  