CREATE TABLE SYSTEM_CONFIGURATION (
  OFFICE_ID SMALLINT,
  BACK_DATED_TXN_ALLOWED SMALLINT,
  CENTER_HIERARCHY_EXIST SMALLINT,
  GROUP_CAN_APPLY_LOANS SMALLINT,
  CLIENT_CAN_EXIST_OUTSIDE_GROUP SMALLINT,
  
  FOREIGN KEY(OFFICE_ID)
    REFERENCES OFFICE(OFFICE_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
) ENGINE=InnoDB CHARACTER SET utf8;

INSERT INTO SYSTEM_CONFIGURATION(OFFICE_ID,BACK_DATED_TXN_ALLOWED,CENTER_HIERARCHY_EXIST,GROUP_CAN_APPLY_LOANS,CLIENT_CAN_EXIST_OUTSIDE_GROUP)
VALUES(1,1,1,1,1);

UPDATE CONFIG_KEY_VALUE_INTEGER
   SET CONFIGURATION_KEY = 'CollectionSheetHelper.daysInAdvance',
       CONFIGURATION_VALUE = 1
 WHERE CONFIGURATION_ID = 1;

UPDATE DATABASE_VERSION SET DATABASE_VERSION = 167 WHERE DATABASE_VERSION = 168;
