DROP TABLE SURVEY_RESPONSE;

CREATE TABLE SURVEY_RESPONSE_CHOICE (
  RESPONSE_ID INTEGER AUTO_INCREMENT NOT NULL,
  INSTANCE_ID INTEGER NOT NULL,
  QUESTION_ID INTEGER NOT NULL,
  CHOICE_ID INTEGER NOT NULL,
  PRIMARY KEY(RESPONSE_ID),
  FOREIGN KEY(QUESTION_ID)
    REFERENCES QUESTIONS(QUESTION_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(INSTANCE_ID)
    REFERENCES SURVEY_INSTANCE(INSTANCE_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE SURVEY_RESPONSE_FREETEXT (
  RESPONSE_ID INTEGER AUTO_INCREMENT NOT NULL,
  INSTANCE_ID INTEGER NOT NULL,
  QUESTION_ID INTEGER NOT NULL,
  FREETEXT_ANSWER TEXT,
  PRIMARY KEY(RESPONSE_ID),
  FOREIGN KEY(QUESTION_ID)
    REFERENCES QUESTIONS(QUESTION_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(INSTANCE_ID)
    REFERENCES SURVEY_INSTANCE(INSTANCE_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE SURVEY_RESPONSE_NUMBER (
  RESPONSE_ID INTEGER AUTO_INCREMENT NOT NULL,
  INSTANCE_ID INTEGER NOT NULL,
  QUESTION_ID INTEGER NOT NULL,
  NUMBER_ANSWER DECIMAL(16,5),
  PRIMARY KEY(RESPONSE_ID),
  FOREIGN KEY(QUESTION_ID)
    REFERENCES QUESTIONS(QUESTION_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(INSTANCE_ID)
    REFERENCES SURVEY_INSTANCE(INSTANCE_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE SURVEY_RESPONSE_DATE (
  RESPONSE_ID INTEGER AUTO_INCREMENT NOT NULL,
  INSTANCE_ID INTEGER NOT NULL,
  QUESTION_ID INTEGER NOT NULL,
  DATE_ANSWER DATE,
  PRIMARY KEY(RESPONSE_ID),
  FOREIGN KEY(QUESTION_ID)
    REFERENCES QUESTIONS(QUESTION_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(INSTANCE_ID)
    REFERENCES SURVEY_INSTANCE(INSTANCE_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);


UPDATE DATABASE_VERSION SET DATABASE_VERSION = 115 WHERE DATABASE_VERSION = 116;
