CREATE TABLE LOAN_MONITORING (
  LOAN_MONITORING_ID INTEGER NOT NULL,
  INDIVIDUAL_MONITORING_FLAG SMALLINT NOT NULL,
  CREATED_BY SMALLINT,
  CREATED_DATE DATE,
  UPDATED_BY SMALLINT,
  UPDATED_DATE DATE,
  VERSION_NO INTEGER NOT NULL,
  PRIMARY KEY(LOAN_MONITORING_ID)
)
ENGINE=InnoDB CHARACTER SET utf8;

INSERT INTO LOAN_MONITORING (LOAN_MONITORING_ID,INDIVIDUAL_MONITORING_FLAG,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE,VERSION_NO)
VALUES(1,0,NULL,NULL,NULL,NULL,1);

DELETE FROM CONFIG_KEY_VALUE_INTEGER WHERE CONFIGURATION_KEY = 'loanIndividualMonitoringIsEnabled';
DELETE FROM CONFIG_KEY_VALUE_INTEGER WHERE CONFIGURATION_KEY = 'repaymentSchedulesIndependentOfMeetingIsEnabled';


UPDATE DATABASE_VERSION set DATABASE_VERSION = 148 where DATABASE_VERSION = 149;