DROP TABLE HOLIDAY;
CREATE TABLE HOLIDAY (
  OFFICE_ID SMALLINT NOT NULL,
  HOLIDAY_DATE DATE NOT NULL,
  HOLIDATY_NAME VARCHAR(100),
  PRIMARY KEY(OFFICE_ID, HOLIDAY_DATE),
  FOREIGN KEY(OFFICE_ID)
    REFERENCES OFFICE(OFFICE_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)
ENGINE=InnoDB CHARACTER SET utf8;
INSERT INTO HOLIDAY(OFFICE_ID, HOLIDAY_DATE, HOLIDATY_NAME)
VALUES(1,'2005-12-20','Chrismass');
INSERT INTO HOLIDAY(OFFICE_ID, HOLIDAY_DATE, HOLIDATY_NAME)
VALUES(1,'2005-12-21','Diwali');
INSERT INTO HOLIDAY(OFFICE_ID, HOLIDAY_DATE, HOLIDATY_NAME)
VALUES(1,'2005-12-10','Holi');
INSERT INTO HOLIDAY(OFFICE_ID, HOLIDAY_DATE, HOLIDATY_NAME)
VALUES(1,'2005-12-11','Eid');
INSERT INTO HOLIDAY(OFFICE_ID, HOLIDAY_DATE, HOLIDATY_NAME)
VALUES(1,'2005-12-22','Pongal');

DROP TABLE REPAYMENT_RULE;

DELETE FROM LOOKUP_VALUE_LOCALE WHERE LOOKUP_VALUE_ID = 921;
DELETE FROM LOOKUP_VALUE_LOCALE WHERE LOOKUP_VALUE_ID = 922;
DELETE FROM LOOKUP_VALUE_LOCALE WHERE LOOKUP_VALUE_ID = 923;
DELETE FROM LOOKUP_VALUE WHERE LOOKUP_ID = 576;
DELETE FROM LOOKUP_VALUE WHERE LOOKUP_ID = 577;
DELETE FROM LOOKUP_VALUE WHERE LOOKUP_ID = 578;
DELETE FROM LOOKUP_ENTITY WHERE ENTITY_ID = 91;

UPDATE DATABASE_VERSION SET DATABASE_VERSION = 103 WHERE DATABASE_VERSION = 104;
