DELETE FROM CONFIG_KEY_VALUE_INTEGER WHERE CONFIGURATION_KEY ='AdministrativeDocumentsIsEnabled';

DROP TABLE IF EXISTS ADMIN_DOCUMENT_ACC_STATE_MIX;
DROP TABLE IF EXISTS ADMIN_DOCUMENT;
 
UPDATE DATABASE_VERSION SET DATABASE_VERSION = 170 WHERE DATABASE_VERSION = 171;

