-- The reason for the drop/create is the same as upgrade_to_125.sql.
-- ALTER TABLE SURVEY_INSTANCE MODIFY COLUMN OFFICER_ID SMALLINT NOT NULL;
-- ALTER TABLE SURVEY_INSTANCE CHANGE COLUMN CUSTOMER_ID CLIENT_ID INTEGER NOT NULL;
-- ALTER TABLE SURVEY_INSTANCE DROP COLUMN ACCOUNT_ID;

drop table SURVEY_RESPONSE;
drop table SURVEY_INSTANCE;

CREATE TABLE SURVEY_INSTANCE (
  INSTANCE_ID INTEGER AUTO_INCREMENT NOT NULL,
  SURVEY_ID INTEGER NOT NULL,
  CLIENT_ID INTEGER NOT NULL,
  OFFICER_ID SMALLINT NOT NULL,
  DATE_CONDUCTED DATE NOT NULL,
  COMPLETED_STATUS INTEGER NOT NULL,
  PRIMARY KEY(INSTANCE_ID),
  FOREIGN KEY(SURVEY_ID)
    REFERENCES SURVEY(SURVEY_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(CLIENT_ID) 
    REFERENCES CUSTOMER(CUSTOMER_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(OFFICER_ID)
    REFERENCES PERSONNEL(PERSONNEL_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE SURVEY_RESPONSE (
  RESPONSE_ID INTEGER AUTO_INCREMENT NOT NULL,
  INSTANCE_ID INTEGER NOT NULL,
  QUESTION_ID INTEGER NOT NULL,

  FREETEXT_VALUE TEXT,
  CHOICE_VALUE INTEGER,
  DATE_VALUE DATE,
  NUMBER_VALUE DECIMAL(16,5),

  UNIQUE(INSTANCE_ID, QUESTION_ID),
  PRIMARY KEY(RESPONSE_ID),
  FOREIGN KEY(QUESTION_ID)
    REFERENCES QUESTIONS(QUESTION_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(INSTANCE_ID)
    REFERENCES SURVEY_INSTANCE(INSTANCE_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(CHOICE_VALUE)
    REFERENCES QUESTION_CHOICES(CHOICE_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);


update DATABASE_VERSION set DATABASE_VERSION = 124 where DATABASE_VERSION = 125;
