ALTER TABLE PRD_OFFERING DROP COLUMN PRD_MIX_FLAG;

DROP TABLE PRD_OFFERING_MIX;

UPDATE ACTIVITY SET PARENT_ID=NULL WHERE ACTIVITY_ID=209;

UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Product mix' WHERE LOOKUP_VALUE_ID=928;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can Define product mix' WHERE LOOKUP_VALUE_ID=929;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can Edit product mix' WHERE LOOKUP_VALUE_ID=930;

UPDATE DATABASE_VERSION SET DATABASE_VERSION = 126 WHERE DATABASE_VERSION = 127;
