DROP TABLE SURVEY_RESPONSE_DATE;
DROP TABLE SURVEY_RESPONSE_NUMBER;
DROP TABLE SURVEY_RESPONSE_FREETEXT;
DROP TABLE QUESTION_CHOICES;
DROP TABLE SURVEY_RESPONSE_CHOICE;
DROP TABLE SURVEY_QUESTIONS;
DROP TABLE QUESTIONS;
DROP TABLE SURVEY_INSTANCE;
DROP TABLE SURVEY;

-- recreate the old, unused tables that 112 drops

CREATE TABLE SURVEY_TEMPLATE (
  SURVEY_TEMPLATE_ID SMALLINT NOT NULL,
  SURVEY_NAME VARCHAR(200),
  PRIMARY KEY(SURVEY_TEMPLATE_ID)
) ENGINE=InnoDB CHARACTER SET utf8;

CREATE TABLE SURVEY (
  SURVEY_ID INTEGER NOT NULL,
  SURVEY_TEMPLATE_ID SMALLINT NOT NULL,
  PRIMARY KEY(SURVEY_ID),
  FOREIGN KEY(SURVEY_TEMPLATE_ID)
    REFERENCES SURVEY_TEMPLATE(SURVEY_TEMPLATE_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
) ENGINE=InnoDB CHARACTER SET utf8;

CREATE TABLE PRD_SURVEY (
  PRD_SURVEYID SMALLINT NOT NULL,
  PRD_OFFERING_ID SMALLINT,
  ACCOUNT_STATE_ID SMALLINT,
  SURVEY_TEMPLATE_ID SMALLINT,
  PRIMARY KEY(PRD_SURVEYID),
  FOREIGN KEY(ACCOUNT_STATE_ID)
    REFERENCES ACCOUNT_STATE(ACCOUNT_STATE_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(PRD_OFFERING_ID)
    REFERENCES PRD_OFFERING(PRD_OFFERING_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(SURVEY_TEMPLATE_ID)
    REFERENCES SURVEY_TEMPLATE(SURVEY_TEMPLATE_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
) ENGINE=InnoDB CHARACTER SET utf8;


CREATE TABLE ACCOUNT_SURVEY (
  ACCOUNT_SURVEY_ID SMALLINT NOT NULL,
  ACCOUNT_ID INTEGER,
  SURVEY_ID INTEGER,
  STATUS_ID SMALLINT NOT NULL,
  COMPLETED SMALLINT NOT NULL,
  COMPLETED_DATE DATE NOT NULL,
  PRIMARY KEY(ACCOUNT_SURVEY_ID),
  FOREIGN KEY(ACCOUNT_ID)
    REFERENCES ACCOUNT(ACCOUNT_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(STATUS_ID)
    REFERENCES ACCOUNT_STATE(ACCOUNT_STATE_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(SURVEY_ID)
    REFERENCES SURVEY(SURVEY_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
) ENGINE=InnoDB CHARACTER SET utf8;

CREATE TABLE CUSTOMER_SURVEY (
  CUSTOMER_SURVEY_ID INTEGER NOT NULL,
  CUSTOMER_ID INTEGER,
  SURVEY_ID INTEGER,
  STATUS_ID SMALLINT NOT NULL,
  COMPLETED SMALLINT NOT NULL,
  COMPLETED_DATE DATE NOT NULL,
  CREATED_BY SMALLINT NOT NULL,
  CREATED_DATE DATE,
  UPDATED_BY SMALLINT NOT NULL,
  UPDATED_DATE DATE NOT NULL,
  PRIMARY KEY(CUSTOMER_SURVEY_ID),
  FOREIGN KEY(CUSTOMER_ID)
    REFERENCES CUSTOMER(CUSTOMER_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(STATUS_ID)
    REFERENCES CUSTOMER_STATE(STATUS_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(CREATED_BY)
    REFERENCES PERSONNEL(PERSONNEL_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(UPDATED_BY)
    REFERENCES PERSONNEL(PERSONNEL_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(SURVEY_ID)
    REFERENCES SURVEY(SURVEY_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)  ENGINE=InnoDB CHARACTER SET utf8;

UPDATE DATABASE_VERSION SET DATABASE_VERSION = 112 WHERE DATABASE_VERSION = 113;
