DROP TABLE IF EXISTS SYSTEM_CONFIGURATION;

CREATE TABLE SYSTEM_CONFIGURATION (
  OFFICE_ID SMALLINT,
  SCHEDULE_MEETING_ON_HOLIDAY VARCHAR(20),
  DAYS_FOR_CAL_DEFINITION SMALLINT,
  NAME_SEQUENCE VARCHAR(100),
  BACK_DATED_TXN_ALLOWED SMALLINT,
  CENTER_HIERARCHY_EXIST SMALLINT,
  GROUP_CAN_APPLY_LOANS SMALLINT,
  CLIENT_CAN_EXIST_OUTSIDE_GROUP SMALLINT,
  NO_OF_INTEREST_DAYS SMALLINT,
  
  FOREIGN KEY(OFFICE_ID)
    REFERENCES OFFICE(OFFICE_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
) ENGINE=InnoDB CHARACTER SET utf8;

INSERT INTO SYSTEM_CONFIGURATION(OFFICE_ID,SCHEDULE_MEETING_ON_HOLIDAY,DAYS_FOR_CAL_DEFINITION,NAME_SEQUENCE,BACK_DATED_TXN_ALLOWED,CENTER_HIERARCHY_EXIST,GROUP_CAN_APPLY_LOANS,CLIENT_CAN_EXIST_OUTSIDE_GROUP,NO_OF_INTEREST_DAYS)
VALUES(1,'same_day',30,'first_name,middle_name,last_name,second_last_name',1,1,1,1,365);


UPDATE DATABASE_VERSION SET DATABASE_VERSION = 151 WHERE DATABASE_VERSION = 152;