DELETE FROM CONFIG_KEY_VALUE_INTEGER WHERE CONFIGURATION_KEY='CenterHierarchyExists';
DELETE FROM CONFIG_KEY_VALUE_INTEGER WHERE CONFIGURATION_KEY='ClientCanExistOutsideGroup';
DELETE FROM CONFIG_KEY_VALUE_INTEGER WHERE CONFIGURATION_KEY='GroupCanApplyLoans';


UPDATE DATABASE_VERSION SET DATABASE_VERSION = 156 WHERE DATABASE_VERSION = 157;