DROP TABLE PPI_SURVEY;

ALTER TABLE QUESTION_CHOICES DROP COLUMN PPI;
ALTER TABLE QUESTION_CHOICES DROP COLUMN PPI_POINTS;

update DATABASE_VERSION set DATABASE_VERSION = 133 where DATABASE_VERSION = 134;