INSERT INTO FUND_CODE(FUNDCODE_ID,FUNDCODE_VALUE) VALUES(1,'00');
INSERT INTO FUND_CODE(FUNDCODE_ID,FUNDCODE_VALUE) VALUES(2,'01');
INSERT INTO FUND_CODE(FUNDCODE_ID,FUNDCODE_VALUE) VALUES(3,'02');
INSERT INTO FUND_CODE(FUNDCODE_ID,FUNDCODE_VALUE) VALUES(4,'03');
INSERT INTO FUND_CODE(FUNDCODE_ID,FUNDCODE_VALUE) VALUES(5,'04');

INSERT INTO FUND(FUND_ID,FUNDCODE_ID,FUND_NAME,VERSION_NO)
VALUES(1,1,'Non Donor',0);
INSERT INTO FUND(FUND_ID,FUNDCODE_ID,FUND_NAME,VERSION_NO)
VALUES(2,1,'Funding Org A',0);
INSERT INTO FUND(FUND_ID,FUNDCODE_ID,FUND_NAME,VERSION_NO)
VALUES(3,1,'Funding Org B',0);
INSERT INTO FUND(FUND_ID,FUNDCODE_ID,FUND_NAME,VERSION_NO)
VALUES(4,1,'Funding Org C',0);
INSERT INTO FUND(FUND_ID,FUNDCODE_ID,FUND_NAME,VERSION_NO)
VALUES(5,1,'Funding Org D',0);
