ALTER TABLE ACTIVITY ADD COLUMN ACTIVITY_NAME_LOOKUP_ID INTEGER NOT NULL;
ALTER TABLE ACTIVITY ADD COLUMN DESCRIPTION_LOOKUP_ID INTEGER NOT NULL;



ALTER TABLE ACTIVITY DROP COLUMN ACTIVITY_NAME;
ALTER TABLE ACTIVITY DROP COLUMN DESCRIPTION;

ALTER TABLE SYSTEM_CONFIGURATION ADD COLUMN DAYS_FOR_CAL_DEFINITION SMALLINT NULL;
ALTER TABLE SYSTEM_CONFIGURATION ADD COLUMN BACK_DATED_TXN_ALLOWED SMALLINT NULL;
ALTER TABLE SYSTEM_CONFIGURATION ADD COLUMN CENTER_HIERARCHY_EXIST SMALLINT NULL;
ALTER TABLE SYSTEM_CONFIGURATION ADD COLUMN GROUP_CAN_APPLY_LOANS SMALLINT NULL;
ALTER TABLE SYSTEM_CONFIGURATION ADD COLUMN CLIENT_CAN_EXIST_OUTSIDE_GROUP SMALLINT NULL;


ALTER TABLE SYSTEM_CONFIGURATION DROP COLUMN NO_OF_DAYS_FOR_CAL_DEFINITION;
ALTER TABLE SYSTEM_CONFIGURATION DROP COLUMN IS_BACK_DATED_TXN_ALLOWED;
ALTER TABLE SYSTEM_CONFIGURATION DROP COLUMN IS_CENTERHIERARCHYEXIST;
ALTER TABLE SYSTEM_CONFIGURATION DROP COLUMN CAN_GROUP_APPLY_LOANS;
ALTER TABLE SYSTEM_CONFIGURATION DROP COLUMN CAN_CLIENT_EXIST_OUTSIDE_GROUP;

DROP TABLE IF EXISTS  FIELD_CONFIGURATION;

DROP TABLE IF EXISTS  FIELD_MASTER;

CREATE TABLE FIELD_CONFIGURATION (
  FIELD_CONFIG_ID INTEGER NOT NULL AUTO_INCREMENT,
  FIELD_NAME VARCHAR(100) NOT NULL,
  ENTITY_ID SMALLINT NOT NULL,
  MANDATORY_FLAG SMALLINT NOT NULL,
  HIDDEN_FLAG SMALLINT NOT NULL,
  PARENT_FIELD_CONFIG_ID INTEGER NULL,
  PRIMARY KEY(FIELD_CONFIG_ID),
  FOREIGN KEY(ENTITY_ID)
    REFERENCES ENTITY_MASTER(ENTITY_TYPE_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(PARENT_FIELD_CONFIG_ID)
    REFERENCES FIELD_CONFIGURATION(FIELD_CONFIG_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION  
)TYPE=InnoDB;


ALTER TABLE WEEK_DAYS_MASTER ADD COLUMN WORKING_DAY SMALLINT NOT NULL;

ALTER TABLE WEEK_DAYS_MASTER  DROP COLUMN IS_WORKING_DAY;


ALTER TABLE PERSONNEL_DETAILS MODIFY GOVERNMENT_ID_NUMBER VARCHAR(50) NULL;

ALTER TABLE CURRENCY MODIFY DEFAULT_DIGITS_AFTER_DECIMAL SMALLINT NOT NULL;


CREATE TABLE TRANSACTION_TYPE
(  
  TRANSACTION_ID SMALLINT NOT NULL,  
  TRANSACTION_NAME VARCHAR(100) NOT NULL,  
  PRIMARY KEY (TRANSACTION_ID) 
)TYPE=InnoDB; 


CREATE TABLE SUPPORTED_MODES 
(
  MODE_ID SMALLINT NOT NULL,  
  TRANSACTION_ID SMALLINT NOT NULL,  
  PAYMENT_TYPE_ID SMALLINT NOT NULL,  
  PRIMARY KEY(MODE_ID),  
  FOREIGN KEY(TRANSACTION_ID)    
  REFERENCES TRANSACTION_TYPE(TRANSACTION_ID)       
  ON DELETE NO ACTION       
  ON UPDATE NO ACTION,   
  FOREIGN KEY(PAYMENT_TYPE_ID)     
  REFERENCES PAYMENT_TYPE(PAYMENT_TYPE_ID)       
  ON DELETE NO ACTION       
  ON UPDATE NO ACTION 
)TYPE=InnoDB;


UPDATE CURRENCY set DEFAULT_DIGITS_AFTER_DECIMAL = 1;

UPDATE CUSTOMER_STATE set CURRENTLY_IN_USE = 0; 




update LOOKUP_ENTITY set ENTITY_NAME = 'Citizenship' where ENTITY_ID = 18;
update LOOKUP_ENTITY set ENTITY_NAME = 'PostalCode' where ENTITY_ID = 24;
update LOOKUP_ENTITY set ENTITY_NAME = 'ExternalId' where ENTITY_ID = 62;

update LOOKUP_LABEL set ENTITY_NAME = 'Postal Code' where LABEL_ID = 47;

update CUSTOMER_STATE set CURRENTLY_IN_USE = 1;
 
update PRD_TYPE set DORMANCY_DAYS = 30 where PRD_TYPE_ID = 2;

 

INSERT INTO LOOKUP_ENTITY  
VALUES(83,'State','State'); 
INSERT INTO LOOKUP_ENTITY  
VALUES(84,'Address1','Address1'); 
INSERT INTO LOOKUP_ENTITY  
VALUES(85,'Address2','Address2'); 
INSERT INTO LOOKUP_ENTITY  
VALUES(86,'GovernmentId','GovernmentId'); 
INSERT INTO LOOKUP_ENTITY  
VALUES(87,'Permissions','Permissions'); 
INSERT INTO LOOKUP_ENTITY(ENTITY_ID,ENTITY_NAME,DESCRIPTION) 
VALUES(88,'Service Charge','Service Charge'); 


INSERT INTO LOOKUP_VALUE 
VALUES(371,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(372,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(373,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(374,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(375,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(376,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(377,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(378,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(379,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(380,87, " ");
INSERT INTO LOOKUP_VALUE
VALUES(381,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(382,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(383,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(384,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(385,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(386,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(387,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(388,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(389,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(390,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(391,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(392,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(393,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(394,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(395,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(396,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(397,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(398,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(399,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(400,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(401,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(402,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(403,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(404,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(405,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(406,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(407,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(408,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(409,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(410,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(411,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(412,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(413,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(414,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(415,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(416,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(417,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(418,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(419,87, " ");
INSERT INTO LOOKUP_VALUE
VALUES(420,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(421,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(422,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(423,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(424,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(425,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(426,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(427,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(428,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(429,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(430,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(431,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(432,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(433,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(434,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(435,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(436,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(437,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(438,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(439,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(440,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(441,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(442,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(443,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(444,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(445,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(446,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(447,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(448,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(449,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(450,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(451,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(452,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(453,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(454,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(455,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(456,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(457,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(458,87, " ");
INSERT INTO LOOKUP_VALUE
VALUES(459,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(460,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(461,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(462,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(463,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(464,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(465,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(466,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(467,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(468,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(469,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(470,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(471,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(472,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(473,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(474,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(475,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(476,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(477,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(478,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(479,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(480,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(481,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(482,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(483,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(484,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(485,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(486,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(487,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(488,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(489,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(490,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(491,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(492,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(493,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(494,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(495,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(496,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(497,87, " ");
INSERT INTO LOOKUP_VALUE
VALUES(498,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(499,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(500,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(501,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(502,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(503,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(504,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(505,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(506,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(507,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(508,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(509,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(510,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(511,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(512,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(513,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(514,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(515,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(516,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(517,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(518,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(519,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(520,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(521,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(522,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(523,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(524,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(525,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(526,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(527,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(528,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(529,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(530,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(531,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(532,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(533,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(534,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(535,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(536,87, " ");
INSERT INTO LOOKUP_VALUE
VALUES(537,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(538,87, " ");
INSERT INTO LOOKUP_VALUE 
VALUES(539,87, " ");
INSERT INTO LOOKUP_VALUE
VALUES(540,29," ");
INSERT INTO LOOKUP_VALUE
VALUES(541,29," ");
INSERT INTO LOOKUP_VALUE
VALUES(542,29," ");
INSERT INTO LOOKUP_VALUE
VALUES(543,29," ");
INSERT INTO LOOKUP_VALUE
VALUES(544,29," ");
INSERT INTO LOOKUP_VALUE
VALUES(545,29," ");
INSERT INTO LOOKUP_VALUE 
VALUES(546,87," ");

INSERT INTO LOOKUP_LABEL  
VALUES(167,83,1,'State'); 
INSERT INTO LOOKUP_LABEL  
VALUES(168,84,1,'Address1'); 
INSERT INTO LOOKUP_LABEL  
VALUES(169,85,1,'Address2'); 
INSERT INTO LOOKUP_LABEL  
VALUES(170,86,1,'Government ID'); 
INSERT INTO LOOKUP_LABEL  
VALUES(171,87,1,'Permissions');
INSERT INTO LOOKUP_LABEL 
VALUES(172,88,1,'Service Charge'); 



UPDATE LOOKUP_VALUE_LOCALE set LOOKUP_VALUE = 'Cashier' where LOOKUP_VALUE_ID = 113;
UPDATE LOOKUP_VALUE_LOCALE set LOOKUP_VALUE = 'Kendra Manager' where LOOKUP_VALUE_ID = 114;
UPDATE LOOKUP_VALUE_LOCALE set LOOKUP_VALUE = 'Branch Manager' where LOOKUP_VALUE_ID = 115;


INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(709,1,371,'Organization Management');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(710,1,372,'Funds');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(711,1,373,'Can create funds');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(712,1,374,'Can modify funds');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(713,1,375,'Fees');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(714,1,376,'Can define new fee type');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(715,1,377,'Can modify fee information');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(716,1,378,'Checklists');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(717,1,379,'Can define new checklist type');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(718,1,380,'Can modify checklist information');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(719,1,381,'Office management');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(720,1,382,'Offices');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(721,1,383,'Can create new office');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(722,1,384,'Can modify office information');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(723,1,385,'User management');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(724,1,386,'Personnel');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(725,1,387,'Can create new system users');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(726,1,388,'Can modify user information');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(727,1,389,'Can unlock a user');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(728,1,390,'Roles');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(729,1,391,'Can create new role');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(730,1,392,'Can modify a role');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(731,1,393,'Can delete a role');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(732,1,394,'Member management');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(733,1,395,'Members');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(734,1,396,'Can create new member in save for later state');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(735,1,397,'Can create new member in submit for approval state');
INSERT INTO LOOKUP_VALUE_LOCALE
VALUES(736,1,398,'Can change state to partial application');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(737,1,399,'Can change state to Approved');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(738,1,400,'Can change state to Cancelled');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(739,1,401,'Can change state to On Hold');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(740,1,402,'Can change state to Closed');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(741,1,403,'Can change state to pending for approval');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(742,1,404,'Can make payments to member accounts');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(743,1,405,'Can make adjustment entries to member account');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(744,1,406,'Can waive penalty');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(745,1,407,'Can waive a fee installment');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(746,1,408,'Can remove fee types from member account');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(747,1,409,'Can add notes to member');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(748,1,410,'Can edit MFI and personal information');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(749,1,411,'Can change group membership');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(750,1,412,'Can transfer the member');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(751,1,413,'Can edit meeting schedule');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(752,1,414,'Can add/edit historical data');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(753,1,415,'Can edit fee type attached to the account');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(754,1,416,'Can Blacklist a member');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(755,1,417,'Groups');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(756,1,418,'Can create new group in save for later state');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(757,1,419,'Can create new group in submit for approval state');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(758,1,420,'Can change state to Save for later');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(759,1,421,'Can change state to Approved');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(760,1,422,'Can change state to Cancelled');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(761,1,423,'Can change state to On Hold');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(762,1,424,'Can change state to Closed');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(763,1,425,'Can change state to pending for approval');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(764,1,426,'Can make payments to group accounts');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(765,1,427,'Can make adjustment entries to group account');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(766,1,428,'Can waive penalty');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(767,1,429,'Can waive a fee installment');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(768,1,430,'Can remove fee types from group account');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(769,1,431,'Can add notes to group');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(770,1,432,'Can edit Group information');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(771,1,433,'Can edit kendra membership');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(772,1,434,'Can transfer the group');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(773,1,435,'Can edit meeting schedule');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(774,1,436,'Can add/edit historical data');
INSERT INTO LOOKUP_VALUE_LOCALE
VALUES(775,1,437,'Can edit fee type attached to the account');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(776,1,438,'Can Blacklist a group');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(777,1,439,'Kendras');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(778,1,440,'Can create new kendra ');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(779,1,441,'Can modify kendra information ');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(780,1,442,'Can edit kendra status');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(781,1,443,'Can make payments to kendra accounts');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(782,1,444,'Can make adjustment entries to kendra account');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(783,1,445,'Can waive penalty');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(784,1,446,'Can waive a fee installment');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(785,1,447,'Can remove fee types from kendra account');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(786,1,448,'Can add notes to kendra records');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(787,1,449,'Can edit fee type attached to the account');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(788,1,450,'Product definition');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(789,1,451,'Product Categories');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(790,1,452,'Can define new product categories');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(791,1,453,'Can edit product category information');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(792,1,454,'Loan Products');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(793,1,455,'Can define new loan product instance');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(794,1,456,'Can edit loan product instances');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(795,1,457,'Margin money Products');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(796,1,458,'Can define new margin money product instance');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(797,1,459,'Can edit margin money product instances');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(798,1,460,'Loan management');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(799,1,461,'Loan Processing');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(800,1,462,'Can create new loan account in Save for later state');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(801,1,463,'Can create new loan account in Submit for approval state');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(802,1,464,'Can change state to partial application');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(803,1,465,'Can change state to Approved');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(804,1,466,'Can change state to Cancelled');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(805,1,467,'Can change state to Disbursed to LO');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(806,1,468,'Can change state to Active in good standing');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(807,1,469,'Can change state to pending approval');
INSERT INTO LOOKUP_VALUE_LOCALE
VALUES(808,1,470,'Can change state to Closed- Written off');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(809,1,471,'Can change state to Closed-rescheduled');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(810,1,472,'Can change state to Closed-Obligation met');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(811,1,473,'Can change state to bad standing');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(812,1,474,'Loan Transactions');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(813,1,475,'Can make payment to the account');
INSERT INTO LOOKUP_VALUE_LOCALE
VALUES(814,1,476,'Can make adjustment entry to the account');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(815,1,477,'Can edit account information');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(816,1,478,'Can waive penalty');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(817,1,479,'Can waive a fee installment');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(818,1,480,'Can remove fee types attached to the account');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(819,1,481,'Can specify meeting schedule');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(820,1,482,'Can specify meeting schedule');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(821,1,483,'Can update member');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(822,1,484,'Can edit meeting schedule ');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(823,1,485,'Can specify meeting schedule');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(824,1,486,'Can edit Loan account information');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(825,1,487,'Can apply charges to loans ');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(826,1,488,'Can edit self information');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(827,1,489,'Margin money Management');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(828,1,490,'Can create new margin money account in Save for later tate');
INSERT INTO LOOKUP_VALUE_LOCALE
VALUES(829,1,491,'Can update margin money account');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(830,1,492,'Can close margin money account');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(831,1,493,'Can change state to partial application');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(832,1,494,'Reports Management');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(833,1,495,'Can Administer Reports');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(834,1,496,'Can Preview Reports');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(835,1,497,'Can upload new reports');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(836,1,498,'Member Detail');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(837,1,499,'Kendra');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(838,1,500,'Status');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(839,1,501,'Performance');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(840,1,502,'Loan Product Detail');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(841,1,503,'Analysis');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(842,1,504,'Miscellaneous');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(843,1,505,'Can view Member Summary.& History Report');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(844,1,506,'Can view Member Product Wise History Report');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(845,1,507,'Can view Member Settlement info Report');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(846,1,508,'Can view Member Loan repayment schedule');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(847,1,509,'Can view Member Fees, Charges and Penalties report');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(848,1,510,'Can view Member pending approval report');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(849,1,511,'Can view Members without Margin Money Account');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(850,1,512,'Can view Collection sheet');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(851,1,513,'Can view Daily Cash Confirmation Report - Staff Wise');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(852,1,514,'Can view Daily Cash Flow Report - Branch');
INSERT INTO LOOKUP_VALUE_LOCALE
VALUES(853,1,515,'Can view Fund Requirement Report');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(854,1,516,'Can view Daily Transaction Summary report');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(855,1,517,'Can view Branch Performance Status Report');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(856,1,518,'Can view Area Performance Status Report');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(857,1,519,'Can view Division Performance Status Report');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(858,1,520,'Can view Region Performance Status Report');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(859,1,521,'Can view Grameen Koota Performance Status Report');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(860,1,522,'Can view Staff Performance Report');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(861,1,523,'Can view Outreach Report');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(862,1,524,'Can view Kendra Summary Report');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(863,1,525,'Can view Loan Product Distribution - Activity Wise, Size Wize, Product Wise, Sequency Wise');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(864,1,526,'Can view Branch Due disbursement Report');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(865,1,527,'Can view Loans pending approval report');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(866,1,528,'Can view Loan Accounts reports');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(867,1,529,'Can view Daily Portfolio quality data report - Aging analysis');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(868,1,530,'Can view Kendra Meeting Schedule');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(869,1,531,'Can repay loan');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(870,1,532,'Can add notes to loan account');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(871,1,533,'Can change state to pending approval');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(872,1,534,'Can change state to cancel');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(873,1,535,'Can change state to approved');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(874,1,536,'Can change state to inactive');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(875,1,537,'Can blacklist margin money account');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(876,1,538,'Can create new margin money account in submit for approval state');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(877,1,539,'Not implemented');
INSERT INTO LOOKUP_VALUE_LOCALE
VALUES(878,1,540,"Area Manager");
INSERT INTO LOOKUP_VALUE_LOCALE
VALUES(879,1,541,"Divisional Manager");
INSERT INTO LOOKUP_VALUE_LOCALE
VALUES(880,1,542,"Regional Manager");
INSERT INTO LOOKUP_VALUE_LOCALE
VALUES(881,1,543,"COO");
INSERT INTO LOOKUP_VALUE_LOCALE
VALUES(882,1,544,"MIS Team");
INSERT INTO LOOKUP_VALUE_LOCALE
VALUES(883,1,545,"IT Team");
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(884,1,546,'Can do adjustments for savings account');




UPDATE ACTIVITY set PARENT_ID = NULL,ACTIVITY_NAME_LOOKUP_ID = 371,DESCRIPTION_LOOKUP_ID = 371 where ACTIVITY_ID =1;
UPDATE ACTIVITY set PARENT_ID = 1,ACTIVITY_NAME_LOOKUP_ID = 372,DESCRIPTION_LOOKUP_ID = 372 where ACTIVITY_ID =2;
UPDATE ACTIVITY set PARENT_ID = 2,ACTIVITY_NAME_LOOKUP_ID = 373,DESCRIPTION_LOOKUP_ID = 373 where ACTIVITY_ID =3;
UPDATE ACTIVITY set PARENT_ID = 2,ACTIVITY_NAME_LOOKUP_ID = 374,DESCRIPTION_LOOKUP_ID = 374 where ACTIVITY_ID =4;
UPDATE ACTIVITY set PARENT_ID = 1,ACTIVITY_NAME_LOOKUP_ID = 375,DESCRIPTION_LOOKUP_ID = 375 where ACTIVITY_ID =5;
UPDATE ACTIVITY set PARENT_ID = 5,ACTIVITY_NAME_LOOKUP_ID = 376,DESCRIPTION_LOOKUP_ID = 376 where ACTIVITY_ID =6;
UPDATE ACTIVITY set PARENT_ID = 5,ACTIVITY_NAME_LOOKUP_ID = 377,DESCRIPTION_LOOKUP_ID = 377 where ACTIVITY_ID =7;
UPDATE ACTIVITY set PARENT_ID = 1,ACTIVITY_NAME_LOOKUP_ID = 378,DESCRIPTION_LOOKUP_ID = 378 where ACTIVITY_ID =8;
UPDATE ACTIVITY set PARENT_ID = 8,ACTIVITY_NAME_LOOKUP_ID = 379,DESCRIPTION_LOOKUP_ID = 379 where ACTIVITY_ID =9;
UPDATE ACTIVITY set PARENT_ID = 8,ACTIVITY_NAME_LOOKUP_ID = 380,DESCRIPTION_LOOKUP_ID = 380 where ACTIVITY_ID =10;
UPDATE ACTIVITY set PARENT_ID = NULL,ACTIVITY_NAME_LOOKUP_ID = 381,DESCRIPTION_LOOKUP_ID = 381 where ACTIVITY_ID =13;
UPDATE ACTIVITY set PARENT_ID = 13,ACTIVITY_NAME_LOOKUP_ID = 382,DESCRIPTION_LOOKUP_ID = 382 where ACTIVITY_ID =14;
UPDATE ACTIVITY set PARENT_ID = 14,ACTIVITY_NAME_LOOKUP_ID = 383,DESCRIPTION_LOOKUP_ID = 383 where ACTIVITY_ID =15;
UPDATE ACTIVITY set PARENT_ID = 14,ACTIVITY_NAME_LOOKUP_ID = 384,DESCRIPTION_LOOKUP_ID = 384 where ACTIVITY_ID =16;
UPDATE ACTIVITY set PARENT_ID = NULL,ACTIVITY_NAME_LOOKUP_ID = 385,DESCRIPTION_LOOKUP_ID = 385 where ACTIVITY_ID =17;
UPDATE ACTIVITY set PARENT_ID = 17,ACTIVITY_NAME_LOOKUP_ID = 386,DESCRIPTION_LOOKUP_ID = 386 where ACTIVITY_ID =18;
UPDATE ACTIVITY set PARENT_ID = 18,ACTIVITY_NAME_LOOKUP_ID = 387,DESCRIPTION_LOOKUP_ID = 387 where ACTIVITY_ID =19;
UPDATE ACTIVITY set PARENT_ID = 18,ACTIVITY_NAME_LOOKUP_ID = 388,DESCRIPTION_LOOKUP_ID = 388 where ACTIVITY_ID =20;
UPDATE ACTIVITY set PARENT_ID = 18,ACTIVITY_NAME_LOOKUP_ID = 389,DESCRIPTION_LOOKUP_ID = 389 where ACTIVITY_ID =21;
UPDATE ACTIVITY set PARENT_ID = 17,ACTIVITY_NAME_LOOKUP_ID = 390,DESCRIPTION_LOOKUP_ID = 390 where ACTIVITY_ID =22;
UPDATE ACTIVITY set PARENT_ID = 22,ACTIVITY_NAME_LOOKUP_ID = 391,DESCRIPTION_LOOKUP_ID = 391 where ACTIVITY_ID =23;
UPDATE ACTIVITY set PARENT_ID = 22,ACTIVITY_NAME_LOOKUP_ID = 392,DESCRIPTION_LOOKUP_ID = 392 where ACTIVITY_ID =24;
UPDATE ACTIVITY set PARENT_ID = 22,ACTIVITY_NAME_LOOKUP_ID = 393,DESCRIPTION_LOOKUP_ID = 393 where ACTIVITY_ID =25;
UPDATE ACTIVITY set PARENT_ID = NULL,ACTIVITY_NAME_LOOKUP_ID = 394,DESCRIPTION_LOOKUP_ID = 394 where ACTIVITY_ID =33;
UPDATE ACTIVITY set PARENT_ID = 33,ACTIVITY_NAME_LOOKUP_ID = 395,DESCRIPTION_LOOKUP_ID = 395 where ACTIVITY_ID =34;
UPDATE ACTIVITY set PARENT_ID = 34,ACTIVITY_NAME_LOOKUP_ID = 396,DESCRIPTION_LOOKUP_ID = 396 where ACTIVITY_ID =35;
UPDATE ACTIVITY set PARENT_ID = 34,ACTIVITY_NAME_LOOKUP_ID = 397,DESCRIPTION_LOOKUP_ID = 397 where ACTIVITY_ID =36;
UPDATE ACTIVITY set PARENT_ID = 34,ACTIVITY_NAME_LOOKUP_ID = 398,DESCRIPTION_LOOKUP_ID = 398 where ACTIVITY_ID =37;
UPDATE ACTIVITY set PARENT_ID = 34,ACTIVITY_NAME_LOOKUP_ID = 399,DESCRIPTION_LOOKUP_ID = 399 where ACTIVITY_ID =38;
UPDATE ACTIVITY set PARENT_ID = 34,ACTIVITY_NAME_LOOKUP_ID = 400,DESCRIPTION_LOOKUP_ID = 400 where ACTIVITY_ID =39;
UPDATE ACTIVITY set PARENT_ID = 34,ACTIVITY_NAME_LOOKUP_ID = 401,DESCRIPTION_LOOKUP_ID = 401 where ACTIVITY_ID =40;
UPDATE ACTIVITY set PARENT_ID = 34,ACTIVITY_NAME_LOOKUP_ID = 402,DESCRIPTION_LOOKUP_ID = 402 where ACTIVITY_ID =41;
UPDATE ACTIVITY set PARENT_ID = 34,ACTIVITY_NAME_LOOKUP_ID = 403,DESCRIPTION_LOOKUP_ID = 403 where ACTIVITY_ID =42;
UPDATE ACTIVITY set PARENT_ID = 34,ACTIVITY_NAME_LOOKUP_ID = 404,DESCRIPTION_LOOKUP_ID = 539 where ACTIVITY_ID =43;
UPDATE ACTIVITY set PARENT_ID = 34,ACTIVITY_NAME_LOOKUP_ID = 405,DESCRIPTION_LOOKUP_ID = 539 where ACTIVITY_ID =44;
UPDATE ACTIVITY set PARENT_ID = 34,ACTIVITY_NAME_LOOKUP_ID = 406,DESCRIPTION_LOOKUP_ID = 539 where ACTIVITY_ID =45;
UPDATE ACTIVITY set PARENT_ID = 34,ACTIVITY_NAME_LOOKUP_ID = 407,DESCRIPTION_LOOKUP_ID = 539 where ACTIVITY_ID =46;
UPDATE ACTIVITY set PARENT_ID = 34,ACTIVITY_NAME_LOOKUP_ID = 408,DESCRIPTION_LOOKUP_ID = 539 where ACTIVITY_ID =47;
UPDATE ACTIVITY set PARENT_ID = 34,ACTIVITY_NAME_LOOKUP_ID = 409,DESCRIPTION_LOOKUP_ID = 409 where ACTIVITY_ID =48;
UPDATE ACTIVITY set PARENT_ID = 34,ACTIVITY_NAME_LOOKUP_ID = 410,DESCRIPTION_LOOKUP_ID = 410 where ACTIVITY_ID =49;
UPDATE ACTIVITY set PARENT_ID = 34,ACTIVITY_NAME_LOOKUP_ID = 411,DESCRIPTION_LOOKUP_ID = 411 where ACTIVITY_ID =50;
UPDATE ACTIVITY set PARENT_ID = 34,ACTIVITY_NAME_LOOKUP_ID = 412,DESCRIPTION_LOOKUP_ID = 412 where ACTIVITY_ID =51;
UPDATE ACTIVITY set PARENT_ID = 34,ACTIVITY_NAME_LOOKUP_ID = 413,DESCRIPTION_LOOKUP_ID = 413 where ACTIVITY_ID =52;
UPDATE ACTIVITY set PARENT_ID = 34,ACTIVITY_NAME_LOOKUP_ID = 414,DESCRIPTION_LOOKUP_ID = 414 where ACTIVITY_ID =53;
UPDATE ACTIVITY set PARENT_ID = 34,ACTIVITY_NAME_LOOKUP_ID = 415,DESCRIPTION_LOOKUP_ID = 539 where ACTIVITY_ID =54;
UPDATE ACTIVITY set PARENT_ID = 34,ACTIVITY_NAME_LOOKUP_ID = 416,DESCRIPTION_LOOKUP_ID = 416 where ACTIVITY_ID =55;
UPDATE ACTIVITY set PARENT_ID = 33,ACTIVITY_NAME_LOOKUP_ID = 417,DESCRIPTION_LOOKUP_ID = 417 where ACTIVITY_ID =56;
UPDATE ACTIVITY set PARENT_ID = 56,ACTIVITY_NAME_LOOKUP_ID = 418,DESCRIPTION_LOOKUP_ID = 418 where ACTIVITY_ID =57;
UPDATE ACTIVITY set PARENT_ID = 56,ACTIVITY_NAME_LOOKUP_ID = 419,DESCRIPTION_LOOKUP_ID = 419 where ACTIVITY_ID =58;
UPDATE ACTIVITY set PARENT_ID = 56,ACTIVITY_NAME_LOOKUP_ID = 420,DESCRIPTION_LOOKUP_ID = 420 where ACTIVITY_ID =59;
UPDATE ACTIVITY set PARENT_ID = 56,ACTIVITY_NAME_LOOKUP_ID = 421,DESCRIPTION_LOOKUP_ID = 421 where ACTIVITY_ID =60;
UPDATE ACTIVITY set PARENT_ID = 56,ACTIVITY_NAME_LOOKUP_ID = 422,DESCRIPTION_LOOKUP_ID = 422 where ACTIVITY_ID =61;
UPDATE ACTIVITY set PARENT_ID = 56,ACTIVITY_NAME_LOOKUP_ID = 423,DESCRIPTION_LOOKUP_ID = 423 where ACTIVITY_ID =62;
UPDATE ACTIVITY set PARENT_ID = 56,ACTIVITY_NAME_LOOKUP_ID = 424,DESCRIPTION_LOOKUP_ID = 424 where ACTIVITY_ID =63;
UPDATE ACTIVITY set PARENT_ID = 56,ACTIVITY_NAME_LOOKUP_ID = 425,DESCRIPTION_LOOKUP_ID = 425 where ACTIVITY_ID =64;
UPDATE ACTIVITY set PARENT_ID = 56,ACTIVITY_NAME_LOOKUP_ID = 426,DESCRIPTION_LOOKUP_ID = 539 where ACTIVITY_ID =65;
UPDATE ACTIVITY set PARENT_ID = 56,ACTIVITY_NAME_LOOKUP_ID = 427,DESCRIPTION_LOOKUP_ID = 539 where ACTIVITY_ID =66;
UPDATE ACTIVITY set PARENT_ID = 56,ACTIVITY_NAME_LOOKUP_ID = 428,DESCRIPTION_LOOKUP_ID = 539 where ACTIVITY_ID =67;
UPDATE ACTIVITY set PARENT_ID = 56,ACTIVITY_NAME_LOOKUP_ID = 429,DESCRIPTION_LOOKUP_ID = 539 where ACTIVITY_ID =68;
UPDATE ACTIVITY set PARENT_ID = 56,ACTIVITY_NAME_LOOKUP_ID = 430,DESCRIPTION_LOOKUP_ID = 539 where ACTIVITY_ID =69;
UPDATE ACTIVITY set PARENT_ID = 56,ACTIVITY_NAME_LOOKUP_ID = 431,DESCRIPTION_LOOKUP_ID = 431 where ACTIVITY_ID =70;
UPDATE ACTIVITY set PARENT_ID = 56,ACTIVITY_NAME_LOOKUP_ID = 432,DESCRIPTION_LOOKUP_ID = 432 where ACTIVITY_ID =71;
UPDATE ACTIVITY set PARENT_ID = 56,ACTIVITY_NAME_LOOKUP_ID = 433,DESCRIPTION_LOOKUP_ID = 433 where ACTIVITY_ID =72;
UPDATE ACTIVITY set PARENT_ID = 56,ACTIVITY_NAME_LOOKUP_ID = 434,DESCRIPTION_LOOKUP_ID = 434 where ACTIVITY_ID =73;
UPDATE ACTIVITY set PARENT_ID = 56,ACTIVITY_NAME_LOOKUP_ID = 435,DESCRIPTION_LOOKUP_ID = 435 where ACTIVITY_ID =74;
UPDATE ACTIVITY set PARENT_ID = 56,ACTIVITY_NAME_LOOKUP_ID = 436,DESCRIPTION_LOOKUP_ID = 436 where ACTIVITY_ID =75;
UPDATE ACTIVITY set PARENT_ID = 56,ACTIVITY_NAME_LOOKUP_ID = 437,DESCRIPTION_LOOKUP_ID = 539 where ACTIVITY_ID =76;
UPDATE ACTIVITY set PARENT_ID = 56,ACTIVITY_NAME_LOOKUP_ID = 438,DESCRIPTION_LOOKUP_ID = 438 where ACTIVITY_ID =77;
UPDATE ACTIVITY set PARENT_ID = 33,ACTIVITY_NAME_LOOKUP_ID = 439,DESCRIPTION_LOOKUP_ID = 439 where ACTIVITY_ID =78;
UPDATE ACTIVITY set PARENT_ID = 78,ACTIVITY_NAME_LOOKUP_ID = 440,DESCRIPTION_LOOKUP_ID = 440 where ACTIVITY_ID =79;
UPDATE ACTIVITY set PARENT_ID = 78,ACTIVITY_NAME_LOOKUP_ID = 441,DESCRIPTION_LOOKUP_ID = 441 where ACTIVITY_ID =80;
UPDATE ACTIVITY set PARENT_ID = 78,ACTIVITY_NAME_LOOKUP_ID = 442,DESCRIPTION_LOOKUP_ID = 442 where ACTIVITY_ID =81;
UPDATE ACTIVITY set PARENT_ID = 78,ACTIVITY_NAME_LOOKUP_ID = 443,DESCRIPTION_LOOKUP_ID = 539 where ACTIVITY_ID =82;
UPDATE ACTIVITY set PARENT_ID = 78,ACTIVITY_NAME_LOOKUP_ID = 444,DESCRIPTION_LOOKUP_ID = 539 where ACTIVITY_ID =83;
UPDATE ACTIVITY set PARENT_ID = 78,ACTIVITY_NAME_LOOKUP_ID = 445,DESCRIPTION_LOOKUP_ID = 539 where ACTIVITY_ID =84;
UPDATE ACTIVITY set PARENT_ID = 78,ACTIVITY_NAME_LOOKUP_ID = 446,DESCRIPTION_LOOKUP_ID = 539 where ACTIVITY_ID =85;
UPDATE ACTIVITY set PARENT_ID = 78,ACTIVITY_NAME_LOOKUP_ID = 447,DESCRIPTION_LOOKUP_ID = 539 where ACTIVITY_ID =86;
UPDATE ACTIVITY set PARENT_ID = 78,ACTIVITY_NAME_LOOKUP_ID = 448,DESCRIPTION_LOOKUP_ID = 438 where ACTIVITY_ID =87;
UPDATE ACTIVITY set PARENT_ID = 78,ACTIVITY_NAME_LOOKUP_ID = 449,DESCRIPTION_LOOKUP_ID = 539 where ACTIVITY_ID =88;
UPDATE ACTIVITY set PARENT_ID = NULL,ACTIVITY_NAME_LOOKUP_ID = 450,DESCRIPTION_LOOKUP_ID = 450 where ACTIVITY_ID =89;
UPDATE ACTIVITY set PARENT_ID = 89,ACTIVITY_NAME_LOOKUP_ID = 451,DESCRIPTION_LOOKUP_ID = 451 where ACTIVITY_ID =90;
UPDATE ACTIVITY set PARENT_ID = 90,ACTIVITY_NAME_LOOKUP_ID = 452,DESCRIPTION_LOOKUP_ID = 452 where ACTIVITY_ID =91;
UPDATE ACTIVITY set PARENT_ID = 90,ACTIVITY_NAME_LOOKUP_ID = 453,DESCRIPTION_LOOKUP_ID = 453 where ACTIVITY_ID =92;
UPDATE ACTIVITY set PARENT_ID = 89,ACTIVITY_NAME_LOOKUP_ID = 454,DESCRIPTION_LOOKUP_ID = 454 where ACTIVITY_ID =93;
UPDATE ACTIVITY set PARENT_ID = 93,ACTIVITY_NAME_LOOKUP_ID = 455,DESCRIPTION_LOOKUP_ID = 455 where ACTIVITY_ID =94;
UPDATE ACTIVITY set PARENT_ID = 93,ACTIVITY_NAME_LOOKUP_ID = 456,DESCRIPTION_LOOKUP_ID = 456 where ACTIVITY_ID =95;
UPDATE ACTIVITY set PARENT_ID = 89,ACTIVITY_NAME_LOOKUP_ID = 457,DESCRIPTION_LOOKUP_ID = 457 where ACTIVITY_ID =96;
UPDATE ACTIVITY set PARENT_ID = 96,ACTIVITY_NAME_LOOKUP_ID = 458,DESCRIPTION_LOOKUP_ID = 458 where ACTIVITY_ID =97;
UPDATE ACTIVITY set PARENT_ID = 96,ACTIVITY_NAME_LOOKUP_ID = 459,DESCRIPTION_LOOKUP_ID = 459 where ACTIVITY_ID =98;
UPDATE ACTIVITY set PARENT_ID = NULL,ACTIVITY_NAME_LOOKUP_ID = 460,DESCRIPTION_LOOKUP_ID = 460 where ACTIVITY_ID =99;
UPDATE ACTIVITY set PARENT_ID = 99,ACTIVITY_NAME_LOOKUP_ID = 461,DESCRIPTION_LOOKUP_ID = 461 where ACTIVITY_ID =100;
UPDATE ACTIVITY set PARENT_ID = 100,ACTIVITY_NAME_LOOKUP_ID = 462,DESCRIPTION_LOOKUP_ID = 462 where ACTIVITY_ID =101;
UPDATE ACTIVITY set PARENT_ID = 100,ACTIVITY_NAME_LOOKUP_ID = 463,DESCRIPTION_LOOKUP_ID = 463 where ACTIVITY_ID =102;
UPDATE ACTIVITY set PARENT_ID = 100,ACTIVITY_NAME_LOOKUP_ID = 464,DESCRIPTION_LOOKUP_ID = 464 where ACTIVITY_ID =103;
UPDATE ACTIVITY set PARENT_ID = 100,ACTIVITY_NAME_LOOKUP_ID = 465,DESCRIPTION_LOOKUP_ID = 465 where ACTIVITY_ID =104;
UPDATE ACTIVITY set PARENT_ID = 100,ACTIVITY_NAME_LOOKUP_ID = 466,DESCRIPTION_LOOKUP_ID = 466 where ACTIVITY_ID =105;
UPDATE ACTIVITY set PARENT_ID = 100,ACTIVITY_NAME_LOOKUP_ID = 467,DESCRIPTION_LOOKUP_ID = 467 where ACTIVITY_ID =106;
UPDATE ACTIVITY set PARENT_ID = 100,ACTIVITY_NAME_LOOKUP_ID = 468,DESCRIPTION_LOOKUP_ID = 468 where ACTIVITY_ID =107;
UPDATE ACTIVITY set PARENT_ID = 100,ACTIVITY_NAME_LOOKUP_ID = 469,DESCRIPTION_LOOKUP_ID = 469 where ACTIVITY_ID =108;
UPDATE ACTIVITY set PARENT_ID = 100,ACTIVITY_NAME_LOOKUP_ID = 470,DESCRIPTION_LOOKUP_ID = 470 where ACTIVITY_ID =109;
UPDATE ACTIVITY set PARENT_ID = 100,ACTIVITY_NAME_LOOKUP_ID = 471,DESCRIPTION_LOOKUP_ID = 471 where ACTIVITY_ID =110;
UPDATE ACTIVITY set PARENT_ID = 100,ACTIVITY_NAME_LOOKUP_ID = 472,DESCRIPTION_LOOKUP_ID = 472 where ACTIVITY_ID =111;
UPDATE ACTIVITY set PARENT_ID = 100,ACTIVITY_NAME_LOOKUP_ID = 473,DESCRIPTION_LOOKUP_ID = 473 where ACTIVITY_ID =112;
UPDATE ACTIVITY set PARENT_ID = 99,ACTIVITY_NAME_LOOKUP_ID = 474,DESCRIPTION_LOOKUP_ID = 474 where ACTIVITY_ID =113;
UPDATE ACTIVITY set PARENT_ID = 113,ACTIVITY_NAME_LOOKUP_ID = 475,DESCRIPTION_LOOKUP_ID = 539 where ACTIVITY_ID =115;
UPDATE ACTIVITY set PARENT_ID = 113,ACTIVITY_NAME_LOOKUP_ID = 476,DESCRIPTION_LOOKUP_ID = 539 where ACTIVITY_ID =116;
UPDATE ACTIVITY set PARENT_ID = 113,ACTIVITY_NAME_LOOKUP_ID = 477,DESCRIPTION_LOOKUP_ID = 539 where ACTIVITY_ID =117;
UPDATE ACTIVITY set PARENT_ID = 113,ACTIVITY_NAME_LOOKUP_ID = 478,DESCRIPTION_LOOKUP_ID = 539 where ACTIVITY_ID =118;
UPDATE ACTIVITY set PARENT_ID = 113,ACTIVITY_NAME_LOOKUP_ID = 479,DESCRIPTION_LOOKUP_ID = 539 where ACTIVITY_ID =119;
UPDATE ACTIVITY set PARENT_ID = 113,ACTIVITY_NAME_LOOKUP_ID = 480,DESCRIPTION_LOOKUP_ID = 480 where ACTIVITY_ID =120;
UPDATE ACTIVITY set PARENT_ID = 34,ACTIVITY_NAME_LOOKUP_ID = 481,DESCRIPTION_LOOKUP_ID = 481 where ACTIVITY_ID =121;
UPDATE ACTIVITY set PARENT_ID = 56,ACTIVITY_NAME_LOOKUP_ID = 482,DESCRIPTION_LOOKUP_ID = 482 where ACTIVITY_ID =122;
UPDATE ACTIVITY set PARENT_ID = 34,ACTIVITY_NAME_LOOKUP_ID = 483,DESCRIPTION_LOOKUP_ID = 483 where ACTIVITY_ID =126;
UPDATE ACTIVITY set PARENT_ID = 78,ACTIVITY_NAME_LOOKUP_ID = 484,DESCRIPTION_LOOKUP_ID = 484 where ACTIVITY_ID =127;
UPDATE ACTIVITY set PARENT_ID = 78,ACTIVITY_NAME_LOOKUP_ID = 485,DESCRIPTION_LOOKUP_ID = 485 where ACTIVITY_ID =128;
UPDATE ACTIVITY set PARENT_ID = 100,ACTIVITY_NAME_LOOKUP_ID = 486,DESCRIPTION_LOOKUP_ID = 486 where ACTIVITY_ID =129;
UPDATE ACTIVITY set PARENT_ID = 113,ACTIVITY_NAME_LOOKUP_ID = 487,DESCRIPTION_LOOKUP_ID = 487 where ACTIVITY_ID =131;
UPDATE ACTIVITY set PARENT_ID = 18,ACTIVITY_NAME_LOOKUP_ID = 488,DESCRIPTION_LOOKUP_ID = 488 where ACTIVITY_ID =135;
UPDATE ACTIVITY set PARENT_ID = NULL,ACTIVITY_NAME_LOOKUP_ID = 489,DESCRIPTION_LOOKUP_ID = 489 where ACTIVITY_ID =136;
UPDATE ACTIVITY set PARENT_ID = 136,ACTIVITY_NAME_LOOKUP_ID = 490,DESCRIPTION_LOOKUP_ID = 490 where ACTIVITY_ID =137;
UPDATE ACTIVITY set PARENT_ID = 136,ACTIVITY_NAME_LOOKUP_ID = 491,DESCRIPTION_LOOKUP_ID = 491 where ACTIVITY_ID =138;
UPDATE ACTIVITY set PARENT_ID = 136,ACTIVITY_NAME_LOOKUP_ID = 492,DESCRIPTION_LOOKUP_ID = 492 where ACTIVITY_ID =139;
UPDATE ACTIVITY set PARENT_ID = 136,ACTIVITY_NAME_LOOKUP_ID = 493,DESCRIPTION_LOOKUP_ID = 493 where ACTIVITY_ID =140;
UPDATE ACTIVITY set PARENT_ID = NULL,ACTIVITY_NAME_LOOKUP_ID = 494,DESCRIPTION_LOOKUP_ID = 493 where ACTIVITY_ID =141;
UPDATE ACTIVITY set PARENT_ID = 141,ACTIVITY_NAME_LOOKUP_ID = 495,DESCRIPTION_LOOKUP_ID = 495 where ACTIVITY_ID =142;
UPDATE ACTIVITY set PARENT_ID = 141,ACTIVITY_NAME_LOOKUP_ID = 496,DESCRIPTION_LOOKUP_ID = 496 where ACTIVITY_ID =143;
UPDATE ACTIVITY set PARENT_ID = 141,ACTIVITY_NAME_LOOKUP_ID = 497,DESCRIPTION_LOOKUP_ID = 497 where ACTIVITY_ID =144;
UPDATE ACTIVITY set PARENT_ID = 141,ACTIVITY_NAME_LOOKUP_ID = 498,DESCRIPTION_LOOKUP_ID = 498 where ACTIVITY_ID =145;
UPDATE ACTIVITY set PARENT_ID = 141,ACTIVITY_NAME_LOOKUP_ID = 499,DESCRIPTION_LOOKUP_ID = 499 where ACTIVITY_ID =146;
UPDATE ACTIVITY set PARENT_ID = 141,ACTIVITY_NAME_LOOKUP_ID = 500,DESCRIPTION_LOOKUP_ID = 500 where ACTIVITY_ID =147;
UPDATE ACTIVITY set PARENT_ID = 141,ACTIVITY_NAME_LOOKUP_ID = 501,DESCRIPTION_LOOKUP_ID = 501 where ACTIVITY_ID =148;
UPDATE ACTIVITY set PARENT_ID = 141,ACTIVITY_NAME_LOOKUP_ID = 502,DESCRIPTION_LOOKUP_ID = 502 where ACTIVITY_ID =149;
UPDATE ACTIVITY set PARENT_ID = 141,ACTIVITY_NAME_LOOKUP_ID = 503,DESCRIPTION_LOOKUP_ID = 503 where ACTIVITY_ID =150;
UPDATE ACTIVITY set PARENT_ID = 141,ACTIVITY_NAME_LOOKUP_ID = 504,DESCRIPTION_LOOKUP_ID = 504 where ACTIVITY_ID =151;
UPDATE ACTIVITY set PARENT_ID = 145,ACTIVITY_NAME_LOOKUP_ID = 505,DESCRIPTION_LOOKUP_ID = 505 where ACTIVITY_ID =152;
UPDATE ACTIVITY set PARENT_ID = 145,ACTIVITY_NAME_LOOKUP_ID = 506,DESCRIPTION_LOOKUP_ID = 506 where ACTIVITY_ID =153;
UPDATE ACTIVITY set PARENT_ID = 145,ACTIVITY_NAME_LOOKUP_ID = 507,DESCRIPTION_LOOKUP_ID = 507 where ACTIVITY_ID =154;
UPDATE ACTIVITY set PARENT_ID = 145,ACTIVITY_NAME_LOOKUP_ID = 508,DESCRIPTION_LOOKUP_ID = 508 where ACTIVITY_ID =155;
UPDATE ACTIVITY set PARENT_ID = 145,ACTIVITY_NAME_LOOKUP_ID = 509,DESCRIPTION_LOOKUP_ID = 509 where ACTIVITY_ID =156;
UPDATE ACTIVITY set PARENT_ID = 145,ACTIVITY_NAME_LOOKUP_ID = 510,DESCRIPTION_LOOKUP_ID = 510 where ACTIVITY_ID =157;
UPDATE ACTIVITY set PARENT_ID = 145,ACTIVITY_NAME_LOOKUP_ID = 511,DESCRIPTION_LOOKUP_ID = 511 where ACTIVITY_ID =158;
UPDATE ACTIVITY set PARENT_ID = 146,ACTIVITY_NAME_LOOKUP_ID = 512,DESCRIPTION_LOOKUP_ID = 512 where ACTIVITY_ID =159;
UPDATE ACTIVITY set PARENT_ID = 147,ACTIVITY_NAME_LOOKUP_ID = 513,DESCRIPTION_LOOKUP_ID = 513 where ACTIVITY_ID =160;
UPDATE ACTIVITY set PARENT_ID = 147,ACTIVITY_NAME_LOOKUP_ID = 514,DESCRIPTION_LOOKUP_ID = 514 where ACTIVITY_ID =161;
UPDATE ACTIVITY set PARENT_ID = 147,ACTIVITY_NAME_LOOKUP_ID = 515,DESCRIPTION_LOOKUP_ID = 515 where ACTIVITY_ID =162;
UPDATE ACTIVITY set PARENT_ID = 147,ACTIVITY_NAME_LOOKUP_ID = 516,DESCRIPTION_LOOKUP_ID = 516 where ACTIVITY_ID =163;
UPDATE ACTIVITY set PARENT_ID = 148,ACTIVITY_NAME_LOOKUP_ID = 517,DESCRIPTION_LOOKUP_ID = 517 where ACTIVITY_ID =164;
UPDATE ACTIVITY set PARENT_ID = 148,ACTIVITY_NAME_LOOKUP_ID = 518,DESCRIPTION_LOOKUP_ID = 518 where ACTIVITY_ID =165;
UPDATE ACTIVITY set PARENT_ID = 148,ACTIVITY_NAME_LOOKUP_ID = 519,DESCRIPTION_LOOKUP_ID = 519 where ACTIVITY_ID =166;
UPDATE ACTIVITY set PARENT_ID = 148,ACTIVITY_NAME_LOOKUP_ID = 520,DESCRIPTION_LOOKUP_ID = 520 where ACTIVITY_ID =167;
UPDATE ACTIVITY set PARENT_ID = 148,ACTIVITY_NAME_LOOKUP_ID = 521,DESCRIPTION_LOOKUP_ID = 521 where ACTIVITY_ID =168;
UPDATE ACTIVITY set PARENT_ID = 148,ACTIVITY_NAME_LOOKUP_ID = 522,DESCRIPTION_LOOKUP_ID = 522 where ACTIVITY_ID =169;
UPDATE ACTIVITY set PARENT_ID = 148,ACTIVITY_NAME_LOOKUP_ID = 523,DESCRIPTION_LOOKUP_ID = 523 where ACTIVITY_ID =170;
UPDATE ACTIVITY set PARENT_ID = 148,ACTIVITY_NAME_LOOKUP_ID = 524,DESCRIPTION_LOOKUP_ID = 524 where ACTIVITY_ID =171;
UPDATE ACTIVITY set PARENT_ID = 149,ACTIVITY_NAME_LOOKUP_ID = 525,DESCRIPTION_LOOKUP_ID = 525 where ACTIVITY_ID =172;
UPDATE ACTIVITY set PARENT_ID = 149,ACTIVITY_NAME_LOOKUP_ID = 526,DESCRIPTION_LOOKUP_ID = 526 where ACTIVITY_ID =173;
UPDATE ACTIVITY set PARENT_ID = 149,ACTIVITY_NAME_LOOKUP_ID = 527,DESCRIPTION_LOOKUP_ID = 527 where ACTIVITY_ID =174;
UPDATE ACTIVITY set PARENT_ID = 149,ACTIVITY_NAME_LOOKUP_ID = 528,DESCRIPTION_LOOKUP_ID = 528 where ACTIVITY_ID =175;
UPDATE ACTIVITY set PARENT_ID = 150,ACTIVITY_NAME_LOOKUP_ID = 529,DESCRIPTION_LOOKUP_ID = 529 where ACTIVITY_ID =176;
UPDATE ACTIVITY set PARENT_ID = 151,ACTIVITY_NAME_LOOKUP_ID = 530,DESCRIPTION_LOOKUP_ID = 530 where ACTIVITY_ID =177;
UPDATE ACTIVITY set PARENT_ID = 113,ACTIVITY_NAME_LOOKUP_ID = 531,DESCRIPTION_LOOKUP_ID = 531 where ACTIVITY_ID =178;
UPDATE ACTIVITY set PARENT_ID = 100,ACTIVITY_NAME_LOOKUP_ID = 532,DESCRIPTION_LOOKUP_ID = 532 where ACTIVITY_ID =179;
UPDATE ACTIVITY set PARENT_ID = 136,ACTIVITY_NAME_LOOKUP_ID = 533,DESCRIPTION_LOOKUP_ID = 533 where ACTIVITY_ID =180;
UPDATE ACTIVITY set PARENT_ID = 136,ACTIVITY_NAME_LOOKUP_ID = 534,DESCRIPTION_LOOKUP_ID = 534 where ACTIVITY_ID =181;
UPDATE ACTIVITY set PARENT_ID = 136,ACTIVITY_NAME_LOOKUP_ID = 535,DESCRIPTION_LOOKUP_ID = 535 where ACTIVITY_ID =182;
UPDATE ACTIVITY set PARENT_ID = 136,ACTIVITY_NAME_LOOKUP_ID = 536,DESCRIPTION_LOOKUP_ID = 536 where ACTIVITY_ID =183;
UPDATE ACTIVITY set PARENT_ID = 136,ACTIVITY_NAME_LOOKUP_ID = 537,DESCRIPTION_LOOKUP_ID = 537 where ACTIVITY_ID =184;
UPDATE ACTIVITY set PARENT_ID = 136,ACTIVITY_NAME_LOOKUP_ID = 538,DESCRIPTION_LOOKUP_ID = 538 where ACTIVITY_ID =185;
INSERT INTO ACTIVITY(ACTIVITY_ID,PARENT_ID,ACTIVITY_NAME_LOOKUP_ID,DESCRIPTION_LOOKUP_ID) VALUES(186,136,546,546 );

INSERT INTO ROLES_ACTIVITY(ACTIVITY_ID,ROLE_ID,VERSION_NO) 
VALUES(186,1,1);


ALTER TABLE ACTIVITY ADD FOREIGN KEY(ACTIVITY_NAME_LOOKUP_ID) REFERENCES LOOKUP_VALUE(LOOKUP_ID);
ALTER TABLE ACTIVITY ADD FOREIGN KEY(DESCRIPTION_LOOKUP_ID) REFERENCES LOOKUP_VALUE(LOOKUP_ID);

INSERT INTO ENTITY_MASTER(ENTITY_TYPE_ID,ENTITY_TYPE)
VALUES(23,"BulkEntry");

INSERT INTO WEEK_DAYS_MASTER(WEEK_DAYS_MASTER_ID,LOOKUP_ID,WORKING_DAY,START_OF_FISCAL_WEEK)
VALUES(1,72,0,0); 

UPDATE WEEK_DAYS_MASTER set WORKING_DAY = 1 where WEEK_DAYS_MASTER_ID = 2;
UPDATE WEEK_DAYS_MASTER set WORKING_DAY = 1 where WEEK_DAYS_MASTER_ID = 3;
UPDATE WEEK_DAYS_MASTER set WORKING_DAY = 1 where WEEK_DAYS_MASTER_ID = 4;
UPDATE WEEK_DAYS_MASTER set WORKING_DAY = 1 where WEEK_DAYS_MASTER_ID = 5;
UPDATE WEEK_DAYS_MASTER set WORKING_DAY = 1 where WEEK_DAYS_MASTER_ID = 6;
UPDATE WEEK_DAYS_MASTER set WORKING_DAY = 1 where WEEK_DAYS_MASTER_ID = 7;



INSERT INTO FIELD_CONFIGURATION
VALUES(1,"MiddleName",1,0,1,NULL);
INSERT INTO FIELD_CONFIGURATION
VALUES(2,"MiddleName",17,0,1,NULL);
INSERT INTO FIELD_CONFIGURATION
VALUES(3,"SecondLastName",1,0,1,NULL);
INSERT INTO FIELD_CONFIGURATION
VALUES(4,"SecondLastName",17,0,1,NULL);
INSERT INTO FIELD_CONFIGURATION
VALUES(5,"GovernmentId",1,0,1,NULL);
INSERT INTO FIELD_CONFIGURATION
VALUES(6,"GovernmentId",17,0,1,NULL);
INSERT INTO FIELD_CONFIGURATION
VALUES(7,"ExternalId",1,0,0,NULL);
INSERT INTO FIELD_CONFIGURATION
VALUES(8,"ExternalId",12,0,0,NULL);
INSERT INTO FIELD_CONFIGURATION
VALUES(9,"ExternalId",20,0,0,NULL);
INSERT INTO FIELD_CONFIGURATION
VALUES(10,"Ethinicity",1,0,0,NULL);
INSERT INTO FIELD_CONFIGURATION
VALUES(11,"Citizenship",1,1,0,NULL);
INSERT INTO FIELD_CONFIGURATION
VALUES(12,"Handicapped",1,0,0,NULL);
INSERT INTO FIELD_CONFIGURATION
VALUES(13,"BusinessActivities",1,0,0,NULL);
INSERT INTO FIELD_CONFIGURATION
VALUES(14,"EducationLevel",1,1,0,NULL);
INSERT INTO FIELD_CONFIGURATION
VALUES(15,"Photo",1,0,0,NULL);
INSERT INTO FIELD_CONFIGURATION
VALUES(16,"SpouseFatherMiddleName",1,0,0,NULL);
INSERT INTO FIELD_CONFIGURATION
VALUES(17,"SpouseFatherSecondLastName",1,0,0,NULL);
INSERT INTO FIELD_CONFIGURATION
VALUES(18,"Trained",1,0,0,NULL);
INSERT INTO FIELD_CONFIGURATION
VALUES(19,"Trained",12,0,0,NULL);
INSERT INTO FIELD_CONFIGURATION
VALUES(20,"TrainedDate",1,0,0,NULL);
INSERT INTO FIELD_CONFIGURATION
VALUES(21,"TrainedDate",12,0,0,NULL);
INSERT INTO FIELD_CONFIGURATION
VALUES(22,"Address",1,0,1,NULL);
INSERT INTO FIELD_CONFIGURATION
VALUES(23,"Address",12,0,1,NULL);
INSERT INTO FIELD_CONFIGURATION
VALUES(24,"Address",20,0,0,NULL);
INSERT INTO FIELD_CONFIGURATION
VALUES(25,"Address1",1,0,1,22);
INSERT INTO FIELD_CONFIGURATION
VALUES(26,"Address1",12,0,1,23);
INSERT INTO FIELD_CONFIGURATION
VALUES(27,"Address1",20,0,0,24);
INSERT INTO FIELD_CONFIGURATION
VALUES(28,"Address2",1,0,1,22);
INSERT INTO FIELD_CONFIGURATION
VALUES(29,"Address2",12,0,1,23);
INSERT INTO FIELD_CONFIGURATION
VALUES(30,"Address2",20,0,0,24);
INSERT INTO FIELD_CONFIGURATION
VALUES(31,"Address3",1,0,1,22);
INSERT INTO FIELD_CONFIGURATION
VALUES(32,"Address3",12,0,1,23);
INSERT INTO FIELD_CONFIGURATION
VALUES(33,"Address3",20,0,0,24);
INSERT INTO FIELD_CONFIGURATION
VALUES(34,"Address3",15,0,0,NULL);
INSERT INTO FIELD_CONFIGURATION
VALUES(35,"Address3",17,0,0,NULL);
INSERT INTO FIELD_CONFIGURATION
VALUES(36,"City",1,0,0,22);
INSERT INTO FIELD_CONFIGURATION
VALUES(37,"City",12,0,0,23);
INSERT INTO FIELD_CONFIGURATION
VALUES(38,"City",20,0,0,24);
INSERT INTO FIELD_CONFIGURATION
VALUES(39,"State",1,0,0,22);
INSERT INTO FIELD_CONFIGURATION
VALUES(40,"State",12,0,0,23);
INSERT INTO FIELD_CONFIGURATION
VALUES(41,"State",20,0,0,24);
INSERT INTO FIELD_CONFIGURATION
VALUES(42,"State",15,0,0,NULL);
INSERT INTO FIELD_CONFIGURATION
VALUES(43,"State",17,0,0,NULL);
INSERT INTO FIELD_CONFIGURATION
VALUES(44,"Country",1,0,1,22);
INSERT INTO FIELD_CONFIGURATION
VALUES(45,"Country",12,0,1,23);
INSERT INTO FIELD_CONFIGURATION
VALUES(46,"Country",20,0,1,24);
INSERT INTO FIELD_CONFIGURATION
VALUES(47,"Country",15,0,1,NULL);
INSERT INTO FIELD_CONFIGURATION
VALUES(48,"Country",17,0,1,NULL);
INSERT INTO FIELD_CONFIGURATION
VALUES(49,"PostalCode",1,0,0,22);
INSERT INTO FIELD_CONFIGURATION
VALUES(50,"PostalCode",12,0,0,23);
INSERT INTO FIELD_CONFIGURATION
VALUES(51,"PostalCode",20,0,0,24);
INSERT INTO FIELD_CONFIGURATION
VALUES(52,"PostalCode",15,0,0,NULL);
INSERT INTO FIELD_CONFIGURATION
VALUES(53,"PostalCode",17,0,0,NULL);
INSERT INTO FIELD_CONFIGURATION
VALUES(54,"PhoneNumber",1,0,1,NULL);
INSERT INTO FIELD_CONFIGURATION
VALUES(55,"PhoneNumber",12,0,1,NULL);
INSERT INTO FIELD_CONFIGURATION
VALUES(56,"PhoneNumber",20,0,1,NULL);
INSERT INTO FIELD_CONFIGURATION
VALUES(57,"PhoneNumber",17,0,1,NULL);
INSERT INTO FIELD_CONFIGURATION
VALUES(58,"PurposeOfLoan",22,0,0,NULL);
INSERT INTO FIELD_CONFIGURATION
VALUES(59,"CollateralType",22,0,1,NULL);
INSERT INTO FIELD_CONFIGURATION
VALUES(60,"CollateralNotes",22,0,1,NULL);
INSERT INTO FIELD_CONFIGURATION
VALUES(61,"ReceiptId",1,0,1,NULL);
INSERT INTO FIELD_CONFIGURATION
VALUES(62,"ReceiptId",12,0,1,NULL);
INSERT INTO FIELD_CONFIGURATION
VALUES(63,"ReceiptId",20,0,1,NULL);
INSERT INTO FIELD_CONFIGURATION
VALUES(64,"ReceiptId",21,0,1,NULL);
INSERT INTO FIELD_CONFIGURATION
VALUES(65,"ReceiptId",22,0,1,NULL);
INSERT INTO FIELD_CONFIGURATION
VALUES(66,"ReceiptId",23,0,1,NULL);
INSERT INTO FIELD_CONFIGURATION
VALUES(67,"ReceiptDate",1,0,1,NULL);
INSERT INTO FIELD_CONFIGURATION
VALUES(68,"ReceiptDate",12,0,1,NULL);
INSERT INTO FIELD_CONFIGURATION
VALUES(69,"ReceiptDate",20,0,1,NULL);
INSERT INTO FIELD_CONFIGURATION
VALUES(70,"ReceiptDate",21,0,1,NULL);
INSERT INTO FIELD_CONFIGURATION
VALUES(71,"ReceiptDate",22,0,1,NULL);
INSERT INTO FIELD_CONFIGURATION
VALUES(72,"ReceiptDate",23,0,1,NULL);


UPDATE SYSTEM_CONFIGURATION set DAYS_FOR_CAL_DEFINITION = 30,NO_OF_INTEREST_DAYS = 365 where OFFICE_ID = 1;



INSERT INTO TRANSACTION_TYPE (TRANSACTION_ID,TRANSACTION_NAME)
VALUES(1,'Loan Disbursement');
INSERT INTO TRANSACTION_TYPE (TRANSACTION_ID,TRANSACTION_NAME)
VALUES(2,'Loan Repayment');
INSERT INTO TRANSACTION_TYPE (TRANSACTION_ID,TRANSACTION_NAME)
VALUES(3,'Savings Deposit');
INSERT INTO TRANSACTION_TYPE (TRANSACTION_ID,TRANSACTION_NAME)
VALUES(4,'Savings Withdrawals');
INSERT INTO TRANSACTION_TYPE (TRANSACTION_ID,TRANSACTION_NAME)
VALUES(5,'Fees/penalty payments'); 



INSERT INTO SUPPORTED_MODES (MODE_ID,TRANSACTION_ID,PAYMENT_TYPE_ID)
VALUES (1,1,1); 
INSERT INTO SUPPORTED_MODES (MODE_ID,TRANSACTION_ID,PAYMENT_TYPE_ID)
VALUES (2,2,1);
INSERT INTO SUPPORTED_MODES (MODE_ID,TRANSACTION_ID,PAYMENT_TYPE_ID)
VALUES (3,3,1);
INSERT INTO SUPPORTED_MODES (MODE_ID,TRANSACTION_ID,PAYMENT_TYPE_ID) 
VALUES (4,4,1);
INSERT INTO SUPPORTED_MODES (MODE_ID,TRANSACTION_ID,PAYMENT_TYPE_ID)
VALUES (5,5,1);