/* DB Creation changes */

ALTER TABLE FEES MODIFY FEE_NAME VARCHAR(50) NOT NULL;
ALTER TABLE FEES MODIFY OFFICE_ID SMALLINT NOT NULL;
ALTER TABLE FEES MODIFY STATUS SMALLINT NOT NULL;
ALTER TABLE FEES MODIFY CATEGORY_ID SMALLINT NOT NULL;
ALTER TABLE FEES MODIFY CREATED_DATE DATE  NOT NULL;
ALTER TABLE FEES MODIFY CREATED_BY SMALLINT  NOT NULL;
ALTER TABLE FEES MODIFY VERSION_NO INTEGER NOT NULL;


ALTER TABLE CUSTOMER_MEETING ADD COLUMN UPDATED_FLAG SMALLINT NOT NULL;

CREATE TABLE CLIENT_PERF_HISTORY (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  CUSTOMER_ID INTEGER NOT NULL,
  LOAN_CYCLE_COUNTER SMALLINT NULL,
  LAST_LOAN_AMNT DECIMAL(10,3) NULL,
  LAST_LOAN_AMNT_CURRENCY_ID SMALLINT NULL,
  TOTAL_ACTIVE_LOANS SMALLINT NULL,
  TOTAL_SAVINGS_AMNT DECIMAL(10,3) NULL,
  TOTAL_SAVINGS_AMNT_CURRENCY_ID SMALLINT NULL,
  DELINQUINT_PORTFOLIO DECIMAL(10,3) NULL,
  DELINQUINT_PORTFOLIO_CURRENCY_ID SMALLINT NULL,
  PRIMARY KEY(ID),
  FOREIGN KEY(CUSTOMER_ID)
    REFERENCES CUSTOMER(CUSTOMER_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)
TYPE=InnoDB CHARACTER SET utf8;

CREATE TABLE GROUP_PERF_HISTORY (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  CUSTOMER_ID INTEGER NOT NULL,
  NO_OF_CLIENTS SMALLINT NULL,
  LAST_GROUP_LOAN_AMNT_DISB DECIMAL(10,3) NULL,
  LAST_GROUP_LOAN_AMNT_DISB_CURRENCY_ID SMALLINT NULL,
  AVG_LOAN_SIZE DECIMAL(10,3) NULL,
  AVG_LOAN_SIZE_CURRENCY_ID SMALLINT NULL,
  TOTAL_OUTSTAND_LOAN_AMNT DECIMAL(10,3) NULL,
  TOTAL_OUTSTAND_LOAN_AMNT_CURRENCY_ID SMALLINT NULL,
  PORTFOLIO_AT_RISK DECIMAL(10,3) NULL,
  PORTFOLIO_AT_RISK_CURRENCY_ID SMALLINT NULL,
  TOTAL_SAVINGS_AMNT DECIMAL(10,3) NULL,
  TOTAL_SAVINGS_AMNT_CURRENCY_ID SMALLINT NULL,
  PRIMARY KEY(ID),
  FOREIGN KEY(CUSTOMER_ID)
    REFERENCES CUSTOMER(CUSTOMER_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)
TYPE=InnoDB CHARACTER SET utf8;

CREATE TABLE LOAN_PERF_HISTORY (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  ACCOUNT_ID INTEGER NOT NULL,
  NO_OF_PAYMENTS SMALLINT NULL,
  NO_OF_MISSED_PAYMENTS SMALLINT NULL,
  DAYS_IN_ARREARS SMALLINT NULL,
  LOAN_MATURITY_DATE DATE NULL,
  PRIMARY KEY(ID),
  FOREIGN KEY(ACCOUNT_ID)
    REFERENCES ACCOUNT(ACCOUNT_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)
TYPE=InnoDB CHARACTER SET utf8;



/* Master Data Changes */



INSERT INTO LOOKUP_VALUE
VALUES(553,87,"  ");
INSERT INTO LOOKUP_VALUE 
VALUES(554,87," ");


INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(891,1,553,'Can disburse loan');
INSERT INTO LOOKUP_VALUE_LOCALE 
VALUES(892,1,554,'Can make deposit/withdrawal to savings account');


UPDATE ACTIVITY SET DESCRIPTION_LOOKUP_ID = 404 where ACTIVITY_ID = 43;
UPDATE ACTIVITY SET DESCRIPTION_LOOKUP_ID = 426 where ACTIVITY_ID = 65;
UPDATE ACTIVITY SET DESCRIPTION_LOOKUP_ID = 443 where ACTIVITY_ID = 82;
UPDATE ACTIVITY SET DESCRIPTION_LOOKUP_ID = 475 where ACTIVITY_ID = 115;
UPDATE ACTIVITY SET DESCRIPTION_LOOKUP_ID = 476 where ACTIVITY_ID = 116;
UPDATE ACTIVITY SET DESCRIPTION_LOOKUP_ID = 477 where ACTIVITY_ID = 117;
UPDATE ACTIVITY SET DESCRIPTION_LOOKUP_ID = 478 where ACTIVITY_ID = 118;
UPDATE ACTIVITY SET DESCRIPTION_LOOKUP_ID = 479 where ACTIVITY_ID = 119;

INSERT INTO ACTIVITY(ACTIVITY_ID,PARENT_ID,ACTIVITY_NAME_LOOKUP_ID,DESCRIPTION_LOOKUP_ID)
VALUES(189,113,553,553 );
INSERT INTO ACTIVITY(ACTIVITY_ID,PARENT_ID,ACTIVITY_NAME_LOOKUP_ID,DESCRIPTION_LOOKUP_ID)
VALUES(190,136,554,554 );

INSERT INTO ROLES_ACTIVITY(ACTIVITY_ID,ROLE_ID,VERSION_NO)
VALUES(189,1,1);
INSERT INTO ROLES_ACTIVITY(ACTIVITY_ID,ROLE_ID,VERSION_NO)
VALUES(190,1,1);

UPDATE LOOKUP_VALUE_LOCALE set LOOKUP_VALUE = 'Can edit MFI information' where LOOKUP_VALUE_ID = 748;
UPDATE LOOKUP_VALUE_LOCALE set LOOKUP_VALUE = 'Can edit fee amount attached to the account' where LOOKUP_VALUE_ID = 753;
UPDATE LOOKUP_VALUE_LOCALE set LOOKUP_VALUE = 'Can edit fee amount attached to the account' where LOOKUP_VALUE_ID = 775;
UPDATE LOOKUP_VALUE_LOCALE set LOOKUP_VALUE = 'Can edit fee amount attached to the account' where LOOKUP_VALUE_ID = 787;
UPDATE LOOKUP_VALUE_LOCALE set LOOKUP_VALUE = 'Can edit personal information' where LOOKUP_VALUE_ID = 821;

