ALTER TABLE CUSTOMER_MEETING ADD COLUMN UPDATED_MEETING_ID INTEGER;
ALTER TABLE CUSTOMER_MEETING ADD FOREIGN KEY (UPDATED_MEETING_ID) 
  REFERENCES MEETING(MEETING_ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE CLIENT_PERF_HISTORY DROP COLUMN LOAN_CYCLE_COUNTER ;

DROP TABLE IF EXISTS LOAN_COUNTER;

CREATE TABLE LOAN_COUNTER(
 LOAN_COUNTER_ID INTEGER auto_increment NOT NULL,
 CLIENT_PERF_ID INTEGER NOT NULL,
 LOAN_OFFERING_ID SMALLINT NOT NULL,
 LOAN_CYCLE_COUNTER SMALLINT,
 
 PRIMARY KEY(LOAN_COUNTER_ID)
)
ENGINE=InnoDB CHARACTER SET utf8;