ALTER TABLE CUSTOMER_MEETING ADD UPDATED_MEETING_ID INTEGER NULL;
ALTER TABLE CUSTOMER_MEETING ADD FOREIGN KEY (UPDATED_MEETING_ID) REFERENCES MEETING(MEETING_ID) ON DELETE NO ACTION ON UPDATE NO ACTION;
