DROP TABLE IF EXISTS FUND_CODE;

CREATE TABLE FUND_CODE (
  FUNDCODE_ID SMALLINT AUTO_INCREMENT NOT NULL,
  FUNDCODE_VALUE VARCHAR(50) NOT NULL,
  PRIMARY KEY(FUNDCODE_ID)
)
ENGINE=InnoDB CHARACTER SET utf8;

ALTER TABLE FUND DROP FOREIGN KEY FUND_GLCODE;
ALTER TABLE FUND DROP  GLCODE_ID,ADD FUNDCODE_ID SMALLINT NOT NULL;
ALTER TABLE FUND ADD FOREIGN KEY (FUNDCODE_ID) REFERENCES FUND_CODE(FUNDCODE_ID) ON DELETE NO ACTION ON UPDATE NO ACTION; 

ALTER TABLE CUSTOMER_DETAIL ADD POVERTY_STATUS INTEGER NULL;
ALTER TABLE CUSTOMER_DETAIL ADD FOREIGN KEY (POVERTY_STATUS) REFERENCES LOOKUP_VALUE(LOOKUP_ID) ON DELETE NO ACTION ON UPDATE NO ACTION;
