insert into INTEREST_TYPES values (2, 80, 1, 'Declining');

INSERT INTO LOOKUP_VALUE VALUES(561,87,' ');
INSERT INTO LOOKUP_VALUE VALUES(562,87,' ');
INSERT INTO LOOKUP_VALUE VALUES(563,87,' ');
INSERT INTO LOOKUP_VALUE VALUES(564,87,' ');
INSERT INTO LOOKUP_VALUE VALUES(565,87,' ');

INSERT INTO LOOKUP_VALUE_LOCALE VALUES(899,1,561,'Can modify lateness/dormancy definition');
INSERT INTO LOOKUP_VALUE_LOCALE VALUES(900,1,562,'Can modify office hierarchy');
INSERT INTO LOOKUP_VALUE_LOCALE VALUES(901,1,563,'Can Add Notes to Personnel');
INSERT INTO LOOKUP_VALUE_LOCALE VALUES(902,1,564,'Bulk');
INSERT INTO LOOKUP_VALUE_LOCALE VALUES(903,1,565,'Can Enter Collection Sheet Data');


INSERT INTO ACTIVITY(ACTIVITY_ID,PARENT_ID,ACTIVITY_NAME_LOOKUP_ID,DESCRIPTION_LOOKUP_ID)
VALUES(195,90,561,561);
INSERT INTO ACTIVITY(ACTIVITY_ID,PARENT_ID,ACTIVITY_NAME_LOOKUP_ID,DESCRIPTION_LOOKUP_ID)
VALUES(193,13,562,562 );
INSERT INTO ACTIVITY(ACTIVITY_ID,PARENT_ID,ACTIVITY_NAME_LOOKUP_ID,DESCRIPTION_LOOKUP_ID)
VALUES(194,18,563,563 );
INSERT INTO ACTIVITY(ACTIVITY_ID,PARENT_ID,ACTIVITY_NAME_LOOKUP_ID,DESCRIPTION_LOOKUP_ID)
VALUES(196,null,564,564 );
INSERT INTO ACTIVITY(ACTIVITY_ID,PARENT_ID,ACTIVITY_NAME_LOOKUP_ID,DESCRIPTION_LOOKUP_ID)
VALUES(197,196,565,565 );

UPDATE ACTIVITY SET PARENT_ID=196 WHERE ACTIVITY_ID=192;

INSERT INTO ROLES_ACTIVITY VALUES (193,1);
INSERT INTO ROLES_ACTIVITY VALUES (194,1);
INSERT INTO ROLES_ACTIVITY VALUES (195,1);
INSERT INTO ROLES_ACTIVITY VALUES (197,1);

DELETE from LOOKUP_VALUE_LOCALE where LOOKUP_VALUE_ID = 744;
DELETE from LOOKUP_VALUE_LOCALE where LOOKUP_VALUE_ID = 766;
DELETE from LOOKUP_VALUE_LOCALE where LOOKUP_VALUE_ID = 783;
DELETE from LOOKUP_VALUE_LOCALE where LOOKUP_VALUE_ID = 815;

DELETE from ROLES_ACTIVITY where ACTIVITY_ID = 45;
DELETE from ROLES_ACTIVITY where ACTIVITY_ID = 67;
DELETE from ROLES_ACTIVITY where ACTIVITY_ID = 84;
DELETE from ROLES_ACTIVITY where ACTIVITY_ID = 117;

DELETE from ACTIVITY where ACTIVITY_ID = 45;
DELETE from ACTIVITY where ACTIVITY_ID = 67;
DELETE from ACTIVITY where ACTIVITY_ID = 84;
DELETE from ACTIVITY where ACTIVITY_ID = 117;

DELETE from LOOKUP_VALUE where LOOKUP_ID = 406;
DELETE from LOOKUP_VALUE where LOOKUP_ID = 428;
DELETE from LOOKUP_VALUE where LOOKUP_ID = 445;
DELETE from LOOKUP_VALUE where LOOKUP_ID = 477;

UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can waive a due amount' where LOOKUP_VALUE_ID = 745;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can waive a due amount' where LOOKUP_VALUE_ID = 767;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can waive a due amount' where LOOKUP_VALUE_ID = 784;
/* The table Personnelcustom field contains the additional information of the default user  - Configuration */
INSERT INTO PERSONNEL_CUSTOM_FIELD (FIELD_ID,PERSONNEL_ID,FIELD_VALUE)
VALUES(9,1,'');
