-- This script contains Iteration15-DBScripts20061012.sql,
-- Iteration15-DDL-DBScripts24102006.sql and also some 
-- update scripts which is required as part of missing data in GK-Database.

update lookup_label set ENTITY_NAME = 'Handicapped' where Label_ID = 43;

update customer_hierarchy set status = 1 where status is null and end_date is not null;

update customer_name_detail set display_name = concat(first_name,last_name) where display_name is null;

Update meeting set Meeting_place = 'Bangalore' where meeting_place is null;

insert into INTEREST_TYPES values (2, 80, 1, 'Declining');

INSERT INTO LOOKUP_VALUE VALUES(560,87,' ');
INSERT INTO LOOKUP_VALUE VALUES(561,87,' ');
INSERT INTO LOOKUP_VALUE VALUES(562,87,' ');
INSERT INTO LOOKUP_VALUE VALUES(563,87,' ');
INSERT INTO LOOKUP_VALUE VALUES(564,87,' ');
INSERT INTO LOOKUP_VALUE VALUES(565,87,' ');

UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_ID = 561,LOOKUP_VALUE = 'Can modify lateness/dormancy definition' WHERE LOOKUP_VALUE_ID = 899;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_ID = 562,LOOKUP_VALUE = 'Can modify office hierarchy' WHERE LOOKUP_VALUE_ID = 900;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_ID = 563,LOOKUP_VALUE = 'Can Add Notes to Personnel' WHERE LOOKUP_VALUE_ID = 901;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_ID = 564,LOOKUP_VALUE = 'Bulk' WHERE LOOKUP_VALUE_ID = 902;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_ID = 565,LOOKUP_VALUE = 'Can Enter Collection Sheet Data' WHERE LOOKUP_VALUE_ID = 903;

INSERT INTO ACTIVITY(ACTIVITY_ID,PARENT_ID,ACTIVITY_NAME_LOOKUP_ID,DESCRIPTION_LOOKUP_ID) 
VALUES(192,113,560,560 );
INSERT INTO ACTIVITY(ACTIVITY_ID,PARENT_ID,ACTIVITY_NAME_LOOKUP_ID,DESCRIPTION_LOOKUP_ID)
VALUES(193,13,562,562 );
INSERT INTO ACTIVITY(ACTIVITY_ID,PARENT_ID,ACTIVITY_NAME_LOOKUP_ID,DESCRIPTION_LOOKUP_ID)
VALUES(194,18,563,563 );
INSERT INTO ACTIVITY(ACTIVITY_ID,PARENT_ID,ACTIVITY_NAME_LOOKUP_ID,DESCRIPTION_LOOKUP_ID)
VALUES(195,90,561,561);
INSERT INTO ACTIVITY(ACTIVITY_ID,PARENT_ID,ACTIVITY_NAME_LOOKUP_ID,DESCRIPTION_LOOKUP_ID)
VALUES(196,null,564,564 );
INSERT INTO ACTIVITY(ACTIVITY_ID,PARENT_ID,ACTIVITY_NAME_LOOKUP_ID,DESCRIPTION_LOOKUP_ID)
VALUES(197,196,565,565 );

UPDATE ACTIVITY SET PARENT_ID=196 WHERE ACTIVITY_ID=192;

INSERT INTO ROLES_ACTIVITY VALUES (192,1);
INSERT INTO ROLES_ACTIVITY VALUES (193,1);
INSERT INTO ROLES_ACTIVITY VALUES (194,1);
INSERT INTO ROLES_ACTIVITY VALUES (195,1);
INSERT INTO ROLES_ACTIVITY VALUES (197,1);

DELETE from LOOKUP_VALUE_LOCALE where LOOKUP_VALUE_ID = 744;
DELETE from LOOKUP_VALUE_LOCALE where LOOKUP_VALUE_ID = 766;
DELETE from LOOKUP_VALUE_LOCALE where LOOKUP_VALUE_ID = 783;
DELETE from LOOKUP_VALUE_LOCALE where LOOKUP_VALUE_ID = 815;
DELETE from LOOKUP_VALUE_LOCALE where LOOKUP_VALUE_ID = 806;
DELETE from LOOKUP_VALUE_LOCALE where LOOKUP_VALUE_ID = 810;
DELETE from LOOKUP_VALUE_LOCALE where LOOKUP_VALUE_ID = 811;

DELETE from ROLES_ACTIVITY where ACTIVITY_ID = 45;
DELETE from ROLES_ACTIVITY where ACTIVITY_ID = 67;
DELETE from ROLES_ACTIVITY where ACTIVITY_ID = 84;
DELETE from ROLES_ACTIVITY where ACTIVITY_ID = 117;
DELETE from ROLES_ACTIVITY where ACTIVITY_ID = 107;
DELETE from ROLES_ACTIVITY where ACTIVITY_ID = 111;
DELETE from ROLES_ACTIVITY where ACTIVITY_ID = 112;

DELETE from ACTIVITY where ACTIVITY_ID = 45;
DELETE from ACTIVITY where ACTIVITY_ID = 67;
DELETE from ACTIVITY where ACTIVITY_ID = 84;
DELETE from ACTIVITY where ACTIVITY_ID = 117;
DELETE from ACTIVITY where ACTIVITY_ID = 107;
DELETE from ACTIVITY where ACTIVITY_ID = 111;
DELETE from ACTIVITY where ACTIVITY_ID = 112;

DELETE from LOOKUP_VALUE where LOOKUP_ID = 406;
DELETE from LOOKUP_VALUE where LOOKUP_ID = 428;
DELETE from LOOKUP_VALUE where LOOKUP_ID = 445;
DELETE from LOOKUP_VALUE where LOOKUP_ID = 477;
DELETE from LOOKUP_VALUE where LOOKUP_ID = 468;
DELETE from LOOKUP_VALUE where LOOKUP_ID = 472;
DELETE from LOOKUP_VALUE where LOOKUP_ID = 473;

UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can waive a due amount' where LOOKUP_VALUE_ID = 745;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can waive a due amount' where LOOKUP_VALUE_ID = 767;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can waive a due amount' where LOOKUP_VALUE_ID = 784;
/* The table Personnelcustom field contains the additional information of the default user  - Configuration */
INSERT INTO PERSONNEL_CUSTOM_FIELD (FIELD_ID,PERSONNEL_ID,FIELD_VALUE)
VALUES(9,1,'');


UPDATE LOOKUP_ENTITY SET ENTITY_NAME = 'Handicapped', DESCRIPTION = 'Handicaped' where ENTITY_ID =22;

UPDATE FIELD_CONFIGURATION SET FIELD_NAME = 'Handicapped' where FIELD_CONFIG_ID =12;



DELETE from LOOKUP_VALUE_LOCALE where LOOKUP_VALUE_ID = 378;
DELETE from LOOKUP_VALUE where LOOKUP_ID = 190;

INSERT INTO OFFICE_CUSTOM_FIELD (OFFICE_ID,FIELD_ID,FIELD_VALUE) VALUES(1,10,'');
INSERT INTO OFFICE_CUSTOM_FIELD (OFFICE_ID,FIELD_ID,FIELD_VALUE) VALUES(1,11,'');
INSERT INTO OFFICE_CUSTOM_FIELD (OFFICE_ID,FIELD_ID,FIELD_VALUE) VALUES(1,12,'');
INSERT INTO OFFICE_CUSTOM_FIELD (OFFICE_ID,FIELD_ID,FIELD_VALUE) VALUES(1,13,'');

INSERT INTO LOOKUP_VALUE VALUES(566,87,' ');
INSERT INTO LOOKUP_VALUE VALUES(567,87,' ');
INSERT INTO LOOKUP_VALUE VALUES(568,87,' ');


UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_ID = 554,LOOKUP_VALUE = 'Can make deposit/withdrawal to savings account' WHERE LOOKUP_VALUE_ID = 892 ;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_ID = 555,LOOKUP_VALUE = 'Can add notes to margin money account' WHERE LOOKUP_VALUE_ID = 893 ;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_ID = 556,LOOKUP_VALUE = 'Applies to existing & future accounts' WHERE LOOKUP_VALUE_ID = 894 ;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_ID = 557,LOOKUP_VALUE = 'Applies to future accounts' WHERE LOOKUP_VALUE_ID = 895 ;

UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_ID = 558,LOOKUP_VALUE = 'Periodic' WHERE LOOKUP_VALUE_ID = 896 ;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_ID = 559,LOOKUP_VALUE = 'One Time' WHERE LOOKUP_VALUE_ID = 897 ;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_ID = 560,LOOKUP_VALUE = 'Can approve loans in bulk' WHERE LOOKUP_VALUE_ID = 898 ;

UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_ID = 566,LOOKUP_VALUE = 'Can apply charges to member accounts' WHERE LOOKUP_VALUE_ID = 904 ;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_ID = 567,LOOKUP_VALUE = 'Can apply charges to group accounts' WHERE LOOKUP_VALUE_ID = 905 ;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_ID = 568,LOOKUP_VALUE = 'Can apply charges to kendra accounts' WHERE LOOKUP_VALUE_ID = 906 ;



INSERT INTO ACTIVITY(ACTIVITY_ID,PARENT_ID,ACTIVITY_NAME_LOOKUP_ID,DESCRIPTION_LOOKUP_ID)
VALUES(198,34,566,566 );
INSERT INTO ACTIVITY(ACTIVITY_ID,PARENT_ID,ACTIVITY_NAME_LOOKUP_ID,DESCRIPTION_LOOKUP_ID)
VALUES(199,56,567,567 );
INSERT INTO ACTIVITY(ACTIVITY_ID,PARENT_ID,ACTIVITY_NAME_LOOKUP_ID,DESCRIPTION_LOOKUP_ID)
VALUES(200,78,568,568 );

INSERT INTO ROLES_ACTIVITY VALUES (198,1);
INSERT INTO ROLES_ACTIVITY VALUES (199,1);
INSERT INTO ROLES_ACTIVITY VALUES (200,1);



ALTER TABLE CUSTOMER_MEETING ADD UPDATED_MEETING_ID INTEGER NULL;
ALTER TABLE CUSTOMER_MEETING ADD FOREIGN KEY (UPDATED_MEETING_ID) REFERENCES MEETING(MEETING_ID) ON DELETE NO ACTION ON UPDATE NO ACTION;


ALTER TABLE CLIENT_PERF_HISTORY DROP COLUMN LOAN_CYCLE_COUNTER ;

DROP TABLE IF EXISTS LOAN_COUNTER;

CREATE TABLE LOAN_COUNTER(
 LOAN_COUNTER_ID INTEGER auto_increment NOT NULL,
 CLIENT_PERF_ID INTEGER NOT NULL,
 LOAN_OFFERING_ID SMALLINT NOT NULL,
 LOAN_CYCLE_COUNTER SMALLINT,
 
 PRIMARY KEY(LOAN_COUNTER_ID)
)
ENGINE=InnoDB CHARACTER SET utf8;

