CREATE TABLE CONFIG_KEY_VALUE_INTEGER (
  CONFIGURATION_ID INTEGER AUTO_INCREMENT NOT NULL,
  CONFIGURATION_KEY VARCHAR(100) NOT NULL,
  CONFIGURATION_VALUE INTEGER NOT NULL,
  PRIMARY KEY(CONFIGURATION_ID),
  UNIQUE (CONFIGURATION_KEY)
)
ENGINE = InnoDB CHARACTER SET utf8;

INSERT INTO CONFIG_KEY_VALUE_INTEGER(CONFIGURATION_KEY, CONFIGURATION_VALUE) VALUES ('CollectionSheetHelper.daysInAdvance',1);

UPDATE DATABASE_VERSION SET DATABASE_VERSION = 107 WHERE DATABASE_VERSION = 106;