INSERT INTO LOOKUP_VALUE VALUES(574,87,' ');
INSERT INTO LOOKUP_VALUE_LOCALE VALUES(919,1,574,'Configuration Management');
INSERT INTO ACTIVITY(ACTIVITY_ID,PARENT_ID,ACTIVITY_NAME_LOOKUP_ID,DESCRIPTION_LOOKUP_ID) VALUES(203,NULL,574,574);
INSERT INTO ROLES_ACTIVITY VALUES (203,1);

INSERT INTO LOOKUP_VALUE VALUES(575,87,' ');
INSERT INTO LOOKUP_VALUE_LOCALE VALUES(920,1,575,'Can define labels');
INSERT INTO ACTIVITY(ACTIVITY_ID,PARENT_ID,ACTIVITY_NAME_LOOKUP_ID,DESCRIPTION_LOOKUP_ID) VALUES(204,203,575,575);
INSERT INTO ROLES_ACTIVITY VALUES (204,1);

update DATABASE_VERSION set DATABASE_VERSION = 103 where DATABASE_VERSION = 102;