INSERT INTO LOOKUP_ENTITY(ENTITY_ID,ENTITY_NAME,DESCRIPTION)
VALUES(91,'Repayment Rule','Repayment Rule Types');
INSERT INTO LOOKUP_VALUE(LOOKUP_ID,ENTITY_ID,LOOKUP_NAME)
VALUES(576,91,' ');
INSERT INTO LOOKUP_VALUE(LOOKUP_ID,ENTITY_ID,LOOKUP_NAME)
VALUES(577,91,' ');
INSERT INTO LOOKUP_VALUE(LOOKUP_ID,ENTITY_ID,LOOKUP_NAME)
VALUES(578,91,' ');
INSERT INTO LOOKUP_VALUE_LOCALE(LOOKUP_VALUE_ID,LOCALE_ID,LOOKUP_ID,LOOKUP_VALUE)
VALUES(921,1,576,'Same Day');
INSERT INTO LOOKUP_VALUE_LOCALE(LOOKUP_VALUE_ID,LOCALE_ID,LOOKUP_ID,LOOKUP_VALUE)
VALUES(922,1,577,'Next Meeting/Repayment');
INSERT INTO LOOKUP_VALUE_LOCALE(LOOKUP_VALUE_ID,LOCALE_ID,LOOKUP_ID,LOOKUP_VALUE)
VALUES(923,1,578,'Next Working Day');

CREATE TABLE REPAYMENT_RULE (
  REPAYMENT_RULE_ID SMALLINT AUTO_INCREMENT NOT NULL,
  REPAYMENT_RULE_LOOKUP_ID INTEGER,
  PRIMARY KEY(REPAYMENT_RULE_ID),
  FOREIGN KEY(REPAYMENT_RULE_LOOKUP_ID)
    REFERENCES LOOKUP_VALUE(LOOKUP_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)
ENGINE=InnoDB CHARACTER SET utf8;

INSERT INTO REPAYMENT_RULE(REPAYMENT_RULE_ID, REPAYMENT_RULE_LOOKUP_ID)
VALUES(1,576);
INSERT INTO REPAYMENT_RULE(REPAYMENT_RULE_ID, REPAYMENT_RULE_LOOKUP_ID)
VALUES(2,577);
INSERT INTO REPAYMENT_RULE(REPAYMENT_RULE_ID, REPAYMENT_RULE_LOOKUP_ID)
VALUES(3,578);

DROP TABLE HOLIDAY;
CREATE TABLE HOLIDAY (
  OFFICE_ID SMALLINT NOT NULL,
  HOLIDAY_FROM_DATE DATE NOT NULL,
  HOLIDAY_THRU_DATE DATE,
  HOLIDAY_NAME VARCHAR(100),
  REPAYMENT_RULE_ID SMALLINT NOT NULL,
  PRIMARY KEY(OFFICE_ID, HOLIDAY_FROM_DATE),
  FOREIGN KEY(OFFICE_ID)
    REFERENCES OFFICE(OFFICE_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(REPAYMENT_RULE_ID)
    REFERENCES REPAYMENT_RULE(REPAYMENT_RULE_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)
ENGINE=InnoDB CHARACTER SET utf8;

UPDATE DATABASE_VERSION SET DATABASE_VERSION = 104 WHERE DATABASE_VERSION = 103;
