INSERT INTO LOOKUP_VALUE VALUES(591,87,' ');
INSERT INTO LOOKUP_VALUE_LOCALE VALUES(936,1,591,'Can adjust payment when account status is "closed-obligation met"');
INSERT INTO ACTIVITY(ACTIVITY_ID,PARENT_ID,ACTIVITY_NAME_LOOKUP_ID,DESCRIPTION_LOOKUP_ID) VALUES(217,141,591,591);
INSERT INTO ROLES_ACTIVITY VALUES (217,1);

update DATABASE_VERSION set DATABASE_VERSION = 130 where DATABASE_VERSION = 129;