INSERT INTO LOOKUP_VALUE VALUES(588,87,' ');
INSERT INTO LOOKUP_VALUE_LOCALE VALUES(933,1,588,'Can upload report template');
INSERT INTO ACTIVITY(ACTIVITY_ID,PARENT_ID,ACTIVITY_NAME_LOOKUP_ID,DESCRIPTION_LOOKUP_ID) VALUES(214,141,588,588);
INSERT INTO ROLES_ACTIVITY VALUES (214,1);

update DATABASE_VERSION set DATABASE_VERSION = 124 where DATABASE_VERSION = 123;