UPDATE REPORT_JASPER_MAP SET REPORT_CATEGORY_ID = 1 WHERE REPORT_NAME = 'Collection Sheet Report';
UPDATE REPORT SET REPORT_CATEGORY_ID = 1 WHERE REPORT_NAME = 'Collection Sheet Report';
UPDATE  ACTIVITY SET PARENT_ID = 145 WHERE ACTIVITY_ID = 229;

DELETE FROM REPORT WHERE REPORT_NAME = 'Detailed Aging of Portfolio at Risk';
DELETE FROM REPORT_JASPER_MAP WHERE REPORT_NAME = 'Detailed Aging of Portfolio at Risk';
DELETE FROM ROLES_ACTIVITY WHERE ACTIVITY_ID = 207;
DELETE FROM ACTIVITY WHERE ACTIVITY_ID = 207;

DELETE FROM REPORT WHERE REPORT_NAME = 'Active Loans By Loan Officer';
DELETE FROM REPORT_JASPER_MAP WHERE REPORT_NAME = 'Active Loans By Loan Officer';
DELETE FROM ROLES_ACTIVITY WHERE ACTIVITY_ID = 212;
DELETE FROM ACTIVITY WHERE ACTIVITY_ID = 212;

UPDATE DATABASE_VERSION SET DATABASE_VERSION = 202 WHERE DATABASE_VERSION = 201;