/* Remove whitespace from Entity names to prepare for usage as property keys */
UPDATE LOOKUP_ENTITY SET ENTITY_NAME='ClientStatus' WHERE ENTITY_ID=1;
UPDATE LOOKUP_ENTITY SET ENTITY_NAME='GroupStatus' WHERE ENTITY_ID=2;
UPDATE LOOKUP_ENTITY SET ENTITY_NAME='CenterStatus' WHERE ENTITY_ID=3;
UPDATE LOOKUP_ENTITY SET ENTITY_NAME='OfficeStatus' WHERE ENTITY_ID=4;
UPDATE LOOKUP_ENTITY SET ENTITY_NAME='PersonnelStatus' WHERE ENTITY_ID=6;
UPDATE LOOKUP_ENTITY SET ENTITY_NAME='GroupFlag' WHERE ENTITY_ID=7;
UPDATE LOOKUP_ENTITY SET ENTITY_NAME='FeeType' WHERE ENTITY_ID=8;
UPDATE LOOKUP_ENTITY SET ENTITY_NAME='ClientFormedBy' WHERE ENTITY_ID=23;
UPDATE LOOKUP_ENTITY SET ENTITY_NAME='ProductState' WHERE ENTITY_ID=25;
UPDATE LOOKUP_ENTITY SET ENTITY_NAME='ReplacementStatus' WHERE ENTITY_ID=58;
UPDATE LOOKUP_ENTITY SET ENTITY_NAME='GRTStaffId' WHERE ENTITY_ID=59;
UPDATE LOOKUP_ENTITY SET ENTITY_NAME='MeetingTime' WHERE ENTITY_ID=60;
UPDATE LOOKUP_ENTITY SET ENTITY_NAME='DistanceFromBoToCenter' WHERE ENTITY_ID=61;
UPDATE LOOKUP_ENTITY SET ENTITY_NAME='NoOfClientsPerGroup' WHERE ENTITY_ID=63;
UPDATE LOOKUP_ENTITY SET ENTITY_NAME='NoOfClientsPerCenter' WHERE ENTITY_ID=64;
UPDATE LOOKUP_ENTITY SET ENTITY_NAME='DistanceFromHoToBO' WHERE ENTITY_ID=65;
UPDATE LOOKUP_ENTITY SET ENTITY_NAME='ExternalLoanId' WHERE ENTITY_ID=66;
UPDATE LOOKUP_ENTITY SET ENTITY_NAME='ExternalSavingsId' WHERE ENTITY_ID=67;
UPDATE LOOKUP_ENTITY SET ENTITY_NAME='FinancialAction' WHERE ENTITY_ID=76;
UPDATE LOOKUP_ENTITY SET ENTITY_NAME='SavingsAccountFlag' WHERE ENTITY_ID=78;
UPDATE LOOKUP_ENTITY SET ENTITY_NAME='LoanPurposes' WHERE ENTITY_ID=82;
UPDATE LOOKUP_ENTITY SET ENTITY_NAME='ServiceCharge' WHERE ENTITY_ID=88;
UPDATE LOOKUP_ENTITY SET ENTITY_NAME='FeeFrequency' WHERE ENTITY_ID=90;
UPDATE LOOKUP_ENTITY SET ENTITY_NAME='RepaymentRule' WHERE ENTITY_ID=91;

UPDATE LOOKUP_LABEL SET ENTITY_NAME='Savings Status' WHERE LABEL_ID=136;
DELETE FROM LOOKUP_LABEL WHERE LABEL_ID=138;
DELETE FROM LOOKUP_LABEL WHERE LABEL_ID=140;
DELETE FROM LOOKUP_LABEL WHERE LABEL_ID=142;
DELETE FROM LOOKUP_LABEL WHERE LABEL_ID=144;

UPDATE DATABASE_VERSION SET DATABASE_VERSION = 165 WHERE DATABASE_VERSION = 164;
