UPDATE CONFIG_KEY_VALUE_INTEGER SET CONFIGURATION_VALUE=365 
WHERE CONFIGURATION_KEY='maxDaysBetweenDisbursalAndFirstRepaymentDay' AND CONFIGURATION_VALUE=31;

UPDATE DATABASE_VERSION SET DATABASE_VERSION=199 WHERE DATABASE_VERSION=198;