INSERT INTO LOOKUP_VALUE VALUES(583,87,' ');
INSERT INTO LOOKUP_VALUE_LOCALE VALUES(928,1,583,'Product mix');
INSERT INTO ACTIVITY(ACTIVITY_ID,PARENT_ID,ACTIVITY_NAME_LOOKUP_ID,DESCRIPTION_LOOKUP_ID) VALUES(209,NULL,583,583);
INSERT INTO ROLES_ACTIVITY VALUES (209,1);

INSERT INTO LOOKUP_VALUE VALUES(584,87,' ');
INSERT INTO LOOKUP_VALUE_LOCALE VALUES(929,1,584,'Can Define product mix');
INSERT INTO ACTIVITY(ACTIVITY_ID,PARENT_ID,ACTIVITY_NAME_LOOKUP_ID,DESCRIPTION_LOOKUP_ID) VALUES(210,209,584,584);
INSERT INTO ROLES_ACTIVITY VALUES (210,1);

INSERT INTO LOOKUP_VALUE VALUES(585,87,' ');
INSERT INTO LOOKUP_VALUE_LOCALE VALUES(930,1,585,'Can Edit product mix');
INSERT INTO ACTIVITY(ACTIVITY_ID,PARENT_ID,ACTIVITY_NAME_LOOKUP_ID,DESCRIPTION_LOOKUP_ID) VALUES(211,209,585,585);
INSERT INTO ROLES_ACTIVITY VALUES (211,1);

update DATABASE_VERSION set DATABASE_VERSION = 119 where DATABASE_VERSION = 118;
