-- allow this script to be re-run
DROP TABLE IF EXISTS MAX_MIN_NO_OF_INSTALL;
DROP TABLE IF EXISTS MAX_MIN_LOAN_AMOUNT;
DROP TABLE IF EXISTS NO_OF_INSTALL_SAME_FOR_ALL_LOAN;
DROP TABLE IF EXISTS LOAN_AMOUNT_SAME_FOR_ALL_LOAN;
DROP TABLE IF EXISTS NO_OF_INSTALL_FROM_LOAN_CYCLE;
DROP TABLE IF EXISTS LOAN_AMOUNT_FROM_LOAN_CYCLE;
DROP TABLE IF EXISTS NO_OF_INSTALL_FROM_LAST_LOAN;
DROP TABLE IF EXISTS LOAN_AMOUNT_FROM_LAST_LOAN;

-- tables for loan defaults based on last loan
CREATE TABLE LOAN_AMOUNT_FROM_LAST_LOAN (
LOAN_AMOUNT_FROM_LAST_LOAN_ID  SMALLINT AUTO_INCREMENT NOT NULL,
  PRD_OFFERING_ID  SMALLINT NOT NULL,
START_RANGE DECIMAL(10, 3) NOT NULL, 
END_RANGE DECIMAL(10, 3)  NOT NULL,
  MIN_LOAN_AMOUNT  DECIMAL(10, 3) NOT NULL,
  MAX_LOAN_AMNT  DECIMAL(10, 3) NOT NULL,
  DEFAULT_LOAN_AMOUNT  DECIMAL(10, 3) NOT NULL,
 PRIMARY KEY(LOAN_AMOUNT_FROM_LAST_LOAN_ID),  
FOREIGN KEY(PRD_OFFERING_ID)
    REFERENCES  LOAN_OFFERING(PRD_OFFERING_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)
ENGINE=InnoDB CHARACTER SET utf8;


CREATE TABLE  NO_OF_INSTALL_FROM_LAST_LOAN (
 NO_OF_INSTALL_FROM_LAST_LOAN_ID  SMALLINT AUTO_INCREMENT NOT NULL,
  PRD_OFFERING_ID  SMALLINT NOT NULL,
START_RANGE DECIMAL(10, 3) NOT NULL, 
END_RANGE DECIMAL(10, 3)  NOT NULL,
  MIN_NO_INSTALL  DECIMAL(10, 3) NOT NULL,
  MAX_NO_INSTALL  DECIMAL(10, 3) NOT NULL,
  DEFAULT_NO_INSTALL  DECIMAL(10, 3) NOT NULL,
 PRIMARY KEY(NO_OF_INSTALL_FROM_LAST_LOAN_ID ),  
FOREIGN KEY(PRD_OFFERING_ID)
    REFERENCES  LOAN_OFFERING(PRD_OFFERING_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)
ENGINE=InnoDB CHARACTER SET utf8;


CREATE TABLE  LOAN_AMOUNT_FROM_LOAN_CYCLE(
 LOAN_AMOUNT_FROM_LOAN_CYCLE_ID  SMALLINT AUTO_INCREMENT NOT NULL,
  PRD_OFFERING_ID  SMALLINT NOT NULL,
  MIN_LOAN_AMOUNT  DECIMAL(10, 3) NOT NULL,
  MAX_LOAN_AMNT  DECIMAL(10, 3) NOT NULL,
  DEFAULT_LOAN_AMOUNT  DECIMAL(10, 3) NOT NULL,
 RANGE_INDEX DECIMAL(10, 3) NOT NULL,
 PRIMARY KEY(LOAN_AMOUNT_FROM_LOAN_CYCLE_ID),  
FOREIGN KEY(PRD_OFFERING_ID)
    REFERENCES  LOAN_OFFERING(PRD_OFFERING_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)
ENGINE=InnoDB CHARACTER SET utf8;

CREATE TABLE  NO_OF_INSTALL_FROM_LOAN_CYCLE (
 NO_OF_INSTALL_FROM_LOAN_CYCLE_ID  SMALLINT AUTO_INCREMENT NOT NULL,
  PRD_OFFERING_ID  SMALLINT NOT NULL,
  MIN_NO_INSTALL  DECIMAL(10, 3) NOT NULL,
  MAX_NO_INSTALL  DECIMAL(10, 3) NOT NULL,
  DEFAULT_NO_INSTALL  DECIMAL(10, 3) NOT NULL,
RANGE_INDEX DECIMAL(10, 3) NOT NULL,
 PRIMARY KEY(NO_OF_INSTALL_FROM_LOAN_CYCLE_ID),  
FOREIGN KEY(PRD_OFFERING_ID)
    REFERENCES  LOAN_OFFERING(PRD_OFFERING_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)
ENGINE=InnoDB CHARACTER SET utf8;

CREATE TABLE  LOAN_AMOUNT_SAME_FOR_ALL_LOAN(
LOAN_AMOUNT_SAME_FOR_ALL_LOAN_ID  SMALLINT AUTO_INCREMENT NOT NULL,
  PRD_OFFERING_ID  SMALLINT NOT NULL,
  MIN_LOAN_AMOUNT  DECIMAL(10, 3) NOT NULL,
  MAX_LOAN_AMNT  DECIMAL(10, 3) NOT NULL,
  DEFAULT_LOAN_AMOUNT  DECIMAL(10, 3) NOT NULL,
 PRIMARY KEY(LOAN_AMOUNT_SAME_FOR_ALL_LOAN_ID),  
FOREIGN KEY(PRD_OFFERING_ID)
    REFERENCES  LOAN_OFFERING(PRD_OFFERING_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)
ENGINE=InnoDB CHARACTER SET utf8;

CREATE TABLE  NO_OF_INSTALL_SAME_FOR_ALL_LOAN(
  NO_OF_INSTALL_SAME_FOR_ALL_LOAN_ID  SMALLINT AUTO_INCREMENT NOT NULL,
  PRD_OFFERING_ID  SMALLINT NOT NULL,
  MIN_NO_INSTALL  DECIMAL(10, 3) NOT NULL,
  MAX_NO_INSTALL  DECIMAL(10, 3) NOT NULL,
  DEFAULT_NO_INSTALL  DECIMAL(10, 3) NOT NULL,
 PRIMARY KEY(NO_OF_INSTALL_SAME_FOR_ALL_LOAN_ID),  
FOREIGN KEY(PRD_OFFERING_ID)
    REFERENCES  LOAN_OFFERING(PRD_OFFERING_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)
ENGINE=InnoDB CHARACTER SET utf8;



CREATE TABLE  MAX_MIN_LOAN_AMOUNT(
ACCOUNT_ID INTEGER   AUTO_INCREMENT NOT NULL,
  MIN_LOAN_AMOUNT  DECIMAL(10, 3) NOT NULL,
  MAX_LOAN_AMOUNT  DECIMAL(10, 3) NOT NULL,
  PRIMARY KEY(ACCOUNT_ID),  
FOREIGN KEY(ACCOUNT_ID)
    REFERENCES  LOAN_ACCOUNT(ACCOUNT_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)
ENGINE=InnoDB CHARACTER SET utf8;


CREATE TABLE MAX_MIN_NO_OF_INSTALL(
ACCOUNT_ID INTEGER   AUTO_INCREMENT NOT NULL,
 MIN_NO_INSTALL  DECIMAL(10, 3) NOT NULL,
  MAX_NO_INSTALL  DECIMAL(10, 3) NOT NULL,
  PRIMARY KEY(ACCOUNT_ID),  
FOREIGN KEY(ACCOUNT_ID)
    REFERENCES  LOAN_ACCOUNT(ACCOUNT_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)
ENGINE=InnoDB CHARACTER SET utf8;

UPDATE DATABASE_VERSION SET DATABASE_VERSION = 160 WHERE DATABASE_VERSION = 159;
