ALTER TABLE SURVEY_INSTANCE MODIFY COLUMN OFFICER_ID SMALLINT;
ALTER TABLE SURVEY_INSTANCE CHANGE COLUMN CLIENT_ID CUSTOMER_ID INTEGER;
ALTER TABLE SURVEY_INSTANCE ADD COLUMN ACCOUNT_ID INTEGER;

ALTER TABLE SURVEY_INSTANCE ADD FOREIGN KEY (ACCOUNT_ID)
  REFERENCES ACCOUNT(ACCOUNT_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

update DATABASE_VERSION set DATABASE_VERSION = 125 where DATABASE_VERSION = 124;
