INSERT INTO LOOKUP_VALUE VALUES(589,87,' ');
INSERT INTO LOOKUP_VALUE_LOCALE VALUES(934,1,589,'Can view reports');
INSERT INTO ACTIVITY(ACTIVITY_ID,PARENT_ID,ACTIVITY_NAME_LOOKUP_ID,DESCRIPTION_LOOKUP_ID) VALUES(215,141,589,589);
INSERT INTO ROLES_ACTIVITY VALUES (215,1);

INSERT INTO LOOKUP_VALUE VALUES(590,87,' ');
INSERT INTO LOOKUP_VALUE_LOCALE VALUES(935,1,590,'Can edit report information');
INSERT INTO ACTIVITY(ACTIVITY_ID,PARENT_ID,ACTIVITY_NAME_LOOKUP_ID,DESCRIPTION_LOOKUP_ID) VALUES(216,141,590,590);
INSERT INTO ROLES_ACTIVITY VALUES (216,1);

update DATABASE_VERSION set DATABASE_VERSION = 126 where DATABASE_VERSION = 125;