INSERT INTO LOOKUP_ENTITY(ENTITY_ID,ENTITY_NAME,DESCRIPTION)
VALUES(91,'Repayment Rule','Repayment Rule Types');
INSERT INTO LOOKUP_VALUE(LOOKUP_ID,ENTITY_ID,LOOKUP_NAME)
VALUES(574,91,' ');
INSERT INTO LOOKUP_VALUE(LOOKUP_ID,ENTITY_ID,LOOKUP_NAME)
VALUES(575,91,' ');
INSERT INTO LOOKUP_VALUE(LOOKUP_ID,ENTITY_ID,LOOKUP_NAME)
VALUES(576,91,' ');
INSERT INTO LOOKUP_VALUE_LOCALE(LOOKUP_VALUE_ID,LOCALE_ID,LOOKUP_ID,LOOKUP_VALUE)
VALUES(919,1,574,'Same Day');
INSERT INTO LOOKUP_VALUE_LOCALE(LOOKUP_VALUE_ID,LOCALE_ID,LOOKUP_ID,LOOKUP_VALUE)
VALUES(920,1,575,'Next Meeting/Repayment');
INSERT INTO LOOKUP_VALUE_LOCALE(LOOKUP_VALUE_ID,LOCALE_ID,LOOKUP_ID,LOOKUP_VALUE)
VALUES(921,1,576,'Next Working Day');

CREATE TABLE REPAYMENT_RULE (
  REPAYMENT_RULE_ID SMALLINT AUTO_INCREMENT NOT NULL,
  REPAYMENT_RULE_LOOKUP_ID INTEGER,
  PRIMARY KEY(REPAYMENT_RULE_ID),
  FOREIGN KEY(REPAYMENT_RULE_LOOKUP_ID)
    REFERENCES LOOKUP_VALUE(LOOKUP_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)
ENGINE=InnoDB CHARACTER SET utf8;

INSERT INTO REPAYMENT_RULE(REPAYMENT_RULE_ID, REPAYMENT_RULE_LOOKUP_ID)
VALUES(1,574);
INSERT INTO REPAYMENT_RULE(REPAYMENT_RULE_ID, REPAYMENT_RULE_LOOKUP_ID)
VALUES(2,575);
INSERT INTO REPAYMENT_RULE(REPAYMENT_RULE_ID, REPAYMENT_RULE_LOOKUP_ID)
VALUES(3,576);

ALTER TABLE HOLIDAY 
	CHANGE HOLIDAY_DATE HOLIDAY_FROM_DATE DATE NOT NULL,
	CHANGE HOLIDATY_NAME HOLIDAY_NAME VARCHAR( 100 ) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
	CHANGE OFFICE_ID OFFICE_ID SMALLINT( 6 ) NULL,
	ADD HOLIDAY_THRU_DATE DATE NULL,
	ADD REPAYMENT_RULE_ID SMALLINT NOT NULL DEFAULT '1',
	ADD FOREIGN KEY (REPAYMENT_RULE_ID) 
		REFERENCES REPAYMENT_RULE(REPAYMENT_RULE_ID)
      	ON DELETE NO ACTION
      	ON UPDATE NO ACTION;

UPDATE DATABASE_VERSION SET DATABASE_VERSION = 103 WHERE DATABASE_VERSION = 102;
