INSERT INTO LOOKUP_VALUE VALUES(580,87,' ');
INSERT INTO LOOKUP_VALUE_LOCALE VALUES(925,1,580,'Can remove clients from groups');
INSERT INTO ACTIVITY(ACTIVITY_ID,PARENT_ID,ACTIVITY_NAME_LOOKUP_ID,DESCRIPTION_LOOKUP_ID) VALUES(206,34,580,580);
INSERT INTO ROLES_ACTIVITY VALUES (206,1);

update DATABASE_VERSION set DATABASE_VERSION = 115 where DATABASE_VERSION = 114;
