ALTER TABLE LOAN_ACCOUNT DROP COLUMN PARENT_ACCOUNT_ID;
ALTER TABLE LOAN_ACCOUNT ADD COLUMN  PARENT_ACCOUNT_ID INTEGER;


ALTER TABLE LOAN_ACCOUNT ADD FOREIGN KEY (PARENT_ACCOUNT_ID)
  REFERENCES LOAN_ACCOUNT(ACCOUNT_ID) ON DELETE NO ACTION  ON UPDATE NO ACTION;
  
  
UPDATE DATABASE_VERSION SET DATABASE_VERSION = 154 WHERE DATABASE_VERSION = 153;
  