INSERT INTO LOOKUP_VALUE VALUES(587,87,' ');
INSERT INTO LOOKUP_VALUE_LOCALE VALUES(932,1,587,'Can Define Lookup Values');
INSERT INTO ACTIVITY(ACTIVITY_ID,PARENT_ID,ACTIVITY_NAME_LOOKUP_ID,
  DESCRIPTION_LOOKUP_ID) VALUES(213,203,587,587);
INSERT INTO ROLES_ACTIVITY VALUES (213,1);

update DATABASE_VERSION set DATABASE_VERSION = 123 where DATABASE_VERSION = 122;
