ALTER TABLE REPORT ADD CONSTRAINT REPORT_ibfk_2
FOREIGN KEY(ACTIVITY_ID)
  REFERENCES ACTIVITY(ACTIVITY_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE REPORT_CATEGORY ADD CONSTRAINT REPORT_CATEGORY_ibfk_1
FOREIGN KEY(ACTIVITY_ID)
  REFERENCES ACTIVITY(ACTIVITY_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

UPDATE DATABASE_VERSION SET DATABASE_VERSION = 207 WHERE DATABASE_VERSION = 206;
