-- allow this script to be re-run
DROP TABLE IF EXISTS MAX_MIN_NO_OF_INSTALL;
DROP TABLE IF EXISTS MAX_MIN_LOAN_AMOUNT;
DROP TABLE IF EXISTS NO_OF_INSTALL_SAME_FOR_ALL_LOAN;
DROP TABLE IF EXISTS LOAN_AMOUNT_SAME_FOR_ALL_LOAN;
DROP TABLE IF EXISTS NO_OF_INSTALL_FROM_LOAN_CYCLE;
DROP TABLE IF EXISTS LOAN_AMOUNT_FROM_LOAN_CYCLE;
DROP TABLE IF EXISTS NO_OF_INSTALL_FROM_LAST_LOAN;
DROP TABLE IF EXISTS LOAN_AMOUNT_FROM_LAST_LOAN;

-- tables for loan defaults based on last loan
CREATE TABLE LOAN_AMOUNT_FROM_LAST_LOAN (
LOAN_AMOUNT_FROM_LAST_LOAN_ID  SMALLINT AUTO_INCREMENT NOT NULL,
  PRD_OFFERING_ID  SMALLINT NOT NULL,
START_RANGE DECIMAL(10, 3) NOT NULL, 
END_RANGE DECIMAL(10, 3)  NOT NULL,
  MIN_LOAN_AMOUNT  DECIMAL(10, 3) NOT NULL,
  MAX_LOAN_AMNT  DECIMAL(10, 3) NOT NULL,
  DEFAULT_LOAN_AMOUNT  DECIMAL(10, 3) NOT NULL,
 PRIMARY KEY(LOAN_AMOUNT_FROM_LAST_LOAN_ID),  
FOREIGN KEY(PRD_OFFERING_ID)
    REFERENCES  LOAN_OFFERING(PRD_OFFERING_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)
ENGINE=InnoDB CHARACTER SET utf8;


CREATE TABLE  NO_OF_INSTALL_FROM_LAST_LOAN (
 NO_OF_INSTALL_FROM_LAST_LOAN_ID  SMALLINT AUTO_INCREMENT NOT NULL,
  PRD_OFFERING_ID  SMALLINT NOT NULL,
START_RANGE DECIMAL(10, 3) NOT NULL, 
END_RANGE DECIMAL(10, 3)  NOT NULL,
  MIN_NO_INSTALL  DECIMAL(10, 3) NOT NULL,
  MAX_NO_INSTALL  DECIMAL(10, 3) NOT NULL,
  DEFAULT_NO_INSTALL  DECIMAL(10, 3) NOT NULL,
 PRIMARY KEY(NO_OF_INSTALL_FROM_LAST_LOAN_ID ),  
FOREIGN KEY(PRD_OFFERING_ID)
    REFERENCES  LOAN_OFFERING(PRD_OFFERING_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)
ENGINE=InnoDB CHARACTER SET utf8;


CREATE TABLE  LOAN_AMOUNT_FROM_LOAN_CYCLE(
 LOAN_AMOUNT_FROM_LOAN_CYCLE_ID  SMALLINT AUTO_INCREMENT NOT NULL,
  PRD_OFFERING_ID  SMALLINT NOT NULL,
  MIN_LOAN_AMOUNT  DECIMAL(10, 3) NOT NULL,
  MAX_LOAN_AMNT  DECIMAL(10, 3) NOT NULL,
  DEFAULT_LOAN_AMOUNT  DECIMAL(10, 3) NOT NULL,
 RANGE_INDEX DECIMAL(10, 3) NOT NULL,
 PRIMARY KEY(LOAN_AMOUNT_FROM_LOAN_CYCLE_ID),  
FOREIGN KEY(PRD_OFFERING_ID)
    REFERENCES  LOAN_OFFERING(PRD_OFFERING_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)
ENGINE=InnoDB CHARACTER SET utf8;

CREATE TABLE  NO_OF_INSTALL_FROM_LOAN_CYCLE (
 NO_OF_INSTALL_FROM_LOAN_CYCLE_ID  SMALLINT AUTO_INCREMENT NOT NULL,
  PRD_OFFERING_ID  SMALLINT NOT NULL,
  MIN_NO_INSTALL  DECIMAL(10, 3) NOT NULL,
  MAX_NO_INSTALL  DECIMAL(10, 3) NOT NULL,
  DEFAULT_NO_INSTALL  DECIMAL(10, 3) NOT NULL,
RANGE_INDEX DECIMAL(10, 3) NOT NULL,
 PRIMARY KEY(NO_OF_INSTALL_FROM_LOAN_CYCLE_ID),  
FOREIGN KEY(PRD_OFFERING_ID)
    REFERENCES  LOAN_OFFERING(PRD_OFFERING_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)
ENGINE=InnoDB CHARACTER SET utf8;

CREATE TABLE  LOAN_AMOUNT_SAME_FOR_ALL_LOAN(
LOAN_AMOUNT_SAME_FOR_ALL_LOAN_ID  SMALLINT AUTO_INCREMENT NOT NULL,
  PRD_OFFERING_ID  SMALLINT NOT NULL,
  MIN_LOAN_AMOUNT  DECIMAL(10, 3) NOT NULL,
  MAX_LOAN_AMNT  DECIMAL(10, 3) NOT NULL,
  DEFAULT_LOAN_AMOUNT  DECIMAL(10, 3) NOT NULL,
 PRIMARY KEY(LOAN_AMOUNT_SAME_FOR_ALL_LOAN_ID),  
FOREIGN KEY(PRD_OFFERING_ID)
    REFERENCES  LOAN_OFFERING(PRD_OFFERING_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)
ENGINE=InnoDB CHARACTER SET utf8;

CREATE TABLE  NO_OF_INSTALL_SAME_FOR_ALL_LOAN(
  NO_OF_INSTALL_SAME_FOR_ALL_LOAN_ID  SMALLINT AUTO_INCREMENT NOT NULL,
  PRD_OFFERING_ID  SMALLINT NOT NULL,
  MIN_NO_INSTALL  DECIMAL(10, 3) NOT NULL,
  MAX_NO_INSTALL  DECIMAL(10, 3) NOT NULL,
  DEFAULT_NO_INSTALL  DECIMAL(10, 3) NOT NULL,
 PRIMARY KEY(NO_OF_INSTALL_SAME_FOR_ALL_LOAN_ID),  
FOREIGN KEY(PRD_OFFERING_ID)
    REFERENCES  LOAN_OFFERING(PRD_OFFERING_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)
ENGINE=InnoDB CHARACTER SET utf8;



CREATE TABLE  MAX_MIN_LOAN_AMOUNT(
ACCOUNT_ID INTEGER   AUTO_INCREMENT NOT NULL,
  MIN_LOAN_AMOUNT  DECIMAL(10, 3) NOT NULL,
  MAX_LOAN_AMOUNT  DECIMAL(10, 3) NOT NULL,
  PRIMARY KEY(ACCOUNT_ID),  
FOREIGN KEY(ACCOUNT_ID)
    REFERENCES  LOAN_ACCOUNT(ACCOUNT_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)
ENGINE=InnoDB CHARACTER SET utf8;


CREATE TABLE MAX_MIN_NO_OF_INSTALL(
ACCOUNT_ID INTEGER   AUTO_INCREMENT NOT NULL,
 MIN_NO_INSTALL  DECIMAL(10, 3) NOT NULL,
  MAX_NO_INSTALL  DECIMAL(10, 3) NOT NULL,
  PRIMARY KEY(ACCOUNT_ID),  
FOREIGN KEY(ACCOUNT_ID)
    REFERENCES  LOAN_ACCOUNT(ACCOUNT_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)
ENGINE=InnoDB CHARACTER SET utf8;

/* the following queries will move data from loan_offering, loan_acount to the new tables for existing users */
/* fix the loan products min/max/default loan amounts */
INSERT INTO LOAN_AMOUNT_SAME_FOR_ALL_LOAN (PRD_OFFERING_ID, MAX_LOAN_AMNT, MIN_LOAN_AMOUNT, DEFAULT_LOAN_AMOUNT)  SELECT PRD_OFFERING_ID, MAX_LOAN_AMNT, MIN_LOAN_AMOUNT, DEFAULT_LOAN_AMOUNT FROM LOAN_OFFERING WHERE MAX_LOAN_AMNT IS NOT NULL and MIN_LOAN_AMOUNT IS NOT NULL AND DEFAULT_LOAN_AMOUNT IS NOT NULL AND (PRD_OFFERING_ID NOT IN (SELECT PRD_OFFERING_ID FROM LOAN_AMOUNT_SAME_FOR_ALL_LOAN) AND PRD_OFFERING_ID NOT IN (SELECT PRD_OFFERING_ID FROM LOAN_AMOUNT_FROM_LOAN_CYCLE) AND PRD_OFFERING_ID NOT IN (SELECT PRD_OFFERING_ID FROM LOAN_AMOUNT_FROM_LAST_LOAN));

/*fix the loan products installments */
INSERT INTO NO_OF_INSTALL_SAME_FOR_ALL_LOAN (PRD_OFFERING_ID, MIN_NO_INSTALL, MAX_NO_INSTALL, DEFAULT_NO_INSTALL)  SELECT PRD_OFFERING_ID, MIN_NO_INSTALLMENTS, MAX_NO_INSTALLMENTS, DEF_NO_INSTALLMENTS FROM LOAN_OFFERING WHERE MIN_NO_INSTALLMENTS IS NOT NULL AND MAX_NO_INSTALLMENTS IS NOT NULL AND DEF_NO_INSTALLMENTS IS NOT NULL AND (PRD_OFFERING_ID NOT IN (SELECT PRD_OFFERING_ID FROM NO_OF_INSTALL_SAME_FOR_ALL_LOAN) AND PRD_OFFERING_ID NOT IN (SELECT PRD_OFFERING_ID FROM NO_OF_INSTALL_FROM_LOAN_CYCLE) AND PRD_OFFERING_ID NOT IN (SELECT PRD_OFFERING_ID FROM NO_OF_INSTALL_FROM_LAST_LOAN));

/* fix the loan min/max/loan amounts for loan accounts */
INSERT INTO MAX_MIN_LOAN_AMOUNT (ACCOUNT_ID, MIN_LOAN_AMOUNT, MAX_LOAN_AMOUNT) SELECT LA.ACCOUNT_ID, LO.MIN_LOAN_AMOUNT, LO.MAX_LOAN_AMNT FROM LOAN_ACCOUNT LA, LOAN_OFFERING LO WHERE LO.MIN_LOAN_AMOUNT IS NOT NULL AND LO.MAX_LOAN_AMNT IS NOT NULL AND LA.ACCOUNT_ID NOT IN (SELECT ACCOUNT_ID FROM MAX_MIN_LOAN_AMOUNT) AND LO.PRD_OFFERING_ID=LA.PRD_OFFERING_ID; 

/* fix the loan min/max/no of installments for loan accounts */
INSERT INTO MAX_MIN_NO_OF_INSTALL (ACCOUNT_ID, MIN_NO_INSTALL, MAX_NO_INSTALL) SELECT LA.ACCOUNT_ID, LO.MIN_NO_INSTALLMENTS, LO.MAX_NO_INSTALLMENTS FROM LOAN_ACCOUNT LA, LOAN_OFFERING LO WHERE LO.MIN_NO_INSTALLMENTS IS NOT NULL AND LO.MAX_NO_INSTALLMENTS IS NOT NULL AND LA.ACCOUNT_ID NOT IN (SELECT ACCOUNT_ID FROM MAX_MIN_NO_OF_INSTALL) AND LO.PRD_OFFERING_ID=LA.PRD_OFFERING_ID; 

UPDATE DATABASE_VERSION SET DATABASE_VERSION = 160 WHERE DATABASE_VERSION = 159;
