INSERT INTO LOOKUP_VALUE VALUES(582,87,' ');
INSERT INTO LOOKUP_VALUE_LOCALE 
  VALUES(927,1,582,'Can add an existing client to a group');
INSERT INTO ACTIVITY(ACTIVITY_ID,PARENT_ID,
  ACTIVITY_NAME_LOOKUP_ID,DESCRIPTION_LOOKUP_ID) 
  VALUES(208,34,582,582);
INSERT INTO ROLES_ACTIVITY VALUES (208,1);

update DATABASE_VERSION set DATABASE_VERSION = 118 where DATABASE_VERSION = 117;
