CREATE TABLE PRODUCT_OFFERING_MANDATORY_SAVINGS (
  PRODUCT_OFFERING_MANDATORY_SAVINGS_ID SMALLINT NOT NULL, 
  PRODUCT_OFFERING_MANDATORY_SAVINGS_TYPE SMALLINT, 
  PRD_OFFERING_ID SMALLINT, 
  PRODUCT_OFFERING_MANDATORY_SAVINGS_VALUE SMALLINT, 
  PRODUCT_OFFERING_MANDATORY_SAVINGS_RANGE smallint, 
  primary key (PRODUCT_OFFERING_MANDATORY_SAVINGS_ID), 
  foreign key (PRD_OFFERING_ID) references prd_offering (PRD_OFFERING_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) 
ENGINE=InnoDB CHARACTER SET utf8;

UPDATE DATABASE_VERSION SET DATABASE_VERSION = 110 WHERE DATABASE_VERSION = 109;
