INSERT INTO LOOKUP_VALUE VALUES(569,87,' ');
INSERT INTO LOOKUP_VALUE_LOCALE VALUES(914,1,569,'Can create multiple Loan accounts');
INSERT INTO ACTIVITY(ACTIVITY_ID,PARENT_ID,ACTIVITY_NAME_LOOKUP_ID,DESCRIPTION_LOOKUP_ID) VALUES(201,196,569,569);
INSERT INTO ROLES_ACTIVITY VALUES (201,1);

update DATABASE_VERSION set DATABASE_VERSION = 101 where DATABASE_VERSION = 100;