ALTER TABLE LOAN_ACCOUNT DROP FOREIGN KEY loan_account_ibfk_9;
ALTER TABLE LOAN_ACCOUNT DROP FOREIGN KEY loan_account_ibfk_10;
ALTER TABLE LOAN_ACCOUNT DROP FOREIGN KEY loan_account_ibfk_11;
ALTER TABLE LOAN_ACCOUNT DROP FOREIGN KEY loan_account_ibfk_12;
ALTER TABLE LOAN_ACCOUNT DROP FOREIGN KEY fk_loan_account;
ALTER TABLE LOAN_ACCOUNT DROP FOREIGN KEY fk_loan_rankday;
ALTER TABLE LOAN_ACCOUNT DROP FOREIGN KEY fk_loan_monthweek;

UPDATE LOAN_ACCOUNT SET COLLATERAL_TYPE_ID=109 WHERE COLLATERAL_TYPE_ID=1;
UPDATE LOAN_ACCOUNT SET COLLATERAL_TYPE_ID=110 WHERE COLLATERAL_TYPE_ID=2;

ALTER TABLE LOAN_ACCOUNT MODIFY COLUMN COLLATERAL_TYPE_ID INTEGER;

ALTER TABLE LOAN_ACCOUNT ADD CONSTRAINT fk_loan_col_type_id FOREIGN KEY(COLLATERAL_TYPE_ID) REFERENCES LOOKUP_VALUE(LOOKUP_ID);
ALTER TABLE LOAN_ACCOUNT ADD CONSTRAINT fk_loan_bus_act_id FOREIGN KEY(BUSINESS_ACTIVITIES_ID) REFERENCES LOOKUP_VALUE(LOOKUP_ID);
ALTER TABLE LOAN_ACCOUNT ADD CONSTRAINT fk_loan_prd_off_id FOREIGN KEY(PRD_OFFERING_ID) REFERENCES PRD_OFFERING(PRD_OFFERING_ID);
ALTER TABLE LOAN_ACCOUNT ADD CONSTRAINT fk_loan_acc_id FOREIGN KEY(PARENT_ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID);
ALTER TABLE LOAN_ACCOUNT ADD CONSTRAINT fk_loan_account FOREIGN KEY(PARENT_ACCOUNT_ID) REFERENCES LOAN_ACCOUNT(ACCOUNT_ID);
ALTER TABLE LOAN_ACCOUNT ADD CONSTRAINT fk_loan_rankday FOREIGN KEY(MONTH_RANK) REFERENCES RANK_DAYS_MASTER(RANK_DAYS_MASTER_ID);
ALTER TABLE LOAN_ACCOUNT ADD CONSTRAINT fk_loan_monthweek FOREIGN KEY(MONTH_WEEK) REFERENCES WEEK_DAYS_MASTER(WEEK_DAYS_MASTER_ID);

DROP TABLE COLLATERAL_TYPE;

UPDATE DATABASE_VERSION SET DATABASE_VERSION = 182 WHERE DATABASE_VERSION = 181;
