INSERT INTO LOOKUP_VALUE VALUES(579,87,' ');
INSERT INTO LOOKUP_VALUE_LOCALE VALUES(924,1,579,'Can define hidden/mandatory fields');
INSERT INTO ACTIVITY(ACTIVITY_ID,PARENT_ID,ACTIVITY_NAME_LOOKUP_ID,DESCRIPTION_LOOKUP_ID) VALUES(205,203,579,579);
INSERT INTO ROLES_ACTIVITY VALUES (205,1);

INSERT INTO FIELD_CONFIGURATION(FIELD_CONFIG_ID,FIELD_NAME,ENTITY_ID,MANDATORY_FLAG,HIDDEN_FLAG)
VALUES(74,'AssignClients',1,0,0);

update DATABASE_VERSION set DATABASE_VERSION = 106 where DATABASE_VERSION = 105;