/* Moved into application-wide configuration. See configurationFactory.xml. */
UPDATE CONFIG_KEY_VALUE_INTEGER
   SET CONFIGURATION_KEY = ' ',
       CONFIGURATION_VALUE = 0
 WHERE CONFIGURATION_ID = 2;


UPDATE DATABASE_VERSION SET DATABASE_VERSION = 166 WHERE DATABASE_VERSION = 165;
