-- Copyright (c) 2005-2008 Grameen Foundation USA
-- 1029 Vermont Avenue, NW, Suite 400, Washington DC 20005
-- All rights reserved.
-- 
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
-- 
--     http://www.apache.org/licenses/LICENSE-2.0
-- 
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
-- implied. See the License for the specific language governing
-- permissions and limitations under the License.
-- 
-- See also http://www.apache.org/licenses/LICENSE-2.0.html for an
-- explanation of the license and how it is applied.
DROP TABLE IF EXISTS BATCH_CLIENT_SUMMARY;
DROP TABLE IF EXISTS BATCH_STAFF_SUMMARY;
DROP TABLE IF EXISTS BATCH_LOAN_ARREARS_AGING;
DROP TABLE IF EXISTS BATCH_STAFFING_LEVEL_SUMMARY;
DROP TABLE IF EXISTS BATCH_LOAN_DETAILS;
DROP TABLE IF EXISTS BATCH_LOAN_ARREARS_PROFILE;
DROP TABLE IF EXISTS BATCH_BRANCH_REPORT;

DROP TABLE IF EXISTS BATCH_BRANCH_CONFIRMATION_RECOVERY;
DROP TABLE IF EXISTS BATCH_BRANCH_CONFIRMATION_ISSUE;
DROP TABLE IF EXISTS BATCH_BRANCH_CONFIRMATION_DISBURSEMENT;
DROP TABLE IF EXISTS BATCH_BRANCH_CASH_CONFIRMATION_REPORT;

CREATE TABLE BATCH_BRANCH_REPORT(
  BRANCH_REPORT_ID INTEGER AUTO_INCREMENT NOT NULL,
  BRANCH_ID SMALLINT NOT NULL,
  RUN_DATE DATE NOT NULL,
  PRIMARY KEY(BRANCH_REPORT_ID)
)ENGINE=InnoDB CHARACTER SET utf8;

CREATE TABLE BATCH_CLIENT_SUMMARY(
  CLIENT_SUMMARY_ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
  BRANCH_REPORT_ID INTEGER NOT NULL,
  FIELD_NAME VARCHAR(50) NOT NULL,
  TOTAL VARCHAR(50),
  VPOOR_TOTAL VARCHAR(50),
  FOREIGN KEY(BRANCH_REPORT_ID) REFERENCES BATCH_BRANCH_REPORT(BRANCH_REPORT_ID)
)ENGINE=InnoDB CHARACTER SET utf8;

CREATE TABLE BATCH_LOAN_ARREARS_AGING (
  LOAN_ARREARS_AGING_ID INTEGER AUTO_INCREMENT NOT NULL,
  AGING_PERIOD_ID INTEGER NOT NULL,
  BRANCH_REPORT_ID INTEGER NOT NULL,
  CLIENTS_AGING INTEGER NOT NULL,
  LOANS_AGING INTEGER NOT NULL,
  AMOUNT_AGING DECIMAL(20,3) NOT NULL,
  AMOUNT_AGING_CURRENCY_ID SMALLINT NOT NULL,
  AMOUNT_OUTSTANDING_AGING DECIMAL(20,3) NOT NULL,
  AMOUNT_OUTSTANDING_AGING_CURRENCY_ID SMALLINT NOT NULL,
  PRIMARY KEY (LOAN_ARREARS_AGING_ID),
  FOREIGN KEY (BRANCH_REPORT_ID)
    REFERENCES BATCH_BRANCH_REPORT (BRANCH_REPORT_ID)
) ENGINE = InnoDB CHARACTER SET utf8;

CREATE TABLE BATCH_STAFF_SUMMARY(
  STAFF_SUMMARY_ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
  BRANCH_REPORT_ID INTEGER NOT NULL,
  PERSONNEL_ID SMALLINT NOT NULL,
  PERSONNEL_NAME VARCHAR(50) NOT NULL,
  JOINING_DATE DATE,
  ACTIVE_BORROWERS INTEGER NOT NULL,
  ACTIVE_LOANS INTEGER NOT NULL,
  CENTER_COUNT INTEGER NOT NULL,
  CLIENT_COUNT INTEGER NOT NULL,
  NEW_GROUP_COUNT INTEGER NOT NULL,  
  LOAN_AMOUNT_OUTSTANDING DECIMAL(20,3) NOT NULL,
  LOAN_AMOUNT_OUTSTANDING_CURRENCY_ID SMALLINT NOT NULL,
  INTEREST_FEES_OUTSTANDING DECIMAL(20,3) NOT NULL,
  INTEREST_FEES_OUTSTANDING_CURRENCY_ID SMALLINT NOT NULL,
  PORTFOLIO_AT_RISK DECIMAL(20,3) NOT NULL,
  FOREIGN KEY(BRANCH_REPORT_ID) REFERENCES BATCH_BRANCH_REPORT(BRANCH_REPORT_ID)
)ENGINE=InnoDB CHARACTER SET utf8;

CREATE TABLE BATCH_STAFFING_LEVEL_SUMMARY(
 STAFFING_LEVEL_SUMMARY_ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
 BRANCH_REPORT_ID INTEGER NOT NULL,
 ROLE_ID INTEGER NOT NULL,
 ROLE_NAME VARCHAR(50) NOT NULL,
 PERSONNEL_COUNT INTEGER NOT NULL,
 FOREIGN KEY(BRANCH_REPORT_ID) REFERENCES BATCH_BRANCH_REPORT(BRANCH_REPORT_ID)
)ENGINE=InnoDB CHARACTER SET utf8;

CREATE TABLE BATCH_LOAN_DETAILS(
 LOAN_DETAILS_ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
 BRANCH_REPORT_ID INTEGER NOT NULL,
 PRODUCT_NAME VARCHAR(50) NOT NULL,
 NUMBER_OF_LOANS_ISSUED INTEGER NOT NULL,
 LOAN_AMOUNT_ISSUED DECIMAL(20,3) NOT NULL,
 LOAN_AMOUNT_ISSUED_CURRENCY_ID SMALLINT NOT NULL,
 LOAN_INTEREST_ISSUED DECIMAL(20,3) NOT NULL,
 LOAN_INTEREST_ISSUED_CURRENCY_ID SMALLINT NOT NULL,
 NUMBER_OF_LOANS_OUTSTANDING INTEGER NOT NULL,
 LOAN_OUTSTANDING_AMOUNT DECIMAL(20,3) NOT NULL,
 LOAN_OUTSTANDING_AMOUNT_CURRENCY_ID SMALLINT NOT NULL,
 LOAN_OUTSTANDING_INTEREST DECIMAL(20,3) NOT NULL,
 LOAN_OUTSTANDING_INTEREST_CURRENCY_ID SMALLINT NOT NULL,
 FOREIGN KEY(BRANCH_REPORT_ID) REFERENCES BATCH_BRANCH_REPORT(BRANCH_REPORT_ID)
)ENGINE=InnoDB CHARACTER SET utf8;

CREATE TABLE BATCH_LOAN_ARREARS_PROFILE(
 LOAN_ARREARS_PROFILE_ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
 BRANCH_REPORT_ID INTEGER NOT NULL,
 LOANS_IN_ARREARS INTEGER NOT NULL,
 CLIENTS_IN_ARREARS INTEGER NOT NULL,
 OVERDUE_BALANCE DECIMAL(20,3) NOT NULL,
 OVERDUE_BALANCE_CURRENCY_ID SMALLINT NOT NULL,
 UNPAID_BALANCE DECIMAL(20,3) NOT NULL,
 UNPAID_BALANCE_CURRENCY_ID SMALLINT NOT NULL,
 LOANS_AT_RISK INTEGER NOT NULL,
 OUTSTANDING_AMOUNT_AT_RISK DECIMAL(20,3) NOT NULL,
 OUTSTANDING_AMOUNT_AT_RISK_CURRENCY_ID SMALLINT NOT NULL,
 OVERDUE_AMOUNT_AT_RISK DECIMAL(20,3) NOT NULL,
 OVERDUE_AMOUNT_AT_RISK_CURRENCY_ID SMALLINT NOT NULL,
 CLIENTS_AT_RISK INTEGER NOT NULL,
 FOREIGN KEY(BRANCH_REPORT_ID) REFERENCES BATCH_BRANCH_REPORT(BRANCH_REPORT_ID)
)ENGINE=InnoDB CHARACTER SET utf8;

CREATE TABLE BATCH_BRANCH_CASH_CONFIRMATION_REPORT(
  BRANCH_CASH_CONFIRMATION_REPORT_ID INTEGER AUTO_INCREMENT NOT NULL,
  BRANCH_ID SMALLINT NOT NULL,
  RUN_DATE DATE NOT NULL,
  PRIMARY KEY(BRANCH_CASH_CONFIRMATION_REPORT_ID)
)ENGINE=InnoDB CHARACTER SET utf8;

CREATE TABLE BATCH_BRANCH_CONFIRMATION_RECOVERY(
  RECOVERY_ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
  BRANCH_CASH_CONFIRMATION_REPORT_ID INTEGER NOT NULL,
  PRODUCT_NAME VARCHAR(50) NOT NULL,
  DUE DECIMAL(20,3) NOT NULL,
  DUE_CURRENCY_ID SMALLINT NOT NULL,
  ACTUAL DECIMAL(20,3) NOT NULL,
  ACTUAL_CURRENCY_ID SMALLINT NOT NULL,
  ARREARS DECIMAL(20,3) NOT NULL,
  ARREARS_CURRENCY_ID SMALLINT NOT NULL,
  FOREIGN KEY(BRANCH_CASH_CONFIRMATION_REPORT_ID) 
  REFERENCES BATCH_BRANCH_CASH_CONFIRMATION_REPORT(BRANCH_CASH_CONFIRMATION_REPORT_ID)
)ENGINE=InnoDB CHARACTER SET utf8;

CREATE TABLE BATCH_BRANCH_CONFIRMATION_ISSUE(
  ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
  BRANCH_CASH_CONFIRMATION_REPORT_ID INTEGER NOT NULL,
  PRODUCT_NAME VARCHAR(50) NOT NULL,  
  ACTUAL DECIMAL(20,3) NOT NULL,
  ACTUAL_CURRENCY_ID SMALLINT NOT NULL,  
  FOREIGN KEY(BRANCH_CASH_CONFIRMATION_REPORT_ID) 
  REFERENCES BATCH_BRANCH_CASH_CONFIRMATION_REPORT(BRANCH_CASH_CONFIRMATION_REPORT_ID)
)ENGINE=InnoDB CHARACTER SET utf8;

CREATE TABLE BATCH_BRANCH_CONFIRMATION_DISBURSEMENT(
  ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
  BRANCH_CASH_CONFIRMATION_REPORT_ID INTEGER NOT NULL,
  PRODUCT_NAME VARCHAR(50) NOT NULL,  
  ACTUAL DECIMAL(20,3) NOT NULL,
  ACTUAL_CURRENCY_ID SMALLINT NOT NULL,  
  FOREIGN KEY(BRANCH_CASH_CONFIRMATION_REPORT_ID) 
  REFERENCES BATCH_BRANCH_CASH_CONFIRMATION_REPORT(BRANCH_CASH_CONFIRMATION_REPORT_ID)
)ENGINE=InnoDB CHARACTER SET utf8;

UPDATE DATABASE_VERSION SET DATABASE_VERSION = 180 WHERE DATABASE_VERSION = 179;
