-- updating some activities for Products Mix

UPDATE ACTIVITY SET PARENT_ID=89 WHERE ACTIVITY_ID=209;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Product Mix' WHERE LOOKUP_VALUE_ID=928;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can define product mix' WHERE LOOKUP_VALUE_ID=929;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can edit product mix' WHERE LOOKUP_VALUE_ID=930;

-- adding column to PRD_OFFERING : Tagging products for which mixes were defined

ALTER TABLE PRD_OFFERING ADD COLUMN PRD_MIX_FLAG SMALLINT;

-- defining table for products mix 

DROP TABLE IF EXISTS PRD_OFFERING_MIX;

CREATE TABLE PRD_OFFERING_MIX (
  PRD_OFFERING_MIX_ID  INTEGER AUTO_INCREMENT NOT NULL,
  PRD_OFFERING_ID SMALLINT NOT NULL ,
  PRD_OFFERING_NOT_ALLOWED_ID SMALLINT NOT NULL ,
  CREATED_BY SMALLINT ,
  CREATED_DATE date ,
  UPDATED_BY SMALLINT,
  UPDATED_DATE date ,
  VERSION_NO INTEGER,
  PRIMARY KEY  (PRD_OFFERING_MIX_ID),
  CONSTRAINT PRD_OFFERING_MIX_PRD_OFFERING_ID_1
  FOREIGN KEY (PRD_OFFERING_ID) 
  REFERENCES PRD_OFFERING (PRD_OFFERING_ID) 
  ON DELETE NO ACTION 
  ON UPDATE NO ACTION,
  CONSTRAINT PRD_OFFERING_MIX_PRD_OFFERING_ID_2 
  FOREIGN KEY (PRD_OFFERING_NOT_ALLOWED_ID) 
  REFERENCES PRD_OFFERING (PRD_OFFERING_ID) 
  ON DELETE NO ACTION 
  ON UPDATE NO ACTION
) ENGINE=InnoDB CHARACTER SET utf8;

update DATABASE_VERSION set DATABASE_VERSION = 127 where DATABASE_VERSION = 126;
