-- See bug 1721: https://mifos.dev.java.net/issues/show_bug.cgi?id=1721
DELETE FROM ROLES_ACTIVITY WHERE ACTIVITY_ID >= 152 AND ACTIVITY_ID <= 177;
DELETE FROM ACTIVITY WHERE ACTIVITY_ID >= 152 AND ACTIVITY_ID <= 177;
DELETE FROM LOOKUP_VALUE_LOCALE WHERE LOOKUP_ID >= 505 AND LOOKUP_ID <= 530;
DELETE FROM LOOKUP_VALUE  WHERE LOOKUP_ID >= 505 AND LOOKUP_ID <= 530;
DELETE FROM REPORT_JASPER_MAP WHERE REPORT_ID <= 27;
DELETE FROM REPORT WHERE REPORT_ID <= 27;

UPDATE DATABASE_VERSION SET DATABASE_VERSION=189 WHERE DATABASE_VERSION=188;