UPDATE LOOKUP_ENTITY SET ENTITY_NAME='Client Formed By',DESCRIPTION='CustomField ClientFormedBy for client'
WHERE ENTITY_ID=23;
UPDATE LOOKUP_ENTITY SET ENTITY_NAME='No of Clients per Group',DESCRIPTION='Custom Field  No. of Clients per Group'
WHERE ENTITY_ID=63;
UPDATE LOOKUP_ENTITY SET ENTITY_NAME='No of Clients per Center',DESCRIPTION='Custom Field No. of Clients per Center'
WHERE ENTITY_ID=64;
UPDATE LOOKUP_LABEL SET ENTITY_NAME='Client' WHERE LABEL_ID=25;
UPDATE LOOKUP_LABEL SET ENTITY_NAME='Number of Clients per Group' WHERE LABEL_ID=118;
UPDATE LOOKUP_LABEL SET ENTITY_NAME='Number of Clients per Center' WHERE LABEL_ID=120;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Clients' WHERE LOOKUP_VALUE_ID=135;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Client' WHERE LOOKUP_VALUE_ID=162;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Only Client' WHERE LOOKUP_VALUE_ID=247;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Client management' WHERE LOOKUP_VALUE_ID=732;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Clients' WHERE LOOKUP_VALUE_ID=733;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can create new Client in save for later state' WHERE LOOKUP_VALUE_ID=734;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can create new Client in submit for approval state' WHERE LOOKUP_VALUE_ID=735;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can make payments to Client accounts' WHERE LOOKUP_VALUE_ID=742;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can make adjustment entries to Client account' WHERE LOOKUP_VALUE_ID=743;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can remove fee types from Client account' WHERE LOOKUP_VALUE_ID=746;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can add notes to Client' WHERE LOOKUP_VALUE_ID=747;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can Blacklist a Client' WHERE LOOKUP_VALUE_ID=754;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Client Detail' WHERE LOOKUP_VALUE_ID=836;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can view Client Summary.& History Report' WHERE LOOKUP_VALUE_ID=843;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can view Client Product Wise History Report' WHERE LOOKUP_VALUE_ID=844;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can view Client Settlement info Report' WHERE LOOKUP_VALUE_ID=845;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can view Client Loan repayment schedule' WHERE LOOKUP_VALUE_ID=846;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can view Client Fees, Charges and Penalties report' WHERE LOOKUP_VALUE_ID=847;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can view Client pending approval report' WHERE LOOKUP_VALUE_ID=848;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can view Clients without Savings Account' WHERE LOOKUP_VALUE_ID=849;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can apply charges to Client accounts' WHERE LOOKUP_VALUE_ID=904;
UPDATE REPORT SET REPORT_NAME='Clients without Saving Accouts' WHERE REPORT_ID=7;
UPDATE REPORT_JASPER_MAP SET REPORT_NAME='Clients without Saving Accouts' WHERE REPORT_ID=7;

UPDATE LOOKUP_LABEL SET ENTITY_NAME='Savings' WHERE LABEL_ID=53;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Savings' WHERE LOOKUP_VALUE_ID=109;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Savings' WHERE LOOKUP_VALUE_ID=167;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Savings Products' WHERE LOOKUP_VALUE_ID=795;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can define new Savings product instance' WHERE LOOKUP_VALUE_ID=796;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can edit Savings product instances' WHERE LOOKUP_VALUE_ID=797;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Savings Management' WHERE LOOKUP_VALUE_ID=827;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can create new Savings account in Save for later state' WHERE LOOKUP_VALUE_ID=828;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can update Savings account' WHERE LOOKUP_VALUE_ID=829;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can close Savings account' WHERE LOOKUP_VALUE_ID=830;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can blacklist Savings account' WHERE LOOKUP_VALUE_ID=875;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can create new Savings account in submit for approval state' WHERE LOOKUP_VALUE_ID=876;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can waive due deposits for Savings account' WHERE LOOKUP_VALUE_ID=889;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can waive over due deposits for Savings account' WHERE LOOKUP_VALUE_ID=890;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can add notes to Savings account' WHERE LOOKUP_VALUE_ID=893;

UPDATE LOOKUP_ENTITY SET DESCRIPTION='Ethnicity' WHERE ENTITY_ID=19;
UPDATE LOOKUP_LABEL SET ENTITY_NAME='Ethnicity' WHERE LABEL_ID=37;

UPDATE LOOKUP_ENTITY SET DESCRIPTION='Citizenship' WHERE ENTITY_ID=18;
UPDATE LOOKUP_LABEL SET ENTITY_NAME='Citizenship' WHERE LABEL_ID=35;

UPDATE LOOKUP_LABEL SET ENTITY_NAME='Address 3' WHERE LABEL_ID=160;

UPDATE LOOKUP_ENTITY SET DESCRIPTION='Interest' WHERE ENTITY_ID=81;
UPDATE LOOKUP_ENTITY SET DESCRIPTION='Interest' WHERE ENTITY_ID=88;
UPDATE LOOKUP_LABEL SET ENTITY_NAME='Interest' WHERE LABEL_ID=164;
UPDATE LOOKUP_LABEL SET ENTITY_NAME='Interest' WHERE LABEL_ID=172;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Loan Amount+Interest' WHERE LOOKUP_VALUE_ID=275;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Interest' WHERE LOOKUP_VALUE_ID=277;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Interest' WHERE LOOKUP_VALUE_ID=395;
UPDATE COA SET COA_NAME='Interest' WHERE COA_ID=45;


UPDATE LOOKUP_LABEL SET ENTITY_NAME='Center' WHERE LABEL_ID=21;
UPDATE LOOKUP_LABEL SET ENTITY_NAME='Meeting Time for Center' WHERE LABEL_ID=112;
UPDATE LOOKUP_LABEL SET ENTITY_NAME='Distance from BO to Center' WHERE LABEL_ID=114;
UPDATE LOOKUP_LABEL SET ENTITY_NAME='Number of Clients per Center' WHERE LABEL_ID=120;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Center Manager' WHERE LOOKUP_VALUE_ID=114;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Centers' WHERE LOOKUP_VALUE_ID=137;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Center' WHERE LOOKUP_VALUE_ID=164;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Center Leader' WHERE LOOKUP_VALUE_ID=347;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Center Secretary' WHERE LOOKUP_VALUE_ID=349;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can edit Center Clientship' WHERE LOOKUP_VALUE_ID=771;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Centers' WHERE LOOKUP_VALUE_ID=777;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can create new Center ' WHERE LOOKUP_VALUE_ID=778;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can modify Center information ' WHERE LOOKUP_VALUE_ID=779;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can edit Center status' WHERE LOOKUP_VALUE_ID=780;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can make payments to Center accounts' WHERE LOOKUP_VALUE_ID=781;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can make adjustment entries to Center account' WHERE LOOKUP_VALUE_ID=782;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can remove fee types from Center account' WHERE LOOKUP_VALUE_ID=785;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can add notes to Center records' WHERE LOOKUP_VALUE_ID=786;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Center' WHERE LOOKUP_VALUE_ID=837;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can view Center Summary Report' WHERE LOOKUP_VALUE_ID=862;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can view Center Meeting Schedule' WHERE LOOKUP_VALUE_ID=868;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can apply charges to Center accounts' WHERE LOOKUP_VALUE_ID=906;
UPDATE REPORT_CATEGORY SET REPORT_CATEGORY_VALUE='Center' WHERE REPORT_CATEGORY_ID=3;
UPDATE REPORT SET REPORT_NAME='Center Summary Report' WHERE REPORT_ID=15;
UPDATE REPORT SET REPORT_NAME='Center Meeting Schedule' WHERE REPORT_ID=26;
UPDATE REPORT_JASPER_MAP SET REPORT_NAME='Center Summary Report' WHERE REPORT_ID=15;
UPDATE REPORT_JASPER_MAP SET REPORT_NAME='Center Meeting Schedule' WHERE REPORT_ID=26;

UPDATE DATABASE_VERSION SET DATABASE_VERSION=105 WHERE DATABASE_VERSION=104;