INSERT INTO LOOKUP_VALUE VALUES(570,87,' ');
INSERT INTO LOOKUP_VALUE_LOCALE VALUES(915,1,570,'Can reverse Loan disbursals');
INSERT INTO ACTIVITY(ACTIVITY_ID,PARENT_ID,ACTIVITY_NAME_LOOKUP_ID,DESCRIPTION_LOOKUP_ID) VALUES(202,99,570,570);
INSERT INTO ROLES_ACTIVITY VALUES (202,1);

INSERT INTO LOOKUP_VALUE VALUES(571,70,' ');
INSERT INTO LOOKUP_VALUE_LOCALE VALUES(916,1,571,'Loan reversal');
INSERT INTO ACCOUNT_STATE_FLAG(FLAG_ID,LOOKUP_ID,STATUS_ID,FLAG_DESCRIPTION,RETAIN_FLAG) VALUES(7,571,10,'Loan reversal',0);

INSERT INTO LOOKUP_VALUE VALUES(572,69,' ');
INSERT INTO LOOKUP_VALUE_LOCALE VALUES(917,1,572,'Loan Reversal');
INSERT INTO ACCOUNT_ACTION(ACCOUNT_ACTION_ID,LOOKUP_ID) VALUES(18,572);

INSERT INTO LOOKUP_VALUE VALUES(573,69,' ');
INSERT INTO LOOKUP_VALUE_LOCALE VALUES(918,1,573,'Disrbursal amount Reversal');
INSERT INTO ACCOUNT_ACTION(ACCOUNT_ACTION_ID,LOOKUP_ID) VALUES(19,573);

update DATABASE_VERSION set DATABASE_VERSION = 102 where DATABASE_VERSION = 101;