CREATE TABLE PPI_SURVEY (
  COUNTRY_ID INTEGER AUTO_INCREMENT NOT NULL,
  SURVEY_ID INTEGER NOT NULL,
  VERY_POOR_MIN INTEGER NOT NULL,
  VERY_POOR_MAX INTEGER NOT NULL,
  POOR_MIN INTEGER NOT NULL,
  POOR_MAX INTEGER NOT NULL,
  AT_RISK_MIN INTEGER NOT NULL,
  AT_RISK_MAX INTEGER NOT NULL,
  NON_POOR_MIN INTEGER NOT NULL,
  NON_POOR_MAX INTEGER NOT NULL,
  PRIMARY KEY(COUNTRY_ID),
  FOREIGN KEY(SURVEY_ID)
    REFERENCES SURVEY(SURVEY_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

ALTER TABLE QUESTION_CHOICES ADD COLUMN PPI VARCHAR(1) NOT NULL;
ALTER TABLE QUESTION_CHOICES ADD COLUMN PPI_POINTS INTEGER;

update DATABASE_VERSION set DATABASE_VERSION = 134 where DATABASE_VERSION = 133;