package org.mifos.framework.util.helpers;


public enum ConversionError  {
	EXCEEDING_NUMBER_OF_DIGITS_BEFORE_DECIMAL_SEPARATOR_FOR_MONEY, 
	EXCEEDING_NUMBER_OF_DIGITS_AFTER_DECIMAL_SEPARATOR_FOR_MONEY,
	EXCEEDING_NUMBER_OF_DIGITS_BEFORE_DECIMAL_SEPARATOR_FOR_INTEREST, 
	EXCEEDING_NUMBER_OF_DIGITS_AFTER_DECIMAL_SEPARATOR_FOR_INTEREST, 
	INTEREST_OUT_OF_RANGE, 
	NOT_ALL_NUMBER,
	CONVERSION_ERROR,
	NO_ERROR;

}



