CREATE TABLE FOO (
FOO_ID INTEGER AUTO INCREMENTNOT NULL,
Description VARCHAR(25),
PRIMARY KEY(FOO_ID)

)
ENGINE=InnoDB CHARACTER SET utf8;

INSERT INTO FOO VALUES(1, 'BAR');
INSERT INTO FOO VALUES(2, 'BAZ');
