/* Data for Grameen Koota.
   This just has data (DML) not schema changes (DDL).  The latter we
     want to avoid doing specific to one deployment.
   This file seems to have some customization, and some rules for
     how certain fields are computed(?).
*/

UPDATE CUSTOMER_ATTENDANCE_TYPES SET DESCRIPTION = "Leave" WHERE ATTENDANCE_ID = 3;
UPDATE CUSTOMER_ATTENDANCE_TYPES SET DESCRIPTION = "Late Present" WHERE ATTENDANCE_ID = 4;

UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = "A" WHERE LOOKUP_ID = 195;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = "L" WHERE LOOKUP_ID = 196;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE = "LP" WHERE LOOKUP_ID = 197;

INSERT INTO LOAN_PERF_HISTORY(ACCOUNT_ID)
SELECT LA.ACCOUNT_ID FROM LOAN_ACCOUNT LA WHERE LA.ACCOUNT_ID NOT IN
(SELECT ACCOUNT_ID FROM LOAN_PERF_HISTORY);

UPDATE LOAN_PERF_HISTORY LPH SET LPH.NO_OF_PAYMENTS =
(SELECT COUNT(*)  FROM LOAN_ACCOUNT LA, LOAN_SCHEDULE LS
WHERE LA.ACCOUNT_ID=LS.ACCOUNT_ID AND
LS.PAYMENT_STATUS=1 AND LPH.ACCOUNT_ID=LA.ACCOUNT_ID
GROUP BY LS.ACCOUNT_ID) WHERE LPH.NO_OF_PAYMENTS IS NULL;

UPDATE LOAN_PERF_HISTORY LPH SET LPH. LOAN_MATURITY_DATE=
(SELECT LS.ACTION_DATE FROM LOAN_ACCOUNT LA, LOAN_SCHEDULE LS, ACCOUNT A WHERE
LA.ACCOUNT_ID=LS.ACCOUNT_ID AND
A.ACCOUNT_ID=LA.ACCOUNT_ID AND
LS.INSTALLMENT_ID=LA.NO_OF_INSTALLMENTS
AND A.ACCOUNT_STATE_ID NOT IN (1,2,3,4,10) AND
LPH.ACCOUNT_ID=LA.ACCOUNT_ID);


UPDATE LOAN_PERF_HISTORY LPH SET LPH.NO_OF_PAYMENTS = 0 WHERE LPH.NO_OF_PAYMENTS IS NULL;


INSERT INTO GROUP_PERF_HISTORY(CUSTOMER_ID,NO_OF_CLIENTS,LAST_GROUP_LOAN_AMNT_DISB_CURRENCY_ID,AVG_LOAN_SIZE_CURRENCY_ID,
TOTAL_OUTSTAND_LOAN_AMNT_CURRENCY_ID, TOTAL_SAVINGS_AMNT_CURRENCY_ID,AVG_LOAN_SIZE,TOTAL_OUTSTAND_LOAN_AMNT,PORTFOLIO_AT_RISK,PORTFOLIO_AT_RISK_CURRENCY_ID,TOTAL_SAVINGS_AMNT)
SELECT C.CUSTOMER_ID,0,2,2,2,2,0,0,0,2,0 FROM CUSTOMER C WHERE C.CUSTOMER_LEVEL_ID=2 AND
C.CUSTOMER_ID NOT IN
(SELECT CUSTOMER_ID FROM GROUP_PERF_HISTORY);

UPDATE GROUP_PERF_HISTORY GPF SET GPF.LAST_GROUP_LOAN_AMNT_DISB = (
SELECT LA.LOAN_AMOUNT FROM LOAN_ACCOUNT LA, ACCOUNT A,ACCOUNT_PAYMENT
AP WHERE
AP.PAYMENT_ID = (SELECT MAX(AP.PAYMENT_ID) ID FROM CUSTOMER C,ACCOUNT
A,ACCOUNT_PAYMENT AP,ACCOUNT_TRXN AT WHERE
C.CUSTOMER_LEVEL_ID=2 AND
A.CUSTOMER_ID=C.CUSTOMER_ID AND
A.ACCOUNT_TYPE_ID=1 AND
A.ACCOUNT_STATE_ID NOT IN (1,2,3,4,10) AND
A.ACCOUNT_ID=AP.ACCOUNT_ID AND
AT.ACCOUNT_ID=A.ACCOUNT_ID AND
AT.ACCOUNT_ACTION_ID=10 AND
GPF.CUSTOMER_ID=A.CUSTOMER_ID)
AND
AP.ACCOUNT_ID=LA.ACCOUNT_ID AND
A.ACCOUNT_ID=LA.ACCOUNT_ID AND
GPF.CUSTOMER_ID=A.CUSTOMER_ID) WHERE GPF.LAST_GROUP_LOAN_AMNT_DISB IS NULL;


UPDATE GROUP_PERF_HISTORY GPF SET GPF.LAST_GROUP_LOAN_AMNT_DISB = 0  WHERE GPF.LAST_GROUP_LOAN_AMNT_DISB IS NULL;


INSERT INTO CLIENT_PERF_HISTORY(CUSTOMER_ID,LAST_LOAN_AMNT_CURRENCY_ID, TOTAL_SAVINGS_AMNT_CURRENCY_ID, TOTAL_SAVINGS_AMNT,DELINQUINT_PORTFOLIO,DELINQUINT_PORTFOLIO_CURRENCY_ID)
SELECT C.CUSTOMER_ID,2,2,0,0,2 FROM CUSTOMER C WHERE C.CUSTOMER_LEVEL_ID=1 AND
C.CUSTOMER_ID NOT IN
(SELECT CUSTOMER_ID FROM CLIENT_PERF_HISTORY);

UPDATE CLIENT_PERF_HISTORY CPH SET CPH.LAST_LOAN_AMNT=
(SELECT AP.AMOUNT FROM ACCOUNT_PAYMENT AP,ACCOUNT A WHERE AP.PAYMENT_ID=
(SELECT MAX(PAYMENT_ID) FROM CUSTOMER C,ACCOUNT A,ACCOUNT_PAYMENT AP WHERE
C.CUSTOMER_LEVEL_ID=1 AND
A.CUSTOMER_ID=C.CUSTOMER_ID AND
A.ACCOUNT_TYPE_ID=1 AND
A.ACCOUNT_STATE_ID=6 AND
AP.ACCOUNT_ID=A.ACCOUNT_ID AND
CPH.CUSTOMER_ID=C.CUSTOMER_ID)
AND A.ACCOUNT_ID=AP.ACCOUNT_ID
AND A.CUSTOMER_ID=CPH.CUSTOMER_ID) WHERE CPH.LAST_LOAN_AMNT IS NULL;


UPDATE CLIENT_PERF_HISTORY CPH SET CPH.TOTAL_ACTIVE_LOANS =
(SELECT COUNT(*) FROM LOAN_ACCOUNT LA, ACCOUNT A WHERE
A.ACCOUNT_TYPE_ID=1 AND
A.ACCOUNT_STATE_ID IN (5,9) AND
A.ACCOUNT_ID=LA.ACCOUNT_ID AND
CPH.CUSTOMER_ID=A.CUSTOMER_ID) WHERE CPH.TOTAL_ACTIVE_LOANS IS NULL;


UPDATE CLIENT_PERF_HISTORY CPH SET CPH.LAST_LOAN_AMNT=0
WHERE CPH.LAST_LOAN_AMNT IS NULL;

UPDATE CLIENT_PERF_HISTORY CPH SET CPH.TOTAL_ACTIVE_LOANS =0
WHERE CPH.TOTAL_ACTIVE_LOANS IS NULL;
 
INSERT INTO LOAN_COUNTER(LOAN_OFFERING_ID,CLIENT_PERF_ID,LOAN_CYCLE_COUNTER)
SELECT LA.PRD_OFFERING_ID, CPH.ID , COUNT(*) FROM ACCOUNT A, LOAN_ACCOUNT LA,CLIENT_PERF_HISTORY CPH
WHERE A.ACCOUNT_ID=LA.ACCOUNT_ID AND
A.CUSTOMER_ID=CPH.CUSTOMER_ID AND
A.ACCOUNT_STATE_ID IN (5,6,9,10) GROUP BY LA.PRD_OFFERING_ID,CPH.ID; 
