ALTER TABLE LOAN_OFFERING MODIFY COLUMN PENALTY_GRACE SMALLINT;
ALTER TABLE LOAN_OFFERING MODIFY COLUMN PENALTIES_GLCODE_ID SMALLINT;

ALTER TABLE ROLE DROP COLUMN DESCRIPTION;
ALTER TABLE ROLE MODIFY COLUMN ROLE_NAME VARCHAR(50) NOT NULL;
ALTER TABLE ROLES_ACTIVITY DROP COLUMN VERSION_NO;

ALTER TABLE SCHEDULED_TASKS ADD COLUMN STARTTIME TIMESTAMP;
ALTER TABLE SCHEDULED_TASKS ADD COLUMN ENDTIME TIMESTAMP;
ALTER TABLE SCHEDULED_TASKS ADD COLUMN STATUS SMALLINT;
ALTER TABLE SCHEDULED_TASKS DROP COLUMN TIME;