insert into INTEREST_TYPES values (2, 80, 1, 'Declining');

INSERT INTO LOOKUP_VALUE VALUES(561,87,' ');
INSERT INTO LOOKUP_VALUE VALUES(562,87,' ');
INSERT INTO LOOKUP_VALUE VALUES(563,87,' ');
INSERT INTO LOOKUP_VALUE VALUES(564,87,' ');
INSERT INTO LOOKUP_VALUE VALUES(565,87,' ');

INSERT INTO LOOKUP_VALUE_LOCALE VALUES(899,1,561,'Can modify lateness/dormancy definition');
INSERT INTO LOOKUP_VALUE_LOCALE VALUES(900,1,562,'Can modify office hierarchy');
INSERT INTO LOOKUP_VALUE_LOCALE VALUES(901,1,563,'Can Add Notes to Personnel');
INSERT INTO LOOKUP_VALUE_LOCALE VALUES(902,1,564,'Bulk');
INSERT INTO LOOKUP_VALUE_LOCALE VALUES(903,1,565,'Can Enter Collection Sheet Data');


INSERT INTO ACTIVITY(ACTIVITY_ID,PARENT_ID,ACTIVITY_NAME_LOOKUP_ID,DESCRIPTION_LOOKUP_ID)
VALUES(195,90,561,561);
INSERT INTO ACTIVITY(ACTIVITY_ID,PARENT_ID,ACTIVITY_NAME_LOOKUP_ID,DESCRIPTION_LOOKUP_ID)
VALUES(193,13,562,562 );
INSERT INTO ACTIVITY(ACTIVITY_ID,PARENT_ID,ACTIVITY_NAME_LOOKUP_ID,DESCRIPTION_LOOKUP_ID)
VALUES(194,18,563,563 );
INSERT INTO ACTIVITY(ACTIVITY_ID,PARENT_ID,ACTIVITY_NAME_LOOKUP_ID,DESCRIPTION_LOOKUP_ID)
VALUES(196,null,564,564 );
INSERT INTO ACTIVITY(ACTIVITY_ID,PARENT_ID,ACTIVITY_NAME_LOOKUP_ID,DESCRIPTION_LOOKUP_ID)
VALUES(197,196,565,565 );

UPDATE ACTIVITY SET PARENT_ID=196 WHERE ACTIVITY_ID=192;

INSERT INTO ROLES_ACTIVITY VALUES (193,1);
INSERT INTO ROLES_ACTIVITY VALUES (194,1);
INSERT INTO ROLES_ACTIVITY VALUES (195,1);
INSERT INTO ROLES_ACTIVITY VALUES (197,1);

DELETE from LOOKUP_VALUE_LOCALE where LOOKUP_VALUE_ID = 744;
DELETE from LOOKUP_VALUE_LOCALE where LOOKUP_VALUE_ID = 766;
DELETE from LOOKUP_VALUE_LOCALE where LOOKUP_VALUE_ID = 783;
DELETE from LOOKUP_VALUE_LOCALE where LOOKUP_VALUE_ID = 815;
DELETE from LOOKUP_VALUE_LOCALE where LOOKUP_VALUE_ID = 806;
DELETE from LOOKUP_VALUE_LOCALE where LOOKUP_VALUE_ID = 810;
DELETE from LOOKUP_VALUE_LOCALE where LOOKUP_VALUE_ID = 811;

DELETE from ROLES_ACTIVITY where ACTIVITY_ID = 45;
DELETE from ROLES_ACTIVITY where ACTIVITY_ID = 67;
DELETE from ROLES_ACTIVITY where ACTIVITY_ID = 84;
DELETE from ROLES_ACTIVITY where ACTIVITY_ID = 117;
DELETE from ROLES_ACTIVITY where ACTIVITY_ID = 107;
DELETE from ROLES_ACTIVITY where ACTIVITY_ID = 111;
DELETE from ROLES_ACTIVITY where ACTIVITY_ID = 112;

DELETE from ACTIVITY where ACTIVITY_ID = 45;
DELETE from ACTIVITY where ACTIVITY_ID = 67;
DELETE from ACTIVITY where ACTIVITY_ID = 84;
DELETE from ACTIVITY where ACTIVITY_ID = 117;
DELETE from ACTIVITY where ACTIVITY_ID = 107;
DELETE from ACTIVITY where ACTIVITY_ID = 111;
DELETE from ACTIVITY where ACTIVITY_ID = 112;

DELETE from LOOKUP_VALUE where LOOKUP_ID = 406;
DELETE from LOOKUP_VALUE where LOOKUP_ID = 428;
DELETE from LOOKUP_VALUE where LOOKUP_ID = 445;
DELETE from LOOKUP_VALUE where LOOKUP_ID = 477;
DELETE from LOOKUP_VALUE where LOOKUP_ID = 468;
DELETE from LOOKUP_VALUE where LOOKUP_ID = 472;
DELETE from LOOKUP_VALUE where LOOKUP_ID = 473;

UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can waive a due amount' where LOOKUP_VALUE_ID = 745;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can waive a due amount' where LOOKUP_VALUE_ID = 767;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can waive a due amount' where LOOKUP_VALUE_ID = 784;
/* The table Personnelcustom field contains the additional information of the default user  - Configuration */
INSERT INTO PERSONNEL_CUSTOM_FIELD (FIELD_ID,PERSONNEL_ID,FIELD_VALUE)
VALUES(9,1,'');

DELETE from LOOKUP_VALUE_LOCALE where LOOKUP_VALUE_ID = 378;
DELETE from LOOKUP_VALUE where LOOKUP_ID = 190;

INSERT INTO OFFICE_CUSTOM_FIELD (OFFICE_ID,FIELD_ID,FIELD_VALUE) VALUES(1,10,'');
INSERT INTO OFFICE_CUSTOM_FIELD (OFFICE_ID,FIELD_ID,FIELD_VALUE) VALUES(1,11,'');
INSERT INTO OFFICE_CUSTOM_FIELD (OFFICE_ID,FIELD_ID,FIELD_VALUE) VALUES(1,12,'');
INSERT INTO OFFICE_CUSTOM_FIELD (OFFICE_ID,FIELD_ID,FIELD_VALUE) VALUES(1,13,'');

INSERT INTO LOOKUP_VALUE VALUES(566,87,' ');
INSERT INTO LOOKUP_VALUE VALUES(567,87,' ');
INSERT INTO LOOKUP_VALUE VALUES(568,87,' ');

INSERT INTO LOOKUP_VALUE_LOCALE VALUES(904,1,566,'Can apply charges to member accounts');
INSERT INTO LOOKUP_VALUE_LOCALE VALUES(905,1,567,'Can apply charges to group accounts');
INSERT INTO LOOKUP_VALUE_LOCALE VALUES(906,1,568,'Can apply charges to kendra accounts');

INSERT INTO ACTIVITY(ACTIVITY_ID,PARENT_ID,ACTIVITY_NAME_LOOKUP_ID,DESCRIPTION_LOOKUP_ID)
VALUES(198,34,566,566 );
INSERT INTO ACTIVITY(ACTIVITY_ID,PARENT_ID,ACTIVITY_NAME_LOOKUP_ID,DESCRIPTION_LOOKUP_ID)
VALUES(199,56,567,567 );
INSERT INTO ACTIVITY(ACTIVITY_ID,PARENT_ID,ACTIVITY_NAME_LOOKUP_ID,DESCRIPTION_LOOKUP_ID)
VALUES(200,78,568,568 );

INSERT INTO ROLES_ACTIVITY VALUES (198,1);
INSERT INTO ROLES_ACTIVITY VALUES (199,1);
INSERT INTO ROLES_ACTIVITY VALUES (200,1);


UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can change state to partial application' WHERE LOOKUP_VALUE_ID=758;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can change state to active' WHERE LOOKUP_VALUE_ID=737;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can change state to active' WHERE LOOKUP_VALUE_ID=873;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can change state to active' WHERE LOOKUP_VALUE_ID=759;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can change state to application pending approval' WHERE LOOKUP_VALUE_ID=741;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can change state to application pending approval' WHERE LOOKUP_VALUE_ID=763;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can edit office membership' WHERE LOOKUP_VALUE_ID=772;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can edit group membership' WHERE LOOKUP_VALUE_ID=749;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can edit office membership' WHERE LOOKUP_VALUE_ID=750;

/*
  Assigning the LOOKUP_VALUE_ID, as in the following, is the right thing
  when there might be locally customized lookup values.  But LatestTest
  isn't flexible enough to consider this OK (because 912 and 913 are
  not the next two values).
  INSERT INTO LOOKUP_VALUE_LOCALE(LOCALE_ID, LOOKUP_ID, LOOKUP_VALUE) 
    VALUES(1,179,'Voucher')
  INSERT INTO LOOKUP_VALUE_LOCALE(LOCALE_ID, LOOKUP_ID, LOOKUP_VALUE) 
    VALUES(1,180,'Cheque')
*/
INSERT INTO LOOKUP_VALUE_LOCALE VALUES(912,1,179,'Voucher');
INSERT INTO LOOKUP_VALUE_LOCALE VALUES(913,1,180,'Cheque');

INSERT INTO PAYMENT_TYPE(PAYMENT_TYPE_ID,PAYMENT_TYPE_LOOKUP_ID) VALUES(2,179);
INSERT INTO PAYMENT_TYPE(PAYMENT_TYPE_ID,PAYMENT_TYPE_LOOKUP_ID) VALUES(3,180);
