INSERT INTO FUND_CODE(FUNDCODE_ID,FUNDCODE_VALUE) VALUES(1,'00');
INSERT INTO FUND_CODE(FUNDCODE_ID,FUNDCODE_VALUE) VALUES(2,'01');
INSERT INTO FUND_CODE(FUNDCODE_ID,FUNDCODE_VALUE) VALUES(3,'02');
INSERT INTO FUND_CODE(FUNDCODE_ID,FUNDCODE_VALUE) VALUES(4,'03');
INSERT INTO FUND_CODE(FUNDCODE_ID,FUNDCODE_VALUE) VALUES(5,'04');

INSERT INTO FUND(FUND_ID,FUNDCODE_ID,FUND_NAME,VERSION_NO)
VALUES(1,1,'Non Donor',0);
INSERT INTO FUND(FUND_ID,FUNDCODE_ID,FUND_NAME,VERSION_NO)
VALUES(2,1,'Funding Org A',0);
INSERT INTO FUND(FUND_ID,FUNDCODE_ID,FUND_NAME,VERSION_NO)
VALUES(3,1,'Funding Org B',0);
INSERT INTO FUND(FUND_ID,FUNDCODE_ID,FUND_NAME,VERSION_NO)
VALUES(4,1,'Funding Org C',0);
INSERT INTO FUND(FUND_ID,FUNDCODE_ID,FUND_NAME,VERSION_NO)
VALUES(5,1,'Funding Org D',0);

DELETE FROM CUSTOM_FIELD_DEFINITION WHERE ENTITY_ID=10;

UPDATE LOOKUP_ENTITY SET ENTITY_NAME='PovertyStatus' WHERE ENTITY_ID=10;
UPDATE LOOKUP_ENTITY SET DESCRIPTION='Poverty Status For Client' WHERE ENTITY_ID=10;

UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Very poor' WHERE LOOKUP_ID=41 AND LOCALE_ID=1;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Poor' WHERE LOOKUP_ID=42 AND LOCALE_ID=1;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Non-poor' WHERE LOOKUP_ID=43 AND LOCALE_ID=1;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can waive due deposits for margin money account' WHERE LOOKUP_ID=551 AND LOCALE_ID=1;
UPDATE LOOKUP_VALUE_LOCALE SET LOOKUP_VALUE='Can waive over due deposits for margin money account' WHERE LOOKUP_ID=552 AND LOCALE_ID=1;

INSERT INTO FIELD_CONFIGURATION(FIELD_CONFIG_ID,FIELD_NAME,ENTITY_ID,MANDATORY_FLAG,HIDDEN_FLAG)
VALUES(73,'PovertyStatus',1,1,0);

UPDATE ACTIVITY SET DESCRIPTION_LOOKUP_ID=ACTIVITY_NAME_LOOKUP_ID WHERE DESCRIPTION_LOOKUP_ID=539;
