/* Tables removed from latest-schema.sql should be added here */
DROP TABLE IF EXISTS collateral_type;
DROP TABLE IF EXISTS logmessages;
DROP TABLE IF EXISTS mis_bank;
DROP TABLE IF EXISTS mis_bankbranch;
DROP TABLE IF EXISTS mis_geographicalarea;
DROP TABLE IF EXISTS mis_geographicalareatype;
DROP TABLE IF EXISTS mis_shgmemberprofile;
DROP TABLE IF EXISTS mis_shgprofile;

DROP TABLE IF EXISTS COLL_SHEET_SAVINGS_DETAILS;
DROP TABLE IF EXISTS COLL_SHEET_LOAN_DETAILS;
DROP TABLE IF EXISTS COLL_SHEET_CUSTOMER;
DROP TABLE IF EXISTS COLL_SHEET;
