DROP TABLE IF EXISTS PRD_OFFERING_MIX;

DROP TABLE IF EXISTS CUSTOMER_FAMILY_DETAIL;

DROP TABLE IF EXISTS PPI_LIKELIHOODS;
DROP TABLE IF EXISTS PPI_SURVEY;
DROP TABLE IF EXISTS SURVEY_RESPONSE_DATE;
DROP TABLE IF EXISTS SURVEY_RESPONSE_NUMBER;
DROP TABLE IF EXISTS SURVEY_RESPONSE_FREETEXT;
DROP TABLE IF EXISTS SURVEY_RESPONSE;
DROP TABLE IF EXISTS QUESTION_CHOICES;
DROP TABLE IF EXISTS SURVEY_RESPONSE_CHOICE;
DROP TABLE IF EXISTS SURVEY_QUESTIONS;
DROP TABLE IF EXISTS QUESTIONS;
DROP TABLE IF EXISTS PPI_SURVEY_INSTANCE;
DROP TABLE IF EXISTS SURVEY_INSTANCE;
DROP TABLE IF EXISTS SURVEY;

DROP TABLE IF EXISTS  FINANCIAL_TRXN;
DROP TABLE IF EXISTS  COAHIERARCHY;
DROP TABLE IF EXISTS  FINANCIAL_ACTION;
DROP TABLE IF EXISTS  COA_IDMAPPER;
DROP TABLE IF EXISTS  COA;

DROP TABLE IF EXISTS CUSTOMER_ATTENDANCE;

DROP TABLE IF EXISTS PRODUCT_OFFERING_MANDATORY_SAVINGS;
DROP TABLE IF EXISTS PRD_OFFERING_MEETING;

DROP TABLE IF EXISTS CUSTOMER_LOAN_ACCOUNT_DETAIL;

DROP TABLE IF EXISTS LOAN_TRXN_DETAIL;

DROP TABLE IF EXISTS SAVINGS_TRXN_DETAIL;

DROP TABLE IF EXISTS CUSTOMER_TRXN_DETAIL;

DROP TABLE IF EXISTS LOAN_ARREARS_AGING;

DROP TABLE IF EXISTS ACCOUNT_FEES_ACTION_DETAIL;

DROP TABLE IF EXISTS LOAN_FEE_SCHEDULE;

DROP TABLE IF EXISTS CUSTOMER_FEE_SCHEDULE;

DROP TABLE IF EXISTS FEE_TRXN_DETAIL;

DROP TABLE IF EXISTS ACCOUNT_TRXN;

DROP TABLE IF EXISTS SAVINGS_ACTIVITY_DETAILS;

DROP TABLE IF EXISTS SAVINGS_ACCOUNT;

DROP TABLE IF EXISTS ACCOUNT_FEES;

DROP TABLE IF EXISTS CUSTOMER_CHECKLIST;

DROP TABLE IF EXISTS ACCOUNT_ACTIONS_DATE;

DROP TABLE IF EXISTS CUSTOMER_SCHEDULE;
DROP TABLE IF EXISTS LOAN_SCHEDULE;
DROP TABLE IF EXISTS SAVING_SCHEDULE;

DROP TABLE IF EXISTS ACCOUNT_SURVEY;

DROP TABLE IF EXISTS ACCOUNT_PAYMENT;

DROP TABLE IF EXISTS PRD_CHECKLIST;

DROP TABLE IF EXISTS LOAN_PENALTY;

DROP TABLE IF EXISTS CHECKLIST_DETAIL;

DROP TABLE IF EXISTS ATTENDANCE;

DROP TABLE IF EXISTS CUSTOMER_ACCOUNT_ACTIVITY;

DROP TABLE IF EXISTS CUSTOMER_ACCOUNT;

DROP TABLE IF EXISTS CHANGE_LOG_DETAIL;

DROP TABLE IF EXISTS LOAN_SUMMARY;

DROP TABLE IF EXISTS WAIVE_OFF_HISTORY;

DROP TABLE IF EXISTS ACCOUNT_NON_TRXN_DETAILS;

DROP TABLE IF EXISTS LOAN_ACTIVITY_DETAILS;

DROP TABLE IF EXISTS LOAN_PERF_HISTORY;

DROP TABLE IF EXISTS MAX_MIN_NO_OF_INSTALL;

DROP TABLE IF EXISTS MAX_MIN_LOAN_AMOUNT;

DROP TABLE IF EXISTS LOAN_ACCOUNT;

DROP TABLE IF EXISTS CUSTOMER_MOVEMENT;

DROP TABLE IF EXISTS ACCOUNT_NOTES;

DROP TABLE IF EXISTS ACCOUNT_FLAG_DETAIL;

DROP TABLE IF EXISTS ACCOUNT_STATUS_CHANGE_HISTORY;

DROP TABLE IF EXISTS ACCOUNT_STATE_FLAG;

DROP TABLE IF EXISTS ACCOUNT_ACTIVITY;

DROP TABLE IF EXISTS SAVINGS_PERFORMANCE;

DROP TABLE IF EXISTS ACCOUNT_CUSTOM_FIELD;

DROP TABLE IF EXISTS ACCOUNT;

DROP TABLE IF EXISTS CHECKLIST;
DROP TABLE IF EXISTS SPOUSE_FATHER_LOOKUP;
DROP TABLE IF EXISTS CUSTOMER_ATTENDANCE_TYPES;
DROP TABLE IF EXISTS CUSTOMER_NAME_DETAIL;

DROP TABLE IF EXISTS CUSTOMER_FLAG_DETAIL;

DROP TABLE IF EXISTS CUSTOMER_HIERARCHY;

DROP TABLE IF EXISTS OFFICE_HIERARCHY;

-- DROP TABLE IF EXISTS PRD_SURVEY;

DROP TABLE IF EXISTS PRD_FEE_FREQUENCY;

DROP TABLE IF EXISTS CUSTOMER_POSITION;

DROP TABLE IF EXISTS CUSTOMER_NOTE;

DROP TABLE IF EXISTS LOAN_OFFERING_FUND;

DROP TABLE IF EXISTS CUSTOMER_PROGRAM;

DROP TABLE IF EXISTS CUSTOMER_MEETING_DETAIL;

DROP TABLE IF EXISTS INHERITED_MEETING;

DROP TABLE IF EXISTS CUSTOMER_MEETING;

DROP TABLE IF EXISTS RECUR_ON_DAY;

DROP TABLE IF EXISTS RECURRENCE_DETAIL;

DROP TABLE IF EXISTS FEE_FREQUENCY;

DROP TABLE IF EXISTS MEETING;

DROP TABLE IF EXISTS PERSONNEL_ROLE;
DROP TABLE IF EXISTS PERSONNEL_STATUS;
DROP TABLE IF EXISTS ROLES_ACTIVITY;

DROP TABLE IF EXISTS PERSONNEL_CUSTOM_FIELD;

DROP TABLE IF EXISTS PROGRAM_FUND;

DROP TABLE IF EXISTS PRD_OFFERING_FEES;

DROP TABLE IF EXISTS OFFERING_FUND;

DROP TABLE IF EXISTS CUSTOMER_CUSTOM_FIELD;

DROP TABLE IF EXISTS CUSTOMER_ADDRESS_DETAIL;

DROP TABLE IF EXISTS CUSTOMER_HISTORICAL_DATA;

DROP TABLE IF EXISTS CUSTOMER_PICTURE;

DROP TABLE IF EXISTS FIELD_CONFIGURATION;

DROP TABLE IF EXISTS CUSTOM_FIELD_DEFINITION;

DROP TABLE IF EXISTS ENTITY_MASTER;

DROP TABLE IF EXISTS SYSTEM_CONFIGURATION;

DROP TABLE IF EXISTS CONFIG_KEY_VALUE_INTEGER;

DROP TABLE IF EXISTS CHANGE_LOG;

DROP TABLE IF EXISTS PERSONNEL_NOTES;

DROP TABLE IF EXISTS PERSONNEL_MOVEMENT;

DROP TABLE IF EXISTS PERSONNEL_DETAILS;

DROP TABLE IF EXISTS INSURANCE_OFFERING;

DROP TABLE IF EXISTS SAVINGS_OFFERING;

DROP TABLE IF EXISTS NO_OF_INSTALL_SAME_FOR_ALL_LOAN;

DROP TABLE IF EXISTS LOAN_AMOUNT_SAME_FOR_ALL_LOAN;

DROP TABLE IF EXISTS NO_OF_INSTALL_FROM_LOAN_CYCLE ;

DROP TABLE IF EXISTS LOAN_AMOUNT_FROM_LOAN_CYCLE;

DROP TABLE IF EXISTS NO_OF_INSTALL_FROM_LAST_LOAN ;

DROP TABLE IF EXISTS LOAN_AMOUNT_FROM_LAST_LOAN ;

DROP TABLE IF EXISTS LOAN_OFFERING;

DROP TABLE IF EXISTS CLIENT_INITIAL_SAVINGS_OFFERING;

DROP TABLE IF EXISTS PRD_OFFERING;

DROP TABLE IF EXISTS CUSTOMER_DETAIL;

DROP TABLE IF EXISTS CUSTOMER_SURVEY;

DROP TABLE IF EXISTS CUST_PERF_HISTORY;

DROP TABLE IF EXISTS CLIENT_PERF_HISTORY;

DROP TABLE IF EXISTS GROUP_PERF_HISTORY;

DROP TABLE IF EXISTS CUSTOMER;

DROP TABLE IF EXISTS OFFICE_ACTION_PAYMENT_TYPE;

DROP TABLE IF EXISTS PENALTY;

DROP TABLE IF EXISTS ROLE;

DROP TABLE IF EXISTS PERSONNEL_HIERARCHY;

DROP TABLE IF EXISTS FEE_FREQUENCY_TYPE;
DROP TABLE IF EXISTS FEELEVEL;
DROP TABLE IF EXISTS FEES;
DROP TABLE IF EXISTS FEE_STATUS;
DROP TABLE IF EXISTS FEE_FORMULA_MASTER;
DROP TABLE IF EXISTS FEE_UPDATE_TYPE;

DROP TABLE IF EXISTS IMPORTED_TRANSACTIONS_FILES;

DROP TABLE IF EXISTS PERSONNEL;

DROP TABLE IF EXISTS PROGRAM;

DROP TABLE IF EXISTS CUSTOMER_STATE_FLAG;

DROP TABLE IF EXISTS LOOKUP_LABEL;

DROP TABLE IF EXISTS LOOKUP_VALUE_LOCALE;

DROP TABLE IF EXISTS BRANCH_HO_UPDATE;

DROP TABLE IF EXISTS HOLIDAY;
DROP TABLE IF EXISTS REPAYMENT_RULE;

DROP TABLE IF EXISTS MFI_ATTRIBUTE;

DROP TABLE IF EXISTS OFFICE_ADDRESS;

DROP TABLE IF EXISTS  OFFICE_CUSTOM_FIELD;

DROP TABLE IF EXISTS OFFICE;

DROP TABLE IF EXISTS OFFICE_STATUS;

DROP TABLE IF EXISTS OFFICE_CODE;


DROP TABLE IF EXISTS INTEREST_CALC_RULE;

DROP TABLE IF EXISTS FEE_PAYMENTS_CATEGORIES_TYPE;

DROP TABLE IF EXISTS SUPPORTED_LOCALE;

DROP TABLE IF EXISTS CUSTOMER_STATE;

DROP TABLE IF EXISTS INTEREST_TYPES;

DROP TABLE IF EXISTS PRD_STATUS;

DROP TABLE IF EXISTS PRD_PMNT_TYPE;

DROP TABLE IF EXISTS ACCEPTED_PAYMENT_TYPE;

DROP TABLE IF EXISTS ADMIN_DOCUMENT_ACC_STATE_MIX;

DROP TABLE IF EXISTS ACCOUNT_STATE;

DROP TABLE IF EXISTS CUSTOMER_LEVEL;

DROP TABLE IF EXISTS CATEGORY_TYPE;

DROP TABLE IF EXISTS POSITION;

DROP TABLE IF EXISTS PRD_CATEGORY;

DROP TABLE IF EXISTS PRD_APPLICABLE_MASTER;

DROP TABLE IF EXISTS OFFICE_LEVEL;

DROP TABLE IF EXISTS PERSONNEL_LEVEL;

DROP TABLE IF EXISTS SAVINGS_TYPE;

DROP TABLE IF EXISTS YES_NO_MASTER;

DROP TABLE IF EXISTS PRD_STATE;

DROP TABLE IF EXISTS PRD_CATEGORY_STATUS;

DROP TABLE IF EXISTS RECOMMENDED_AMNT_UNIT;

DROP TABLE IF EXISTS PRD_TYPE;

DROP TABLE IF EXISTS GRACE_PERIOD_TYPE;

DROP TABLE IF EXISTS INTEREST_CALCULATION_TYPES;

DROP TABLE IF EXISTS FUND;

DROP TABLE IF EXISTS FEE_PAYMENT;

DROP TABLE IF EXISTS FREQ_OF_DEPOSITS;

DROP TABLE IF EXISTS FEE_TYPE;

DROP TABLE IF EXISTS ACCOUNT_TYPE;







DROP TABLE IF EXISTS MEETING_TYPE;

DROP TABLE IF EXISTS FINANICAL_ACTION;

DROP TABLE IF EXISTS LANGUAGE;

DROP TABLE IF EXISTS ACCOUNT_ACTION;

DROP TABLE IF EXISTS SURVEY_TEMPLATE;

DROP TABLE IF EXISTS RECURRENCE_TYPE;

DROP TABLE IF EXISTS REPORT;
DROP TABLE IF EXISTS report_datasource;
DROP TABLE IF EXISTS report_parameter;
DROP TABLE IF EXISTS report_jasper_map;
DROP TABLE IF EXISTS REPORT_CATEGORY;
DROP TABLE IF EXISTS report_parameter_map;

DROP TABLE IF EXISTS ACTIVITY;

DROP TABLE IF EXISTS GL_CODE;

DROP TABLE IF EXISTS COUNTRY;

DROP TABLE IF EXISTS SUPPORTED_MODES;

DROP TABLE IF EXISTS TRANSACTION_TYPE;

DROP TABLE IF EXISTS PAYMENT_TYPE;

DROP TABLE IF EXISTS LOOKUP_VALUE;

DROP TABLE IF EXISTS LOOKUP_ENTITY;



DROP TABLE IF EXISTS SCHEDULED_TASKS;

DROP TABLE IF EXISTS TEMP_ID;

DROP TABLE IF EXISTS CURRENCY;

DROP TABLE IF EXISTS GLCODE;


DROP TABLE IF EXISTS FUND_CODE;

DROP TABLE IF EXISTS LOAN_COUNTER;
DROP TABLE IF EXISTS GROUP_LOAN_COUNTER;

DROP TABLE IF EXISTS LOAN_MONITORING;

DROP TABLE IF EXISTS ADMIN_DOCUMENT;

DROP TABLE IF EXISTS DATABASE_VERSION;

DROP TABLE IF EXISTS BATCH_CLIENT_SUMMARY;
DROP TABLE IF EXISTS BATCH_STAFF_SUMMARY;
DROP TABLE IF EXISTS BATCH_LOAN_ARREARS_AGING;
DROP TABLE IF EXISTS BATCH_STAFFING_LEVEL_SUMMARY;
DROP TABLE IF EXISTS BATCH_LOAN_DETAILS;
DROP TABLE IF EXISTS BATCH_LOAN_ARREARS_PROFILE;
DROP TABLE IF EXISTS BATCH_BRANCH_REPORT;

DROP TABLE IF EXISTS BATCH_BRANCH_CONFIRMATION_RECOVERY;
DROP TABLE IF EXISTS BATCH_BRANCH_CONFIRMATION_ISSUE;
DROP TABLE IF EXISTS BATCH_BRANCH_CONFIRMATION_DISBURSEMENT;
DROP TABLE IF EXISTS BATCH_BRANCH_CASH_CONFIRMATION_REPORT;





