ALTER TABLE REPORT_CATEGORY ADD COLUMN ACTIVITY_ID SMALLINT;
UPDATE REPORT SET ACTIVITY_ID = null;

UPDATE REPORT_CATEGORY SET ACTIVITY_ID=145 WHERE REPORT_CATEGORY_ID=1;
UPDATE REPORT_CATEGORY SET ACTIVITY_ID=148 WHERE REPORT_CATEGORY_ID=2;
UPDATE REPORT_CATEGORY SET ACTIVITY_ID=146 WHERE REPORT_CATEGORY_ID=3;
UPDATE REPORT_CATEGORY SET ACTIVITY_ID=149 WHERE REPORT_CATEGORY_ID=4;
UPDATE REPORT_CATEGORY SET ACTIVITY_ID=147 WHERE REPORT_CATEGORY_ID=5;
UPDATE REPORT_CATEGORY SET ACTIVITY_ID=150 WHERE REPORT_CATEGORY_ID=6;
UPDATE REPORT_CATEGORY SET ACTIVITY_ID=151 WHERE REPORT_CATEGORY_ID=7;



update DATABASE_VERSION set DATABASE_VERSION = 129 where DATABASE_VERSION = 128;