INSERT INTO FIELD_CONFIGURATION(FIELD_CONFIG_ID,FIELD_NAME,ENTITY_ID,MANDATORY_FLAG,HIDDEN_FLAG) VALUES(79,'City',15,0,0);

UPDATE DATABASE_VERSION SET DATABASE_VERSION = 229 WHERE DATABASE_VERSION = 228;