ALTER TABLE SURVEY_INSTANCE ADD COLUMN CREATING_OFFICER_ID SMALLINT NOT NULL;
ALTER TABLE QUESTIONS ADD COLUMN SHORT_NAME VARCHAR(50);

ALTER TABLE SURVEY_INSTANCE ADD FOREIGN KEY (CREATING_OFFICER_ID)
  REFERENCES PERSONNEL(PERSONNEL_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

update DATABASE_VERSION set DATABASE_VERSION = 131 where DATABASE_VERSION = 130;
