ALTER TABLE currency DROP COLUMN DISPLAY_SYMBOL;
ALTER TABLE currency DROP COLUMN DEFAULT_CURRENCY;
ALTER TABLE currency DROP COLUMN DEFAULT_DIGITS_AFTER_DECIMAL;

UPDATE DATABASE_VERSION SET DATABASE_VERSION = 228 WHERE DATABASE_VERSION = 227;
