CREATE TABLE IMPORTED_TRANSACTIONS_FILES 
( FILE_NAME VARCHAR(100) NOT NULL, 
  SUBMITTED_ON TIMESTAMP NOT NULL, 
  SUBMITTED_BY SMALLINT NOT NULL,
  PRIMARY KEY (FILE_NAME),
  FOREIGN KEY (SUBMITTED_BY) 
  REFERENCES PERSONNEL(PERSONNEL_ID) 
  ON DELETE NO ACTION 
  ON UPDATE NO ACTION
)ENGINE=InnoDB CHARACTER SET utf8;

UPDATE DATABASE_VERSION SET DATABASE_VERSION = 221 WHERE DATABASE_VERSION = 220;