DROP TABLE IF EXISTS PRD_PMNT_TYPE;

CREATE TABLE ACCEPTED_PAYMENT_TYPE (
  ACCEPTED_PAYMENT_TYPE_ID SMALLINT AUTO_INCREMENT NOT NULL,
  PAYMENT_TYPE_ID SMALLINT NOT NULL,
  ACCOUNT_ACTION_ID SMALLINT NOT NULL,
  VERSION_NO INTEGER NOT NULL,
  PRIMARY KEY(ACCEPTED_PAYMENT_TYPE_ID),
  FOREIGN KEY(PAYMENT_TYPE_ID)
    REFERENCES PAYMENT_TYPE(PAYMENT_TYPE_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(ACCOUNT_ACTION_ID)
    REFERENCES ACCOUNT_ACTION(ACCOUNT_ACTION_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)
ENGINE=InnoDB CHARACTER SET utf8;

update DATABASE_VERSION set DATABASE_VERSION = 139 where DATABASE_VERSION = 138;