UPDATE PRD_CATEGORY_STATUS SET PRD_CATEGORY_STATUS_ID = 2 WHERE PRD_CATEGORY_STATUS_ID = 0;
UPDATE PRD_CATEGORY SET STATE = 2 WHERE STATE = 0;

UPDATE DATABASE_VERSION SET DATABASE_VERSION = 215 WHERE DATABASE_VERSION = 214;
