-- Add column POVERTY_LHOOD_PCT DECIMAL(10,3)
-- See Mingle story 281
 

ALTER TABLE CUSTOMER_DETAIL
  ADD COLUMN POVERTY_LHOOD_PCT DECIMAL(10,3);
  
UPDATE DATABASE_VERSION SET DATABASE_VERSION = 184 WHERE DATABASE_VERSION = 183;
   
    

