UPDATE LOAN_FEE_SCHEDULE SET AMOUNT_PAID = 0 WHERE AMOUNT_PAID IS NULL;
UPDATE LOAN_FEE_SCHEDULE LFS SET AMOUNT_PAID_CURRENCY_ID = LFS.AMOUNT_CURRENCY_ID WHERE AMOUNT_PAID_CURRENCY_ID IS NULL;
ALTER TABLE LOAN_FEE_SCHEDULE MODIFY COLUMN AMOUNT_PAID DECIMAL(10,3) NOT NULL;
ALTER TABLE LOAN_FEE_SCHEDULE MODIFY COLUMN AMOUNT_PAID_CURRENCY_ID SMALLINT NOT NULL;

UPDATE DATABASE_VERSION SET DATABASE_VERSION = 235 WHERE DATABASE_VERSION = 234;
