ALTER TABLE CURRENCY ADD COLUMN CURRENCY_CODE VARCHAR(3);
UPDATE CURRENCY SET CURRENCY_CODE='USD' WHERE CURRENCY_ID=1;
UPDATE CURRENCY SET CURRENCY_CODE='INR' WHERE CURRENCY_ID=2;
UPDATE CURRENCY SET CURRENCY_CODE='EUR' WHERE CURRENCY_ID=3;
UPDATE CURRENCY SET CURRENCY_CODE='GBP' WHERE CURRENCY_ID=4;

UPDATE DATABASE_VERSION SET DATABASE_VERSION = 164 WHERE DATABASE_VERSION = 163;