CREATE TABLE EVENTS (
    ID INTEGER AUTO_INCREMENT NOT NULL,
    EVENT_NAME VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID)
)ENGINE=InnoDB CHARACTER SET utf8;

CREATE TABLE ENTITY_EVENTS (
    ID INTEGER AUTO_INCREMENT NOT NULL,
    ENTITY_TYPE_ID  SMALLINT NOT NULL,
    EVENT_ID INTEGER NOT NULL,
    DESCRIPTION VARCHAR(200) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (ENTITY_TYPE_ID) REFERENCES ENTITY_MASTER(ENTITY_TYPE_ID),
    FOREIGN KEY (EVENT_ID) REFERENCES EVENTS(ID)
)ENGINE=InnoDB CHARACTER SET utf8;

CREATE TABLE QUESTION_GROUP_ENTITY_EVENTS(
    ID INTEGER AUTO_INCREMENT NOT NULL,
    QUESTION_GROUP_ID INTEGER NOT NULL,
    ENTITY_EVENT_ID INTEGER NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (QUESTION_GROUP_ID) REFERENCES QUESTION_GROUP(ID),
    FOREIGN KEY (ENTITY_EVENT_ID) REFERENCES ENTITY_EVENTS(ID)
)ENGINE=InnoDB CHARACTER SET utf8;

UPDATE DATABASE_VERSION SET DATABASE_VERSION = 259 WHERE DATABASE_VERSION = 258;
