
ALTER TABLE LOAN_ACCOUNT ADD CONSTRAINT fk_loan_account FOREIGN KEY (PARENT_ACCOUNT_ID)
  REFERENCES LOAN_ACCOUNT(ACCOUNT_ID) ON DELETE NO ACTION  ON UPDATE NO ACTION;
  
UPDATE DATABASE_VERSION SET DATABASE_VERSION = 154 WHERE DATABASE_VERSION = 153;
  