SET FOREIGN_KEY_CHECKS=0;
ALTER TABLE loan_account DROP FOREIGN KEY fk_loan_rankday;
ALTER TABLE loan_account DROP INDEX fk_loan_rankday;
ALTER TABLE loan_account DROP FOREIGN KEY fk_loan_monthweek;
ALTER TABLE loan_account DROP INDEX fk_loan_monthweek;

ALTER TABLE recur_on_day DROP FOREIGN KEY recur_on_day_ibfk_2;
ALTER TABLE recur_on_day DROP INDEX DAYS;
ALTER TABLE recur_on_day DROP FOREIGN KEY recur_on_day_ibfk_3;
ALTER TABLE recur_on_day DROP INDEX RANK_OF_DAYS;

DELETE FROM lookup_value_locale 
WHERE LOOKUP_VALUE_ID = 143 
OR LOOKUP_VALUE_ID = 145 
OR LOOKUP_VALUE_ID = 147
OR LOOKUP_VALUE_ID = 149 
OR LOOKUP_VALUE_ID = 151
OR LOOKUP_VALUE_ID = 153 
OR LOOKUP_VALUE_ID = 155
OR LOOKUP_VALUE_ID = 179 
OR LOOKUP_VALUE_ID = 181 
OR LOOKUP_VALUE_ID = 183
OR LOOKUP_VALUE_ID = 185 
OR LOOKUP_VALUE_ID = 187;

DELETE FROM lookup_value 
WHERE LOOKUP_ID = 72
OR LOOKUP_ID = 73 
OR LOOKUP_ID = 74 
OR LOOKUP_ID = 75 
OR LOOKUP_ID = 76
OR LOOKUP_ID = 77 
OR LOOKUP_ID = 78
OR LOOKUP_ID = 99
OR LOOKUP_ID = 100 
OR LOOKUP_ID = 101 
OR LOOKUP_ID = 102 
OR LOOKUP_ID = 103;

DROP TABLE week_days_master;
DROP TABLE rank_days_master;
SET FOREIGN_KEY_CHECKS=1;
UPDATE DATABASE_VERSION SET DATABASE_VERSION = 244 WHERE DATABASE_VERSION = 243;