CREATE TABLE QUESTION_GROUP(
  ID INTEGER AUTO_INCREMENT NOT NULL,
  TITLE VARCHAR(200) NOT NULL,
  DATE_OF_CREATION DATE NOT NULL,
  STATE INTEGER NOT NULL,
  PRIMARY KEY (ID)
)ENGINE=InnoDB CHARACTER SET utf8;

UPDATE DATABASE_VERSION SET DATABASE_VERSION = 255 WHERE DATABASE_VERSION = 254;