INSERT INTO SUPPORTED_LOCALE(LOCALE_ID,COUNTRY_ID,LANG_ID,LOCALE_NAME,DEFAULT_LOCALE) VALUES(46,25,1,'English-Lebanon-AlMajmoua',0);

UPDATE DATABASE_VERSION SET DATABASE_VERSION = 224 WHERE DATABASE_VERSION = 223;
