SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS COLL_SHEET_SAVINGS_DETAILS;
DROP TABLE IF EXISTS COLL_SHEET_LOAN_DETAILS;
DROP TABLE IF EXISTS COLL_SHEET_CUSTOMER;
DROP TABLE IF EXISTS COLL_SHEET;

SET FOREIGN_KEY_CHECKS=1;

UPDATE DATABASE_VERSION SET DATABASE_VERSION = 245 WHERE DATABASE_VERSION = 244;