CREATE TABLE  MAX_MIN_INTEREST_RATE(
ACCOUNT_ID INTEGER   AUTO_INCREMENT NOT NULL,
  MIN_INTEREST_RATE  DECIMAL(21,4) NOT NULL,
  MAX_INTEREST_RATE  DECIMAL(21,4) NOT NULL,
  PRIMARY KEY(ACCOUNT_ID),
FOREIGN KEY(ACCOUNT_ID)
    REFERENCES  LOAN_ACCOUNT(ACCOUNT_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)
ENGINE=InnoDB CHARACTER SET utf8;

INSERT INTO MAX_MIN_INTEREST_RATE (ACCOUNT_ID, MIN_INTEREST_RATE, MAX_INTEREST_RATE)
SELECT LOAN_ACCOUNT.ACCOUNT_ID, LOAN_OFFERING.MIN_INTEREST_RATE, LOAN_OFFERING.MAX_INTEREST_RATE
FROM LOAN_ACCOUNT, LOAN_OFFERING
WHERE LOAN_ACCOUNT.PRD_OFFERING_ID = LOAN_OFFERING.PRD_OFFERING_ID;

UPDATE DATABASE_VERSION SET DATABASE_VERSION = 249 WHERE DATABASE_VERSION = 248;