
ALTER TABLE FEES 
MODIFY FEE_AMOUNT DECIMAL(21,4);

ALTER TABLE CUST_PERF_HISTORY 
MODIFY LAST_LOAN_AMNT DECIMAL(21,4),
MODIFY TOTAL_SAVINGS_AMNT DECIMAL(21,4),
MODIFY DELINQUINT_PORTFOLIO DECIMAL(21,4);

ALTER TABLE CUSTOMER_DETAIL 
MODIFY POVERTY_LHOOD_PCT DECIMAL(21,4);

ALTER TABLE LOAN_OFFERING 
MODIFY MIN_LOAN_AMOUNT DECIMAL(21,4) DEFAULT null,
MODIFY MAX_LOAN_AMNT DECIMAL(21,4) DEFAULT null,
MODIFY DEFAULT_LOAN_AMOUNT DECIMAL(21,4) DEFAULT null;

ALTER TABLE SAVINGS_OFFERING 
MODIFY RECOMMENDED_AMOUNT DECIMAL(21,4),
MODIFY MAX_AMNT_WITHDRAWL DECIMAL(21,4),
MODIFY MIN_AMNT_FOR_INT DECIMAL(21,4);

ALTER TABLE CUSTOMER_HISTORICAL_DATA 
MODIFY LOAN_AMOUNT DECIMAL(21,4),
MODIFY TOTAL_AMOUNT_PAID DECIMAL(21,4),
MODIFY INTEREST_PAID DECIMAL(21,4);

ALTER TABLE ACCOUNT_ACTIVITY 
MODIFY PRINCIPAL DECIMAL(21,4),
MODIFY PRINCIPAL_OUTSTANDING DECIMAL(21,4);

ALTER TABLE LOAN_ACCOUNT 
MODIFY LOAN_AMOUNT DECIMAL(21,4),
MODIFY LOAN_BALANCE DECIMAL(21,4);

ALTER TABLE LOAN_ACTIVITY_DETAILS 
MODIFY PRINCIPAL_AMOUNT DECIMAL(21,4),
MODIFY INTEREST_AMOUNT DECIMAL(21,4),
MODIFY PENALTY_AMOUNT DECIMAL(21,4),
MODIFY FEE_AMOUNT DECIMAL(21,4),
MODIFY BALANCE_PRINCIPAL_AMOUNT DECIMAL(21,4),
MODIFY BALANCE_INTEREST_AMOUNT DECIMAL(21,4),
MODIFY BALANCE_PENALTY_AMOUNT DECIMAL(21,4),
MODIFY BALANCE_FEE_AMOUNT DECIMAL(21,4);

ALTER TABLE LOAN_SUMMARY 
MODIFY ORIG_PRINCIPAL DECIMAL(21,4), 
MODIFY ORIG_INTEREST DECIMAL(21,4), 
MODIFY ORIG_FEES DECIMAL(21,4), 
MODIFY ORIG_PENALTY DECIMAL(21,4), 
MODIFY PRINCIPAL_PAID DECIMAL(21,4),
MODIFY INTEREST_PAID DECIMAL(21,4),
MODIFY FEES_PAID DECIMAL(21,4),
MODIFY PENALTY_PAID DECIMAL(21,4),
MODIFY RAW_AMOUNT_TOTAL DECIMAL(21,4);

ALTER TABLE CUSTOMER_ACCOUNT_ACTIVITY 
MODIFY AMOUNT DECIMAL(21,4);

ALTER TABLE ACCOUNT_PAYMENT 
MODIFY AMOUNT DECIMAL(21,4) NOT NULL;

ALTER TABLE CUSTOMER_SCHEDULE
MODIFY MISC_FEES DECIMAL(21,4),
MODIFY MISC_FEES_PAID DECIMAL(21,4), 
MODIFY MISC_PENALTY DECIMAL(21,4),
MODIFY MISC_PENALTY_PAID DECIMAL(21,4);

ALTER TABLE LOAN_SCHEDULE 
MODIFY PRINCIPAL DECIMAL(21,4) NOT NULL,
MODIFY INTEREST DECIMAL(21,4) NOT NULL,
MODIFY PENALTY DECIMAL(21,4) NOT NULL,
MODIFY MISC_FEES DECIMAL(21,4), 
MODIFY MISC_FEES_PAID DECIMAL(21,4),
MODIFY MISC_PENALTY DECIMAL(21,4),
MODIFY MISC_PENALTY_PAID DECIMAL(21,4),
MODIFY PRINCIPAL_PAID DECIMAL(21,4),
MODIFY INTEREST_PAID DECIMAL(21,4),
MODIFY PENALTY_PAID DECIMAL(21,4);

ALTER TABLE SAVING_SCHEDULE 
MODIFY DEPOSIT DECIMAL(21,4) NOT NULL,
MODIFY DEPOSIT_PAID DECIMAL(21,4);

ALTER TABLE ACCOUNT_FEES 
MODIFY ACCOUNT_FEE_AMNT DECIMAL(21,4) NOT NULL,
MODIFY FEE_AMNT DECIMAL(21,4) NOT NULL;

ALTER TABLE SAVINGS_ACCOUNT 
MODIFY SAVINGS_BALANCE DECIMAL(21,4),
MODIFY RECOMMENDED_AMOUNT DECIMAL(21,4),
MODIFY INT_TO_BE_POSTED DECIMAL(21,4),
MODIFY MIN_AMNT_FOR_INT DECIMAL(21,4);

ALTER TABLE SAVINGS_ACTIVITY_DETAILS 
MODIFY AMOUNT DECIMAL(21,4) NOT NULL,
MODIFY BALANCE_AMOUNT DECIMAL(21,4) NOT NULL;

ALTER TABLE SAVINGS_PERFORMANCE 
MODIFY TOTAL_DEPOSITS DECIMAL(21,4),
MODIFY TOTAL_WITHDRAWALS DECIMAL(21,4),
MODIFY TOTAL_INTEREST_EARNED DECIMAL(21,4);

ALTER TABLE ACCOUNT_TRXN 
MODIFY AMOUNT DECIMAL(21,4) NOT NULL;

ALTER TABLE FEE_TRXN_DETAIL
MODIFY FEE_AMOUNT DECIMAL(21,4) NOT NULL;

ALTER TABLE LOAN_FEE_SCHEDULE 
MODIFY AMOUNT DECIMAL(21,4),
MODIFY AMOUNT_PAID DECIMAL(21,4) NOT NULL;

ALTER TABLE CUSTOMER_FEE_SCHEDULE
MODIFY AMOUNT DECIMAL(21,4),
MODIFY AMOUNT_PAID DECIMAL(21,4);

ALTER TABLE SAVINGS_TRXN_DETAIL
MODIFY DEPOSIT_AMOUNT DECIMAL(21,4) ,
MODIFY WITHDRAWAL_AMOUNT DECIMAL(21,4) ,
MODIFY INTEREST_AMOUNT DECIMAL(21,4) ,
MODIFY BALANCE DECIMAL(21,4);

ALTER TABLE LOAN_TRXN_DETAIL
MODIFY PRINCIPAL_AMOUNT DECIMAL(21,4),
MODIFY INTEREST_AMOUNT DECIMAL(21,4),
MODIFY PENALTY_AMOUNT DECIMAL(21,4),
MODIFY MISC_FEE_AMOUNT DECIMAL(21,4),
MODIFY MISC_PENALTY_AMOUNT DECIMAL(21,4);

ALTER TABLE CUSTOMER_TRXN_DETAIL
MODIFY TOTAL_AMOUNT DECIMAL(21,4),
MODIFY MISC_FEE_AMOUNT DECIMAL(21,4),
MODIFY MISC_PENALTY_AMOUNT DECIMAL(21,4);

ALTER TABLE CUSTOMER_LOAN_ACCOUNT_DETAIL
MODIFY PRINCIPAL DECIMAL(21,4) NOT NULL,
MODIFY INTEREST DECIMAL(21,4) NOT NULL,
MODIFY PENALTY DECIMAL(21,4) NOT NULL;

ALTER TABLE FINANCIAL_TRXN
MODIFY POSTED_AMOUNT DECIMAL(21,4) NOT NULL,
MODIFY BALANCE_AMOUNT DECIMAL(21,4) NOT NULL;

ALTER TABLE COLL_SHEET_CUSTOMER
MODIFY TOTAL_DUE_SAVINGS_LOAN DECIMAL(21,4) ,
MODIFY CUST_ACCNT_FEE DECIMAL(21,4),
MODIFY CUST__ACCNT_PENALTY DECIMAL(21,4) ,
MODIFY COLLECTIVE_LN_AMNT_DUE DECIMAL(21,4),
MODIFY COLLECTIVE_LN_DISBURSAL DECIMAL(21,4),
MODIFY COLLECTIVE_SAVINGS_DUE DECIMAL(21,4),
MODIFY COLLECTIVE_ACCNT_CHARGES DECIMAL(21,4),
MODIFY COLLECTIVE_TOTAL_CHARGES DECIMAL(21,4),
MODIFY COLLECTIVE_NET_CASH_IN DECIMAL(21,4);

ALTER TABLE COLL_SHEET_LOAN_DETAILS
MODIFY TOTAL_PRIN_DUE DECIMAL(21,4) NOT NULL,
MODIFY ORIG_LOAN_AMNT DECIMAL(21,4) NOT NULL, 
MODIFY AMNT_TO_CLOSE_LOAN DECIMAL(21,4) NOT NULL,
MODIFY PRINCIPAL_DUE DECIMAL(21,4),
MODIFY INTEREST_DUE DECIMAL(21,4), 
MODIFY FEES_DUE DECIMAL(21,4),
MODIFY PENALTY_DUE DECIMAL(21,4),
MODIFY TOTAL_SCHEDULED_AMNT_DUE DECIMAL(21,4),
MODIFY PRINCIPAL_OVERDUE DECIMAL(21,4),
MODIFY INTEREST_OVERDUE DECIMAL(21,4),
MODIFY FEES_OVERDUE DECIMAL(21,4),
MODIFY PENALTY_OVERDUE DECIMAL(21,4),
MODIFY TOTAL_AMNT_OVERDUE DECIMAL(21,4),
MODIFY TOTAL_AMNT_DUE DECIMAL(21,4),
MODIFY AMNT_TOBE_DISBURSED DECIMAL(21,4);

ALTER TABLE COLL_SHEET_SAVINGS_DETAILS 
MODIFY ACCNT_BALANCE DECIMAL(21,4), 
MODIFY RECOMMENDED_AMNT_DUE DECIMAL(21,4),
MODIFY AMNT_OVERDUE DECIMAL(21,4),
MODIFY TOTAL_SAVINGS_AMNT_DUE DECIMAL(21,4);

ALTER TABLE CLIENT_PERF_HISTORY 
MODIFY LAST_LOAN_AMNT DECIMAL(21,4),
MODIFY TOTAL_SAVINGS_AMNT DECIMAL(21,4),
MODIFY DELINQUINT_PORTFOLIO DECIMAL(21,4);

ALTER TABLE GROUP_PERF_HISTORY 
MODIFY LAST_GROUP_LOAN_AMNT_DISB DECIMAL(21,4),
MODIFY AVG_LOAN_SIZE DECIMAL(21,4),
MODIFY TOTAL_OUTSTAND_LOAN_AMNT DECIMAL(21,4),
MODIFY PORTFOLIO_AT_RISK DECIMAL(21,4),
MODIFY TOTAL_SAVINGS_AMNT DECIMAL(21,4);

ALTER TABLE LOAN_ARREARS_AGING 
MODIFY OVERDUE_PRINCIPAL DECIMAL(21,4), 
MODIFY OVERDUE_INTEREST DECIMAL(21,4),
MODIFY OVERDUE_BALANCE DECIMAL(21,4),
MODIFY UNPAID_PRINCIPAL DECIMAL(21,4),
MODIFY UNPAID_INTEREST DECIMAL(21,4),
MODIFY UNPAID_BALANCE DECIMAL(21,4);


ALTER TABLE PPI_SURVEY_INSTANCE 
MODIFY BOTTOM_HALF_BELOW DECIMAL(21,4),
MODIFY TOP_HALF_BELOW DECIMAL(21,4);

ALTER TABLE PPI_LIKELIHOODS 
MODIFY BOTTOM_HALF_BELOW DECIMAL(21,4) NOT NULL,
MODIFY TOP_HALF_BELOW DECIMAL(21,4) NOT NULL;

ALTER TABLE LOAN_AMOUNT_FROM_LAST_LOAN 
MODIFY START_RANGE DECIMAL(21,4) NOT NULL,
MODIFY END_RANGE DECIMAL(21,4) NOT NULL,
MODIFY MIN_LOAN_AMOUNT DECIMAL(21,4) NOT NULL,
MODIFY MAX_LOAN_AMNT DECIMAL(21,4) NOT NULL,
MODIFY DEFAULT_LOAN_AMOUNT DECIMAL(21,4) NOT NULL;

ALTER TABLE NO_OF_INSTALL_FROM_LAST_LOAN 
MODIFY START_RANGE DECIMAL(21,4) NOT NULL,
MODIFY END_RANGE DECIMAL(21,4) NOT NULL,
MODIFY MIN_NO_INSTALL DECIMAL(21,4) NOT NULL,
MODIFY MAX_NO_INSTALL DECIMAL(21,4) NOT NULL,
MODIFY DEFAULT_NO_INSTALL DECIMAL(21,4) NOT NULL;

ALTER TABLE LOAN_AMOUNT_FROM_LOAN_CYCLE 
MODIFY MIN_LOAN_AMOUNT DECIMAL(21,4) NOT NULL,
MODIFY MAX_LOAN_AMNT DECIMAL(21,4) NOT NULL,
MODIFY DEFAULT_LOAN_AMOUNT DECIMAL(21,4) NOT NULL;

ALTER TABLE NO_OF_INSTALL_FROM_LOAN_CYCLE
MODIFY MIN_NO_INSTALL DECIMAL(21,4) NOT NULL,
MODIFY MAX_NO_INSTALL DECIMAL(21,4) NOT NULL,
MODIFY DEFAULT_NO_INSTALL DECIMAL(21,4) NOT NULL,
MODIFY RANGE_INDEX DECIMAL(21,4) NOT NULL;

ALTER TABLE LOAN_AMOUNT_SAME_FOR_ALL_LOAN 
MODIFY MIN_LOAN_AMOUNT DECIMAL(21,4) NOT NULL,
MODIFY MAX_LOAN_AMNT DECIMAL(21,4) NOT NULL,
MODIFY DEFAULT_LOAN_AMOUNT DECIMAL(21,4) NOT NULL;

ALTER TABLE NO_OF_INSTALL_SAME_FOR_ALL_LOAN 
MODIFY MIN_NO_INSTALL DECIMAL(21,4) NOT NULL,
MODIFY MAX_NO_INSTALL DECIMAL(21,4) NOT NULL,
MODIFY DEFAULT_NO_INSTALL DECIMAL(21,4) NOT NULL;

ALTER TABLE MAX_MIN_LOAN_AMOUNT 
MODIFY MIN_LOAN_AMOUNT DECIMAL(21,4) NOT NULL,
MODIFY MAX_LOAN_AMOUNT DECIMAL(21,4) NOT NULL;

ALTER TABLE MAX_MIN_NO_OF_INSTALL 
MODIFY MIN_NO_INSTALL DECIMAL(21,4) NOT NULL,
MODIFY MAX_NO_INSTALL DECIMAL(21,4) NOT NULL;

ALTER TABLE BATCH_LOAN_ARREARS_AGING 
MODIFY AMOUNT_AGING DECIMAL(21,4) NOT NULL,
MODIFY AMOUNT_OUTSTANDING_AGING DECIMAL(21,4) NOT NULL,
MODIFY INTEREST_AGING DECIMAL(21,4) NOT NULL;

ALTER TABLE BATCH_STAFF_SUMMARY 
MODIFY LOAN_AMOUNT_OUTSTANDING DECIMAL(21,4) NOT NULL,
MODIFY INTEREST_FEES_OUTSTANDING DECIMAL(21,4) NOT NULL,
MODIFY PORTFOLIO_AT_RISK DECIMAL(21,4) NOT NULL,
MODIFY   LOAN_ARREARS_AMOUNT DECIMAL(21,4) NOT NULL;

ALTER TABLE BATCH_LOAN_DETAILS 
MODIFY LOAN_AMOUNT_ISSUED DECIMAL(21,4) NOT NULL,
MODIFY LOAN_INTEREST_ISSUED DECIMAL(21,4) NOT NULL,
MODIFY LOAN_OUTSTANDING_AMOUNT DECIMAL(21,4) NOT NULL,
MODIFY LOAN_OUTSTANDING_INTEREST DECIMAL(21,4) NOT NULL;

ALTER TABLE BATCH_LOAN_ARREARS_PROFILE
MODIFY OVERDUE_BALANCE DECIMAL(21,4) NOT NULL,
MODIFY UNPAID_BALANCE DECIMAL(21,4) NOT NULL,
MODIFY OUTSTANDING_AMOUNT_AT_RISK DECIMAL(21,4) NOT NULL,
MODIFY OVERDUE_AMOUNT_AT_RISK DECIMAL(21,4) NOT NULL;

ALTER TABLE BATCH_BRANCH_CONFIRMATION_RECOVERY
MODIFY  DUE DECIMAL(21,4) NOT NULL,
MODIFY  ACTUAL DECIMAL(21,4) NOT NULL,
MODIFY  ARREARS DECIMAL(21,4) NOT NULL;

ALTER TABLE BATCH_BRANCH_CONFIRMATION_ISSUE
MODIFY ACTUAL DECIMAL(21,4) NOT NULL;

ALTER TABLE BATCH_BRANCH_CONFIRMATION_DISBURSEMENT
MODIFY ACTUAL DECIMAL(21,4) NOT NULL;
