/* Added for jira issue 2730 */
INSERT INTO FIELD_CONFIGURATION(FIELD_CONFIG_ID,FIELD_NAME,ENTITY_ID,MANDATORY_FLAG,HIDDEN_FLAG)VALUES
(81,'MaritalStatus',1,0,0),
(82,'NumberOfChildren',1,0,0);

UPDATE DATABASE_VERSION SET DATABASE_VERSION = 241 WHERE DATABASE_VERSION = 240;
