INSERT INTO FIELD_CONFIGURATION(FIELD_CONFIG_ID,FIELD_NAME,ENTITY_ID,MANDATORY_FLAG,HIDDEN_FLAG)VALUES
(84,'SpouseFatherInformation',1,1,0),
(85,'FamilyDetails',1,1,0);

UPDATE DATABASE_VERSION SET DATABASE_VERSION = 257 WHERE DATABASE_VERSION = 256;