ALTER TABLE PRD_OFFERING ADD COLUMN CURRENCY_ID SMALLINT;

ALTER TABLE PRD_OFFERING ADD CONSTRAINT FOREIGN KEY (CURRENCY_ID) REFERENCES CURRENCY(CURRENCY_ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

UPDATE DATABASE_VERSION SET DATABASE_VERSION = 226 WHERE DATABASE_VERSION = 225;
