ALTER TABLE HOLIDAY
    DROP FOREIGN KEY holiday_ibfk_1;

ALTER TABLE HOLIDAY
    DROP PRIMARY KEY;

ALTER TABLE HOLIDAY
    ADD COLUMN HOLIDAY_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY;
    
CREATE TABLE OFFICE_HOLIDAY (
  OFFICE_ID SMALLINT,
  HOLIDAY_ID INT,
  PRIMARY KEY(OFFICE_ID, HOLIDAY_ID),
  FOREIGN KEY(OFFICE_ID)
    REFERENCES OFFICE(OFFICE_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(HOLIDAY_ID)
    REFERENCES HOLIDAY(HOLIDAY_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)
ENGINE=InnoDB CHARACTER SET utf8;

UPDATE OFFICE_HOLIDAY, OFFICE, HOLIDAY 
    SET OFFICE_HOLIDAY.OFFICE_ID = OFFICE.OFFICE_ID, 
        OFFICE_HOLIDAY.HOLIDAY_ID = HOLIDAY.OFFICE_ID 
    WHERE OFFICE.OFFICE_ID = HOLIDAY.OFFICE_ID;

ALTER TABLE HOLIDAY
    DROP COLUMN OFFICE_ID;
    
UPDATE DATABASE_VERSION SET DATABASE_VERSION = 246 WHERE DATABASE_VERSION = 245;
