CREATE TABLE CUSTOMER_FAMILY_DETAIL (
CUSTOMER_FAMILY_ID INTEGER AUTO_INCREMENT NOT NULL,
CUSTOMER_ID INTEGER,
CUSTOMER_NAME_ID INTEGER,
RELATIONSHIP SMALLINT,
GENDER SMALLINT,
DATE_OF_BIRTH DATE,
LIVING_STATUS SMALLINT,
PRIMARY KEY (CUSTOMER_FAMILY_ID),
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
FOREIGN KEY (CUSTOMER_NAME_ID) REFERENCES CUSTOMER_NAME_DETAIL(CUSTOMER_NAME_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
)ENGINE=InnoDB CHARACTER SET utf8;

UPDATE DATABASE_VERSION SET DATABASE_VERSION = 222 WHERE DATABASE_VERSION = 221;



