-- This SQL code is invoked from Java based upgrade code
-- It will only run on a clean database (for consistency in a test
-- or development environmnet).  It will not be run when upgrading
-- a database which already contains data
 
-- These are unused values but had been kept because deleting them may cause problems to existing databases
DELETE FROM LOOKUP_VALUE WHERE LOOKUP_ID = 65 AND LOOKUP_NAME = 'DBUpgrade.OfficeLevels.Unsued';
DELETE FROM LOOKUP_VALUE WHERE LOOKUP_ID = 71 AND LOOKUP_NAME = 'DBUpgrade.PrdApplicableMaster.Unused';
DELETE FROM LOOKUP_VALUE WHERE LOOKUP_ID = 90 AND LOOKUP_NAME = 'DBUpgrade.InterestCalcRule.Unused';
DELETE FROM LOOKUP_VALUE WHERE LOOKUP_ID = 223 AND LOOKUP_NAME = 'DBUpgrade.Address3.Unused';
DELETE FROM LOOKUP_VALUE WHERE LOOKUP_ID = 224 AND LOOKUP_NAME = 'DBUpgrade.City.Unused';
DELETE FROM LOOKUP_VALUE WHERE LOOKUP_ID = 259 AND LOOKUP_NAME = 'DBUpgrade.LoanPurposes1.Unused';
DELETE FROM LOOKUP_VALUE WHERE LOOKUP_ID = 263 AND LOOKUP_NAME = 'DBUpgrade.LoanPurposes2.Unused';
-- Business Activities
DELETE FROM LOOKUP_VALUE_LOCALE WHERE LOOKUP_VALUE_ID = 251  AND LOOKUP_ID = 136;
DELETE FROM LOOKUP_VALUE WHERE LOOKUP_ID = 136 AND LOOKUP_NAME = 'BusinessActivities-DailyLabour';

DELETE FROM LOOKUP_VALUE_LOCALE WHERE LOOKUP_VALUE_ID = 253 AND LOOKUP_ID = 137;
DELETE FROM LOOKUP_VALUE WHERE LOOKUP_ID = 137 AND LOOKUP_NAME = 'BusinessActivities-Agriculture';

DELETE FROM LOOKUP_VALUE_LOCALE WHERE LOOKUP_VALUE_ID = 265 AND LOOKUP_ID = 144;
DELETE FROM LOOKUP_VALUE WHERE LOOKUP_ID = 144 AND LOOKUP_NAME = 'BusinessActivities-AnimalHusbandry';

DELETE FROM LOOKUP_VALUE_LOCALE WHERE LOOKUP_VALUE_ID = 266 AND LOOKUP_ID = 145;
DELETE FROM LOOKUP_VALUE WHERE LOOKUP_ID = 145 AND LOOKUP_NAME = 'BusinessActivities-MicroEnterprise';

DELETE FROM LOOKUP_VALUE_LOCALE WHERE LOOKUP_VALUE_ID = 430 AND LOOKUP_ID = 222;
DELETE FROM LOOKUP_VALUE WHERE LOOKUP_ID = 222 AND LOOKUP_NAME = 'BusinessActivities-Production';

DELETE FROM LOOKUP_VALUE_LOCALE WHERE LOOKUP_VALUE_ID = 432 AND LOOKUP_ID = 225;
DELETE FROM LOOKUP_VALUE WHERE LOOKUP_ID = 225 AND LOOKUP_NAME = 'BusinessActivities-Trading';

DELETE FROM LOOKUP_VALUE_LOCALE WHERE LOOKUP_VALUE_ID = 199 AND LOOKUP_ID = 109;
DELETE FROM LOOKUP_VALUE WHERE LOOKUP_ID = 109 AND LOOKUP_NAME = 'CollateralTypes-Type1';

DELETE FROM LOOKUP_VALUE_LOCALE WHERE LOOKUP_VALUE_ID = 200 AND LOOKUP_ID = 110;
DELETE FROM LOOKUP_VALUE WHERE LOOKUP_ID = 110 AND LOOKUP_NAME = 'CollateralTypes-Type2';



