INSERT INTO FIELD_CONFIGURATION(FIELD_CONFIG_ID,FIELD_NAME,ENTITY_ID,MANDATORY_FLAG,HIDDEN_FLAG) VALUES (83,'ExternalId',22,0,0);

UPDATE DATABASE_VERSION SET DATABASE_VERSION = 251 WHERE DATABASE_VERSION = 250;