SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS COLL_SHEET_SAVINGS_DETAILS;
DROP TABLE IF EXISTS COLL_SHEET_LOAN_DETAILS;
DROP TABLE IF EXISTS COLL_SHEET_CUSTOMER;
DROP TABLE IF EXISTS COLL_SHEET;

SET FOREIGN_KEY_CHECKS=1;