// ============================================================================
//
// Copyright (c) 2005-2007, Talend Inc.
//
// This source code has been automatically generated by Talend Open Studio
// / JobDesigner (CodeGenerator version 2.3.0.RC1_r8112).
// You can find more information about Talend products at www.talend.com.
// You may distribute this code under the terms of the GNU LGPL license
// (http://www.gnu.org/licenses/lgpl.html).
//
// ============================================================================ 
package org_mifos_etl.branchofficeloader;

import routines.DataOperation;
import routines.Mathematical;
import routines.Numeric;
import routines.Relational;
import routines.StringHandling;
import routines.TalendDataGenerator;
import routines.TalendDate;
import routines.TalendString;
import routines.system.*;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.math.BigDecimal;

/**
 * Job: BranchOfficeLoader Purpose: <br>
 * Description: Loads the branch office data with the parent as area office.
 * <br>
 * 
 * @author ravikasar@gmail.com
 * @version 0.1
 * @status DEV
 */
public class BranchOfficeLoader {
	// create and load default properties
	private static java.util.Properties defaultProps = new java.util.Properties();
	// create application properties with default
	private static java.util.Properties context = new java.util.Properties();
	private static String OLTP_DB_PASSWORD;
	private static String OLTP_DB_USER;
	private static String OLTP_DB_NAME;
	private static String OLTP_DB_PORT;
	private static String OLTP_HOST_NAME;
	private static String OLAP_DB_HOST;
	private static String OLAP_DB_PORT;
	private static String OLAP_DB_NAME;
	private static String OLAP_DB_USER;
	private static String OLAP_DB_PASSWORD;
	private static String GK_DB_HOST;
	private static String GK_DB_PORT;
	private static String GK_DB_SCHEMA;
	private static String GK_DB_USER;
	private static String GK_DB_PASSWORD;
	private static final String jobName = "BranchOfficeLoader";
	private static final String projectName = "ORG_MIFOS_ETL";
	public static Integer errorCode = null;
	private static final java.util.Map<String, Long> start_Hash = java.util.Collections
			.synchronizedMap(new java.util.HashMap<String, Long>());
	private static final java.util.Map<String, Long> end_Hash = java.util.Collections
			.synchronizedMap(new java.util.HashMap<String, Long>());
	private static final java.util.Map<String, Boolean> ok_Hash = java.util.Collections
			.synchronizedMap(new java.util.HashMap<String, Boolean>());
	private static final java.util.Map<String, Object> globalMap = java.util.Collections
			.synchronizedMap(new java.util.HashMap<String, Object>());

	LogCatcherUtils tLogCatcher_1 = new LogCatcherUtils();
	StatCatcherUtils tStatCatcher_1 = new StatCatcherUtils(
			"_3t3TQOnuEdyQHudWLCxcng", "0.1");

	private class TalendException extends Exception {
		private Exception e = null;
		private BranchOfficeLoader c = null;
		private String currentComponent = null;

		private TalendException(BranchOfficeLoader c, Exception e,
				String errorComponent) {
			this.currentComponent = errorComponent;
			this.e = e;
			this.c = c;
		}

		@Override
		public void printStackTrace() {
			if (!(e instanceof TalendException || e instanceof TDieException)) {
				globalMap.put(currentComponent + "_ERROR_MESSAGE", e
						.getMessage());
				System.err
						.println("Exception in component " + currentComponent);
			}
			if (!(e instanceof TDieException)) {
				e.printStackTrace();
			}
			if (!(e instanceof TalendException)) {
				try {
					for (java.lang.reflect.Method m : this.getClass()
							.getEnclosingClass().getMethods()) {
						if (m.getName().compareTo(currentComponent + "_error") == 0) {
							m.invoke(c, new Object[] { e });
							break;
						}
					}
					if (!(e instanceof TDieException)) {
						tLogCatcher_1.addMessage("Java Exception",
								currentComponent, 6, e.getMessage(), 1);
						tLogCatcher_1Process();
					}

				} catch (java.lang.SecurityException e) {
					this.e.printStackTrace();
				} catch (java.lang.IllegalArgumentException e) {
					this.e.printStackTrace();
				} catch (java.lang.IllegalAccessException e) {
					this.e.printStackTrace();
				} catch (java.lang.reflect.InvocationTargetException e) {
					this.e.printStackTrace();
				} catch (TalendException e) {
					// do nothing
				}

			}
		}
	}

	public void tJava_1_error(Exception exception) throws TalendException {
		end_Hash.put("tJava_1", System.currentTimeMillis());
		tJava_1_onSubJobError(exception);
	}

	public void tMysqlConnection_2_error(Exception exception)
			throws TalendException {
		end_Hash.put("tMysqlConnection_2", System.currentTimeMillis());
		tMysqlConnection_2_onSubJobError(exception);
	}

	public void tMysqlConnection_1_error(Exception exception)
			throws TalendException {
		end_Hash.put("tMysqlConnection_1", System.currentTimeMillis());
		tMysqlConnection_1_onSubJobError(exception);
	}

	public void tMysqlInput_1_error(Exception exception) throws TalendException {
		end_Hash.put("tMysqlInput_1", System.currentTimeMillis());
		tMysqlInput_1_onSubJobError(exception);
	}

	public void tJoin_1_error(Exception exception) throws TalendException {
		end_Hash.put("tJoin_1", System.currentTimeMillis());
		tMysqlInput_1_onSubJobError(exception);
	}

	public void tFilterColumns_1_error(Exception exception)
			throws TalendException {
		end_Hash.put("tFilterColumns_1", System.currentTimeMillis());
		tMysqlInput_1_onSubJobError(exception);
	}

	public void tMysqlOutput_4_error(Exception exception)
			throws TalendException {
		end_Hash.put("tMysqlOutput_4", System.currentTimeMillis());
		tMysqlInput_1_onSubJobError(exception);
	}

	public void tMysqlCommit_1_error(Exception exception)
			throws TalendException {
		end_Hash.put("tMysqlCommit_1", System.currentTimeMillis());
		tMysqlCommit_1_onSubJobError(exception);
	}

	public void tLogCatcher_1_error(Exception exception) throws TalendException {
		end_Hash.put("tLogCatcher_1", System.currentTimeMillis());
		tLogCatcher_1_onSubJobError(exception);
	}

	public void tFileOutputDelimited_1_error(Exception exception)
			throws TalendException {
		end_Hash.put("tFileOutputDelimited_1", System.currentTimeMillis());
		tLogCatcher_1_onSubJobError(exception);
	}

	public void tMysqlInput_3_error(Exception exception) throws TalendException {
		end_Hash.put("tMysqlInput_3", System.currentTimeMillis());
		tMysqlInput_3_onSubJobError(exception);
	}

	public void tStatCatcher_1_error(Exception exception)
			throws TalendException {
		end_Hash.put("tStatCatcher_1", System.currentTimeMillis());
		tStatCatcher_1_onSubJobError(exception);
	}

	public void tFileOutputDelimited_2_error(Exception exception)
			throws TalendException {
		end_Hash.put("tFileOutputDelimited_2", System.currentTimeMillis());
		tStatCatcher_1_onSubJobError(exception);
	}

	public void tHash_row2_error(Exception exception) throws TalendException {
		end_Hash.put("tHash_row2", System.currentTimeMillis());
		tMysqlInput_3_onSubJobError(exception);
	}

	public void tJava_1_onSubJobError(Exception exception)
			throws TalendException {
	}

	public void tMysqlConnection_2_onSubJobError(Exception exception)
			throws TalendException {
	}

	public void tMysqlConnection_1_onSubJobError(Exception exception)
			throws TalendException {
	}

	public void tMysqlInput_1_onSubJobError(Exception exception)
			throws TalendException {
	}

	public void tMysqlCommit_1_onSubJobError(Exception exception)
			throws TalendException {
	}

	public void tLogCatcher_1_onSubJobError(Exception exception)
			throws TalendException {
	}

	public void tMysqlInput_3_onSubJobError(Exception exception)
			throws TalendException {
	}

	public void tStatCatcher_1_onSubJobError(Exception exception)
			throws TalendException {
	}

	public void tJava_1Process() throws TalendException {
		String currentComponent = "";
		try {

			/**
			 * [tJava_1 begin ] start
			 */

			ok_Hash.put("tJava_1", false);
			start_Hash.put("tJava_1", System.currentTimeMillis());
			currentComponent = "tJava_1";

			java.util.Properties p = new java.util.Properties();

			java.io.InputStream inStream = BranchOfficeLoader.class
					.getClassLoader().getResourceAsStream(
							"hibernate.properties");

			p.load(inStream);
			OLTP_DB_PASSWORD = (String) p.get("OLTP_DB_PASSWORD");
			OLTP_DB_USER = (String) p.get("OLTP_DB_USER");
			OLTP_DB_NAME = (String) p.get("OLTP_DB_NAME");
			OLTP_DB_PORT = (String) p.get("OLTP_DB_PORT");
			OLTP_HOST_NAME = (String) p.get("OLTP_HOST_NAME");
			OLAP_DB_HOST = (String) p.get("OLAP_DB_HOST");
			OLAP_DB_PORT = (String) p.get("OLAP_DB_PORT");
			OLAP_DB_NAME = (String) p.get("OLAP_DB_NAME");
			OLAP_DB_USER = (String) p.get("OLAP_DB_USER");
			OLAP_DB_PASSWORD = (String) p.get("OLAP_DB_PASSWORD");

			/**
			 * [tJava_1 begin ] stop
			 */
			/**
			 * [tJava_1 main ] start
			 */

			currentComponent = "tJava_1";

			/**
			 * [tJava_1 main ] stop
			 */

			/**
			 * [tJava_1 end ] start
			 */

			currentComponent = "tJava_1";

			ok_Hash.put("tJava_1", true);
			end_Hash.put("tJava_1", System.currentTimeMillis());

			/**
			 * [tJava_1 end ] stop
			 */

			tMysqlConnection_2Process();

		} catch (Exception e) {
			throw new TalendException(this, e, currentComponent);
		}
	}

	public void tMysqlConnection_2Process() throws TalendException {
		String currentComponent = "";
		try {

			/**
			 * [tMysqlConnection_2 begin ] start
			 */

			ok_Hash.put("tMysqlConnection_2", false);
			start_Hash.put("tMysqlConnection_2", System.currentTimeMillis());
			currentComponent = "tMysqlConnection_2";

			java.lang.Class.forName("org.gjt.mm.mysql.Driver");

			String url_tMysqlConnection_2 = "jdbc:mysql://" + OLAP_DB_HOST
					+ ":" + OLAP_DB_PORT + "/" + OLAP_DB_NAME + "?"
					+ "noDatetimeStringSync=true";

			String userName_tMysqlConnection_2 = OLAP_DB_USER;

			String password_tMysqlConnection_2 = OLAP_DB_PASSWORD;

			java.sql.Connection conn_tMysqlConnection_2 = java.sql.DriverManager
					.getConnection(url_tMysqlConnection_2,
							userName_tMysqlConnection_2,
							password_tMysqlConnection_2);

			conn_tMysqlConnection_2.setAutoCommit(false);

			globalMap.put("conn_" + "tMysqlConnection_2",
					conn_tMysqlConnection_2);

			/**
			 * [tMysqlConnection_2 begin ] stop
			 */
			/**
			 * [tMysqlConnection_2 main ] start
			 */

			currentComponent = "tMysqlConnection_2";

			/**
			 * [tMysqlConnection_2 main ] stop
			 */

			/**
			 * [tMysqlConnection_2 end ] start
			 */

			currentComponent = "tMysqlConnection_2";

			ok_Hash.put("tMysqlConnection_2", true);
			end_Hash.put("tMysqlConnection_2", System.currentTimeMillis());

			/**
			 * [tMysqlConnection_2 end ] stop
			 */

			tMysqlConnection_1Process();

		} catch (Exception e) {
			throw new TalendException(this, e, currentComponent);
		}
	}

	public void tMysqlConnection_1Process() throws TalendException {
		String currentComponent = "";
		try {

			/**
			 * [tMysqlConnection_1 begin ] start
			 */

			ok_Hash.put("tMysqlConnection_1", false);
			start_Hash.put("tMysqlConnection_1", System.currentTimeMillis());
			currentComponent = "tMysqlConnection_1";

			java.lang.Class.forName("org.gjt.mm.mysql.Driver");

			String url_tMysqlConnection_1 = "jdbc:mysql://" + GK_DB_HOST + ":"
					+ GK_DB_PORT + "/" + GK_DB_SCHEMA + "?"
					+ "noDatetimeStringSync=true";

			String userName_tMysqlConnection_1 = GK_DB_USER;

			String password_tMysqlConnection_1 = GK_DB_PASSWORD;

			java.sql.Connection conn_tMysqlConnection_1 = java.sql.DriverManager
					.getConnection(url_tMysqlConnection_1,
							userName_tMysqlConnection_1,
							password_tMysqlConnection_1);

			conn_tMysqlConnection_1.setAutoCommit(false);

			globalMap.put("conn_" + "tMysqlConnection_1",
					conn_tMysqlConnection_1);

			/**
			 * [tMysqlConnection_1 begin ] stop
			 */
			/**
			 * [tMysqlConnection_1 main ] start
			 */

			currentComponent = "tMysqlConnection_1";

			/**
			 * [tMysqlConnection_1 main ] stop
			 */

			/**
			 * [tMysqlConnection_1 end ] start
			 */

			currentComponent = "tMysqlConnection_1";

			ok_Hash.put("tMysqlConnection_1", true);
			end_Hash.put("tMysqlConnection_1", System.currentTimeMillis());

			/**
			 * [tMysqlConnection_1 end ] stop
			 */

			tMysqlInput_1Process();
			tMysqlCommit_1Process();

		} catch (Exception e) {
			throw new TalendException(this, e, currentComponent);
		}
	}

	private class row4Struct {
		private static final int DEFAULT_HASHCODE = 1;
		private static final int PRIME = 31;
		private int hashCode = DEFAULT_HASHCODE;
		public boolean hashCodeDirty = true;

		String GLOBAL_OFFICE_NUM;

		short OFFICE_LEVEL_ID;

		String SEARCH_ID;

		int MAX_CHILD_COUNT;

		short LOCAL_REMOTE_FLAG;

		String DISPLAY_NAME;

		Short CREATED_BY;

		java.util.Date CREATED_DATE;

		Short UPDATED_BY;

		java.util.Date UPDATED_DATE;

		String OFFICE_SHORT_NAME;

		short STATUS_ID;

		int VERSION_NO;

		Short OFFICE_CODE_ID;

		Short area_office_id;

		@Override
		public int hashCode() {
			if (this.hashCodeDirty) {
				final int prime = PRIME;
				int result = DEFAULT_HASHCODE;

				result = prime
						* result
						+ ((this.GLOBAL_OFFICE_NUM == null) ? 0
								: this.GLOBAL_OFFICE_NUM.hashCode());

				this.hashCode = result;
				this.hashCodeDirty = false;
			}
			return this.hashCode;
		}

		@Override
		public boolean equals(Object obj) {
			if (this == obj)
				return true;
			if (obj == null)
				return false;
			if (getClass() != obj.getClass())
				return false;
			final row4Struct other = (row4Struct) obj;

			if (this.GLOBAL_OFFICE_NUM == null) {
				if (other.GLOBAL_OFFICE_NUM != null)
					return false;
			} else if (!this.GLOBAL_OFFICE_NUM.equals(other.GLOBAL_OFFICE_NUM))
				return false;

			return true;
		}

	}

	private class row3Struct {
		private static final int DEFAULT_HASHCODE = 1;
		private static final int PRIME = 31;
		private int hashCode = DEFAULT_HASHCODE;
		public boolean hashCodeDirty = true;

		String GLOBAL_OFFICE_NUM;

		short OFFICE_LEVEL_ID;

		String SEARCH_ID;

		int MAX_CHILD_COUNT;

		short LOCAL_REMOTE_FLAG;

		String DISPLAY_NAME;

		Short CREATED_BY;

		java.util.Date CREATED_DATE;

		Short UPDATED_BY;

		java.util.Date UPDATED_DATE;

		String OFFICE_SHORT_NAME;

		Short parent_id;

		short STATUS_ID;

		int VERSION_NO;

		Short OFFICE_CODE_ID;

		String parent_office_num;

		Short area_office_id;

		@Override
		public int hashCode() {
			if (this.hashCodeDirty) {
				final int prime = PRIME;
				int result = DEFAULT_HASHCODE;

				result = prime
						* result
						+ ((this.GLOBAL_OFFICE_NUM == null) ? 0
								: this.GLOBAL_OFFICE_NUM.hashCode());

				this.hashCode = result;
				this.hashCodeDirty = false;
			}
			return this.hashCode;
		}

		@Override
		public boolean equals(Object obj) {
			if (this == obj)
				return true;
			if (obj == null)
				return false;
			if (getClass() != obj.getClass())
				return false;
			final row3Struct other = (row3Struct) obj;

			if (this.GLOBAL_OFFICE_NUM == null) {
				if (other.GLOBAL_OFFICE_NUM != null)
					return false;
			} else if (!this.GLOBAL_OFFICE_NUM.equals(other.GLOBAL_OFFICE_NUM))
				return false;

			return true;
		}

	}

	private class row1Struct {
		private static final int DEFAULT_HASHCODE = 1;
		private static final int PRIME = 31;
		private int hashCode = DEFAULT_HASHCODE;
		public boolean hashCodeDirty = true;

		String GLOBAL_OFFICE_NUM;

		short OFFICE_LEVEL_ID;

		String SEARCH_ID;

		int MAX_CHILD_COUNT;

		short LOCAL_REMOTE_FLAG;

		String DISPLAY_NAME;

		Short CREATED_BY;

		java.util.Date CREATED_DATE;

		Short UPDATED_BY;

		java.util.Date UPDATED_DATE;

		String OFFICE_SHORT_NAME;

		Short parent_id;

		short STATUS_ID;

		int VERSION_NO;

		Short OFFICE_CODE_ID;

		String parent_office_num;

		@Override
		public int hashCode() {
			if (this.hashCodeDirty) {
				final int prime = PRIME;
				int result = DEFAULT_HASHCODE;

				result = prime
						* result
						+ ((this.GLOBAL_OFFICE_NUM == null) ? 0
								: this.GLOBAL_OFFICE_NUM.hashCode());

				this.hashCode = result;
				this.hashCodeDirty = false;
			}
			return this.hashCode;
		}

		@Override
		public boolean equals(Object obj) {
			if (this == obj)
				return true;
			if (obj == null)
				return false;
			if (getClass() != obj.getClass())
				return false;
			final row1Struct other = (row1Struct) obj;

			if (this.GLOBAL_OFFICE_NUM == null) {
				if (other.GLOBAL_OFFICE_NUM != null)
					return false;
			} else if (!this.GLOBAL_OFFICE_NUM.equals(other.GLOBAL_OFFICE_NUM))
				return false;

			return true;
		}

	}

	private class after_tMysqlInput_1Struct {
		private static final int DEFAULT_HASHCODE = 1;
		private static final int PRIME = 31;
		private int hashCode = DEFAULT_HASHCODE;
		public boolean hashCodeDirty = true;

		String GLOBAL_OFFICE_NUM;

		short OFFICE_LEVEL_ID;

		String SEARCH_ID;

		int MAX_CHILD_COUNT;

		short LOCAL_REMOTE_FLAG;

		String DISPLAY_NAME;

		Short CREATED_BY;

		java.util.Date CREATED_DATE;

		Short UPDATED_BY;

		java.util.Date UPDATED_DATE;

		String OFFICE_SHORT_NAME;

		Short parent_id;

		short STATUS_ID;

		int VERSION_NO;

		Short OFFICE_CODE_ID;

		String parent_office_num;

		@Override
		public int hashCode() {
			if (this.hashCodeDirty) {
				final int prime = PRIME;
				int result = DEFAULT_HASHCODE;

				result = prime
						* result
						+ ((this.GLOBAL_OFFICE_NUM == null) ? 0
								: this.GLOBAL_OFFICE_NUM.hashCode());

				this.hashCode = result;
				this.hashCodeDirty = false;
			}
			return this.hashCode;
		}

		@Override
		public boolean equals(Object obj) {
			if (this == obj)
				return true;
			if (obj == null)
				return false;
			if (getClass() != obj.getClass())
				return false;
			final after_tMysqlInput_1Struct other = (after_tMysqlInput_1Struct) obj;

			if (this.GLOBAL_OFFICE_NUM == null) {
				if (other.GLOBAL_OFFICE_NUM != null)
					return false;
			} else if (!this.GLOBAL_OFFICE_NUM.equals(other.GLOBAL_OFFICE_NUM))
				return false;

			return true;
		}

	}

	public void tMysqlInput_1Process() throws TalendException {
		String currentComponent = "";
		try {
			tMysqlInput_3Process();

			row1Struct row1 = new row1Struct();
			row3Struct row3 = new row3Struct();
			row4Struct row4 = new row4Struct();

			/**
			 * [tMysqlOutput_4 begin ] start
			 */

			ok_Hash.put("tMysqlOutput_4", false);
			start_Hash.put("tMysqlOutput_4", System.currentTimeMillis());
			currentComponent = "tMysqlOutput_4";

			int keyCount_tMysqlOutput_4 = 1;
			if (keyCount_tMysqlOutput_4 < 1) {
				throw new Exception(
						"For update or delete, Schema must have a key");
			}

			int nb_line_tMysqlOutput_4 = 0;
			int nb_line_update_tMysqlOutput_4 = 0;
			int nb_line_inserted_tMysqlOutput_4 = 0;
			int nb_line_deleted_tMysqlOutput_4 = 0;

			int deletedCount_tMysqlOutput_4 = 0;
			int updatedCount_tMysqlOutput_4 = 0;
			int insertedCount_tMysqlOutput_4 = 0;

			String tableName_tMysqlOutput_4 = "branch_office_dim";
			boolean whetherReject_tMysqlOutput_4 = false;

			java.util.Calendar calendar_tMysqlOutput_4 = java.util.Calendar
					.getInstance();
			calendar_tMysqlOutput_4.set(1, 0, 1, 0, 0, 0);
			long year1_tMysqlOutput_4 = calendar_tMysqlOutput_4.getTime()
					.getTime();
			calendar_tMysqlOutput_4.set(10000, 0, 1, 0, 0, 0);
			long year10000_tMysqlOutput_4 = calendar_tMysqlOutput_4.getTime()
					.getTime();
			long date_tMysqlOutput_4;

			java.sql.Connection conn_tMysqlOutput_4 = null;
			conn_tMysqlOutput_4 = (java.sql.Connection) globalMap
					.get("conn_tMysqlConnection_2");

			java.sql.DatabaseMetaData dbMetaData_tMysqlOutput_4 = conn_tMysqlOutput_4
					.getMetaData();
			java.sql.ResultSet rsTable_tMysqlOutput_4 = dbMetaData_tMysqlOutput_4
					.getTables(null, null, null, new String[] { "TABLE" });
			boolean whetherExist_tMysqlOutput_4 = false;
			while (rsTable_tMysqlOutput_4.next()) {
				String table_tMysqlOutput_4 = rsTable_tMysqlOutput_4
						.getString("TABLE_NAME");
				if (table_tMysqlOutput_4.equalsIgnoreCase("branch_office_dim")) {
					whetherExist_tMysqlOutput_4 = true;
					break;
				}
			}
			if (!whetherExist_tMysqlOutput_4) {
				java.sql.Statement stmtCreate_tMysqlOutput_4 = conn_tMysqlOutput_4
						.createStatement();
				stmtCreate_tMysqlOutput_4
						.execute("CREATE TABLE `"
								+ tableName_tMysqlOutput_4
								+ "`(`GLOBAL_OFFICE_NUM` VARCHAR(100)  not null,`OFFICE_LEVEL_ID` SMALLINT(5)  not null,`SEARCH_ID` VARCHAR(100)  not null,`MAX_CHILD_COUNT` INT(10)  not null,`LOCAL_REMOTE_FLAG` SMALLINT(5)  not null,`DISPLAY_NAME` VARCHAR(200)  not null,`CREATED_BY` SMALLINT(5)  ,`CREATED_DATE` DATE ,`UPDATED_BY` SMALLINT(5)  ,`UPDATED_DATE` DATE ,`OFFICE_SHORT_NAME` VARCHAR(4)  not null,`STATUS_ID` SMALLINT(5)  not null,`VERSION_NO` INT(10)  not null,`OFFICE_CODE_ID` SMALLINT(5)  ,`area_office_id` SMALLINT(4)  ,primary key(`GLOBAL_OFFICE_NUM`))");
			}
			java.sql.PreparedStatement pstmtUpdate_tMysqlOutput_4 = conn_tMysqlOutput_4
					.prepareStatement("UPDATE `"
							+ "branch_office_dim"
							+ "` SET `OFFICE_LEVEL_ID` = ?,`SEARCH_ID` = ?,`MAX_CHILD_COUNT` = ?,`LOCAL_REMOTE_FLAG` = ?,`DISPLAY_NAME` = ?,`CREATED_BY` = ?,`CREATED_DATE` = ?,`UPDATED_BY` = ?,`UPDATED_DATE` = ?,`OFFICE_SHORT_NAME` = ?,`STATUS_ID` = ?,`VERSION_NO` = ?,`OFFICE_CODE_ID` = ?,`area_office_id` = ? WHERE `GLOBAL_OFFICE_NUM` = ?");

			java.sql.PreparedStatement pstmtInsert_tMysqlOutput_4 = conn_tMysqlOutput_4
					.prepareStatement("INSERT INTO `"
							+ "branch_office_dim"
							+ "` (`GLOBAL_OFFICE_NUM`,`OFFICE_LEVEL_ID`,`SEARCH_ID`,`MAX_CHILD_COUNT`,`LOCAL_REMOTE_FLAG`,`DISPLAY_NAME`,`CREATED_BY`,`CREATED_DATE`,`UPDATED_BY`,`UPDATED_DATE`,`OFFICE_SHORT_NAME`,`STATUS_ID`,`VERSION_NO`,`OFFICE_CODE_ID`,`area_office_id`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");

			/**
			 * [tMysqlOutput_4 begin ] stop
			 */

			/**
			 * [tFilterColumns_1 begin ] start
			 */

			ok_Hash.put("tFilterColumns_1", false);
			start_Hash.put("tFilterColumns_1", System.currentTimeMillis());
			currentComponent = "tFilterColumns_1";

			/**
			 * [tFilterColumns_1 begin ] stop
			 */

			/**
			 * [tJoin_1 begin ] start
			 */

			ok_Hash.put("tJoin_1", false);
			start_Hash.put("tJoin_1", System.currentTimeMillis());
			currentComponent = "tJoin_1";

			final java.util.List<row2Struct> list_tJoin_1 = new java.util.ArrayList(
					((java.util.Map<row2Struct, row2Struct>) globalMap
							.get("tHash_row2")).keySet());

			class Util_tJoin_1 {
				row2Struct lookupValue = null;
				final int keyNum = 1;

				public boolean isJoined(row1Struct mainRow) {
					String mainRow_parent_office_num_str = null;
					if (mainRow.parent_office_num != null) {

						mainRow_parent_office_num_str = mainRow.parent_office_num;

					}

					int checkedKeyNum = 0;
					lookupValue = null;

					for (row2Struct row : list_tJoin_1) {
						String row_global_office_num_str = null;
						if (mainRow.parent_office_num != null) {

							row_global_office_num_str = row.global_office_num;

						}
						if (mainRow_parent_office_num_str != null
								&& mainRow_parent_office_num_str
										.equals(row_global_office_num_str)) {
							checkedKeyNum++;
						} else if (mainRow_parent_office_num_str == null
								&& row_global_office_num_str == null) {
							checkedKeyNum++;
						}
						if (checkedKeyNum == keyNum) {
							lookupValue = row;
							return true;
						}
					}
					return false;
				}
			}

			Util_tJoin_1 util_tJoin_1 = new Util_tJoin_1();

			int nb_line_tJoin_1 = 0;
			/**
			 * [tJoin_1 begin ] stop
			 */

			/**
			 * [tMysqlInput_1 begin ] start
			 */

			ok_Hash.put("tMysqlInput_1", false);
			start_Hash.put("tMysqlInput_1", System.currentTimeMillis());
			currentComponent = "tMysqlInput_1";

			int nb_line_tMysqlInput_1 = 0;
			java.sql.Connection conn_tMysqlInput_1 = null;
			conn_tMysqlInput_1 = (java.sql.Connection) globalMap
					.get("conn_tMysqlConnection_1");

			java.sql.Statement stmt_tMysqlInput_1 = conn_tMysqlInput_1
					.createStatement();
			java.sql.ResultSet rs_tMysqlInput_1 = stmt_tMysqlInput_1
					.executeQuery("SELECT office.GLOBAL_OFFICE_NUM, office.OFFICE_LEVEL_ID, office.SEARCH_ID,  office.MAX_CHILD_COUNT, office.LOCAL_REMOTE_FLAG, office.DISPLAY_NAME, office.CREATED_BY,  office.CREATED_DATE, office.UPDATED_BY, office.UPDATED_DATE, office.OFFICE_SHORT_NAME,  office.PARENT_OFFICE_ID parent_id, office.STATUS_ID, office.VERSION_NO, office.OFFICE_CODE_ID, (select global_office_num from office o where parent_id = o.office_id)  parent_office_num FROM office where office.OFFICE_LEVEL_ID = 5");
			java.sql.ResultSetMetaData rsmd_tMysqlInput_1 = rs_tMysqlInput_1
					.getMetaData();
			int colQtyInRs_tMysqlInput_1 = rsmd_tMysqlInput_1.getColumnCount();

			java.util.Calendar calendar_tMysqlInput_1 = java.util.Calendar
					.getInstance();
			calendar_tMysqlInput_1.set(0, 0, 0, 0, 0, 0);
			java.util.Date year0_tMysqlInput_1 = calendar_tMysqlInput_1
					.getTime();

			globalMap
					.put(
							"tMysqlInput_1_QUERY",
							"SELECT office.GLOBAL_OFFICE_NUM, office.OFFICE_LEVEL_ID, office.SEARCH_ID,  office.MAX_CHILD_COUNT, office.LOCAL_REMOTE_FLAG, office.DISPLAY_NAME, office.CREATED_BY,  office.CREATED_DATE, office.UPDATED_BY, office.UPDATED_DATE, office.OFFICE_SHORT_NAME,  office.PARENT_OFFICE_ID parent_id, office.STATUS_ID, office.VERSION_NO, office.OFFICE_CODE_ID, (select global_office_num from office o where parent_id = o.office_id)  parent_office_num FROM office where office.OFFICE_LEVEL_ID = 5");

			while (rs_tMysqlInput_1.next()) {
				nb_line_tMysqlInput_1++;

				if (colQtyInRs_tMysqlInput_1 < 1) {

					row1.GLOBAL_OFFICE_NUM = null;

				} else {

					if (rs_tMysqlInput_1.getObject(1) != null) {
						row1.GLOBAL_OFFICE_NUM = rs_tMysqlInput_1.getString(1);
					} else {

						throw new RuntimeException(
								"Null value in non-Nullable column");
					}

				}

				if (colQtyInRs_tMysqlInput_1 < 2) {

					row1.OFFICE_LEVEL_ID = 0;

				} else {

					if (rs_tMysqlInput_1.getObject(2) != null) {
						row1.OFFICE_LEVEL_ID = rs_tMysqlInput_1.getShort(2);
					} else {

						throw new RuntimeException(
								"Null value in non-Nullable column");
					}

				}

				if (colQtyInRs_tMysqlInput_1 < 3) {

					row1.SEARCH_ID = null;

				} else {

					if (rs_tMysqlInput_1.getObject(3) != null) {
						row1.SEARCH_ID = rs_tMysqlInput_1.getString(3);
					} else {

						throw new RuntimeException(
								"Null value in non-Nullable column");
					}

				}

				if (colQtyInRs_tMysqlInput_1 < 4) {

					row1.MAX_CHILD_COUNT = 0;

				} else {

					if (rs_tMysqlInput_1.getObject(4) != null) {
						row1.MAX_CHILD_COUNT = rs_tMysqlInput_1.getInt(4);
					} else {

						throw new RuntimeException(
								"Null value in non-Nullable column");
					}

				}

				if (colQtyInRs_tMysqlInput_1 < 5) {

					row1.LOCAL_REMOTE_FLAG = 0;

				} else {

					if (rs_tMysqlInput_1.getObject(5) != null) {
						row1.LOCAL_REMOTE_FLAG = rs_tMysqlInput_1.getShort(5);
					} else {

						throw new RuntimeException(
								"Null value in non-Nullable column");
					}

				}

				if (colQtyInRs_tMysqlInput_1 < 6) {

					row1.DISPLAY_NAME = null;

				} else {

					if (rs_tMysqlInput_1.getObject(6) != null) {
						row1.DISPLAY_NAME = rs_tMysqlInput_1.getString(6);
					} else {

						throw new RuntimeException(
								"Null value in non-Nullable column");
					}

				}

				if (colQtyInRs_tMysqlInput_1 < 7) {

					row1.CREATED_BY = null;

				} else {

					if (rs_tMysqlInput_1.getObject(7) != null) {
						row1.CREATED_BY = rs_tMysqlInput_1.getShort(7);
					} else {

						row1.CREATED_BY = null;

					}

				}

				if (colQtyInRs_tMysqlInput_1 < 8) {

					row1.CREATED_DATE = null;

				} else {

					if (rs_tMysqlInput_1.getString(8) != null) {
						String dateString_tMysqlInput_1 = rs_tMysqlInput_1
								.getString(8);
						if (!dateString_tMysqlInput_1.equals("0000-00-00")
								&& !dateString_tMysqlInput_1
										.equals("0000-00-00 00:00:00")) {
							row1.CREATED_DATE = rs_tMysqlInput_1
									.getTimestamp(8);
						} else {
							row1.CREATED_DATE = (java.util.Date) year0_tMysqlInput_1
									.clone();
						}
					} else {
						row1.CREATED_DATE = null;
					}

				}

				if (colQtyInRs_tMysqlInput_1 < 9) {

					row1.UPDATED_BY = null;

				} else {

					if (rs_tMysqlInput_1.getObject(9) != null) {
						row1.UPDATED_BY = rs_tMysqlInput_1.getShort(9);
					} else {

						row1.UPDATED_BY = null;

					}

				}

				if (colQtyInRs_tMysqlInput_1 < 10) {

					row1.UPDATED_DATE = null;

				} else {

					if (rs_tMysqlInput_1.getString(10) != null) {
						String dateString_tMysqlInput_1 = rs_tMysqlInput_1
								.getString(10);
						if (!dateString_tMysqlInput_1.equals("0000-00-00")
								&& !dateString_tMysqlInput_1
										.equals("0000-00-00 00:00:00")) {
							row1.UPDATED_DATE = rs_tMysqlInput_1
									.getTimestamp(10);
						} else {
							row1.UPDATED_DATE = (java.util.Date) year0_tMysqlInput_1
									.clone();
						}
					} else {
						row1.UPDATED_DATE = null;
					}

				}

				if (colQtyInRs_tMysqlInput_1 < 11) {

					row1.OFFICE_SHORT_NAME = null;

				} else {

					if (rs_tMysqlInput_1.getObject(11) != null) {
						row1.OFFICE_SHORT_NAME = rs_tMysqlInput_1.getString(11);
					} else {

						throw new RuntimeException(
								"Null value in non-Nullable column");
					}

				}

				if (colQtyInRs_tMysqlInput_1 < 12) {

					row1.parent_id = null;

				} else {

					if (rs_tMysqlInput_1.getObject(12) != null) {
						row1.parent_id = rs_tMysqlInput_1.getShort(12);
					} else {

						row1.parent_id = null;

					}

				}

				if (colQtyInRs_tMysqlInput_1 < 13) {

					row1.STATUS_ID = 0;

				} else {

					if (rs_tMysqlInput_1.getObject(13) != null) {
						row1.STATUS_ID = rs_tMysqlInput_1.getShort(13);
					} else {

						throw new RuntimeException(
								"Null value in non-Nullable column");
					}

				}

				if (colQtyInRs_tMysqlInput_1 < 14) {

					row1.VERSION_NO = 0;

				} else {

					if (rs_tMysqlInput_1.getObject(14) != null) {
						row1.VERSION_NO = rs_tMysqlInput_1.getInt(14);
					} else {

						throw new RuntimeException(
								"Null value in non-Nullable column");
					}

				}

				if (colQtyInRs_tMysqlInput_1 < 15) {

					row1.OFFICE_CODE_ID = null;

				} else {

					if (rs_tMysqlInput_1.getObject(15) != null) {
						row1.OFFICE_CODE_ID = rs_tMysqlInput_1.getShort(15);
					} else {

						row1.OFFICE_CODE_ID = null;

					}

				}

				if (colQtyInRs_tMysqlInput_1 < 16) {

					row1.parent_office_num = null;

				} else {

					if (rs_tMysqlInput_1.getObject(16) != null) {
						row1.parent_office_num = rs_tMysqlInput_1.getString(16);
					} else {

						row1.parent_office_num = null;

					}

				}

				/**
				 * [tMysqlInput_1 begin ] stop
				 */
				/**
				 * [tMysqlInput_1 main ] start
				 */

				currentComponent = "tMysqlInput_1";

				/**
				 * [tMysqlInput_1 main ] stop
				 */
				/**
				 * [tJoin_1 main ] start
				 */

				currentComponent = "tJoin_1";

				row3 = null;

				row3 = new row3Struct();
				row3.GLOBAL_OFFICE_NUM = row1.GLOBAL_OFFICE_NUM;
				row3.OFFICE_LEVEL_ID = row1.OFFICE_LEVEL_ID;
				row3.SEARCH_ID = row1.SEARCH_ID;
				row3.MAX_CHILD_COUNT = row1.MAX_CHILD_COUNT;
				row3.LOCAL_REMOTE_FLAG = row1.LOCAL_REMOTE_FLAG;
				row3.DISPLAY_NAME = row1.DISPLAY_NAME;
				row3.CREATED_BY = row1.CREATED_BY;
				row3.CREATED_DATE = row1.CREATED_DATE;
				row3.UPDATED_BY = row1.UPDATED_BY;
				row3.UPDATED_DATE = row1.UPDATED_DATE;
				row3.OFFICE_SHORT_NAME = row1.OFFICE_SHORT_NAME;
				row3.parent_id = row1.parent_id;
				row3.STATUS_ID = row1.STATUS_ID;
				row3.VERSION_NO = row1.VERSION_NO;
				row3.OFFICE_CODE_ID = row1.OFFICE_CODE_ID;
				row3.parent_office_num = row1.parent_office_num;

				if (util_tJoin_1.isJoined(row1)) {
					row3.area_office_id = util_tJoin_1.lookupValue.office_id;

				}

				else {
					row3 = null;
				}

				// /////////////////////
				/**
				 * [tJoin_1 main ] stop
				 */
				// Start of branch "row3"
				if (row3 != null) {

					/**
					 * [tFilterColumns_1 main ] start
					 */

					currentComponent = "tFilterColumns_1";

					row4.GLOBAL_OFFICE_NUM = row3.GLOBAL_OFFICE_NUM;
					row4.OFFICE_LEVEL_ID = row3.OFFICE_LEVEL_ID;
					row4.SEARCH_ID = row3.SEARCH_ID;
					row4.MAX_CHILD_COUNT = row3.MAX_CHILD_COUNT;
					row4.LOCAL_REMOTE_FLAG = row3.LOCAL_REMOTE_FLAG;
					row4.DISPLAY_NAME = row3.DISPLAY_NAME;
					row4.CREATED_BY = row3.CREATED_BY;
					row4.CREATED_DATE = row3.CREATED_DATE;
					row4.UPDATED_BY = row3.UPDATED_BY;
					row4.UPDATED_DATE = row3.UPDATED_DATE;
					row4.OFFICE_SHORT_NAME = row3.OFFICE_SHORT_NAME;
					row4.STATUS_ID = row3.STATUS_ID;
					row4.VERSION_NO = row3.VERSION_NO;
					row4.OFFICE_CODE_ID = row3.OFFICE_CODE_ID;
					row4.area_office_id = row3.area_office_id;
					/**
					 * [tFilterColumns_1 main ] stop
					 */
					/**
					 * [tMysqlOutput_4 main ] start
					 */

					currentComponent = "tMysqlOutput_4";

					whetherReject_tMysqlOutput_4 = false;
					int updateFlag_tMysqlOutput_4 = 0;

					pstmtUpdate_tMysqlOutput_4
							.setShort(1, row4.OFFICE_LEVEL_ID);

					if (row4.SEARCH_ID == null) {
						pstmtUpdate_tMysqlOutput_4.setNull(2,
								java.sql.Types.VARCHAR);

					} else {

						pstmtUpdate_tMysqlOutput_4.setString(2, row4.SEARCH_ID);

					}

					pstmtUpdate_tMysqlOutput_4.setInt(3, row4.MAX_CHILD_COUNT);

					pstmtUpdate_tMysqlOutput_4.setShort(4,
							row4.LOCAL_REMOTE_FLAG);

					if (row4.DISPLAY_NAME == null) {
						pstmtUpdate_tMysqlOutput_4.setNull(5,
								java.sql.Types.VARCHAR);

					} else {

						pstmtUpdate_tMysqlOutput_4.setString(5,
								row4.DISPLAY_NAME);

					}

					if (row4.CREATED_BY == null) {
						pstmtUpdate_tMysqlOutput_4.setNull(6,
								java.sql.Types.INTEGER);

					} else {

						pstmtUpdate_tMysqlOutput_4.setShort(6, row4.CREATED_BY);

					}

					if (row4.CREATED_DATE != null) {
						// timestamp < min java date value (year 1) || timestamp
						// > max mysql value (year 10000) => set 0000-00-00 as
						// date in MySQL
						date_tMysqlOutput_4 = row4.CREATED_DATE.getTime();
						if (date_tMysqlOutput_4 < year1_tMysqlOutput_4
								|| date_tMysqlOutput_4 >= year10000_tMysqlOutput_4) {
							pstmtUpdate_tMysqlOutput_4.setString(7,
									"0000-00-00 00:00:00");
						} else {
							pstmtUpdate_tMysqlOutput_4
									.setTimestamp(7, new java.sql.Timestamp(
											date_tMysqlOutput_4));
						}
					} else {

						pstmtUpdate_tMysqlOutput_4.setNull(7,
								java.sql.Types.DATE);

					}

					if (row4.UPDATED_BY == null) {
						pstmtUpdate_tMysqlOutput_4.setNull(8,
								java.sql.Types.INTEGER);

					} else {

						pstmtUpdate_tMysqlOutput_4.setShort(8, row4.UPDATED_BY);

					}

					if (row4.UPDATED_DATE != null) {
						// timestamp < min java date value (year 1) || timestamp
						// > max mysql value (year 10000) => set 0000-00-00 as
						// date in MySQL
						date_tMysqlOutput_4 = row4.UPDATED_DATE.getTime();
						if (date_tMysqlOutput_4 < year1_tMysqlOutput_4
								|| date_tMysqlOutput_4 >= year10000_tMysqlOutput_4) {
							pstmtUpdate_tMysqlOutput_4.setString(9,
									"0000-00-00 00:00:00");
						} else {
							pstmtUpdate_tMysqlOutput_4
									.setTimestamp(9, new java.sql.Timestamp(
											date_tMysqlOutput_4));
						}
					} else {

						pstmtUpdate_tMysqlOutput_4.setNull(9,
								java.sql.Types.DATE);

					}

					if (row4.OFFICE_SHORT_NAME == null) {
						pstmtUpdate_tMysqlOutput_4.setNull(10,
								java.sql.Types.VARCHAR);

					} else {

						pstmtUpdate_tMysqlOutput_4.setString(10,
								row4.OFFICE_SHORT_NAME);

					}

					pstmtUpdate_tMysqlOutput_4.setShort(11, row4.STATUS_ID);

					pstmtUpdate_tMysqlOutput_4.setInt(12, row4.VERSION_NO);

					if (row4.OFFICE_CODE_ID == null) {
						pstmtUpdate_tMysqlOutput_4.setNull(13,
								java.sql.Types.INTEGER);

					} else {

						pstmtUpdate_tMysqlOutput_4.setShort(13,
								row4.OFFICE_CODE_ID);

					}

					if (row4.area_office_id == null) {
						pstmtUpdate_tMysqlOutput_4.setNull(14,
								java.sql.Types.INTEGER);

					} else {

						pstmtUpdate_tMysqlOutput_4.setShort(14,
								row4.area_office_id);

					}

					if (row4.GLOBAL_OFFICE_NUM == null) {
						pstmtUpdate_tMysqlOutput_4.setNull(15,
								java.sql.Types.VARCHAR);

					} else {

						pstmtUpdate_tMysqlOutput_4.setString(15,
								row4.GLOBAL_OFFICE_NUM);

					}

					try {
						updateFlag_tMysqlOutput_4 = pstmtUpdate_tMysqlOutput_4
								.executeUpdate();
						updatedCount_tMysqlOutput_4 = updatedCount_tMysqlOutput_4
								+ updateFlag_tMysqlOutput_4;

					} catch (Exception e) {
						whetherReject_tMysqlOutput_4 = true;
						System.err.print(e.getMessage());
					}
					if (updateFlag_tMysqlOutput_4 == 0) {

						if (row4.GLOBAL_OFFICE_NUM == null) {
							pstmtInsert_tMysqlOutput_4.setNull(1,
									java.sql.Types.VARCHAR);

						} else {

							pstmtInsert_tMysqlOutput_4.setString(1,
									row4.GLOBAL_OFFICE_NUM);

						}

						pstmtInsert_tMysqlOutput_4.setShort(2,
								row4.OFFICE_LEVEL_ID);

						if (row4.SEARCH_ID == null) {
							pstmtInsert_tMysqlOutput_4.setNull(3,
									java.sql.Types.VARCHAR);

						} else {

							pstmtInsert_tMysqlOutput_4.setString(3,
									row4.SEARCH_ID);

						}

						pstmtInsert_tMysqlOutput_4.setInt(4,
								row4.MAX_CHILD_COUNT);

						pstmtInsert_tMysqlOutput_4.setShort(5,
								row4.LOCAL_REMOTE_FLAG);

						if (row4.DISPLAY_NAME == null) {
							pstmtInsert_tMysqlOutput_4.setNull(6,
									java.sql.Types.VARCHAR);

						} else {

							pstmtInsert_tMysqlOutput_4.setString(6,
									row4.DISPLAY_NAME);

						}

						if (row4.CREATED_BY == null) {
							pstmtInsert_tMysqlOutput_4.setNull(7,
									java.sql.Types.INTEGER);

						} else {

							pstmtInsert_tMysqlOutput_4.setShort(7,
									row4.CREATED_BY);

						}

						if (row4.CREATED_DATE != null) {
							// timestamp < min java date value (year 1) ||
							// timestamp > max mysql value (year 10000) => set
							// 0000-00-00 as date in MySQL
							date_tMysqlOutput_4 = row4.CREATED_DATE.getTime();
							if (date_tMysqlOutput_4 < year1_tMysqlOutput_4
									|| date_tMysqlOutput_4 >= year10000_tMysqlOutput_4) {
								pstmtInsert_tMysqlOutput_4.setString(8,
										"0000-00-00 00:00:00");
							} else {
								pstmtInsert_tMysqlOutput_4.setTimestamp(8,
										new java.sql.Timestamp(
												date_tMysqlOutput_4));
							}
						} else {

							pstmtInsert_tMysqlOutput_4.setNull(8,
									java.sql.Types.DATE);

						}

						if (row4.UPDATED_BY == null) {
							pstmtInsert_tMysqlOutput_4.setNull(9,
									java.sql.Types.INTEGER);

						} else {

							pstmtInsert_tMysqlOutput_4.setShort(9,
									row4.UPDATED_BY);

						}

						if (row4.UPDATED_DATE != null) {
							// timestamp < min java date value (year 1) ||
							// timestamp > max mysql value (year 10000) => set
							// 0000-00-00 as date in MySQL
							date_tMysqlOutput_4 = row4.UPDATED_DATE.getTime();
							if (date_tMysqlOutput_4 < year1_tMysqlOutput_4
									|| date_tMysqlOutput_4 >= year10000_tMysqlOutput_4) {
								pstmtInsert_tMysqlOutput_4.setString(10,
										"0000-00-00 00:00:00");
							} else {
								pstmtInsert_tMysqlOutput_4.setTimestamp(10,
										new java.sql.Timestamp(
												date_tMysqlOutput_4));
							}
						} else {

							pstmtInsert_tMysqlOutput_4.setNull(10,
									java.sql.Types.DATE);

						}

						if (row4.OFFICE_SHORT_NAME == null) {
							pstmtInsert_tMysqlOutput_4.setNull(11,
									java.sql.Types.VARCHAR);

						} else {

							pstmtInsert_tMysqlOutput_4.setString(11,
									row4.OFFICE_SHORT_NAME);

						}

						pstmtInsert_tMysqlOutput_4.setShort(12, row4.STATUS_ID);

						pstmtInsert_tMysqlOutput_4.setInt(13, row4.VERSION_NO);

						if (row4.OFFICE_CODE_ID == null) {
							pstmtInsert_tMysqlOutput_4.setNull(14,
									java.sql.Types.INTEGER);

						} else {

							pstmtInsert_tMysqlOutput_4.setShort(14,
									row4.OFFICE_CODE_ID);

						}

						if (row4.area_office_id == null) {
							pstmtInsert_tMysqlOutput_4.setNull(15,
									java.sql.Types.INTEGER);

						} else {

							pstmtInsert_tMysqlOutput_4.setShort(15,
									row4.area_office_id);

						}

						try {
							insertedCount_tMysqlOutput_4 = insertedCount_tMysqlOutput_4
									+ pstmtInsert_tMysqlOutput_4
											.executeUpdate();
						} catch (Exception e) {
							whetherReject_tMysqlOutput_4 = true;
							System.err.print(e.getMessage());
						}
					}
					nb_line_tMysqlOutput_4++;
					/**
					 * [tMysqlOutput_4 main ] stop
					 */

				} // End of branch "row3"

				/**
				 * [tMysqlInput_1 end ] start
				 */

				currentComponent = "tMysqlInput_1";

			}
			stmt_tMysqlInput_1.close();

			globalMap.put("tMysqlInput_1_NB_LINE", nb_line_tMysqlInput_1);

			ok_Hash.put("tMysqlInput_1", true);
			end_Hash.put("tMysqlInput_1", System.currentTimeMillis());

			/**
			 * [tMysqlInput_1 end ] stop
			 */
			/**
			 * [tJoin_1 end ] start
			 */

			currentComponent = "tJoin_1";

			ok_Hash.put("tJoin_1", true);
			end_Hash.put("tJoin_1", System.currentTimeMillis());

			/**
			 * [tJoin_1 end ] stop
			 */
			/**
			 * [tFilterColumns_1 end ] start
			 */

			currentComponent = "tFilterColumns_1";

			ok_Hash.put("tFilterColumns_1", true);
			end_Hash.put("tFilterColumns_1", System.currentTimeMillis());

			/**
			 * [tFilterColumns_1 end ] stop
			 */
			/**
			 * [tMysqlOutput_4 end ] start
			 */

			currentComponent = "tMysqlOutput_4";

			if (pstmtUpdate_tMysqlOutput_4 != null) {

				pstmtUpdate_tMysqlOutput_4.close();

			}
			if (pstmtInsert_tMysqlOutput_4 != null) {

				pstmtInsert_tMysqlOutput_4.close();

			}

			nb_line_deleted_tMysqlOutput_4 = nb_line_deleted_tMysqlOutput_4
					+ deletedCount_tMysqlOutput_4;
			nb_line_update_tMysqlOutput_4 = nb_line_update_tMysqlOutput_4
					+ updatedCount_tMysqlOutput_4;
			nb_line_inserted_tMysqlOutput_4 = nb_line_inserted_tMysqlOutput_4
					+ insertedCount_tMysqlOutput_4;

			globalMap.put("tMysqlOutput_4_NB_LINE", nb_line_tMysqlOutput_4);
			globalMap.put("tMysqlOutput_4_NB_LINE_UPDATED",
					nb_line_update_tMysqlOutput_4);
			globalMap.put("tMysqlOutput_4_NB_LINE_INSERTED",
					nb_line_inserted_tMysqlOutput_4);
			globalMap.put("tMysqlOutput_4_NB_LINE_DELETED",
					nb_line_deleted_tMysqlOutput_4);

			ok_Hash.put("tMysqlOutput_4", true);
			end_Hash.put("tMysqlOutput_4", System.currentTimeMillis());

			/**
			 * [tMysqlOutput_4 end ] stop
			 */

		} catch (Exception e) {
			throw new TalendException(this, e, currentComponent);
		}
	}

	public void tMysqlCommit_1Process() throws TalendException {
		String currentComponent = "";
		try {
			/**
			 * [tMysqlCommit_1 begin ] start
			 */

			ok_Hash.put("tMysqlCommit_1", false);
			start_Hash.put("tMysqlCommit_1", System.currentTimeMillis());
			currentComponent = "tMysqlCommit_1";

			/**
			 * [tMysqlCommit_1 begin ] stop
			 */
			/**
			 * [tMysqlCommit_1 main ] start
			 */

			currentComponent = "tMysqlCommit_1";

			java.sql.Connection conn_tMysqlCommit_1 = (java.sql.Connection) globalMap
					.get("conn_tMysqlConnection_2");
			if (conn_tMysqlCommit_1 != null && !conn_tMysqlCommit_1.isClosed()) {
				conn_tMysqlCommit_1.commit();
			}

			/**
			 * [tMysqlCommit_1 main ] stop
			 */
			/**
			 * [tMysqlCommit_1 end ] start
			 */

			currentComponent = "tMysqlCommit_1";

			ok_Hash.put("tMysqlCommit_1", true);
			end_Hash.put("tMysqlCommit_1", System.currentTimeMillis());

			/**
			 * [tMysqlCommit_1 end ] stop
			 */

		} catch (Exception e) {
			throw new TalendException(this, e, currentComponent);
		}
	}

	private class row5Struct {

		java.util.Date moment;

		String pid;

		String root_pid;

		String father_pid;

		String project;

		String job;

		String context;

		Integer priority;

		String type;

		String origin;

		String message;

		Integer code;

	}

	public void tLogCatcher_1Process() throws TalendException {
		String currentComponent = "";
		try {

			row5Struct row5 = new row5Struct();

			/**
			 * [tFileOutputDelimited_1 begin ] start
			 */

			ok_Hash.put("tFileOutputDelimited_1", false);
			start_Hash
					.put("tFileOutputDelimited_1", System.currentTimeMillis());
			currentComponent = "tFileOutputDelimited_1";

			String fileName_tFileOutputDelimited_1 = (new java.io.File(
					"branch_dimension.csv")).getAbsolutePath().replace("\\",
					"/");
			String fullName_tFileOutputDelimited_1 = null;
			String extension_tFileOutputDelimited_1 = null;
			String directory_tFileOutputDelimited_1 = null;
			if ((fileName_tFileOutputDelimited_1.indexOf("/") != -1)) {
				if (fileName_tFileOutputDelimited_1.lastIndexOf(".") < fileName_tFileOutputDelimited_1
						.lastIndexOf("/")) {
					fullName_tFileOutputDelimited_1 = fileName_tFileOutputDelimited_1;
					extension_tFileOutputDelimited_1 = "";
				} else {
					fullName_tFileOutputDelimited_1 = fileName_tFileOutputDelimited_1
							.substring(0, fileName_tFileOutputDelimited_1
									.lastIndexOf("."));
					extension_tFileOutputDelimited_1 = fileName_tFileOutputDelimited_1
							.substring(fileName_tFileOutputDelimited_1
									.lastIndexOf("."));
				}
				directory_tFileOutputDelimited_1 = fileName_tFileOutputDelimited_1
						.substring(0, fileName_tFileOutputDelimited_1
								.lastIndexOf("/"));
			} else {
				if (fileName_tFileOutputDelimited_1.lastIndexOf(".") != -1) {
					fullName_tFileOutputDelimited_1 = fileName_tFileOutputDelimited_1
							.substring(0, fileName_tFileOutputDelimited_1
									.lastIndexOf("."));
					extension_tFileOutputDelimited_1 = fileName_tFileOutputDelimited_1
							.substring(fileName_tFileOutputDelimited_1
									.lastIndexOf("."));
				} else {
					fullName_tFileOutputDelimited_1 = fileName_tFileOutputDelimited_1;
					extension_tFileOutputDelimited_1 = "";
				}
				directory_tFileOutputDelimited_1 = "";
			}

			int nb_line_tFileOutputDelimited_1 = 0;
			int splitEvery_tFileOutputDelimited_1 = 1000;
			int splitedFileNo_tFileOutputDelimited_1 = 0;
			int currentRow_tFileOutputDelimited_1 = 0;

			final String OUT_DELIM_tFileOutputDelimited_1 = /**
															 * Start field
															 * tFileOutputDelimited_1:FIELDSEPARATOR
															 */
			";"/** End field tFileOutputDelimited_1:FIELDSEPARATOR */
			;

			final String OUT_DELIM_ROWSEP_tFileOutputDelimited_1 = /**
																	 * Start
																	 * field
																	 * tFileOutputDelimited_1:ROWSEPARATOR
																	 */
			"\n"/** End field tFileOutputDelimited_1:ROWSEPARATOR */
			;

			// create directory only if not exists
			if (directory_tFileOutputDelimited_1 != null
					&& directory_tFileOutputDelimited_1.trim().length() != 0) {
				java.io.File dir_tFileOutputDelimited_1 = new java.io.File(
						directory_tFileOutputDelimited_1);
				if (!dir_tFileOutputDelimited_1.exists()) {
					dir_tFileOutputDelimited_1.mkdirs();
				}
			}

			java.io.BufferedWriter outtFileOutputDelimited_1 = new java.io.BufferedWriter(
					new java.io.OutputStreamWriter(
							new java.io.FileOutputStream(
									fileName_tFileOutputDelimited_1, true),
							"ISO-8859-15"));
			java.io.File filetFileOutputDelimited_1 = new java.io.File(
					fileName_tFileOutputDelimited_1);

			if (filetFileOutputDelimited_1.length() == 0) {

				outtFileOutputDelimited_1.write("moment");

				outtFileOutputDelimited_1
						.write(OUT_DELIM_tFileOutputDelimited_1);

				outtFileOutputDelimited_1.write("pid");

				outtFileOutputDelimited_1
						.write(OUT_DELIM_tFileOutputDelimited_1);

				outtFileOutputDelimited_1.write("root_pid");

				outtFileOutputDelimited_1
						.write(OUT_DELIM_tFileOutputDelimited_1);

				outtFileOutputDelimited_1.write("father_pid");

				outtFileOutputDelimited_1
						.write(OUT_DELIM_tFileOutputDelimited_1);

				outtFileOutputDelimited_1.write("project");

				outtFileOutputDelimited_1
						.write(OUT_DELIM_tFileOutputDelimited_1);

				outtFileOutputDelimited_1.write("job");

				outtFileOutputDelimited_1
						.write(OUT_DELIM_tFileOutputDelimited_1);

				outtFileOutputDelimited_1.write("context");

				outtFileOutputDelimited_1
						.write(OUT_DELIM_tFileOutputDelimited_1);

				outtFileOutputDelimited_1.write("priority");

				outtFileOutputDelimited_1
						.write(OUT_DELIM_tFileOutputDelimited_1);

				outtFileOutputDelimited_1.write("type");

				outtFileOutputDelimited_1
						.write(OUT_DELIM_tFileOutputDelimited_1);

				outtFileOutputDelimited_1.write("origin");

				outtFileOutputDelimited_1
						.write(OUT_DELIM_tFileOutputDelimited_1);

				outtFileOutputDelimited_1.write("message");

				outtFileOutputDelimited_1
						.write(OUT_DELIM_tFileOutputDelimited_1);

				outtFileOutputDelimited_1.write("code");

				outtFileOutputDelimited_1
						.write(OUT_DELIM_ROWSEP_tFileOutputDelimited_1);
			}

			/**
			 * [tFileOutputDelimited_1 begin ] stop
			 */

			/**
			 * [tLogCatcher_1 begin ] start
			 */

			ok_Hash.put("tLogCatcher_1", false);
			start_Hash.put("tLogCatcher_1", System.currentTimeMillis());
			currentComponent = "tLogCatcher_1";

			for (LogCatcherUtils.LogCatcherMessage lcm : tLogCatcher_1
					.getMessages()) {
				row5.type = lcm.getType();
				row5.origin = (lcm.getOrigin() == null
						|| lcm.getOrigin().length() < 1 ? null : lcm
						.getOrigin());
				row5.priority = lcm.getPriority();
				row5.message = lcm.getMessage();
				row5.code = lcm.getCode();

				row5.moment = java.util.Calendar.getInstance().getTime();

				row5.pid = pid;
				row5.root_pid = rootPid;
				row5.father_pid = fatherPid;

				row5.project = projectName;
				row5.job = jobName;
				row5.context = contextStr;

				/**
				 * [tLogCatcher_1 begin ] stop
				 */
				/**
				 * [tLogCatcher_1 main ] start
				 */

				currentComponent = "tLogCatcher_1";

				/**
				 * [tLogCatcher_1 main ] stop
				 */
				/**
				 * [tFileOutputDelimited_1 main ] start
				 */

				currentComponent = "tFileOutputDelimited_1";

				StringBuilder sb_tFileOutputDelimited_1 = new StringBuilder();

				if (row5.moment != null) {

					sb_tFileOutputDelimited_1.append(

					FormatterUtils.format_Date(row5.moment,
							"yyyy-MM-dd HH:mm:ss")

					);

				}

				sb_tFileOutputDelimited_1
						.append(OUT_DELIM_tFileOutputDelimited_1);

				if (row5.pid != null) {

					sb_tFileOutputDelimited_1.append(

					row5.pid

					);

				}

				sb_tFileOutputDelimited_1
						.append(OUT_DELIM_tFileOutputDelimited_1);

				if (row5.root_pid != null) {

					sb_tFileOutputDelimited_1.append(

					row5.root_pid

					);

				}

				sb_tFileOutputDelimited_1
						.append(OUT_DELIM_tFileOutputDelimited_1);

				if (row5.father_pid != null) {

					sb_tFileOutputDelimited_1.append(

					row5.father_pid

					);

				}

				sb_tFileOutputDelimited_1
						.append(OUT_DELIM_tFileOutputDelimited_1);

				if (row5.project != null) {

					sb_tFileOutputDelimited_1.append(

					row5.project

					);

				}

				sb_tFileOutputDelimited_1
						.append(OUT_DELIM_tFileOutputDelimited_1);

				if (row5.job != null) {

					sb_tFileOutputDelimited_1.append(

					row5.job

					);

				}

				sb_tFileOutputDelimited_1
						.append(OUT_DELIM_tFileOutputDelimited_1);

				if (row5.context != null) {

					sb_tFileOutputDelimited_1.append(

					row5.context

					);

				}

				sb_tFileOutputDelimited_1
						.append(OUT_DELIM_tFileOutputDelimited_1);

				if (row5.priority != null) {

					sb_tFileOutputDelimited_1.append(

					row5.priority

					);

				}

				sb_tFileOutputDelimited_1
						.append(OUT_DELIM_tFileOutputDelimited_1);

				if (row5.type != null) {

					sb_tFileOutputDelimited_1.append(

					row5.type

					);

				}

				sb_tFileOutputDelimited_1
						.append(OUT_DELIM_tFileOutputDelimited_1);

				if (row5.origin != null) {

					sb_tFileOutputDelimited_1.append(

					row5.origin

					);

				}

				sb_tFileOutputDelimited_1
						.append(OUT_DELIM_tFileOutputDelimited_1);

				if (row5.message != null) {

					sb_tFileOutputDelimited_1.append(

					row5.message

					);

				}

				sb_tFileOutputDelimited_1
						.append(OUT_DELIM_tFileOutputDelimited_1);

				if (row5.code != null) {

					sb_tFileOutputDelimited_1.append(

					row5.code

					);

				}

				sb_tFileOutputDelimited_1
						.append(OUT_DELIM_ROWSEP_tFileOutputDelimited_1);

				outtFileOutputDelimited_1.write(sb_tFileOutputDelimited_1
						.toString());

				nb_line_tFileOutputDelimited_1++;

				/**
				 * [tFileOutputDelimited_1 main ] stop
				 */

				/**
				 * [tLogCatcher_1 end ] start
				 */

				currentComponent = "tLogCatcher_1";

			}

			ok_Hash.put("tLogCatcher_1", true);
			end_Hash.put("tLogCatcher_1", System.currentTimeMillis());

			/**
			 * [tLogCatcher_1 end ] stop
			 */
			/**
			 * [tFileOutputDelimited_1 end ] start
			 */

			currentComponent = "tFileOutputDelimited_1";

			outtFileOutputDelimited_1.close();
			globalMap.put("tFileOutputDelimited_1_NB_LINE",
					nb_line_tFileOutputDelimited_1);

			ok_Hash.put("tFileOutputDelimited_1", true);
			end_Hash.put("tFileOutputDelimited_1", System.currentTimeMillis());

			/**
			 * [tFileOutputDelimited_1 end ] stop
			 */

			tJava_1Process();

		} catch (Exception e) {
			throw new TalendException(this, e, currentComponent);
		}
	}

	private class row2Struct {
		private static final int DEFAULT_HASHCODE = 1;
		private static final int PRIME = 31;
		private int hashCode = DEFAULT_HASHCODE;
		public boolean hashCodeDirty = true;

		short office_id;

		String global_office_num;

		short office_level_id;

		String search_id;

		int max_child_count;

		short local_remote_flag;

		String display_name;

		Short created_by;

		java.util.Date created_date;

		Short updated_by;

		java.util.Date updated_date;

		String office_short_name;

		Short divisional_office_id;

		short status_id;

		int version_no;

		Short office_code_id;

		@Override
		public int hashCode() {
			if (this.hashCodeDirty) {
				final int prime = PRIME;
				int result = DEFAULT_HASHCODE;

				result = prime * result + (int) this.office_id;

				result = prime
						* result
						+ ((this.global_office_num == null) ? 0
								: this.global_office_num.hashCode());

				this.hashCode = result;
				this.hashCodeDirty = false;
			}
			return this.hashCode;
		}

		@Override
		public boolean equals(Object obj) {
			if (this == obj)
				return true;
			if (obj == null)
				return false;
			if (getClass() != obj.getClass())
				return false;
			final row2Struct other = (row2Struct) obj;

			if (this.office_id != other.office_id)
				return false;

			if (this.global_office_num == null) {
				if (other.global_office_num != null)
					return false;
			} else if (!this.global_office_num.equals(other.global_office_num))
				return false;

			return true;
		}

	}

	public void tMysqlInput_3Process() throws TalendException {
		String currentComponent = "";
		try {

			row2Struct row2 = new row2Struct();

			/**
			 * [tHash_row2 begin ] start
			 */

			ok_Hash.put("tHash_row2", false);
			start_Hash.put("tHash_row2", System.currentTimeMillis());
			currentComponent = "tHash_row2";

			java.util.Map<row2Struct, row2Struct> tHash_row2 = new java.util.HashMap<row2Struct, row2Struct>();
			globalMap.put("tHash_row2", tHash_row2);

			/**
			 * [tHash_row2 begin ] stop
			 */

			/**
			 * [tMysqlInput_3 begin ] start
			 */

			ok_Hash.put("tMysqlInput_3", false);
			start_Hash.put("tMysqlInput_3", System.currentTimeMillis());
			currentComponent = "tMysqlInput_3";

			int nb_line_tMysqlInput_3 = 0;
			java.sql.Connection conn_tMysqlInput_3 = null;
			conn_tMysqlInput_3 = (java.sql.Connection) globalMap
					.get("conn_tMysqlConnection_2");

			java.sql.Statement stmt_tMysqlInput_3 = conn_tMysqlInput_3
					.createStatement();
			java.sql.ResultSet rs_tMysqlInput_3 = stmt_tMysqlInput_3
					.executeQuery("SELECT area_office_dim.office_id, area_office_dim.global_office_num FROM area_office_dim");
			java.sql.ResultSetMetaData rsmd_tMysqlInput_3 = rs_tMysqlInput_3
					.getMetaData();
			int colQtyInRs_tMysqlInput_3 = rsmd_tMysqlInput_3.getColumnCount();

			java.util.Calendar calendar_tMysqlInput_3 = java.util.Calendar
					.getInstance();
			calendar_tMysqlInput_3.set(0, 0, 0, 0, 0, 0);
			java.util.Date year0_tMysqlInput_3 = calendar_tMysqlInput_3
					.getTime();

			globalMap
					.put(
							"tMysqlInput_3_QUERY",
							"SELECT area_office_dim.office_id, area_office_dim.global_office_num FROM area_office_dim");

			while (rs_tMysqlInput_3.next()) {
				nb_line_tMysqlInput_3++;

				if (colQtyInRs_tMysqlInput_3 < 1) {

					row2.office_id = 0;

				} else {

					if (rs_tMysqlInput_3.getObject(1) != null) {
						row2.office_id = rs_tMysqlInput_3.getShort(1);
					} else {

						throw new RuntimeException(
								"Null value in non-Nullable column");
					}

				}

				if (colQtyInRs_tMysqlInput_3 < 2) {

					row2.global_office_num = null;

				} else {

					if (rs_tMysqlInput_3.getObject(2) != null) {
						row2.global_office_num = rs_tMysqlInput_3.getString(2);
					} else {

						throw new RuntimeException(
								"Null value in non-Nullable column");
					}

				}

				if (colQtyInRs_tMysqlInput_3 < 3) {

					row2.office_level_id = 0;

				} else {

					if (rs_tMysqlInput_3.getObject(3) != null) {
						row2.office_level_id = rs_tMysqlInput_3.getShort(3);
					} else {

						throw new RuntimeException(
								"Null value in non-Nullable column");
					}

				}

				if (colQtyInRs_tMysqlInput_3 < 4) {

					row2.search_id = null;

				} else {

					if (rs_tMysqlInput_3.getObject(4) != null) {
						row2.search_id = rs_tMysqlInput_3.getString(4);
					} else {

						throw new RuntimeException(
								"Null value in non-Nullable column");
					}

				}

				if (colQtyInRs_tMysqlInput_3 < 5) {

					row2.max_child_count = 0;

				} else {

					if (rs_tMysqlInput_3.getObject(5) != null) {
						row2.max_child_count = rs_tMysqlInput_3.getInt(5);
					} else {

						throw new RuntimeException(
								"Null value in non-Nullable column");
					}

				}

				if (colQtyInRs_tMysqlInput_3 < 6) {

					row2.local_remote_flag = 0;

				} else {

					if (rs_tMysqlInput_3.getObject(6) != null) {
						row2.local_remote_flag = rs_tMysqlInput_3.getShort(6);
					} else {

						throw new RuntimeException(
								"Null value in non-Nullable column");
					}

				}

				if (colQtyInRs_tMysqlInput_3 < 7) {

					row2.display_name = null;

				} else {

					if (rs_tMysqlInput_3.getObject(7) != null) {
						row2.display_name = rs_tMysqlInput_3.getString(7);
					} else {

						throw new RuntimeException(
								"Null value in non-Nullable column");
					}

				}

				if (colQtyInRs_tMysqlInput_3 < 8) {

					row2.created_by = null;

				} else {

					if (rs_tMysqlInput_3.getObject(8) != null) {
						row2.created_by = rs_tMysqlInput_3.getShort(8);
					} else {

						row2.created_by = null;

					}

				}

				if (colQtyInRs_tMysqlInput_3 < 9) {

					row2.created_date = null;

				} else {

					if (rs_tMysqlInput_3.getString(9) != null) {
						String dateString_tMysqlInput_3 = rs_tMysqlInput_3
								.getString(9);
						if (!dateString_tMysqlInput_3.equals("0000-00-00")
								&& !dateString_tMysqlInput_3
										.equals("0000-00-00 00:00:00")) {
							row2.created_date = rs_tMysqlInput_3
									.getTimestamp(9);
						} else {
							row2.created_date = (java.util.Date) year0_tMysqlInput_3
									.clone();
						}
					} else {
						row2.created_date = null;
					}

				}

				if (colQtyInRs_tMysqlInput_3 < 10) {

					row2.updated_by = null;

				} else {

					if (rs_tMysqlInput_3.getObject(10) != null) {
						row2.updated_by = rs_tMysqlInput_3.getShort(10);
					} else {

						row2.updated_by = null;

					}

				}

				if (colQtyInRs_tMysqlInput_3 < 11) {

					row2.updated_date = null;

				} else {

					if (rs_tMysqlInput_3.getString(11) != null) {
						String dateString_tMysqlInput_3 = rs_tMysqlInput_3
								.getString(11);
						if (!dateString_tMysqlInput_3.equals("0000-00-00")
								&& !dateString_tMysqlInput_3
										.equals("0000-00-00 00:00:00")) {
							row2.updated_date = rs_tMysqlInput_3
									.getTimestamp(11);
						} else {
							row2.updated_date = (java.util.Date) year0_tMysqlInput_3
									.clone();
						}
					} else {
						row2.updated_date = null;
					}

				}

				if (colQtyInRs_tMysqlInput_3 < 12) {

					row2.office_short_name = null;

				} else {

					if (rs_tMysqlInput_3.getObject(12) != null) {
						row2.office_short_name = rs_tMysqlInput_3.getString(12);
					} else {

						throw new RuntimeException(
								"Null value in non-Nullable column");
					}

				}

				if (colQtyInRs_tMysqlInput_3 < 13) {

					row2.divisional_office_id = null;

				} else {

					if (rs_tMysqlInput_3.getObject(13) != null) {
						row2.divisional_office_id = rs_tMysqlInput_3
								.getShort(13);
					} else {

						row2.divisional_office_id = null;

					}

				}

				if (colQtyInRs_tMysqlInput_3 < 14) {

					row2.status_id = 0;

				} else {

					if (rs_tMysqlInput_3.getObject(14) != null) {
						row2.status_id = rs_tMysqlInput_3.getShort(14);
					} else {

						throw new RuntimeException(
								"Null value in non-Nullable column");
					}

				}

				if (colQtyInRs_tMysqlInput_3 < 15) {

					row2.version_no = 0;

				} else {

					if (rs_tMysqlInput_3.getObject(15) != null) {
						row2.version_no = rs_tMysqlInput_3.getInt(15);
					} else {

						throw new RuntimeException(
								"Null value in non-Nullable column");
					}

				}

				if (colQtyInRs_tMysqlInput_3 < 16) {

					row2.office_code_id = null;

				} else {

					if (rs_tMysqlInput_3.getObject(16) != null) {
						row2.office_code_id = rs_tMysqlInput_3.getShort(16);
					} else {

						row2.office_code_id = null;

					}

				}

				/**
				 * [tMysqlInput_3 begin ] stop
				 */
				/**
				 * [tMysqlInput_3 main ] start
				 */

				currentComponent = "tMysqlInput_3";

				/**
				 * [tMysqlInput_3 main ] stop
				 */

				/**
				 * [tHash_row2 main ] start
				 */

				currentComponent = "tHash_row2";

				row2Struct row2_HashRow = new row2Struct();

				row2_HashRow.office_id = row2.office_id;
				row2_HashRow.global_office_num = row2.global_office_num;
				row2_HashRow.office_level_id = row2.office_level_id;
				row2_HashRow.search_id = row2.search_id;
				row2_HashRow.max_child_count = row2.max_child_count;
				row2_HashRow.local_remote_flag = row2.local_remote_flag;
				row2_HashRow.display_name = row2.display_name;
				row2_HashRow.created_by = row2.created_by;
				row2_HashRow.created_date = row2.created_date;
				row2_HashRow.updated_by = row2.updated_by;
				row2_HashRow.updated_date = row2.updated_date;
				row2_HashRow.office_short_name = row2.office_short_name;
				row2_HashRow.divisional_office_id = row2.divisional_office_id;
				row2_HashRow.status_id = row2.status_id;
				row2_HashRow.version_no = row2.version_no;
				row2_HashRow.office_code_id = row2.office_code_id;
				tHash_row2.put(row2_HashRow, row2_HashRow);

				/**
				 * [tHash_row2 main ] stop
				 */

				/**
				 * [tMysqlInput_3 end ] start
				 */

				currentComponent = "tMysqlInput_3";

			}
			stmt_tMysqlInput_3.close();

			globalMap.put("tMysqlInput_3_NB_LINE", nb_line_tMysqlInput_3);

			ok_Hash.put("tMysqlInput_3", true);
			end_Hash.put("tMysqlInput_3", System.currentTimeMillis());

			/**
			 * [tMysqlInput_3 end ] stop
			 */

			/**
			 * [tHash_row2 end ] start
			 */

			currentComponent = "tHash_row2";

			ok_Hash.put("tHash_row2", true);
			end_Hash.put("tHash_row2", System.currentTimeMillis());

			/**
			 * [tHash_row2 end ] stop
			 */

		} catch (Exception e) {
			throw new TalendException(this, e, currentComponent);
		}
	}

	private class row6Struct {

		java.util.Date moment;

		String pid;

		String father_pid;

		String root_pid;

		Long system_pid;

		String project;

		String job;

		String job_repository_id;

		String job_version;

		String context;

		String origin;

		String message_type;

		String message;

		Long duration;

	}

	public void tStatCatcher_1Process() throws TalendException {
		String currentComponent = "";
		try {

			row6Struct row6 = new row6Struct();

			/**
			 * [tFileOutputDelimited_2 begin ] start
			 */

			ok_Hash.put("tFileOutputDelimited_2", false);
			start_Hash
					.put("tFileOutputDelimited_2", System.currentTimeMillis());
			currentComponent = "tFileOutputDelimited_2";

			String fileName_tFileOutputDelimited_2 = (new java.io.File(
					"branch_dimension_stats.csv")).getAbsolutePath().replace(
					"\\", "/");
			String fullName_tFileOutputDelimited_2 = null;
			String extension_tFileOutputDelimited_2 = null;
			String directory_tFileOutputDelimited_2 = null;
			if ((fileName_tFileOutputDelimited_2.indexOf("/") != -1)) {
				if (fileName_tFileOutputDelimited_2.lastIndexOf(".") < fileName_tFileOutputDelimited_2
						.lastIndexOf("/")) {
					fullName_tFileOutputDelimited_2 = fileName_tFileOutputDelimited_2;
					extension_tFileOutputDelimited_2 = "";
				} else {
					fullName_tFileOutputDelimited_2 = fileName_tFileOutputDelimited_2
							.substring(0, fileName_tFileOutputDelimited_2
									.lastIndexOf("."));
					extension_tFileOutputDelimited_2 = fileName_tFileOutputDelimited_2
							.substring(fileName_tFileOutputDelimited_2
									.lastIndexOf("."));
				}
				directory_tFileOutputDelimited_2 = fileName_tFileOutputDelimited_2
						.substring(0, fileName_tFileOutputDelimited_2
								.lastIndexOf("/"));
			} else {
				if (fileName_tFileOutputDelimited_2.lastIndexOf(".") != -1) {
					fullName_tFileOutputDelimited_2 = fileName_tFileOutputDelimited_2
							.substring(0, fileName_tFileOutputDelimited_2
									.lastIndexOf("."));
					extension_tFileOutputDelimited_2 = fileName_tFileOutputDelimited_2
							.substring(fileName_tFileOutputDelimited_2
									.lastIndexOf("."));
				} else {
					fullName_tFileOutputDelimited_2 = fileName_tFileOutputDelimited_2;
					extension_tFileOutputDelimited_2 = "";
				}
				directory_tFileOutputDelimited_2 = "";
			}

			int nb_line_tFileOutputDelimited_2 = 0;
			int splitEvery_tFileOutputDelimited_2 = 1000;
			int splitedFileNo_tFileOutputDelimited_2 = 0;
			int currentRow_tFileOutputDelimited_2 = 0;

			final String OUT_DELIM_tFileOutputDelimited_2 = /**
															 * Start field
															 * tFileOutputDelimited_2:FIELDSEPARATOR
															 */
			";"/** End field tFileOutputDelimited_2:FIELDSEPARATOR */
			;

			final String OUT_DELIM_ROWSEP_tFileOutputDelimited_2 = /**
																	 * Start
																	 * field
																	 * tFileOutputDelimited_2:ROWSEPARATOR
																	 */
			"\n"/** End field tFileOutputDelimited_2:ROWSEPARATOR */
			;

			// create directory only if not exists
			if (directory_tFileOutputDelimited_2 != null
					&& directory_tFileOutputDelimited_2.trim().length() != 0) {
				java.io.File dir_tFileOutputDelimited_2 = new java.io.File(
						directory_tFileOutputDelimited_2);
				if (!dir_tFileOutputDelimited_2.exists()) {
					dir_tFileOutputDelimited_2.mkdirs();
				}
			}

			java.io.BufferedWriter outtFileOutputDelimited_2 = new java.io.BufferedWriter(
					new java.io.OutputStreamWriter(
							new java.io.FileOutputStream(
									fileName_tFileOutputDelimited_2, true),
							"ISO-8859-15"));
			java.io.File filetFileOutputDelimited_2 = new java.io.File(
					fileName_tFileOutputDelimited_2);

			if (filetFileOutputDelimited_2.length() == 0) {

				outtFileOutputDelimited_2.write("moment");

				outtFileOutputDelimited_2
						.write(OUT_DELIM_tFileOutputDelimited_2);

				outtFileOutputDelimited_2.write("pid");

				outtFileOutputDelimited_2
						.write(OUT_DELIM_tFileOutputDelimited_2);

				outtFileOutputDelimited_2.write("father_pid");

				outtFileOutputDelimited_2
						.write(OUT_DELIM_tFileOutputDelimited_2);

				outtFileOutputDelimited_2.write("root_pid");

				outtFileOutputDelimited_2
						.write(OUT_DELIM_tFileOutputDelimited_2);

				outtFileOutputDelimited_2.write("system_pid");

				outtFileOutputDelimited_2
						.write(OUT_DELIM_tFileOutputDelimited_2);

				outtFileOutputDelimited_2.write("project");

				outtFileOutputDelimited_2
						.write(OUT_DELIM_tFileOutputDelimited_2);

				outtFileOutputDelimited_2.write("job");

				outtFileOutputDelimited_2
						.write(OUT_DELIM_tFileOutputDelimited_2);

				outtFileOutputDelimited_2.write("job_repository_id");

				outtFileOutputDelimited_2
						.write(OUT_DELIM_tFileOutputDelimited_2);

				outtFileOutputDelimited_2.write("job_version");

				outtFileOutputDelimited_2
						.write(OUT_DELIM_tFileOutputDelimited_2);

				outtFileOutputDelimited_2.write("context");

				outtFileOutputDelimited_2
						.write(OUT_DELIM_tFileOutputDelimited_2);

				outtFileOutputDelimited_2.write("origin");

				outtFileOutputDelimited_2
						.write(OUT_DELIM_tFileOutputDelimited_2);

				outtFileOutputDelimited_2.write("message_type");

				outtFileOutputDelimited_2
						.write(OUT_DELIM_tFileOutputDelimited_2);

				outtFileOutputDelimited_2.write("message");

				outtFileOutputDelimited_2
						.write(OUT_DELIM_tFileOutputDelimited_2);

				outtFileOutputDelimited_2.write("duration");

				outtFileOutputDelimited_2
						.write(OUT_DELIM_ROWSEP_tFileOutputDelimited_2);
			}

			/**
			 * [tFileOutputDelimited_2 begin ] stop
			 */

			/**
			 * [tStatCatcher_1 begin ] start
			 */

			ok_Hash.put("tStatCatcher_1", false);
			start_Hash.put("tStatCatcher_1", System.currentTimeMillis());
			currentComponent = "tStatCatcher_1";

			for (StatCatcherUtils.StatCatcherMessage scm : tStatCatcher_1
					.getMessages()) {
				row6.pid = pid;
				row6.root_pid = rootPid;
				row6.father_pid = fatherPid;
				row6.project = projectName;
				row6.job = jobName;
				row6.context = contextStr;
				row6.origin = (scm.getOrigin() == null
						|| scm.getOrigin().length() < 1 ? null : scm
						.getOrigin());
				row6.message = scm.getMessage();
				row6.duration = scm.getDuration();
				row6.moment = scm.getMoment();
				row6.message_type = scm.getMessageType();
				row6.job_version = scm.getJobVersion();
				row6.job_repository_id = scm.getJobId();
				row6.system_pid = scm.getSystemPid();

				/**
				 * [tStatCatcher_1 begin ] stop
				 */
				/**
				 * [tStatCatcher_1 main ] start
				 */

				currentComponent = "tStatCatcher_1";

				/**
				 * [tStatCatcher_1 main ] stop
				 */
				/**
				 * [tFileOutputDelimited_2 main ] start
				 */

				currentComponent = "tFileOutputDelimited_2";

				StringBuilder sb_tFileOutputDelimited_2 = new StringBuilder();

				if (row6.moment != null) {

					sb_tFileOutputDelimited_2.append(

					FormatterUtils.format_Date(row6.moment,
							"yyyy-MM-dd HH:mm:ss")

					);

				}

				sb_tFileOutputDelimited_2
						.append(OUT_DELIM_tFileOutputDelimited_2);

				if (row6.pid != null) {

					sb_tFileOutputDelimited_2.append(

					row6.pid

					);

				}

				sb_tFileOutputDelimited_2
						.append(OUT_DELIM_tFileOutputDelimited_2);

				if (row6.father_pid != null) {

					sb_tFileOutputDelimited_2.append(

					row6.father_pid

					);

				}

				sb_tFileOutputDelimited_2
						.append(OUT_DELIM_tFileOutputDelimited_2);

				if (row6.root_pid != null) {

					sb_tFileOutputDelimited_2.append(

					row6.root_pid

					);

				}

				sb_tFileOutputDelimited_2
						.append(OUT_DELIM_tFileOutputDelimited_2);

				if (row6.system_pid != null) {

					sb_tFileOutputDelimited_2.append(

					row6.system_pid

					);

				}

				sb_tFileOutputDelimited_2
						.append(OUT_DELIM_tFileOutputDelimited_2);

				if (row6.project != null) {

					sb_tFileOutputDelimited_2.append(

					row6.project

					);

				}

				sb_tFileOutputDelimited_2
						.append(OUT_DELIM_tFileOutputDelimited_2);

				if (row6.job != null) {

					sb_tFileOutputDelimited_2.append(

					row6.job

					);

				}

				sb_tFileOutputDelimited_2
						.append(OUT_DELIM_tFileOutputDelimited_2);

				if (row6.job_repository_id != null) {

					sb_tFileOutputDelimited_2.append(

					row6.job_repository_id

					);

				}

				sb_tFileOutputDelimited_2
						.append(OUT_DELIM_tFileOutputDelimited_2);

				if (row6.job_version != null) {

					sb_tFileOutputDelimited_2.append(

					row6.job_version

					);

				}

				sb_tFileOutputDelimited_2
						.append(OUT_DELIM_tFileOutputDelimited_2);

				if (row6.context != null) {

					sb_tFileOutputDelimited_2.append(

					row6.context

					);

				}

				sb_tFileOutputDelimited_2
						.append(OUT_DELIM_tFileOutputDelimited_2);

				if (row6.origin != null) {

					sb_tFileOutputDelimited_2.append(

					row6.origin

					);

				}

				sb_tFileOutputDelimited_2
						.append(OUT_DELIM_tFileOutputDelimited_2);

				if (row6.message_type != null) {

					sb_tFileOutputDelimited_2.append(

					row6.message_type

					);

				}

				sb_tFileOutputDelimited_2
						.append(OUT_DELIM_tFileOutputDelimited_2);

				if (row6.message != null) {

					sb_tFileOutputDelimited_2.append(

					row6.message

					);

				}

				sb_tFileOutputDelimited_2
						.append(OUT_DELIM_tFileOutputDelimited_2);

				if (row6.duration != null) {

					sb_tFileOutputDelimited_2.append(

					row6.duration

					);

				}

				sb_tFileOutputDelimited_2
						.append(OUT_DELIM_ROWSEP_tFileOutputDelimited_2);

				outtFileOutputDelimited_2.write(sb_tFileOutputDelimited_2
						.toString());

				nb_line_tFileOutputDelimited_2++;

				/**
				 * [tFileOutputDelimited_2 main ] stop
				 */

				/**
				 * [tStatCatcher_1 end ] start
				 */

				currentComponent = "tStatCatcher_1";

			}

			ok_Hash.put("tStatCatcher_1", true);
			end_Hash.put("tStatCatcher_1", System.currentTimeMillis());

			tLogCatcher_1Process();
			/**
			 * [tStatCatcher_1 end ] stop
			 */
			/**
			 * [tFileOutputDelimited_2 end ] start
			 */

			currentComponent = "tFileOutputDelimited_2";

			outtFileOutputDelimited_2.close();
			globalMap.put("tFileOutputDelimited_2_NB_LINE",
					nb_line_tFileOutputDelimited_2);

			ok_Hash.put("tFileOutputDelimited_2", true);
			end_Hash.put("tFileOutputDelimited_2", System.currentTimeMillis());

			/**
			 * [tFileOutputDelimited_2 end ] stop
			 */

		} catch (Exception e) {
			throw new TalendException(this, e, currentComponent);
		}
	}

	public static boolean watch = false;
	public static int portStats = 3334;
	public static int portTraces = 4334;
	public static String clientHost;
	public static String defaultClientHost = "localhost";
	public static String contextStr = "Default";
	public static String pid = "0";
	public static String rootPid = null;
	public static String fatherPid = null;
	private static ThreadLocal threadLocal = new ThreadLocal();
	private static SyncInt runningThreadCount = new SyncInt();

	private static class SyncInt {
		private int count = 0;

		public synchronized void add(int i) {
			count += i;
		}

		public synchronized int getCount() {
			return count;
		}
	}

	private static java.util.Properties context_param = new java.util.Properties();

	public static String status = "";

	public static void main(String[] args) {
		int exitCode = runJob(args);
		System.exit(exitCode);
	}

	public static synchronized int runJob(String[] args) {

		init();

		String lastStr = "";
		for (String arg : args) {
			if (arg.equalsIgnoreCase("--context_param")) {
				lastStr = arg;
			} else if (lastStr.equals("")) {
				evalParam(arg);
			} else {
				evalParam(lastStr + " " + arg);
				lastStr = "";
			}
		}

		if (clientHost == null) {
			clientHost = defaultClientHost;
		}

		pid = TalendString.getAsciiRandomString(6);
		if (rootPid == null) {
			rootPid = pid;
		}
		if (fatherPid == null) {
			fatherPid = pid;
		}

		try {
			java.io.InputStream inContext = BranchOfficeLoader.class
					.getClassLoader()
					.getResourceAsStream(
							"org_mifos_etl/branchofficeloader/contexts/Default.properties");
			if (inContext != null) {
				defaultProps.load(inContext);
				inContext.close();
				context = new java.util.Properties(defaultProps);
			}

			if (contextStr.compareTo("Default") != 0) {
				inContext = BranchOfficeLoader.class.getClassLoader()
						.getResourceAsStream(
								"org_mifos_etl/branchofficeloader/contexts/"
										+ contextStr + ".properties");
				if (inContext != null) {
					context.load(inContext);
					inContext.close();
				}
			}

			if (!context_param.isEmpty()) {
				context.putAll(context_param);
			}

			OLTP_DB_PASSWORD = (String) context.getProperty("OLTP_DB_PASSWORD");

			OLTP_DB_USER = (String) context.getProperty("OLTP_DB_USER");

			OLTP_DB_NAME = (String) context.getProperty("OLTP_DB_NAME");

			OLTP_DB_PORT = (String) context.getProperty("OLTP_DB_PORT");

			OLTP_HOST_NAME = (String) context.getProperty("OLTP_HOST_NAME");

			OLAP_DB_HOST = (String) context.getProperty("OLAP_DB_HOST");

			OLAP_DB_PORT = (String) context.getProperty("OLAP_DB_PORT");

			OLAP_DB_NAME = (String) context.getProperty("OLAP_DB_NAME");

			OLAP_DB_USER = (String) context.getProperty("OLAP_DB_USER");

			OLAP_DB_PASSWORD = (String) context.getProperty("OLAP_DB_PASSWORD");

			GK_DB_HOST = (String) context.getProperty("GK_DB_HOST");

			GK_DB_PORT = (String) context.getProperty("GK_DB_PORT");

			GK_DB_SCHEMA = (String) context.getProperty("GK_DB_SCHEMA");

			GK_DB_USER = (String) context.getProperty("GK_DB_USER");

			GK_DB_PASSWORD = (String) context.getProperty("GK_DB_PASSWORD");

		} catch (java.io.IOException ie) {
			System.err.println("Could not load context " + contextStr);
			ie.printStackTrace();
		}

		long end = 0;
		long start = System.currentTimeMillis();
		final BranchOfficeLoader BranchOfficeLoaderClass = new BranchOfficeLoader();
		BranchOfficeLoaderClass.tStatCatcher_1.addMessage("begin");
		try {
			BranchOfficeLoaderClass.tStatCatcher_1Process();
		} catch (Exception e) {
			e.printStackTrace();
		}
		while (BranchOfficeLoaderClass.runningThreadCount.getCount() > 0) {
			try {
				Thread.sleep(10);
			} catch (Exception e) {
				e.printStackTrace();
			}
		}
		end = System.currentTimeMillis();
		if (watch) {
			System.out.println((end - start) + " milliseconds");
		}
		BranchOfficeLoaderClass.tStatCatcher_1.addMessage(status == "" ? "end"
				: status, (end - start));
		try {
			BranchOfficeLoaderClass.tStatCatcher_1Process();
		} catch (Exception e) {
			e.printStackTrace();
		}
		if (errorCode == null) {
			return status != null && status.equals("failure") ? 1 : 0;
		} else {
			return errorCode.intValue();
		}
	}

	public static void evalParam(String arg) {
		if (arg.startsWith("--watch")) {
			watch = true;
		} else if (arg.startsWith("--stat_port=")) {
			portStats = Integer.parseInt(arg.substring(12));
		} else if (arg.startsWith("--trace_port=")) {
			portTraces = Integer.parseInt(arg.substring(13));
		} else if (arg.startsWith("--client_host=")) {
			clientHost = arg.substring(14);
		} else if (arg.startsWith("--context=")) {
			contextStr = arg.substring(10);
		} else if (arg.startsWith("--father_pid=")) {
			fatherPid = arg.substring(13);
		} else if (arg.startsWith("--root_pid=")) {
			rootPid = arg.substring(11);
		} else if (arg.startsWith("--context_param")) {
			String keyValue = arg.substring(16);
			int index = -1;
			if (keyValue != null && (index = keyValue.indexOf('=')) > -1) {
				context_param.put(keyValue.substring(0, index), keyValue
						.substring(index + 1));
			}
		}

	}

	private static void init() {

		defaultProps.clear();
		context.clear();
		errorCode = null;
		threadLocal = new ThreadLocal();
		runningThreadCount = new SyncInt();
		start_Hash.clear();
		end_Hash.clear();
		ok_Hash.clear();
		globalMap.clear();
		watch = false;
		portStats = 3334;
		portTraces = 4334;
		clientHost = null;
		defaultClientHost = "localhost";
		contextStr = "Default";
		pid = "0";
		rootPid = null;
		fatherPid = null;
		context_param.clear();
		status = "";
	}
}
/*******************************************************************************
 * 89786 characters generated by Talend OpenStudio on the March 14, 2008 2:16:50
 * PM GMT
 ******************************************************************************/
