.TH Mifos 1 "November 20, 2010" Webapps "Microfinance Open Source"
.SH NAME
Mifos \- microfinance management application
.SH SYNOPSIS
.B sudo service tomcat6 start
.SH DESCRIPTION
\fBMifos\fP (MIcrofinance Open Source) is a Java Web application that runs in a
servlet container such as Apache Tomcat.
.SH OPTIONS
None.
.SH SEE ALSO
Apache Tomcat documentation.
.br
Mifos is documented fully online at
.UR http://www.mifos.org
mifos.org
.UE .
.SH AUTHOR
Mifos was written by many authors. See AUTHORS.
.PP
This very spartan manual page was originally written by
.MT haircut@gmail.com
Adam Monsen
.ME ,
for the Debian project (and may be used by others).
.\" vim: ft=nroff
