truncate group_status_dim;
insert into group_status_dim (status_id, status_description) values (1, 'Partial Application');
insert into group_status_dim (status_id, status_description) values (2, 'Pending Approval');
insert into group_status_dim (status_id, status_description) values (3, 'Active');
insert into group_status_dim (status_id, status_description) values (4, 'On Hold');
insert into group_status_dim (status_id, status_description) values (5, 'Cancel-Withdrew');
insert into group_status_dim (status_id, status_description) values (6, 'Calcel-Blacklisted');
insert into group_status_dim (status_id, status_description) values (7, 'Cancel-Duplicate');
insert into group_status_dim (status_id, status_description) values (8, 'Cancel-Rejected');
insert into group_status_dim (status_id, status_description) values (9, 'Cancel-Other');
insert into group_status_dim (status_id, status_description) values (10, 'Closed-Transfered');
insert into group_status_dim (status_id, status_description) values (11, 'Closed-Blacklisted');
insert into group_status_dim (status_id, status_description) values (12, 'Closed-Duplicate');
insert into group_status_dim (status_id, status_description) values (13, 'Closed-Left Program');
insert into group_status_dim (status_id, status_description) values (14, 'Closed-Other');
