CREATE TABLE  `time_dim` (
  `time_id` smallint(4) NOT NULL auto_increment,
  `date` date NOT NULL,
  `day_num_in_week` smallint(2),
  `week_num_in_year` smallint(2),
  `week_num_overall` smallint(4),
  `day_of_week` varchar(50),
  `day_num_in_month` smallint(2),
  `day_num_overall` smallint(4),
  `month` varchar(50),
  `month_num_in_year` smallint(4),
  `month_num_overall` smallint(4),
  `quarter_num_year` smallint(4),
  `quarter_name` varchar(50),
  `year` year(4),
  `week_day_flag` bit(1),
  `last_day_in_month_flag` bit(1),
  `holiday_flag` bit(1),
  `holiday_name` varchar(200),
  PRIMARY KEY  (`time_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
