CREATE TABLE PPI_LIKELIHOODS (
  LIKELIHOOD_ID INTEGER AUTO_INCREMENT NOT NULL,
  SURVEY_ID INTEGER NOT NULL,
  SCORE_FROM INTEGER NOT NULL,
  SCORE_TO INTEGER NOT NULL,
  BOTTOM_HALF_BELOW DECIMAL(10,3) NOT NULL,
  TOP_HALF_BELOW DECIMAL(10,3) NOT NULL,
  LIKELIHOOD_ORDER INTEGER NOT NULL,
  PRIMARY KEY(LIKELIHOOD_ID),
  FOREIGN KEY(SURVEY_ID)
    REFERENCES SURVEY(SURVEY_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);
  
UPDATE DATABASE_VERSION SET DATABASE_VERSION = 188 WHERE DATABASE_VERSION = 187;
