ALTER TABLE LOOKUP_ENTITY MODIFY COLUMN ENTITY_ID SMALLINT  AUTO_INCREMENT NOT NULL ;
ALTER TABLE LOOKUP_LABEL MODIFY COLUMN LABEL_ID INTEGER  AUTO_INCREMENT NOT NULL;
ALTER TABLE CUSTOM_FIELD_DEFINITION MODIFY COLUMN FIELD_ID SMALLINT  AUTO_INCREMENT NOT NULL;


update DATABASE_VERSION set DATABASE_VERSION = 150 where DATABASE_VERSION = 149;