	
ALTER TABLE LOAN_ACCOUNT ADD COLUMN MONTH_RANK SMALLINT;
ALTER TABLE LOAN_ACCOUNT ADD COLUMN MONTH_WEEK SMALLINT;
ALTER TABLE LOAN_ACCOUNT ADD COLUMN RECUR_MONTH SMALLINT;

ALTER TABLE LOAN_ACCOUNT ADD CONSTRAINT fk_loan_rankday FOREIGN KEY (MONTH_RANK)
 REFERENCES RANK_DAYS_MASTER(RANK_DAYS_MASTER_ID) ON DELETE NO ACTION ON UPDATE NO ACTION;   

ALTER TABLE LOAN_ACCOUNT ADD CONSTRAINT fk_loan_monthweek FOREIGN KEY (MONTH_WEEK)
  REFERENCES WEEK_DAYS_MASTER(WEEK_DAYS_MASTER_ID)  ON DELETE NO ACTION ON UPDATE NO ACTION;
 
UPDATE DATABASE_VERSION SET DATABASE_VERSION = 158 WHERE DATABASE_VERSION = 157;
