package org.mifos.framework.formulaic;

public enum ErrorType {
	MISSING,
	NUMBER_OUT_OF_RANGE,
	DATE_FORMAT,
	INVALID_ENUM,
	INVALID_INT,
	INVALID_NUMBER,
	INVALID_PERSONNEL,
	NOT_A_CHOICE,
	WRONG_TYPE,
	STRING_TOO_LONG,
	MISSING_EXPECTED_VALUE,
	WRONG_VALUE;

}
